using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Demo6.Core.Loot;using Newtonsoft.Json;using GamePlayer=Demo6.Game.PlayerController;using Object=UnityEngine.Object;
public static class DodgeV057Review{
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/dodge-v057";
 static void Set(GamePlayer p,string name,object value){var f=typeof(GamePlayer).GetField(name,F);if(f.FieldType.IsEnum&&value is string)value=Enum.Parse(f.FieldType,(string)value);f.SetValue(p,value);}
 public static Texture2D Shot(Camera c){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1920,1080,24);var t=new Texture2D(1920,1080,TextureFormat.RGB24,false);try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t.ReadPixels(new Rect(0,0,1920,1080),0,0);t.Apply();return t;}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);}}
 static void Save(Texture2D t,string n){File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());Object.DestroyImmediate(t);}
 static void Tile(Texture2D board,int i,Texture2D shot,int cols){board.SetPixels((i%cols)*256,board.height-224-(i/cols)*224,256,224,shot.GetPixels(832,428,256,224));Object.DestroyImmediate(shot);}
 public static object Run(){var p=GamePlayer.Instance;var rig=TopDownView.PlayerRig;if(!Application.isPlaying||!p||rig==null)throw new Exception("Original live dungeon required");Directory.CreateDirectory(Out);var fields=typeof(GamePlayer).GetFields(F).Where(f=>!f.IsInitOnly&&!f.IsLiteral).ToDictionary(f=>f,f=>f.GetValue(p));var cam=Camera.main;var cp=cam.transform.position;var size=cam.orthographicSize;var paused=EditorApplication.isPaused;var af=typeof(TopDownPlayerRig).GetField("_angle",F);var oldAngle=af.GetValue(rig);var catF=typeof(EquipmentVisualV049).GetField("_catalog",BindingFlags.Static|BindingFlags.NonPublic);var oldCat=catF.GetValue(null);var cat=JsonUtility.FromJson<EquipmentVisualV049.Catalog>(Resources.Load<TextAsset>("EquipmentV049/calibration").text);var allWeapons=cat.weapons;var art=TopDownView.CurrentArt();var capeProfile=CuteArtProfileV15.Current;var cape=capeProfile.cape;var errors=new List<string>();var rows=new List<object>();var directions=new List<object>();var gear=new List<object>();var layouts=new List<object>();Application.LogCallback logger=(s,t,l)=>{if(l==LogType.Error||l==LogType.Exception)errors.Add(s);};Application.logMessageReceived+=logger;
 Action<string,float,float> pose=(weapon,time,deg)=>{Set(p,"<Weapon>k__BackingField",weapon=="wpn_longsword"?WeaponPresets.Longsword:weapon=="wpn_greatsword"?WeaponPresets.Greatsword:WeaponPresets.Twinblades);Set(p,"_state","Dodge");Set(p,"_stateTime",time);Set(p,"_hurtTime",-999f);Set(p,"_facing",new Vector2(Mathf.Cos(deg*Mathf.Deg2Rad),Mathf.Sin(deg*Mathf.Deg2Rad)));af.SetValue(rig,deg);typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.FirstAttackArt.Stop();rig.Drive(0,art);};
 try{EditorApplication.isPaused=true;cam.transform.position=new Vector3(p.Position.x,p.Position.y,cp.z);catF.SetValue(null,cat);var lib=JsonUtility.FromJson<CharacterMotionV045.Library>(Resources.Load<TextAsset>("CharacterMotionV045/clips").text);var clips=lib.clips.Where(c=>c.id.EndsWith("-dodge")).ToArray();var board=new Texture2D(2560,2016,TextureFormat.RGB24,false);int tile=0;
 foreach(var c in clips)foreach(var f in c.frames){pose(c.weapon,f.t,0);var a=rig.FirstAttackArt;var frame=(FirstAttackArtV042.Frame)typeof(FirstAttackArtV042).GetField("_currentFrame",F).GetValue(a);rows.Add(new{clip=c.id,t=f.t,actual=a.ClipId,cel=a.FrameIndex,active=a.Active,visible=a.VisiblePartCount,expected=a.ExpectedPartCount,scale=frame.bodyScale,spin=frame.spin,head=frame.headScale});Tile(board,tile++,Shot(cam),10);}
 board.Apply();Save(board,"all-native-frames-game-scale");
 board=new Texture2D(2048,1344,TextureFormat.RGB24,false);tile=0;
 foreach(var c in clips)foreach(bool caped in new[]{true,false})foreach(float deg in new[]{0f,45f,90f,135f,180f,225f,270f,315f}){capeProfile.cape=caped?cape:null;pose(c.weapon,.10f,deg);Tile(board,tile++,Shot(cam),8);var meshes=p.GetComponentsInChildren<MeshRenderer>().Where(m=>m.enabled&&m.name.Contains("Cape")).ToArray();directions.Add(new{c.id,caped,deg,capeRenderers=meshes.Length,passed=meshes.Length==(caped?1:0),clip=rig.FirstAttackArt.ClipId});}
 board.Apply();Save(board,"directions-cape-game-scale");capeProfile.cape=cape;
 foreach(var w in allWeapons){cat.weapons=new[]{w};Set(p,"<Look>k__BackingField",new GearLook(w.key.Contains("02-")?"arm_chain":"arm_leather","hlm_leather",null,null));foreach(float t in new[]{0f,.055f,.11f,.165f,.219f}){pose(w.baseId,t,0);var tex=Resources.Load<Texture2D>(w.texture);var visible=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.enabled&&s.sprite&&s.sprite.texture==tex&&!s.name.Contains("Thickness")).ToArray();gear.Add(new{w.key,t,renderers=visible.Length,passed=visible.Length==(w.baseId=="wpn_twinblades"?2:1),sameTwinSprite=visible.Length!=2||visible[0].sprite==visible[1].sprite,ppu=w.sprite?w.sprite.pixelsPerUnit:0});if(t==.11f)Save(Shot(cam),"gear-"+w.key);}}
 cat.weapons=allWeapons;Set(p,"<Look>k__BackingField",new GearLook("arm_leather","hlm_leather",null,null));
 foreach(var c in clips){pose(c.weapon,.10f,0);Save(Shot(cam),"actual-camera-"+c.id);layouts.Add(new{clip=c.id,renderers=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.enabled&&s.sprite).Select(s=>new{s.name,s.sortingOrder,s.sortingLayerName,position=s.transform.position.ToString(),group=s.GetComponentInParent<UnityEngine.Rendering.SortingGroup>()?.name}).ToArray()});Set(p,"_state","Free");Set(p,"_stateTime",0f);typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.FirstAttackArt.Stop();rig.Drive(0,art);var frame=(FirstAttackArtV042.Frame)typeof(FirstAttackArtV042).GetField("_currentFrame",F).GetValue(rig.FirstAttackArt);rows.Add(new{idleReturn=c.id,clip=rig.FirstAttackArt.ClipId,scale=frame.bodyScale,passed=frame.bodyScale==null||frame.bodyScale.All(x=>Mathf.Abs(x-1)<.0001f)});}
 }finally{capeProfile.cape=cape;catF.SetValue(null,oldCat);foreach(var f in fields)f.Key.SetValue(p,f.Value);af.SetValue(rig,oldAngle);cam.transform.position=cp;cam.orthographicSize=size;typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.FirstAttackArt.Stop();rig.Drive(0,art);EditorApplication.isPaused=paused;Application.logMessageReceived-=logger;}
 var result=new{utc=DateTime.UtcNow,method="Original production camera 1920x1080 at unchanged ortho size. Automated paused pose sampling, not physical input. Native-size crops; cape/catalog/player fields and camera restored.",ortho=size,rows,directions,gear,layouts,errors};File.WriteAllText(Out+"/pose-runtime.json",JsonConvert.SerializeObject(result,Formatting.Indented));return new{nativeSamples=84,directions=directions.Count,gearSamples=gear.Count,gearFailures=gear.Count(x=>(bool)x.GetType().GetProperty("passed").GetValue(x)==false),errors};}
}
