using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEngine.Rendering;using UnityEditor;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;using GamePlayer=Demo6.Game.PlayerController;using Object=UnityEngine.Object;
public static class DodgeV057Input{
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/dodge-v057";
 static void Set(GamePlayer p,string n,object v){var f=typeof(GamePlayer).GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 public static async Task<object> Run(){var p=GamePlayer.Instance;if(!Application.isPlaying||!p||EditorApplication.isPaused)throw new Exception("Unpaused original game required");var fields=typeof(GamePlayer).GetFields(F).Where(f=>!f.IsInitOnly&&!f.IsLiteral).ToDictionary(f=>f,f=>f.GetValue(p));var origin=p.Position;var body=p.GetComponent<Rigidbody2D>();var velocity=body.linearVelocity;var nativeKb=Keyboard.current;var nativeMouse=Mouse.current;var kb=InputSystem.AddDevice<Keyboard>("DodgeV057ValidationKeyboard");var mouse=InputSystem.AddDevice<Mouse>("DodgeV057ValidationMouse");var reader=p.GetComponent<PlayerInputReader>();var map=(InputActionMap)typeof(PlayerInputReader).GetField("_map",F).GetValue(reader);var devices=map.devices;var bg=Application.runInBackground;bool inv=p.Health.ExtraInvulnerable;var rows=new List<object>();DodgeV057Capture capture=null;
 try{Application.runInBackground=true;map.devices=new InputDevice[]{kb,mouse};
 foreach(var w in new[]{WeaponPresets.Longsword,WeaponPresets.Greatsword,WeaponPresets.Twinblades}){InputSystem.QueueStateEvent(kb,new KeyboardState());p.Teleport(origin);Set(p,"<Weapon>k__BackingField",w);Set(p,"_state","Free");Set(p,"_stateTime",0f);Set(p,"_dodgeCooldown",0f);Set(p,"_hurtTime",-999f);await Task.Delay(120);InputSystem.QueueStateEvent(mouse,new MouseState{position=Camera.main.WorldToScreenPoint(p.transform.position+Vector3.right*3)});await Task.Delay(60);if(w.id=="wpn_longsword"){var go=new GameObject("DodgeV057 temporary capture");capture=go.AddComponent<DodgeV057Capture>();}
 var start=p.Position;float clock=Time.realtimeSinceStartup;bool released=false;var samples=new List<object>();bool saw=false,returned=false;float maxClock=0;InputSystem.QueueStateEvent(kb,new KeyboardState(Key.Space));
 while(Time.realtimeSinceStartup-clock<.55f){await Task.Delay(8);bool dodge=p.Pose==PlayerPose.Dodge;saw|=dodge;if(saw&&!dodge)returned=true;if(dodge)maxClock=Mathf.Max(maxClock,p.PoseTime);samples.Add(new{frame=Time.frameCount,elapsed=Time.realtimeSinceStartup-clock,pose=p.Pose.ToString(),poseTime=p.PoseTime,position=new[]{p.Position.x,p.Position.y},clip=TopDownView.PlayerRig.FirstAttackArt.ClipId,cel=TopDownView.PlayerRig.FirstAttackArt.FrameIndex,invulnerable=p.Health.ExtraInvulnerable,cooldown=p.DodgeCooldown});if(!released&&saw){InputSystem.QueueStateEvent(kb,new KeyboardState());released=true;}}
 rows.Add(new{weapon=w.id,entered=saw,returned,travel=Vector2.Distance(start,p.Position),lastDodgeClock=maxClock,cooldown=p.DodgeCooldown,samples});InputSystem.QueueStateEvent(kb,new KeyboardState());if(capture){float deadline=Time.realtimeSinceStartup+3;while(!capture.Done&&Time.realtimeSinceStartup<deadline)await Task.Delay(25);if(!capture.Done)throw new Exception("Capture did not complete");Object.DestroyImmediate(capture.gameObject);capture=null;}
 }
 }finally{if(capture)Object.DestroyImmediate(capture.gameObject);InputSystem.QueueStateEvent(kb,new KeyboardState());map.devices=devices;InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);nativeKb?.MakeCurrent();nativeMouse?.MakeCurrent();foreach(var f in fields)f.Key.SetValue(p,f.Value);p.Teleport(origin);body.linearVelocity=velocity;p.Health.ExtraInvulnerable=inv;Application.runInBackground=bg;}
 var result=new{utc=DateTime.UtcNow,method="Temporary synthetic keyboard SPACE through production InputAction/PlayerController/Physics2D. Not physical user input. No gameplay code or constants changed; all devices/restrictions/player setup restored.",rows,nativeKeyboard=Keyboard.current?.native,nativeMouse=Mouse.current?.native,temporaryDevices=InputSystem.devices.Where(d=>d.name.StartsWith("DodgeV057")).Select(d=>d.name).ToArray(),deviceRestrictionRestored=map.devices==devices};File.WriteAllText(Out+"/input-runtime.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
public sealed class DodgeV057Capture:MonoBehaviour{
 public bool Done;bool started;int pending;readonly List<object> trace=new List<object>();readonly byte[][] bytes=new byte[10][];readonly int[] widths=new int[10],heights=new int[10];const string Out="검증/dodge-v057/live";
 void LateUpdate(){if(!started&&GamePlayer.Instance&&GamePlayer.Instance.Pose==PlayerPose.Dodge){started=true;StartCoroutine(Capture());}}
 IEnumerator Capture(){Directory.CreateDirectory(Out);for(int i=0;i<10;i++){yield return new WaitForEndOfFrame();int index=i;var p=GamePlayer.Instance;var a=TopDownView.PlayerRig.FirstAttackArt;int w=Screen.width,h=Screen.height;var rt=new RenderTexture(w,h,0,RenderTextureFormat.ARGB32);rt.Create();ScreenCapture.CaptureScreenshotIntoRenderTexture(rt);trace.Add(new{frame=Time.frameCount,time=Time.time,pose=p.Pose.ToString(),poseTime=p.PoseTime,clip=a.ClipId,cel=a.FrameIndex,position=new[]{p.Position.x,p.Position.y},width=w,height=h});pending++;AsyncGPUReadback.Request(rt,0,TextureFormat.RGBA32,r=>{if(!r.hasError){bytes[index]=r.GetData<byte>().ToArray();widths[index]=w;heights[index]=h;}rt.Release();Destroy(rt);pending--;});}
 while(pending>0)yield return null;for(int i=0;i<10;i++){if(bytes[i]==null)continue;var t=new Texture2D(widths[i],heights[i],TextureFormat.RGBA32,false);t.LoadRawTextureData(bytes[i]);t.Apply();File.WriteAllBytes(Out+"/frame-"+i.ToString("00")+".png",t.EncodeToPNG());Destroy(t);bytes[i]=null;}
 File.WriteAllText(Out+"/trace.json",JsonConvert.SerializeObject(new{method="Ten consecutive actual GameView frames, asynchronous GPU readback; synthetic SPACE triggers production dodge; no pose-time stepping",trace},Formatting.Indented));Done=true;}
}
