using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using Demo6.Game;using Demo6.Core.Loot;using Demo6.Core.Dungeon;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class GearV3Review {
 const string Root="아트/장비-UI-v3/검수";const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;
 static readonly List<object> Results=new List<object>();
 static async Task Shot(string name){string file=Path.GetFullPath(Root+"/"+Screen.height+"-"+name+".png");ScreenCapture.CaptureScreenshot(file);await Task.Delay(450);Results.Add(new{file,width=Screen.width,height=Screen.height,modal=DungeonUi.Modal});}
 public static async Task<object> Run(){
  if(!EditorApplication.isPlaying||!Inventory.Instance)throw new Exception("Play required");if(DungeonUi.ModalOpen)throw new Exception("User modal open; review did not start");
  Results.Clear();var inv=Inventory.Instance;var backup=new CarryData();inv.ExportTo(backup);var selection=typeof(Inventory).GetField("_selected",F);object selectedBefore=selection.GetValue(inv);var scene=SceneManager.GetActiveScene();bool dirty=scene.isDirty,background=Application.runInBackground,paused=TimeScaleService.Paused,blocked=PlayerInputReader.Blocked;
  var a=typeof(Editor).Assembly;var t=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(t).Cast<EditorWindow>().First();var selected=t.GetProperty("selectedSizeIndex",F);int originalIndex=(int)selected.GetValue(view);var sizes=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(sizes).GetProperty("instance").GetValue(null);var group=sizes.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});var sizeType=a.GetType("UnityEditor.GameViewSize");var enumType=a.GetType("UnityEditor.GameViewSizeType");var added=new List<object>();
  var lunch=UnityEngine.Object.FindObjectsByType<LunchboxEvent>().First();var lunchOpen=typeof(LunchboxEvent).GetField("_open",F);var note=UnityEngine.Object.FindObjectsByType<StoryItem>().OrderByDescending(n=>((string)typeof(StoryItem).GetMethod("NoteText",F).Invoke(n,null)).Length).First();var noteOpen=typeof(StoryItem).GetField("_open",F);var stake=UnityEngine.Object.FindObjectsByType<Stake>().First();var stakeOpen=typeof(Stake).GetField("_menuOpen",F);
  try {Application.runInBackground=true;
   foreach(var size in new[]{new[]{1280,720},new[]{1920,1080}}){var entry=Activator.CreateInstance(sizeType,new object[]{Enum.ToObject(enumType,1),size[0],size[1],"Gear v3 review "+size[0]});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{entry});added.Add(entry);selected.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(350);
    inv.ImportFrom(backup);DungeonUi.TryOpen(Inventory.BagWindow);await Task.Delay(100);await Shot("bag-empty-slots");DungeonUi.Close(Inventory.BagWindow);
    var fixture=new CarryData();inv.ExportTo(fixture);fixture.Equipment[(int)GearSlot.Ring1]=new GearItem("rng_iron",Grade.Common,1,1000);fixture.Equipment[(int)GearSlot.Ring2]=new GearItem("rng_blood",Grade.Rare,1,1000);fixture.Equipment[(int)GearSlot.Amulet]=new GearItem("amu_fang",Grade.Epic,1,1000);fixture.Bag.Clear();for(int i=0;i<GearBaseTable.All.Count;i++)fixture.Bag.Add(new GearItem(GearBaseTable.All[i].Id,(Grade)(i%5),30,1100,4));inv.ImportFrom(fixture);DungeonUi.TryOpen(Inventory.BagWindow);selection.SetValue(inv,inv.Bag[6]);await Task.Delay(100);await Shot("bag-all-gear-compare");selection.SetValue(inv,inv.Bag[16]);await Task.Delay(100);await Shot("bag-ring-buttons");selection.SetValue(inv,inv.Bag[20]);typeof(Inventory).GetField("_scroll",F).SetValue(inv,new Vector2(0,200));await Task.Delay(100);await Shot("bag-last-item-scroll");typeof(Inventory).GetField("_scroll",F).SetValue(inv,Vector2.zero);DungeonUi.Close(Inventory.BagWindow);
    foreach(string modal in new[]{SkillPanel.ModalName,BigMap.MapModal,ExplorationLog.SummaryModal}){DungeonUi.TryOpen(modal);await Task.Delay(120);await Shot(modal);DungeonUi.Close(modal);}
    foreach(var x in new[]{new{modal=LunchboxEvent.ModalName,obj=(object)lunch,field=lunchOpen},new{modal=StoryItem.ModalName,obj=(object)note,field=noteOpen},new{modal=Stake.ModalName,obj=(object)stake,field=stakeOpen}}){DungeonUi.TryOpen(x.modal);x.field.SetValue(x.obj,true);await Task.Delay(100);await Shot(x.modal);x.field.SetValue(x.obj,false);DungeonUi.Close(x.modal);}
    var night=NightCard.Instance;night.ShowResults(new ExpeditionSummary{Expedition=3,CellsVisited=12,CellsTotal=16,Chests=4,Kills=23,Level=7,StonesGained=12,GoldGained=860,DeepestFloorThisTrip=2},null);await Task.Delay(100);await Shot("result");typeof(NightCard).GetMethod("Abandon",F).Invoke(night,null);
    night.ShowLandingPicker(new[]{new LandingOption(1,"입구 갱도",1,true,1,false,false),new LandingOption(2,"물이 스미는 갱도",5,false,0,true,true)},2,null);await Task.Delay(100);await Shot("landing");typeof(NightCard).GetMethod("Abandon",F).Invoke(night,null);
    inv.ImportFrom(backup);await Shot("hud-hero-leather");
   }
   var looks=new List<object>();foreach(string n in new[]{"leather","chain","plate"}){var load=new CarryData();inv.ExportTo(load);load.Equipment[(int)GearSlot.Armor]=new GearItem("arm_"+n,Grade.Common,1,1000);load.Equipment[(int)GearSlot.Helm]=new GearItem("hlm_"+n,Grade.Common,1,1000);load.Equipment[(int)GearSlot.Gloves]=new GearItem("glv_"+n,Grade.Common,1,1000);load.Equipment[(int)GearSlot.Boots]=new GearItem("bts_"+n,Grade.Common,1,1000);inv.ImportFrom(load);await Task.Delay(180);await Shot("hero-"+n);looks.Add(new{material=n,sprites=PlayerController.Instance.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.sprite).Select(s=>new{objectName=s.name,sprite=s.sprite.name,scale=s.transform.localScale.ToString()}).ToArray()});}Results.Add(new{lookChecks=looks});
  } finally {lunchOpen.SetValue(lunch,false);noteOpen.SetValue(note,false);stakeOpen.SetValue(stake,false);DungeonUi.Close(DungeonUi.Modal);inv.ImportFrom(backup);selection.SetValue(inv,selectedBefore);TimeScaleService.Paused=paused;PlayerInputReader.Blocked=blocked;Application.runInBackground=background;selected.SetValue(view,originalIndex);foreach(var field in group.GetType().GetFields(F)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(added.Contains(list[i]))list.RemoveAt(i);}view.Repaint();}
  var result=new{captures=Results,scene=scene.path,dirtyBefore=dirty,dirtyAfter=scene.isDirty,originalViewIndex=originalIndex,restoredViewIndex=(int)selected.GetValue(view),bagRestored=inv.Bag.SequenceEqual(backup.Bag),equipmentRestored=GearSlots.All.All(s=>ReferenceEquals(inv.Equipment[s],backup.Equipment[(int)s])),modal=DungeonUi.Modal,interaction="Screen setup used explicit fixture callbacks; not a physical pointer pass."};File.WriteAllText(Root+"/visual-review.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return new{screens=Results.Count,sceneDirty=scene.isDirty,bagRestored=result.bagRestored,equipmentRestored=result.equipmentRestored};
 }
}
