using System;using System.Reflection;using System.Collections;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class HeroV4MotionCheck {
 public static async Task<object> Run(){if(!EditorApplication.isPlaying||DungeonUi.ModalOpen)throw new Exception("An unblocked Play session is required");var p=PlayerController.Instance;var input=p.GetComponent<PlayerInputReader>();var originalKb=Keyboard.current;var originalMouse=Mouse.current;var kb=InputSystem.AddDevice<Keyboard>("V4ReviewKeyboard");var mouse=InputSystem.AddDevice<Mouse>("V4ReviewMouse");bool ke=true,me=true,bg=Application.runInBackground;var start=p.Position;var poses=new HashSet<string>();var movement=new List<object>();bool open=false,escape=false,blockedAttack=false;float distance=0;var pointer=Camera.main.WorldToScreenPoint(p.transform.position)+new Vector3(260,0,0);try{Application.runInBackground=true;InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});InputSystem.QueueStateEvent(kb,new KeyboardState(Key.D));for(int i=0;i<8;i++){await Task.Delay(40);movement.Add(new{position=p.Position.ToString(),pose=p.Pose.ToString(),feet=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.sprite&&s.sprite.name.StartsWith("boot_")).Select(s=>s.transform.localPosition.ToString()).ToArray()});}InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(80);distance=Vector2.Distance(start,p.Position);
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer,buttons=1});bool shot=false;for(int i=0;i<28;i++){await Task.Delay(35);poses.Add(p.Pose.ToString());if(!shot&&p.Pose.ToString()=="Attack"){ScreenCapture.CaptureScreenshot(Path.GetFullPath("검증/비주얼-개선-v4/after/"+Screen.height+"-hero-attack-input.png"));shot=true;}}
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});await Task.Delay(300);InputSystem.QueueStateEvent(kb,new KeyboardState(Key.I));await Task.Delay(140);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);open=DungeonUi.Modal==Inventory.BagWindow;
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer,buttons=1});await Task.Delay(120);blockedAttack=open&&!input.AttackHeld&&PlayerInputReader.Blocked;InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});InputSystem.QueueStateEvent(kb,new KeyboardState(Key.Escape));await Task.Delay(140);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);escape=!DungeonUi.ModalOpen;
 }finally{InputSystem.QueueStateEvent(kb,new KeyboardState());InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});if(!ke)InputSystem.DisableDevice(kb);if(!me)InputSystem.DisableDevice(mouse);InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);if(originalKb!=null)originalKb.MakeCurrent();if(originalMouse!=null)originalMouse.MakeCurrent();p.Teleport(start);Application.runInBackground=bg;if(DungeonUi.Modal==Inventory.BagWindow)DungeonUi.Close(Inventory.BagWindow);}
 var result=new{method="Unity InputSystem temporary virtual keyboard/mouse queued events; no direct movement/attack callbacks and no physical-pointer claim",distance,movePassed=distance>.05f,poses=poses.ToArray(),attackPassed=poses.Contains("Attack"),bagKeyboardOpen=open,escapeClosed=escape,modalBlockedAttack=blockedAttack,movement,sprites=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.sprite).Select(s=>new{sprite=s.sprite.name,objectName=s.name}).ToArray()};File.WriteAllText("검증/비주얼-개선-v4/after/"+Screen.height+"-motion-input-validation.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }

 public static async Task<object> RunResolutions(){const BindingFlags f=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var a=typeof(Editor).Assembly;var t=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(t).Cast<EditorWindow>().First();var index=t.GetProperty("selectedSizeIndex",f);int original=(int)index.GetValue(view);var st=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(st).GetProperty("instance").GetValue(null);var group=st.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});var sizeType=a.GetType("UnityEditor.GameViewSize");var enumType=a.GetType("UnityEditor.GameViewSizeType");var entries=new List<object>();var results=new List<object>();try{foreach(var size in new[]{new[]{1280,720},new[]{1920,1080}}){var e=Activator.CreateInstance(sizeType,new object[]{Enum.ToObject(enumType,1),size[0],size[1],"v4 motion review"});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{e});entries.Add(e);index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(350);Camera.main.GetComponent<DungeonCamera>().Snap();results.Add(await Run());}}finally{index.SetValue(view,original);foreach(var field in group.GetType().GetFields(f)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(entries.Contains(list[i]))list.RemoveAt(i);}view.Repaint();}return results;}
}
