using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class HeroV3MotionCheck {
 public static async Task<object> Run(){if(!EditorApplication.isPlaying||DungeonUi.ModalOpen)throw new Exception("An unblocked Play session is required");var p=PlayerController.Instance;var input=p.GetComponent<PlayerInputReader>();var kb=Keyboard.current;var mouse=Mouse.current;bool ke=kb.enabled,me=mouse.enabled,bg=Application.runInBackground;var start=p.Position;var poses=new HashSet<string>();var movement=new List<object>();bool open=false,escape=false,blockedAttack=false;float distance=0;var pointer=Camera.main.WorldToScreenPoint(p.transform.position)+new Vector3(260,0,0);try{Application.runInBackground=true;InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});InputSystem.QueueStateEvent(kb,new KeyboardState(Key.D));for(int i=0;i<8;i++){await Task.Delay(40);movement.Add(new{position=p.Position.ToString(),pose=p.Pose.ToString(),feet=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.sprite&&s.sprite.name.StartsWith("boot_")).Select(s=>s.transform.localPosition.ToString()).ToArray()});}InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(80);distance=Vector2.Distance(start,p.Position);
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer,buttons=1});bool shot=false;for(int i=0;i<28;i++){await Task.Delay(35);poses.Add(p.Pose.ToString());if(!shot&&p.Pose.ToString()=="Attack"){ScreenCapture.CaptureScreenshot(Path.GetFullPath("아트/장비-UI-v3/검수/hero-attack-input.png"));shot=true;}}
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});await Task.Delay(300);InputSystem.QueueStateEvent(kb,new KeyboardState(Key.I));await Task.Delay(140);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);open=DungeonUi.Modal==Inventory.BagWindow;
  InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer,buttons=1});await Task.Delay(120);blockedAttack=open&&!input.AttackHeld&&PlayerInputReader.Blocked;InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});InputSystem.QueueStateEvent(kb,new KeyboardState(Key.Escape));await Task.Delay(140);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);escape=!DungeonUi.ModalOpen;
 }finally{InputSystem.QueueStateEvent(kb,new KeyboardState());InputSystem.QueueStateEvent(mouse,new MouseState{position=pointer});if(!ke)InputSystem.DisableDevice(kb);if(!me)InputSystem.DisableDevice(mouse);Application.runInBackground=bg;if(DungeonUi.Modal==Inventory.BagWindow)DungeonUi.Close(Inventory.BagWindow);}
 var result=new{method="Unity InputSystem queued device events; no direct movement/attack callbacks and no physical-pointer claim",distance,movePassed=distance>.05f,poses=poses.ToArray(),attackPassed=poses.Contains("Attack"),bagKeyboardOpen=open,escapeClosed=escape,modalBlockedAttack=blockedAttack,movement,sprites=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.sprite).Select(s=>new{sprite=s.sprite.name,objectName=s.name}).ToArray()};File.WriteAllText("아트/장비-UI-v3/검수/motion-input-validation.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
