using System;using System.IO;using System.Linq;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEngine.InputSystem;using Demo6.Game;
public static class InputObserve {
 public static object Read(){if(Application.dataPath.Replace("\\","/")!="E:/personalProject/Demo3/demo6/Assets")throw new Exception("Original only");
 var scene=SceneManager.GetActiveScene();var focused=EditorWindow.focusedWindow;var p=PlayerController.Instance;
 var players=UnityEngine.Object.FindObjectsByType<PlayerInput>().Select(x=>new{x.name,x.enabled,x.isActiveAndEnabled,x.currentControlScheme,actions=x.actions?x.actions.actionMaps.Select(m=>new{m.name,m.enabled}).ToArray():null,userValid=x.user.valid}).ToArray();
 var devices=InputSystem.devices.Select(d=>new{d.deviceId,d.name,d.layout,d.enabled,d.native,d.canRunInBackground,description=d.description.ToString()}).ToArray();
 var value=new{EditorApplication.isPlaying,EditorApplication.isPaused,EditorApplication.isCompiling,EditorApplication.isUpdating,scene=scene.name,scene.isDirty,Time.timeScale,Application.isFocused,Application.runInBackground,editorApplicationActive=UnityEditorInternal.InternalEditorUtility.isApplicationActive,focusedWindow=focused?focused.GetType().FullName:null,focusedTitle=focused?focused.titleContent.text:null,mouseOverWindow=EditorWindow.mouseOverWindow?EditorWindow.mouseOverWindow.GetType().FullName:null,cursorLock=Cursor.lockState.ToString(),Cursor.visible,inputUpdate=InputSystem.settings.updateMode.ToString(),backgroundBehavior=InputSystem.settings.backgroundBehavior.ToString(),keyboardCurrent=Keyboard.current?.deviceId,mouseCurrent=Mouse.current?.deviceId,devices,players,playerPresent=(bool)p,playerEnabled=p?p.isActiveAndEnabled:false,windows=Resources.FindObjectsOfTypeAll<EditorWindow>().Select(w=>new{type=w.GetType().FullName,title=w.titleContent.text}).ToArray()};
 File.WriteAllText("E:/personalProject/Demo3/demo6/검증/입력복구-20261004/input-before-ogre.json",Newtonsoft.Json.JsonConvert.SerializeObject(value,Newtonsoft.Json.Formatting.Indented));return value;}
}
