using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEngine.Rendering.Universal;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;using Object=UnityEngine.Object;
public static class OgreSlamV051Review {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/v049-final/ogre-heavy-slam";
 static object Get(object o,string n)=>o.GetType().GetField(n,F).GetValue(o);
 static object Call(object o,string n,params object[] a)=>o.GetType().GetMethod(n,F).Invoke(o,a);
 static void Capture(Camera c,string path){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(960,720,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(960,720,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,960,720),0,0);t.Apply();File.WriteAllBytes(path,t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)Object.DestroyImmediate(t);}}
 public static object Run(){if(!Application.isPlaying||!PlayerController.Instance)throw new Exception("Original live game required");if(OgreBrain.Current)throw new Exception("Existing live boss preserved; do not run temporary fixture");Directory.CreateDirectory(Out);var initial=new HashSet<GameObject>(Object.FindObjectsByType<GameObject>());var paused=EditorApplication.isPaused;var random=UnityEngine.Random.state;float volume=AudioListener.volume;var ends=(List<float>)typeof(StrongAttackSchedule).GetField("Ends",BindingFlags.Static|BindingFlags.NonPublic).GetValue(null);var savedEnds=ends.ToArray();var scalar=new Dictionary<object,Dictionary<FieldInfo,object>>();foreach(var obj in Object.FindObjectsByType<CombatStats>().Cast<object>().Concat(Object.FindObjectsByType<ScreenShake>().Cast<object>()))scalar[obj]=obj.GetType().GetFields(F).Where(f=>!f.IsInitOnly&&!f.IsLiteral&&f.FieldType.IsValueType).ToDictionary(f=>f,f=>f.GetValue(obj));var trace=new List<object>();OgreBrain o=null;OgreArtRig rig=null;Telegraph tele=null;var above=Telegraph.AboveDark;int captured=0;object result=null;
 try{EditorApplication.isPaused=true;AudioListener.volume=0;Telegraph.AboveDark=true;var player=PlayerController.Instance;var at=player.Position+Vector2.right*3;o=(OgreBrain)EnemySpawner.Create(MonsterKind.Ogre,2,at);o.NoReward=true;typeof(Enemy).GetProperty("Aware",F).SetValue(o,true);typeof(Enemy).GetField("Facing",F).SetValue(o,Vector2.down);foreach(var b in o.GetComponents<MonoBehaviour>())b.enabled=false;o.GetComponent<Rigidbody2D>().simulated=false;rig=o.GetComponentInChildren<OgreArtRig>();var fx=o.GetComponent<OgrePatternVfx>();if(!rig||!fx)throw new Exception("Existing rig/effect adapter missing");rig.enabled=false;fx.enabled=false;Call(o,"BeginSlam",Vector2.down*2);tele=(Telegraph)Get(o,"_telegraph");float windup=(float)Get(o,"_windup");var camera=new GameObject("V051 temporary slam review camera").AddComponent<Camera>();camera.enabled=false;camera.cullingMask=1<<31;foreach(var sr in rig.GetComponentsInChildren<SpriteRenderer>())RenderMaterials.MakeUnlit(sr);camera.orthographic=true;foreach(var tr in rig.GetComponentsInChildren<Transform>())tr.gameObject.layer=31;foreach(var tr in tele.GetComponentsInChildren<Transform>())tr.gameObject.layer=31;camera.orthographicSize=4.5f;camera.transform.position=(Vector3)at+new Vector3(0,-1,-10);camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.08f,.08f,.09f);var light=new GameObject("V051 temporary slam review light").AddComponent<Light2D>();light.gameObject.layer=31;light.lightType=Light2D.LightType.Global;light.pointLightOuterRadius=9;light.intensity=1.2f;light.transform.position=at;float elapsed=0;int impactTick=-1;const float dt=.025f;
 for(int i=0;i<Mathf.CeilToInt((windup+.5f)/dt);i++){string before=Get(o,"_step").ToString();Call(o,"TickSlam",dt,player,false);elapsed+=dt;rig.Sample(dt);fx.Advance(dt);string after=Get(o,"_step").ToString();if(before=="Windup"&&after=="Recover"){impactTick=i;if(fx.SlamCount!=1||fx.ActiveCount!=1)throw new Exception("Slam cue absent or duplicated at impact");if(!tele.Done)throw new Exception("Telegraph not complete at impact");}var pool=GameObject.Find("Ogre pattern effects (owned)");if(pool)foreach(var sr in pool.GetComponentsInChildren<SpriteRenderer>())RenderMaterials.MakeUnlit(sr);var visible=pool?pool.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.enabled).ToArray():new SpriteRenderer[0];trace.Add(new{tick=i,elapsed,step=after,progress=tele?tele.Progress:1,fx.SlamCount,fxActive=fx.ActiveCount,fxFrames=visible.Select(s=>new{texture=s.sprite.texture.name,textureWidth=s.sprite.texture.width,x=s.sprite.rect.x,at=s.transform.position.ToString(),scale=s.transform.localScale.ToString()}).ToArray()});if(impactTick>=0&&i-impactTick>=4&&tele){Object.DestroyImmediate(tele.gameObject);tele=null;}if(elapsed>=windup-.05f&&captured<10){Capture(camera,Out+"/frame-"+captured.ToString("00")+".png");captured++;}}
 if(impactTick<0||captured!=10||fx.SlamCount!=1||fx.ActiveCount!=0)throw new Exception("Slam timing/capture/expiry failed");result=new{passed=true,method="Original OgreBrain.TickSlam and existing rig/FX sampled synchronously at 40Hz in original scene. Dedicated review camera isolates layer31 with neutral unlit materials on temporary rig/FX for visibility (not a lighting test); resolve flash removed after four sampled ticks (~.1s). No injected input, no physical-input claim, playerUp=false prevents damage.",windup,impactTick,capturedFrames=captured,slamCueCount=fx.SlamCount,fxExpired=fx.ActiveCount==0,trace};
 }finally{if(o){typeof(OgreBrain).GetField("_fightActive",F).SetValue(o,false);Call(o,"CancelAll");}foreach(var go in Object.FindObjectsByType<GameObject>())if(go&&!initial.Contains(go))Object.DestroyImmediate(go);ends.Clear();ends.AddRange(savedEnds);foreach(var a in scalar)foreach(var f in a.Value)f.Key.SetValue(a.Key,f.Value);UnityEngine.Random.state=random;AudioListener.volume=volume;Telegraph.AboveDark=above;EditorApplication.isPaused=paused;}
 File.WriteAllText(Out+"/timing.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
