using System;using System.IO;using System.Linq;using System.Security.Cryptography;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;
public static class StyleV4Apply {
 const string Root="검증/비주얼-개선-v4", Game="Assets/Art/TopDown/PlayerV4", Sources="아트/정수리/검사-v4";static readonly string[] Names={"leather","chain","plate"};
 public sealed class Change{public string path,beforeSHA256,afterSHA256,staged;}
 public sealed class Part{public string id;public float[] pivot;}
 static string Hash(string p){using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(File.ReadAllBytes(p))).Replace("-","").ToLowerInvariant();}
 public static object Run(){if(EditorApplication.isPlaying||EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Current Play must be finished by its owner before applying v4.");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Keep the user's unsaved scene; apply only after they finish saving their own work.");const string artPath="Assets/Data/Combat/CombatArtSet.asset";var art=AssetDatabase.LoadAssetAtPath<CombatArtSet>(artPath);if(EditorUtility.IsDirty(art))throw new Exception("CombatArtSet contains unsaved edits.");
 var changes=Newtonsoft.Json.JsonConvert.DeserializeObject<Change[]>(File.ReadAllText(Root+"/staged/manifest.json"));foreach(var c in changes)if(Hash(c.path)!=c.beforeSHA256||Hash(c.staged)!=c.afterSHA256)throw new Exception("Concurrent modification requires review: "+c.path);
 var parts=Newtonsoft.Json.JsonConvert.DeserializeObject<Part[]>(File.ReadAllText(Sources+"/manifest.json"));if(Directory.Exists(Game))throw new Exception("PlayerV4 destination already exists; review before replacing.");
 foreach(string path in changes.Select(c=>c.path).Concat(new[]{artPath})){string dest=Root+"/before-production/"+path;Directory.CreateDirectory(Path.GetDirectoryName(dest));if(File.Exists(dest))throw new Exception("Backup already exists: "+dest);File.Copy(path,dest);}
 Directory.CreateDirectory(Game);foreach(var part in parts)File.Copy(Sources+"/runtime-PNG/"+part.id+".png",Game+"/"+part.id+".png");
 AssetDatabase.Refresh();foreach(var part in parts){string path=Game+"/"+part.id+".png";var t=(TextureImporter)AssetImporter.GetAtPath(path);t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.spritePixelsPerUnit=256;var settings=new TextureImporterSettings();t.ReadTextureSettings(settings);settings.spriteAlignment=(int)SpriteAlignment.Custom;settings.spritePivot=new Vector2(part.pivot[0],part.pivot[1]);settings.spriteMeshType=SpriteMeshType.FullRect;t.SetTextureSettings(settings);t.alphaIsTransparency=true;t.mipmapEnabled=true;t.filterMode=FilterMode.Trilinear;t.wrapMode=TextureWrapMode.Clamp;t.textureCompression=TextureImporterCompression.Uncompressed;t.maxTextureSize=1024;t.SaveAndReimport();}
   var p=art.topDown.player;Sprite S(string id)=>AssetDatabase.LoadAssetAtPath<Sprite>(Game+"/"+id+".png");p.scale=1;p.body=S("body_leather");p.boot=S("boot_leather");p.sleeve=S("sleeve_leather");p.fist=S("fist_leather_closed");p.armors=Names.Select(n=>new TopDownArmorArt{armorId="arm_"+n,body=S("body_"+n),sleeve=S("sleeve_"+n)}).ToArray();p.helms=Names.Select(n=>new TopDownHelmArt{helmId="hlm_"+n,sprite=S("helm_"+n)}).ToArray();p.gloves=Names.Select(n=>new TopDownGlovesArt{glovesId="glv_"+n,fistClosed=S("fist_"+n+"_closed"),fistOpen=S("fist_"+n+"_open")}).ToArray();p.boots=Names.Select(n=>new TopDownBootsArt{bootsId="bts_"+n,boot=S("boot_"+n)}).ToArray();
 art.topDown.weapons.longsword=S("longsword");EditorUtility.SetDirty(art);AssetDatabase.SaveAssetIfDirty(art);
 foreach(var c in changes)File.WriteAllBytes(c.path,File.ReadAllBytes(c.staged));AssetDatabase.Refresh();return new{parts=parts.Length,changed=changes.Select(c=>c.path).ToArray(),note="Import finished; wait for compilation, then run actual DungeonTest review and EditMode tests. No scene or save data written."};}
}
