using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Loot;using Demo6.Core.Combat;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class StyleV4CardCheck {
 const string Root="검증/비주얼-개선-v4";const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;
 public static async Task<object> Run(){if(!EditorApplication.isPlaying||!DungeonRoot.Instance||!Inventory.Instance||!Camera.main||!Camera.main.GetComponent<DungeonCamera>()||DungeonUi.ModalOpen)throw new Exception("Assistant-owned unblocked DungeonTest Play required");var p=PlayerController.Instance;var inv=Inventory.Instance;Vector2 original=p.Position;var kb=Keyboard.current;var mouse=Mouse.current;bool ke=kb.enabled,me=mouse.enabled,bg=Application.runInBackground,paused=TimeScaleService.Paused;var camera=Camera.main;var follow=camera.GetComponent<DungeonCamera>();var records=new List<object>();
  var a=typeof(Editor).Assembly;var type=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(type).Cast<EditorWindow>().First();var selected=type.GetProperty("selectedSizeIndex",F);int originalIndex=(int)selected.GetValue(view);var sizes=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(sizes).GetProperty("instance").GetValue(null);var group=sizes.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});var sizeType=a.GetType("UnityEditor.GameViewSize");var enumType=a.GetType("UnityEditor.GameViewSizeType");var added=new List<object>();var drops=new List<LootDrop>();
  async Task Shot(string name,int delay=200){ScreenCapture.CaptureScreenshot(Path.GetFullPath(Root+"/"+Screen.height+"-"+name+".png"));await Task.Delay(delay);}
  async Task Key(Key key){InputSystem.QueueStateEvent(kb,new KeyboardState(key));await Task.Delay(100);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);}
  try{Application.runInBackground=true;InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);
   foreach(var size in new[]{new[]{1280,720},new[]{1920,1080}}){object entry=Activator.CreateInstance(sizeType,new object[]{Enum.ToObject(enumType,1),size[0],size[1],"Mood review "+size[0]});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{entry});added.Add(entry);selected.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(300);
    p.Teleport(original);follow.Snap();TimeScaleService.Paused=false;InputSystem.QueueStateEvent(mouse,new MouseState{position=new Vector2(Screen.width*.6f,Screen.height*.55f)});await Task.Delay(200);await Shot("exploration");
    var drop=LootDrop.Spawn(new GearItem("rng_blood",Grade.Legendary,11,1100,10),original+Vector2.right*.8f,original+Vector2.right*.8f,0);drops.Add(drop);await Task.Delay(600);TimeScaleService.Paused=true;await Shot("ground-item-card");TimeScaleService.Paused=false;UnityEngine.Object.Destroy(drop.gameObject);drops.Remove(drop);

   }
  }finally{InputSystem.QueueStateEvent(kb,new KeyboardState());InputSystem.QueueStateEvent(mouse,new MouseState{position=new Vector2(Screen.width/2,Screen.height/2)});foreach(var d in drops)if(d)UnityEngine.Object.Destroy(d.gameObject);p.Teleport(original);if(follow)follow.Snap();if(DungeonUi.Modal==Inventory.BagWindow)DungeonUi.Close(Inventory.BagWindow);TimeScaleService.Paused=paused;Application.runInBackground=bg;if(!ke)InputSystem.DisableDevice(kb);if(!me)InputSystem.DisableDevice(mouse);selected.SetValue(view,originalIndex);foreach(var field in group.GetType().GetFields(F)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(added.Contains(list[i]))list.RemoveAt(i);}view.Repaint();}
  var result=new{records,input="Queued Unity InputSystem events, not OS mouse",fixture="Temporary floor item and relocation inside disposable Play; no save or production asset write",restoredResolution=(int)selected.GetValue(view)==originalIndex,restoredPosition=Vector2.Distance(p.Position,original)<.01f,modal=DungeonUi.Modal};File.WriteAllText(Root+"/stage1-card.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
