using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Loot;using Demo6.Core.Combat;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class StyleV4EncounterCheck {
 const string Root="검증/비주얼-개선-v4/after";const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;
 public static async Task<object> Run(){if(!EditorApplication.isPlaying||DungeonUi.ModalOpen)throw new Exception("Unblocked disposable Play required");var p=PlayerController.Instance;var inv=Inventory.Instance;Vector2 original=p.Position;var originalKb=Keyboard.current;var originalMouse=Mouse.current;var kb=InputSystem.AddDevice<Keyboard>("V4EncounterKeyboard");var mouse=InputSystem.AddDevice<Mouse>("V4EncounterMouse");bool ke=true,me=true,bg=Application.runInBackground,paused=TimeScaleService.Paused;var camera=Camera.main;var follow=camera.GetComponent<DungeonCamera>();var records=new List<object>();
  var a=typeof(Editor).Assembly;var type=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(type).Cast<EditorWindow>().First();var selected=type.GetProperty("selectedSizeIndex",F);int originalIndex=(int)selected.GetValue(view);var sizes=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(sizes).GetProperty("instance").GetValue(null);var group=sizes.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});var sizeType=a.GetType("UnityEditor.GameViewSize");var enumType=a.GetType("UnityEditor.GameViewSizeType");var added=new List<object>();var drops=new List<LootDrop>();
  async Task Shot(string name,int delay=200){ScreenCapture.CaptureScreenshot(Path.GetFullPath(Root+"/"+Screen.height+"-"+name+".png"));await Task.Delay(delay);}
  async Task Key(Key key){InputSystem.QueueStateEvent(kb,new KeyboardState(key));await Task.Delay(100);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);}
  try{Application.runInBackground=true;InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);
   foreach(var size in new[]{new[]{1280,720},new[]{1920,1080}}){object entry=Activator.CreateInstance(sizeType,new object[]{Enum.ToObject(enumType,1),size[0],size[1],"Mood review "+size[0]});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{entry});added.Add(entry);selected.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(300);
    p.Teleport(original);follow.Snap();TimeScaleService.Paused=false;InputSystem.QueueStateEvent(mouse,new MouseState{position=new Vector2(Screen.width*.6f,Screen.height*.55f)});await Task.Delay(200);
    var enemy=Enemy.All.Where(e=>e&&!e.Dead&&!e.IsDummy&&e.Kind==MonsterKind.Rat).OrderBy(e=>Vector2.Distance(e.Position,new Vector2(30,16))).First();var target=enemy.Position;p.Teleport(target+Vector2.left*1.05f);follow.Snap();await Task.Delay(150);records.Add(new{screen=Screen.height,encounter="Existing generated rat; player placed nearby for inspection, no map traversal claim",player=p.Position.ToString(),enemy=target.ToString(),enemyHp=enemy.Health.Current});
    for(int i=0;i<9;i++){if(enemy&&!enemy.Dead)target=enemy.Position;var point=camera.WorldToScreenPoint(target);InputSystem.QueueStateEvent(mouse,new MouseState{position=point,buttons=1});await Task.Delay(60);records.Add(new{screen=Screen.height,frame=i,pose=p.Pose.ToString(),combo=p.ComboIndex,poseTime=p.PoseTime,enemyAlive=enemy&&!enemy.Dead,enemyHp=enemy?enemy.Health.Current:0,weaponAngle=p.transform.Find("TopDown/WeaponR").eulerAngles.z});await Shot("combat-"+i.ToString("00"),80);}
    InputSystem.QueueStateEvent(mouse,new MouseState{position=new Vector2(Screen.width/2,Screen.height/2)});await Task.Delay(120);p.Teleport(original);follow.Snap();
   }
  }finally{InputSystem.QueueStateEvent(kb,new KeyboardState());InputSystem.QueueStateEvent(mouse,new MouseState{position=new Vector2(Screen.width/2,Screen.height/2)});foreach(var d in drops)if(d)UnityEngine.Object.Destroy(d.gameObject);p.Teleport(original);follow.Snap();if(DungeonUi.Modal==Inventory.BagWindow)DungeonUi.Close(Inventory.BagWindow);TimeScaleService.Paused=paused;Application.runInBackground=bg;InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);if(originalKb!=null)originalKb.MakeCurrent();if(originalMouse!=null)originalMouse.MakeCurrent();selected.SetValue(view,originalIndex);foreach(var field in group.GetType().GetFields(F)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(added.Contains(list[i]))list.RemoveAt(i);}view.Repaint();}
  var result=new{records,input="Temporary virtual keyboard/mouse through InputSystem, not physical OS input",fixture="Temporary floor item and relocation inside disposable Play; no save or production asset write",restoredResolution=(int)selected.GetValue(view)==originalIndex,restoredPosition=Vector2.Distance(p.Position,original)<.01f,modal=DungeonUi.Modal};File.WriteAllText(Root+"/encounter-review.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
