using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;
public static class TelegraphV051Review {
 const string Out="검증/v049-final";
 static void Capture(Camera c,string n){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1280,720,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(1280,720,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,1280,720),0,0);t.Apply();File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)UnityEngine.Object.DestroyImmediate(t);}}
 public static object Run(){if(!Application.isPlaying||!PlayerController.Instance)throw new Exception("Original live game required");var camera=Camera.main;var pos=camera.transform.position;var size=camera.orthographicSize;var paused=EditorApplication.isPaused;var above=Telegraph.AboveDark;var owner=Telegraph.CreatingOwner;var shapes=new List<Telegraph>();var checks=new List<object>();try{EditorApplication.isPaused=true;Telegraph.CreatingOwner=null;Telegraph.AboveDark=true;var at=(Vector2)PlayerController.Instance.transform.position+Vector2.right*2;camera.transform.position=new Vector3(at.x,at.y,pos.z);camera.orthographicSize=4f;
 foreach(string shape in new[]{"circle","half","rect"}){var t=shape=="circle"?Telegraph.Circle(at,BossRules.SlamRadius,1f):shape=="half"?Telegraph.HalfDisc(at,Vector2.right,BossRules.SweepRadius,1f):Telegraph.Rect(at-Vector2.right*3,Vector2.right,6,2,1);shapes.Add(t);t.Drive(.75f);var renderers=t.GetComponentsInChildren<SpriteRenderer>();checks.Add(new{shape,progress=t.Progress,renderers=renderers.Select(r=>new{r.name,sprite=r.sprite.name,texture=r.sprite.texture.name,bounds=r.bounds.size.ToString(),color=r.color.ToString(),r.sortingOrder}).ToArray(),innerIncluded=t.Contains(at+Vector2.right*(shape=="half"?3.199f:2.999f),0),outerExcluded=!t.Contains(at+Vector2.right*(shape=="half"?3.201f:3.001f),0)});Capture(camera,"telegraph-"+shape+"-75");t.Drive(1f);Capture(camera,"telegraph-"+shape+"-100");UnityEngine.Object.DestroyImmediate(t.gameObject);}
 foreach(string shape in new[]{"circle","half","rect"})foreach(string part in new[]{"fill","outline"}){string path="Assets/Resources/TelegraphV31/"+shape+"-"+part+".png";var tex=new Texture2D(2,2);try{tex.LoadImage(File.ReadAllBytes(path));var samples=new[]{0f,.25f,.5f,.75f,.93f,.98f}.Select(r=>new{radius=r,alpha=tex.GetPixel(Mathf.Clamp(Mathf.FloorToInt(tex.width*(.5f+.5f*r)),0,tex.width-1),tex.height/2).a}).ToArray();checks.Add(new{type="sourceAlpha",shape,part,tex.width,tex.height,samples});}finally{UnityEngine.Object.DestroyImmediate(tex);}}
 }finally{foreach(var t in shapes)if(t)UnityEngine.Object.DestroyImmediate(t.gameObject);Telegraph.AboveDark=above;Telegraph.CreatingOwner=owner;camera.transform.position=pos;camera.orthographicSize=size;EditorApplication.isPaused=paused;}
 var result=new{method="Original Unity world render of temporary visual telegraphs; no damage or input. Camera, global flags and pause restored; temporary shapes destroyed.",checks};File.WriteAllText(Out+"/telegraph-final.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
