using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.InputSystem;using UnityEngine.SceneManagement;using Demo6.Game;
public static class TextureV7Audit {
 public static object Run(string label="restart") {
  var studies=UnityEngine.Object.FindObjectsByType<TextureStudyV7>();var player=PlayerController.Instance;var sprites=UnityEngine.Object.FindObjectsByType<SpriteRenderer>();var cape=player?player.GetComponentInChildren<TopDownCape>():null;var block=new MaterialPropertyBlock();if(cape)cape.GetComponent<MeshRenderer>().GetPropertyBlock(block);
  string PathOf(Transform t){string p=t.name;while(t.parent){t=t.parent;p=t.name+"/"+p;}return p;}
  var result=new{label,project=Application.dataPath,unity=Application.unityVersion,playing=EditorApplication.isPlaying,paused=EditorApplication.isPaused,scene=SceneManager.GetActiveScene().name,dirty=SceneManager.GetActiveScene().isDirty,studies=studies.Select(v=>new{path=PathOf(v.transform),renderers=v.RendererCount,enabled=v.PreviewEnabled}).ToArray(),pilotWalls=sprites.Where(v=>v.sprite&&v.sprite.name=="V7 study wall").Select(v=>PathOf(v.transform)).ToArray(),remainingOriginalWalls=sprites.Count(v=>v.sprite&&v.sprite.name=="Dungeon wall"),hero=player?player.GetComponentsInChildren<SpriteRenderer>().Where(v=>v.sprite).Select(v=>new{v.name,sprite=AssetDatabase.GetAssetPath(v.sprite),ppu=v.sprite.pixelsPerUnit,pivot=v.sprite.pivot.ToString()}).ToArray():null,capeTexture=cape?AssetDatabase.GetAssetPath(block.GetTexture("_MainTex")):null,temporaryDevices=InputSystem.devices.Where(v=>v.name.StartsWith("V7Review")).Select(v=>v.name).ToArray(),input=InputSystem.settings?new{background=InputSystem.settings.backgroundBehavior.ToString(),editor=InputSystem.settings.editorInputBehaviorInPlayMode.ToString()}:null};
  Directory.CreateDirectory("검증/텍스처-시범-v7");File.WriteAllText("검증/텍스처-시범-v7/"+label+"-audit.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
