using System;using System.IO;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Newtonsoft.Json.Linq;
public static class TextureV7Import {
 const string Root="아트/텍스처-시범-v7";
 public static object Run(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");var set=AssetDatabase.LoadAssetAtPath<CombatArtSet>("Assets/Data/Combat/CombatArtSet.asset");if(EditorUtility.IsDirty(set))throw new Exception("Unsaved CombatArtSet preserved");var report=new List<object>();foreach(var part in JArray.Parse(File.ReadAllText(Root+"/manifest.json"))){string id=(string)part["id"];int w=(int)part["width"],h=(int)part["height"],n=(int)part["downsample"];bool ground=(int)part["runtimePPU"]==16;string dest=ground?"Assets/Resources/TextureStudyV7":"Assets/Art/TextureStudyV7/Hero";Directory.CreateDirectory(dest);byte[] rgba=File.ReadAllBytes(Root+"/layers/"+id+"/composite.rgba");var pixels=new Color32[w*h/n/n];Texture2D original=null;
 if(!ground){string old="Assets/Art/TopDown/"+(id=="short_cape"?"PlayerV5/":"PlayerV4/")+id+".png";Directory.CreateDirectory("검증/텍스처-시범-v7/baseline/hero");File.Copy(old,"검증/텍스처-시범-v7/baseline/hero/"+id+".png",true);original=new Texture2D(2,2);original.LoadImage(File.ReadAllBytes(old));}
 var oldPx=original?original.GetPixels32():null;int alphaDifferences=0;
 for(int y=0;y<h/n;y++)for(int x=0;x<w/n;x++){long r=0,g=0,b=0,a=0;for(int j=0;j<n;j++)for(int i=0;i<n;i++){int at=((h-1-(n*y+j))*w+n*x+i)*4;int alpha=rgba[at+3];r+=rgba[at]*alpha;g+=rgba[at+1]*alpha;b+=rgba[at+2]*alpha;a+=alpha;}var value=a>0?new Color32((byte)((r+a/2)/a),(byte)((g+a/2)/a),(byte)((b+a/2)/a),(byte)((a+n*n/2)/(n*n))):new Color32();int index=y*w/n+x;if(oldPx!=null){if(value.a!=oldPx[index].a)alphaDifferences++;value.a=oldPx[index].a;}pixels[index]=value;}
 var texture=new Texture2D(w/n,h/n,TextureFormat.RGBA32,false);texture.SetPixels32(pixels);texture.Apply();byte[] png=texture.EncodeToPNG();string file=dest+"/"+id+".png";File.WriteAllBytes(Root+"/runtime-PNG/"+id+".png",png);File.WriteAllBytes(file,png);UnityEngine.Object.DestroyImmediate(texture);if(original)UnityEngine.Object.DestroyImmediate(original);AssetDatabase.ImportAsset(file);var importer=(TextureImporter)AssetImporter.GetAtPath(file);importer.textureType=TextureImporterType.Sprite;importer.spriteImportMode=SpriteImportMode.Single;importer.spritePixelsPerUnit=(int)part["runtimePPU"];importer.isReadable=id=="wall_tile";importer.mipmapEnabled=!ground;importer.filterMode=ground?FilterMode.Bilinear:FilterMode.Trilinear;importer.wrapMode=TextureWrapMode.Clamp;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.sRGBTexture=true;importer.alphaIsTransparency=true;importer.maxTextureSize=2048;var settings=new TextureImporterSettings();importer.ReadTextureSettings(settings);settings.spriteMeshType=SpriteMeshType.FullRect;settings.spriteAlignment=(int)SpriteAlignment.Custom;settings.spritePivot=new Vector2((float)part["pivot"][0],(float)part["pivot"][1]);importer.SetTextureSettings(settings);importer.SaveAndReimport();report.Add(new{id,width=w/n,height=h/n,runtimePPU=(int)part["runtimePPU"],nativeAlphaRoundingDifferences=alphaDifferences,runtimeAlphaPreserved=!ground});}
 Sprite S(string id)=>AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/TextureStudyV7/Hero/"+id+".png");set.topDown.player.body=S("body_leather");set.topDown.player.sleeve=S("sleeve_leather");foreach(var armor in set.topDown.player.armors)if(armor.armorId=="arm_leather"){armor.body=S("body_leather");armor.sleeve=S("sleeve_leather");}set.topDown.player.cape=S("short_cape");set.topDown.weapons.longsword=S("longsword");EditorUtility.SetDirty(set);AssetDatabase.SaveAssetIfDirty(set);File.WriteAllText(Root+"/export-validation.json",Newtonsoft.Json.JsonConvert.SerializeObject(report,Newtonsoft.Json.Formatting.Indented));return report;}
}
