using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using Demo6.Game;
public static class TextureV7Review {
 public static async Task<object> Run(int height=720){if(!EditorApplication.isPlaying||!DungeonRoot.Instance||!PlayerController.Instance||DungeonUi.ModalOpen||!UnityEngine.Object.FindAnyObjectByType<TextureStudyV7>())throw new Exception("Unblocked Play required");EditorApplication.LockReloadAssemblies();const BindingFlags flags=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var a=typeof(Editor).Assembly;var t=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(t).Cast<EditorWindow>().FirstOrDefault() ?? EditorWindow.GetWindow(t);var index=t.GetProperty("selectedSizeIndex",flags);int oldIndex=(int)index.GetValue(view);var st=a.GetType("UnityEditor.GameViewSizes");var sizes=typeof(ScriptableSingleton<>).MakeGenericType(st).GetProperty("instance").GetValue(null);var group=st.GetMethod("GetGroup").Invoke(sizes,new object[]{GameViewSizeGroupType.Standalone});var entry=Activator.CreateInstance(a.GetType("UnityEditor.GameViewSize"),new object[]{Enum.ToObject(a.GetType("UnityEditor.GameViewSizeType"),1),height==720?1280:1920,height,"V7 temporary review"});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{entry});
 var settings=InputSystem.settings;if(!settings){settings=ScriptableObject.CreateInstance<InputSettings>();settings.hideFlags=HideFlags.HideAndDontSave;InputSystem.settings=settings;}string settingsPath=AssetDatabase.GetAssetPath(settings);var saved=UnityEngine.Object.Instantiate(settings);saved.hideFlags=HideFlags.HideAndDontSave;var review=UnityEngine.Object.Instantiate(settings);InputSystem.settings=review;review.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;review.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;var native=InputSystem.devices.Where(d=>d is Keyboard||d is Mouse).Select(d=>new{d,enabled=d.enabled}).ToArray();var oldK=Keyboard.current;var oldM=Mouse.current;var kb=InputSystem.AddDevice<Keyboard>("V7ReviewKeyboard");var mouse=InputSystem.AddDevice<Mouse>("V7ReviewMouse");Action current=()=>{kb.MakeCurrent();mouse.MakeCurrent();};InputSystem.onAfterUpdate+=current;
 var d=DungeonRoot.Instance;var p=PlayerController.Instance;var origin=p.Position;var art=d.ProjectArt;var oldArt=UnityEngine.Object.Instantiate(art);Sprite Before(string id)=>AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/TopDown/"+(id=="short_cape"?"PlayerV5/":"PlayerV4/")+id+".png");oldArt.topDown.player.body=Before("body_leather");oldArt.topDown.player.sleeve=Before("sleeve_leather");oldArt.topDown.player.cape=Before("short_cape");oldArt.topDown.weapons.longsword=Before("longsword");foreach(var armor in oldArt.topDown.player.armors)if(armor.armorId=="arm_leather"){armor.body=Before("body_leather");armor.sleeve=Before("sleeve_leather");}var artField=typeof(DungeonRoot).GetField("projectArt",flags);var study=UnityEngine.Object.FindAnyObjectByType<TextureStudyV7>();if(!study)throw new Exception("Expected one-room texture pilot");var rows=new List<object>();var frozen=new List<object>();var errors=new List<string>();Application.LogCallback log=(m,s,kind)=>{if(kind==LogType.Exception||kind==LogType.Error)errors.Add(m);};Application.logMessageReceived+=log;string root="검증/텍스처-시범-v7/paired/"+height;Directory.CreateDirectory(root);
 string Walls()=>string.Join("|",UnityEngine.Object.FindObjectsByType<BoxCollider2D>().Where(c=>c.gameObject.layer==Layers.Wall).OrderBy(c=>c.GetEntityId().ToString()).Select(c=>c.GetEntityId().ToString()+":"+c.transform.position+":"+c.size));string initialWalls=Walls();
 void Point(Vector2 at)=>InputSystem.QueueStateEvent(mouse,new MouseState{position=at});
 async Task Shot(string name){if(name.StartsWith("frozen-")){int width=height==720?1280:1920;var cam=Camera.main;var target=cam.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(width,height,24);Texture2D tex=null;try{cam.targetTexture=rt;cam.Render();RenderTexture.active=rt;tex=new Texture2D(width,height,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,width,height),0,0);tex.Apply();File.WriteAllBytes(root+"/"+name+".png",tex.EncodeToPNG());}finally{cam.targetTexture=target;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(tex)UnityEngine.Object.DestroyImmediate(tex);}}else ScreenCapture.CaptureScreenshot(Path.GetFullPath(root+"/"+name+".png"));rows.Add(new{name,frame=Time.frameCount,position=p.Position.ToString(),camera=Camera.main.transform.position.ToString(),size=Camera.main.orthographicSize,weapon=p.Weapon.id,pose=p.Pose.ToString(),pilot=study.PreviewEnabled,cape=p.GetComponentInChildren<TopDownCape>().TailLag});await Task.Delay(170);}
 try{foreach(var device in native)if(device.enabled)InputSystem.DisableDevice(device.d);InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);current();index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(300);
 foreach(bool after in new[]{false,true}){artField.SetValue(d,after?art:oldArt);study.SetPreview(after);p.Teleport(new Vector2(-8f,11.4f));Camera.main.GetComponent<DungeonCamera>().Snap();Point(new Vector2(Screen.width*.5f,Screen.height*.23f));await Task.Delay(700);string mode=after?"after":"before";await Shot(mode+"-wall-floor-down");Point(new Vector2(Screen.width*.75f,Screen.height*.5f));await Task.Delay(500);await Shot(mode+"-hero-right");InputSystem.QueueStateEvent(kb,new KeyboardState(Key.D));for(int i=0;i<6;i++){await Task.Delay(70);await Shot(mode+"-move-"+i);}InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(500);await Shot(mode+"-stopped");}
 foreach(string direction in new[]{"down","right"}){artField.SetValue(d,art);study.SetPreview(true);p.Teleport(new Vector2(-8f,11.4f));Camera.main.GetComponent<DungeonCamera>().Snap();Point(direction=="down"?new Vector2(Screen.width*.5f,Screen.height*.23f):new Vector2(Screen.width*.75f,Screen.height*.5f));await Task.Delay(700);bool paused=EditorApplication.isPaused;EditorApplication.isPaused=true;
 var ids=new[]{"body_leather","sleeve_leather","longsword"};var replacements=ids.Select(id=>new {Old=Before(id),New=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/TextureStudyV7/Hero/"+id+".png")}).ToArray();var sprites=p.GetComponentsInChildren<SpriteRenderer>().Select(sr=>new{sr,source=sr.sprite}).Where(v=>replacements.Any(m=>m.New==v.source)).ToArray();var cape=p.GetComponentInChildren<TopDownCape>().GetComponent<MeshRenderer>();var savedBlock=new MaterialPropertyBlock();cape.GetPropertyBlock(savedBlock);var oldBlock=new MaterialPropertyBlock();cape.GetPropertyBlock(oldBlock);oldBlock.SetTexture("_MainTex",Before("short_cape").texture);
 string Lights()=>string.Join("|",UnityEngine.Object.FindObjectsByType<UnityEngine.Rendering.Universal.Light2D>().OrderBy(l=>l.GetEntityId().ToString()).Select(l=>l.GetEntityId()+":"+l.intensity+":"+l.transform.position));string lightState=Lights();int startFrame=Time.frameCount;
 try{foreach(bool after in new[]{false,true}){study.SetPreview(after);foreach(var v in sprites)v.sr.sprite=after?v.source:replacements.First(m=>m.New==v.source).Old;cape.SetPropertyBlock(after?savedBlock:oldBlock);view.Repaint();await Task.Delay(250);await Shot((after?"frozen-after-":"frozen-before-")+direction);}
 frozen.Add(new{direction,frameStart=startFrame,frameEnd=Time.frameCount,spriteRenderers=sprites.Length,capeMeshVertices=cape.GetComponent<MeshFilter>().sharedMesh.vertexCount,lightsIdentical=lightState==Lights(),pausedFrame=EditorApplication.isPaused,method="Unity paused; direct sprite and cape property-block texture swap only. No light/vision/shader edits. Existing mesh and transforms are held. Immediate camera render; overlay HUD excluded from these frozen pairs; full HUD is present in ordinary gameplay captures."});
 }finally{foreach(var v in sprites)v.sr.sprite=v.source;cape.SetPropertyBlock(savedBlock);study.SetPreview(true);EditorApplication.isPaused=paused;}}

 }finally{InputSystem.QueueStateEvent(kb,new KeyboardState());artField.SetValue(d,art);study.SetPreview(true);p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();Application.logMessageReceived-=log;InputSystem.onAfterUpdate-=current;InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);foreach(var device in native)if(device.enabled)InputSystem.EnableDevice(device.d);oldK?.MakeCurrent();oldM?.MakeCurrent();InputSystem.settings=string.IsNullOrEmpty(settingsPath)?(settings?settings:saved):AssetDatabase.LoadAssetAtPath<InputSettings>(settingsPath);index.SetValue(view,oldIndex);foreach(var field in group.GetType().GetFields(flags)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(ReferenceEquals(list[i],entry))list.RemoveAt(i);}view.Repaint();UnityEngine.Object.Destroy(oldArt);EditorApplication.UnlockReloadAssemblies();}
 var result=new{height,rows,frozen,errors,wallsUnchanged=initialWalls==Walls(),studyRenderers=study.RendererCount,scope="1F E cell only; unchanged renderer materials, tint, transforms, colliders, lights and vision. Character baseline and revised assets switched in the same Play session.",input="Temporary virtual InputSystem keyboard/mouse; physical input not claimed",limits="Same camera, position, equipment and lighting parameters. Ambient flicker and idle animation continue between captures; images are not pixel-identical frame freezes."};File.WriteAllText(root+"/review.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return new{height,shots=rows.Count,frozen,errors,wallsUnchanged=result.wallsUnchanged,studyRenderers=study.RendererCount};}
}
