using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using UnityEngine.InputSystem;using UnityEngine.Rendering.Universal;using Demo6.Game;
public static class TextureV8Review {
 const string Evidence="E:/personalProject/Demo3/demo6/검증/텍스처-구조-v8";
 class Pair{public SpriteRenderer renderer;public Sprite v7,v8;}
 static Texture2D Png(string id){var t=new Texture2D(2,2,TextureFormat.RGBA32,false);t.LoadImage(File.ReadAllBytes(Evidence+"/baseline/"+id+".png"));t.filterMode=FilterMode.Bilinear;t.wrapMode=TextureWrapMode.Clamp;return t;}
 static int Wrap(int v,int n)=>(v%n+n)%n;
 static void CameraShot(string path,int width,int height){var c=Camera.main;var previous=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(width,height,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(width,height,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,width,height),0,0);t.Apply();File.WriteAllBytes(path,t.EncodeToPNG());}finally{c.targetTexture=previous;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)UnityEngine.Object.DestroyImmediate(t);}}
 public static async Task<object> Run(int height=720){
  if(!Application.dataPath.Contains("texture-v8-review-isolated")||!EditorApplication.isPlaying||!DungeonRoot.Instance||!PlayerController.Instance||DungeonUi.ModalOpen)throw new Exception("Owned isolated DungeonTest Play required");
  var study=UnityEngine.Object.FindAnyObjectByType<TextureStudyV7>();if(!study||study.RendererCount!=8)throw new Exception("Expected v7 pilot scope");
  const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var assembly=typeof(Editor).Assembly;var gt=assembly.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(gt).Cast<EditorWindow>().FirstOrDefault()??EditorWindow.GetWindow(gt);var index=gt.GetProperty("selectedSizeIndex",F);int previousIndex=(int)index.GetValue(view);var st=assembly.GetType("UnityEditor.GameViewSizes");var sizes=typeof(ScriptableSingleton<>).MakeGenericType(st).GetProperty("instance").GetValue(null);var group=st.GetMethod("GetGroup").Invoke(sizes,new object[]{GameViewSizeGroupType.Standalone});int width=height==720?1280:1920;var entry=Activator.CreateInstance(assembly.GetType("UnityEditor.GameViewSize"),new object[]{Enum.ToObject(assembly.GetType("UnityEditor.GameViewSizeType"),1),width,height,"V8 temporary review"});
  var p=PlayerController.Instance;var origin=p.Position;bool paused=EditorApplication.isPaused;var devices=InputSystem.devices.Where(v=>v is Keyboard||v is Mouse).Select(v=>new{v,enabled=v.enabled}).ToArray();var owned=new List<UnityEngine.Object>();var pairs=new List<Pair>();var rows=new List<object>();var errors=new List<string>();string root=Evidence+"/paired/"+height;Directory.CreateDirectory(root);
  string WallState()=>string.Join("|",UnityEngine.Object.FindObjectsByType<BoxCollider2D>().Where(v=>v.gameObject.layer==Layers.Wall).OrderBy(v=>v.GetEntityId().ToString()).Select(v=>v.GetEntityId()+":"+v.transform.position+":"+v.size));
  string LightState()=>string.Join("|",UnityEngine.Object.FindObjectsByType<Light2D>().OrderBy(v=>v.GetEntityId().ToString()).Select(v=>v.GetEntityId()+":"+v.intensity+":"+v.color+":"+v.transform.position));
  string walls=WallState();Application.LogCallback log=(m,s,k)=>{if(k==LogType.Exception||k==LogType.Error)errors.Add(m);};Application.logMessageReceived+=log;EditorApplication.LockReloadAssemblies();
  try {
   var floor=Png("entry_floor");var tile=Png("wall_tile");owned.Add(floor);owned.Add(tile);var src=tile.GetPixels32();var floorSprite=Sprite.Create(floor,new Rect(0,0,floor.width,floor.height),Vector2.one*.5f,16,0,SpriteMeshType.FullRect);owned.Add(floorSprite);var fr=study.GetComponent<SpriteRenderer>();pairs.Add(new Pair{renderer=fr,v7=floorSprite,v8=fr.sprite});
   foreach(var sr in study.transform.parent.GetComponentsInChildren<SpriteRenderer>()){if(!sr.sprite||sr.sprite.name!="V7 study wall")continue;var bounds=sr.bounds;int w=Mathf.RoundToInt(bounds.size.x*16),h=Mathf.RoundToInt(bounds.size.y*16),x0=Mathf.RoundToInt(bounds.min.x*16),y0=Mathf.RoundToInt(bounds.min.y*16);var pixels=new Color32[w*h];for(int y=0;y<h;y++)for(int x=0;x<w;x++)pixels[y*w+x]=src[Wrap(y0+y,tile.height)*tile.width+Wrap(x0+x,tile.width)];var tex=new Texture2D(w,h,TextureFormat.RGBA32,false){filterMode=FilterMode.Bilinear,wrapMode=TextureWrapMode.Clamp};tex.SetPixels32(pixels);tex.Apply();owned.Add(tex);var s=Sprite.Create(tex,new Rect(0,0,w,h),Vector2.one*.5f,16,0,SpriteMeshType.FullRect);owned.Add(s);pairs.Add(new Pair{renderer=sr,v7=s,v8=sr.sprite});}
   if(pairs.Count!=8)throw new Exception("Pilot renderer scope differs");foreach(var d in devices)if(d.enabled)InputSystem.DisableDevice(d.v);group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{entry});index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(350);
   var spots=new[]{new{name="pillar",at=new Vector2(-8f,11.4f)},new{name="wall-corner",at=new Vector2(-11.4f,10.5f)}};
   foreach(var spot in spots){foreach(var q in pairs)q.renderer.sprite=q.v8;p.Teleport(spot.at);Camera.main.GetComponent<DungeonCamera>().Snap();await Task.Delay(650);EditorApplication.isPaused=true;int frame=Time.frameCount;string light=LightState();
    try{foreach(bool after in new[]{false,true}){foreach(var q in pairs)q.renderer.sprite=after?q.v8:q.v7;CameraShot(root+"/"+spot.name+(after?"-v8":"-v7")+".png",width,height);}rows.Add(new{spot=spot.name,position=p.Position.ToString(),camera=Camera.main.transform.position.ToString(),size=Camera.main.orthographicSize,frameStart=frame,frameEnd=Time.frameCount,lightsIdentical=light==LightState(),rendererCount=pairs.Count});}
    finally{foreach(var q in pairs)q.renderer.sprite=q.v8;EditorApplication.isPaused=false;}
    view.Repaint();await Task.Delay(200);ScreenCapture.CaptureScreenshot(root+"/"+spot.name+"-v8-game.png");await Task.Delay(300);
   }
  }finally{foreach(var q in pairs)if(q.renderer)q.renderer.sprite=q.v8;p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();EditorApplication.isPaused=paused;foreach(var d in devices)if(d.enabled)InputSystem.EnableDevice(d.v);index.SetValue(view,previousIndex);foreach(var field in group.GetType().GetFields(F)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(ReferenceEquals(list[i],entry))list.RemoveAt(i);}view.Repaint();foreach(var o in owned)if(o)UnityEngine.Object.Destroy(o);Application.logMessageReceived-=log;EditorApplication.UnlockReloadAssemblies();}
  var result=new{height,width,rows,errors,wallsUnchanged=walls==WallState(),method="Same paused frame, camera and unchanged lights. Texture-only v7/v8 swap for 8 environment renderers; hero remains v7. Paired camera renders omit Overlay HUD. Separate -game.png captures include HUD in ordinary Play.",devicesModified="Native keyboard/mouse temporarily disabled only in isolated editor, original enabled states restored; no virtual devices or InputSettings edits."};File.WriteAllText(root+"/review.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
