using System;using System.Reflection;using System.Collections;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Dungeon;using Demo6.Core.Progression;using Demo6.Core.Combat;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class UsabilityV5Actions {
public static async Task<object> Run(){
var p=PlayerController.Instance;var inv=Inventory.Instance;var progress=PlayerProgress.Instance;var carry=new CarryData();progress.ExportTo(carry);inv.ExportTo(carry);var origin=p.Position;var originalSettings=InputSystem.settings;var settings=UnityEngine.Object.Instantiate(originalSettings);var originalPath=AssetDatabase.GetAssetPath(originalSettings);var reviewSettings=UnityEngine.Object.Instantiate(originalSettings);InputSystem.settings=reviewSettings;reviewSettings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;var oldK=Keyboard.current;var oldM=Mouse.current;var native=InputSystem.devices.Where(d=>d is Keyboard||d is Mouse).Select(d=>new{d,d.enabled}).ToArray();var kb=InputSystem.AddDevice<Keyboard>("V5ActionKeyboard");var mouse=InputSystem.AddDevice<Mouse>("V5ActionMouse");Action current=()=>{kb.MakeCurrent();mouse.MakeCurrent();};var bg=InputSystem.settings.backgroundBehavior;var rows=new List<object>();string root="검증/플레이-사용성-v5/after/"+Screen.height+"-";
async Task Press(Key key){InputSystem.QueueStateEvent(kb,new KeyboardState(key));await Task.Delay(90);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);}
async Task Shot(string name){ScreenCapture.CaptureScreenshot(Path.GetFullPath(root+name+".png"));await Task.Delay(150);}
void Point(Vector2 pos,int buttons=0)=>InputSystem.QueueStateEvent(mouse,new MouseState{position=pos,buttons=(ushort)buttons});
try{InputSystem.onAfterUpdate+=current;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;foreach(var d in native)if(d.enabled)InputSystem.DisableDevice(d.d);InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);current();Point(new Vector2(Screen.width*.68f,Screen.height*.5f));await Task.Delay(100);
await Press(Key.Q);await Shot("actionbar-wave-cooldown");rows.Add(new{check="wave",remaining=p.WaveCooldown,max=p.WaveCooldownMax,passed=p.WaveCooldown>0});
Point(new Vector2(Screen.width*.68f,Screen.height*.5f),2);await Task.Delay(140);Point(new Vector2(Screen.width*.68f,Screen.height*.5f));await Shot("actionbar-whirl-cooldown");rows.Add(new{check="whirl",remaining=p.WhirlCooldown,max=p.WhirlCooldownMax,passed=p.WhirlCooldown>0});
await Task.Delay(500);await Press(Key.Space);await Shot("actionbar-dodge-cooldown");rows.Add(new{check="dodge",remaining=p.DodgeCooldown,max=p.DodgeCooldownMax,passed=p.DodgeCooldown>0});
// 2레벨/1점 검증용 상태를 공개 Import로 넣고, 강화는 실제 Enter 입력으로만 실행. 원래 진행 상태는 finally에서 복원.
var fixture=new CarryData{Level=2,TotalXp=340,SkillPoints=1,SkillRanks=new int[4]};progress.ImportFrom(fixture);await Press(Key.K);var panel=UnityEngine.Object.FindAnyObjectByType<SkillPanel>();int before=progress.Rank(panel.SelectedSkill);await Shot("skill-upgrade-ready");await Press(Key.Enter);await Shot("skill-upgrade-spent");rows.Add(new{check="rank-up",selected=panel.SelectedSkill.ToString(),before,after=progress.Rank(panel.SelectedSkill),points=progress.SkillPoints,passed=progress.Rank(panel.SelectedSkill)==before+1&&progress.SkillPoints==0});await Press(Key.Escape);progress.ImportFrom(carry);inv.ImportFrom(carry);
foreach(var key in new[]{Key.Digit1,Key.Digit2,Key.Digit3}){await Press(key);var enemy=Enemy.All.Where(e=>e&&!e.Dead&&!e.IsDummy&&e.Kind==MonsterKind.Rat).OrderBy(e=>Vector2.Distance(e.Position,origin)).First();int hp=enemy.Health.Current;p.Teleport(enemy.Position+Vector2.left*1.0f);Camera.main.GetComponent<DungeonCamera>().Snap();await Task.Delay(100);for(int i=0;i<8;i++){if(enemy&&!enemy.Dead)Point(Camera.main.WorldToScreenPoint(enemy.Position),1);await Task.Delay(90);if(i==2||i==5)await Shot("hit-"+p.Weapon.id+"-"+i);}Point(new Vector2(Screen.width*.7f,Screen.height*.5f));rows.Add(new{check="enemy-hit",weapon=p.Weapon.id,hpBefore=hp,hpAfter=enemy?enemy.Health.Current:0,passed=!enemy||enemy.Health.Current<hp});p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();await Task.Delay(100);}
}finally{if(DungeonUi.ModalOpen)DungeonUi.Close(DungeonUi.Modal);progress.ImportFrom(carry);inv.ImportFrom(carry);p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();InputSystem.onAfterUpdate-=current;InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);foreach(var d in native)if(d.enabled)InputSystem.EnableDevice(d.d);oldK?.MakeCurrent();oldM?.MakeCurrent();InputSystem.settings.backgroundBehavior=bg;InputSystem.settings=string.IsNullOrEmpty(originalPath)?settings:AssetDatabase.LoadAssetAtPath<InputSettings>(originalPath);}
File.WriteAllText(root+"actions.json",Newtonsoft.Json.JsonConvert.SerializeObject(rows,Newtonsoft.Json.Formatting.Indented));return rows;}
 public static async Task<object> RunResolutions(int height=720){const BindingFlags f=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var a=typeof(Editor).Assembly;var t=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(t).Cast<EditorWindow>().First();var index=t.GetProperty("selectedSizeIndex",f);int original=(int)index.GetValue(view);var st=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(st).GetProperty("instance").GetValue(null);var group=st.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});var sizeType=a.GetType("UnityEditor.GameViewSize");var enumType=a.GetType("UnityEditor.GameViewSizeType");var entries=new List<object>();var results=new List<object>();try{foreach(var size in new[]{height==720?new[]{1280,720}:new[]{1920,1080}}){var e=Activator.CreateInstance(sizeType,new object[]{Enum.ToObject(enumType,1),size[0],size[1],"v4 motion review"});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{e});entries.Add(e);index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(350);Camera.main.GetComponent<DungeonCamera>().Snap();results.Add(await Run());}}finally{index.SetValue(view,original);foreach(var field in group.GetType().GetFields(f)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(entries.Contains(list[i]))list.RemoveAt(i);}view.Repaint();}return results;}
}
