using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Demo6.Game;
public static class UsabilityV5Regression{
public static object Run(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");var scene=EditorSceneManager.NewPreviewScene();var results=new List<object>();var objects=new List<GameObject>();GameObject G(string name){var g=new GameObject(name);UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(g,scene);objects.Add(g);return g;}
try{var actor=G("camera target");var cg=G("camera under test");var cam=cg.AddComponent<Camera>();cam.aspect=16f/9;var follow=cg.AddComponent<DungeonCamera>();follow.Bind(actor.transform,new Rect(-5,-5,10,10));foreach(var at in new[]{new Vector2(-5,-5),new Vector2(5,5),new Vector2(30,-20),Vector2.zero}){actor.transform.position=at;follow.Snap();var v=cam.WorldToViewportPoint(actor.transform.position);bool pass=Mathf.Abs(v.x-.5f)<.0001f&&Mathf.Abs(v.y-.5f)<.0001f;results.Add(new{check="camera-edge-and-small-map",position=at.ToString(),viewport=v.ToString(),passed=pass});if(!pass)throw new Exception("Camera center regression");}
var art=AssetDatabase.LoadAssetAtPath<CombatArtSet>("Assets/Data/Combat/CombatArtSet.asset");var body=G("body").AddComponent<SpriteRenderer>();body.color=Color.white;body.sortingOrder=40;
foreach(int fps in new[]{30,60,144}){var obj=G("cape "+fps);var cape=obj.AddComponent<TopDownCape>();float dt=1f/fps,maxLag=0,minArea=999;Vector2 at=Vector2.zero;for(int frame=0;frame<fps*3;frame++){float time=frame*dt;float angle=time<.6f?0:time<1.2f?90:180;if(time<1.2f)at+=Vector2.right*3*dt;cape.Place(art.topDown.player.cape,body,at,angle,Vector2.zero,0,dt);maxLag=Mathf.Max(maxLag,Mathf.Abs(cape.TailLag));var mesh=obj.GetComponent<MeshFilter>().sharedMesh;var v=mesh.vertices;var tris=mesh.triangles;for(int i=0;i<tris.Length;i+=3){Vector2 a=v[tris[i+1]]-v[tris[i]],b=v[tris[i+2]]-v[tris[i]];minArea=Mathf.Min(minArea,Mathf.Abs(a.x*b.y-a.y*b.x));if(float.IsNaN(a.x)||float.IsNaN(b.y))throw new Exception("Invalid cape vertex");}}
bool pass=Mathf.Abs(cape.TailLag)<.02f&&cape.TailDrag.magnitude<.001f&&maxLag<=32.001f&&minArea>.00001f&&obj.GetComponent<MeshRenderer>().sortingOrder==38&&obj.GetComponent<Collider2D>()==null;results.Add(new{check="cape-fps-settle-and-topology",fps,maxLag,settledLag=cape.TailLag,settledDrag=cape.TailDrag.magnitude,minTriangleArea=minArea,passed=pass});if(!pass)throw new Exception("Cape stability regression");}
// 화면 상·하·좌·우 경계에 포개진 이름표를 넣어 실제 배치 함수를 검증.
var labels=G("labels").AddComponent<LootLabels>();var flags=BindingFlags.NonPublic|BindingFlags.Instance;var slots=(Array)typeof(LootLabels).GetField("_slots",flags).GetValue(labels);var slotType=slots.GetType().GetElementType();foreach(var point in new[]{new Vector2(-100,-100),new Vector2(DungeonUi.Width+50,DungeonUi.Height+50)}){int count=12;for(int i=0;i<count;i++){var slot=Activator.CreateInstance(slotType);slotType.GetField("Rect").SetValue(slot,new Rect(point.x,point.y,160,26));slotType.GetField("Alpha").SetValue(slot,1f);slots.SetValue(slot,i);}typeof(LootLabels).GetField("_count",flags).SetValue(labels,count);typeof(LootLabels).GetMethod("Stack",flags).Invoke(labels,null);var rects=Enumerable.Range(0,count).Select(i=>(Rect)slotType.GetField("Rect").GetValue(slots.GetValue(i))).ToArray();bool inside=rects.All(r=>r.x>=12&&r.xMax<=DungeonUi.Width-12&&r.y>=52&&r.yMax<=DungeonUi.Height-114);bool overlap=false;for(int i=0;i<count;i++)for(int j=0;j<i;j++)overlap|=rects[i].Overlaps(rects[j]);bool pass=inside&&!overlap;results.Add(new{check="stacked-label-screen-bounds",corner=point.ToString(),count,passed=pass});if(!pass)throw new Exception("Loot label bounds regression");}
}finally{foreach(var o in objects)if(o)UnityEngine.Object.DestroyImmediate(o);EditorSceneManager.ClosePreviewScene(scene);}File.WriteAllText("검증/플레이-사용성-v5/component-regressions.json",Newtonsoft.Json.JsonConvert.SerializeObject(results,Newtonsoft.Json.Formatting.Indented));return results;}}
