using System;using System.Reflection;using System.Collections;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class UsabilityV5DropReview {
 public static async Task<object> Run(){
 if(!EditorApplication.isPlaying||DungeonUi.ModalOpen)throw new Exception("Unblocked Play required");Directory.CreateDirectory("검증/플레이-사용성-v5/after");var p=PlayerController.Instance;var inv=Inventory.Instance;var input=p.GetComponent<PlayerInputReader>();var origin=p.Position;int originalHp=p.Health.Current,originalPotions=p.Potions;var carry=new Demo6.Core.Dungeon.CarryData();inv.ExportTo(carry);
 var natives=InputSystem.devices.Where(d=>d is Keyboard||d is Mouse).Select(d=>new{d,enabled=d.enabled}).ToArray();var originalSettings=InputSystem.settings;var settings=UnityEngine.Object.Instantiate(originalSettings);var originalPath=AssetDatabase.GetAssetPath(originalSettings);var reviewSettings=UnityEngine.Object.Instantiate(originalSettings);InputSystem.settings=reviewSettings;reviewSettings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;var oldK=Keyboard.current;var oldM=Mouse.current;var kb=InputSystem.AddDevice<Keyboard>("V5ReviewKeyboard");var mouse=InputSystem.AddDevice<Mouse>("V5ReviewMouse");var background=InputSystem.settings.backgroundBehavior;Action current=()=>{kb.MakeCurrent();mouse.MakeCurrent();};InputSystem.onAfterUpdate+=current;var rows=new List<object>();var drops=new List<LootDrop>();var errors=new List<string>();Application.LogCallback log=(m,st,t)=>{if(t==LogType.Error||t==LogType.Exception)errors.Add(m);};Application.logMessageReceived+=log;
 string root="검증/플레이-사용성-v5/after/"+Screen.height+"-";
 async Task Shot(string name){ScreenCapture.CaptureScreenshot(Path.GetFullPath(root+name+".png"));await Task.Delay(180);}
 async Task Press(Key key){kb.MakeCurrent();InputSystem.QueueStateEvent(kb,new KeyboardState(key));await Task.Delay(100);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(100);}
 void Pointer(Vector2 pos,int buttons=0){mouse.MakeCurrent();InputSystem.QueueStateEvent(mouse,new MouseState{position=pos,buttons=(ushort)buttons});}
 try{InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;foreach(var d in natives)if(d.enabled)InputSystem.DisableDevice(d.d);InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);kb.MakeCurrent();mouse.MakeCurrent();
 p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();Pointer(new Vector2(Screen.width*.6f,Screen.height*.5f));
 for(int i=0;i<3;i++)drops.Add(LootDrop.Spawn(new Demo6.Core.Loot.GearItem(i==0?"rng_blood":"wpn_greatsword",i==0?Demo6.Core.Loot.Grade.Legendary:Demo6.Core.Loot.Grade.Rare,11,1100,0),origin+Vector2.right*.8f,origin+Vector2.right*.8f,0));await Task.Delay(750);await Shot("loot-no-auto-card");rows.Add(new{check="no-auto-card",passed=LootLabels.Instance.HoveredDrop==null});
 for(int i=0;i<drops.Count;i++){if(!LootLabels.Instance.TryLabelRect(drops[i],out var rect))continue;Vector2 at=rect.center*(Screen.height/DungeonUi.Height);at.y=Screen.height-at.y;Pointer(at);await Task.Delay(350);await Shot("loot-hover-"+i);rows.Add(new{check="hover",i,passed=LootLabels.Instance.HoveredDrop==drops[i],rect=rect.ToString(),card=inv.GroundCardRect.ToString()});}

 }finally{Application.logMessageReceived-=log;InputSystem.onAfterUpdate-=current;if(DungeonUi.ModalOpen)DungeonUi.Close(DungeonUi.Modal);foreach(var d in drops)if(d)UnityEngine.Object.Destroy(d.gameObject);inv.ImportFrom(carry);p.RestoreVitals(originalHp,originalPotions);p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);foreach(var d in natives)if(d.enabled)InputSystem.EnableDevice(d.d);oldK?.MakeCurrent();oldM?.MakeCurrent();InputSystem.settings.backgroundBehavior=background;InputSystem.settings=string.IsNullOrEmpty(originalPath)?settings:AssetDatabase.LoadAssetAtPath<InputSettings>(originalPath);}
 var result=new{rows,errors,method="Temporary virtual InputSystem devices; physical devices isolated only inside this disposable review, restored in finally. No physical pointer claim."};File.WriteAllText(root+"drop-final.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }

 public static async Task<object> RunResolutions(int height=720){const BindingFlags f=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var a=typeof(Editor).Assembly;var t=a.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(t).Cast<EditorWindow>().First();var index=t.GetProperty("selectedSizeIndex",f);int original=(int)index.GetValue(view);var st=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(st).GetProperty("instance").GetValue(null);var group=st.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});var sizeType=a.GetType("UnityEditor.GameViewSize");var enumType=a.GetType("UnityEditor.GameViewSizeType");var entries=new List<object>();var results=new List<object>();try{foreach(var size in new[]{height==720?new[]{1280,720}:new[]{1920,1080}}){var e=Activator.CreateInstance(sizeType,new object[]{Enum.ToObject(enumType,1),size[0],size[1],"v4 motion review"});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{e});entries.Add(e);index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(350);Camera.main.GetComponent<DungeonCamera>().Snap();results.Add(await Run());}}finally{index.SetValue(view,original);foreach(var field in group.GetType().GetFields(f)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(entries.Contains(list[i]))list.RemoveAt(i);}view.Repaint();}return results;}
}
