using System;using System.IO;using System.Linq;using System.Reflection;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEngine.Rendering.Universal;using Demo6.Game;
public static class V026OriginalFinal {
 const string Root="E:/personalProject/Demo3/demo6",Ev="E:/personalProject/Demo3/demo6/검증/오브젝트-잔여-v026/original-play";
 static void Guard(){if(Application.dataPath.Replace("\\","/")!=Root+"/Assets")throw new Exception("Original project only");}
 static void Save(string file,object data){File.WriteAllText(Ev+"/"+file,Newtonsoft.Json.JsonConvert.SerializeObject(data,Newtonsoft.Json.Formatting.Indented));}
 public static async Task<object> Load(){Guard();if(!EditorApplication.isPlaying)throw new Exception("Play required");var op=SceneManager.LoadSceneAsync("DungeonTest");while(!op.isDone)await Task.Delay(10);await Task.Delay(1200);return new {scene=SceneManager.GetActiveScene().name,root=(bool)DungeonRoot.Instance};}
 static void Capture(Camera c,string file,int w,int h){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(w,h,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(w,h,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,w,h),0,0);t.Apply();File.WriteAllBytes(Ev+"/"+file,t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)UnityEngine.Object.DestroyImmediate(t);}}
 static object[] Geometry(Chest c)=>c.GetComponentsInChildren<SpriteRenderer>(true).Select(r=>(object)new{name=r.name,pos=new[]{r.transform.localPosition.x,r.transform.localPosition.y},scale=new[]{r.transform.localScale.x,r.transform.localScale.y},r.enabled,shader=r.sharedMaterial.shader.name}).ToArray();
 public static async Task<object> Stage(string tag){Guard();await Task.Delay(100);var c=Camera.main;if(!c)throw new Exception("Camera missing");var renderers=UnityEngine.Object.FindObjectsByType<Renderer>();var enabled=renderers.Select(r=>r.enabled).ToArray();var lights=UnityEngine.Object.FindObjectsByType<Light2D>();var intensities=lights.Select(l=>l.intensity).ToArray();var colors=lights.Select(l=>l.color).ToArray();var cp=c.transform.position;var size=c.orthographicSize;var mask=c.cullingMask;var bg=c.backgroundColor;var flags=c.clearFlags;var chest=new Chest[4];object result=null;
  try{
   foreach(var r in renderers)r.enabled=false;foreach(var l in lights){l.intensity=l.lightType==Light2D.LightType.Global?1:0;if(l.lightType==Light2D.LightType.Global)l.color=Color.white;}
   for(int i=0;i<4;i++){chest[i]=Chest.Create(null,null,new Vector2(-1.2f+(i%2)*2.4f,.7f-(i/2)*1.5f),i%2==1);if(i>=2)typeof(Chest).GetMethod("ShowOpened",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(chest[i],null);var g=chest[i].transform.Find("Glint");if(g)g.gameObject.SetActive(false);}
   c.transform.position=new Vector3(0,0,cp.z);c.orthographicSize=2f;c.cullingMask=~0;c.clearFlags=CameraClearFlags.SolidColor;c.backgroundColor=new Color(.12f,.13f,.12f);Capture(c,"chests-"+tag+".png",800,540);
   result=chest.Select(x=>new{x.Iron,x.Opened,x.Available,x.Prompt,x.Range,x.HoldSeconds,colliders=x.GetComponentsInChildren<Collider2D>().Length,geometry=Geometry(x)}).ToArray();Save("chests-"+tag+".json",result);
  }finally{foreach(var x in chest)if(x)UnityEngine.Object.DestroyImmediate(x.gameObject);for(int i=0;i<renderers.Length;i++)if(renderers[i])renderers[i].enabled=enabled[i];for(int i=0;i<lights.Length;i++)if(lights[i]){lights[i].intensity=intensities[i];lights[i].color=colors[i];}c.transform.position=cp;c.orthographicSize=size;c.cullingMask=mask;c.backgroundColor=bg;c.clearFlags=flags;}
  return result;
 }
 public static async Task<object> Runtime(){Guard();await Task.Delay(100);var c=Camera.main;Capture(c,"remaining-props-gameplay.png",1920,1080);var r=UnityEngine.Object.FindObjectsByType<SpriteRenderer>().Where(x=>x.sprite&&new[]{"Assets/Resources/TopDownPilotV9/lantern.png","Assets/Resources/TopDownPilotV9/chain.png"}.Contains(AssetDatabase.GetAssetPath(x.sprite))).Select(x=>new{x.name,path=AssetDatabase.GetAssetPath(x.sprite),shader=x.sharedMaterial.shader.name,ppu=x.sprite.pixelsPerUnit,pivot=new[]{x.sprite.pivot.x,x.sprite.pivot.y},scale=new[]{x.transform.localScale.x,x.transform.localScale.y}}).ToArray();var lamps=UnityEngine.Object.FindObjectsByType<WallLamp>();var result=new{props=r,lamps=lamps.Length,lights=UnityEngine.Object.FindObjectsByType<Light2D>().Length,shaderErrors=ShaderUtil.GetShaderMessages(Shader.Find("Demo6/SpriteFlash")).Select(m=>m.message).ToArray()};Save("runtime.json",result);return result;}
 public static async Task<object> After(){await Stage("after");return await Runtime();}
 public static object Status(){Guard();return new{scene=SceneManager.GetActiveScene().name,SceneManager.GetActiveScene().isDirty,EditorApplication.isPlaying,EditorApplication.isCompiling};}
 public static object Close(){throw new Exception("Never close original editor");}
}
