using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;
public static class V052VisualReview {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/v052-feedback";
 static void Set(PlayerController p,string n,object v){var f=typeof(PlayerController).GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 static void Free(PlayerController p){Set(p,"_state","Free");Set(p,"_hurtTime",-999f);Set(p,"_execPoseAction",-999);Set(p,"_riposteActive",false);}
 static void Capture(Camera camera,string name){var prior=camera.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1280,720,24);Texture2D tex=null;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;tex=new Texture2D(1280,720,TextureFormat.RGBA32,false);tex.ReadPixels(new Rect(0,0,1280,720),0,0);tex.Apply();File.WriteAllBytes(Out+"/"+name+".png",tex.EncodeToPNG());}finally{camera.targetTexture=prior;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(tex)UnityEngine.Object.DestroyImmediate(tex);}}
 public static object Run(){var p=PlayerController.Instance;var rig=TopDownView.PlayerRig;if(!p||rig==null)throw new Exception("Original game must be running");Directory.CreateDirectory(Out);var fields=typeof(PlayerController).GetFields(F).Where(x=>!x.IsInitOnly&&!x.IsLiteral).ToDictionary(x=>x,x=>x.GetValue(p));var camera=Camera.main;var position=camera.transform.position;var size=camera.orthographicSize;var paused=EditorApplication.isPaused;var angle=typeof(TopDownPlayerRig).GetField("_angle",F);var oldAngle=angle.GetValue(rig);var owner=Telegraph.CreatingOwner;var above=Telegraph.AboveDark;var shapes=new List<Telegraph>();var checks=new List<object>();
 try{EditorApplication.isPaused=true;camera.transform.position=new Vector3(p.transform.position.x+.25f,p.transform.position.y,position.z);camera.orthographicSize=1.5f;angle.SetValue(rig,0f);
 foreach(var weapon in new[]{WeaponPresets.Longsword,WeaponPresets.Greatsword,WeaponPresets.Twinblades}){Free(p);Set(p,"<Weapon>k__BackingField",weapon);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());Capture(camera,weapon.id+"-idle");
 int combo=weapon.id=="wpn_greatsword"?2:0;var step=weapon.combo[combo];var plan=SwingTiming.Plan(step,0);
 for(int i=0;i<10;i++){float t=plan.Duration*(.08f+i*.055f);Set(p,"_state","Swing");Set(p,"_stateTime",t);Set(p,"_comboStepNumber",combo+1);Set(p,"_step",step);Set(p,"_plan",plan);Set(p,"_swingDuration",plan.Duration);Set(p,"_actionId",91000);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());Capture(camera,weapon.id+"-attack-"+i.ToString("00"));var edges=p.GetComponentsInChildren<WeaponEdgeV052>();checks.Add(new{weapon=weapon.id,phase="attack",t,rig.FirstAttackArt.ClipId,rig.FirstAttackArt.FrameIndex,edges=edges.Select(e=>new{visible=e.GetComponent<MeshRenderer>().enabled,vertices=e.GetComponent<MeshFilter>().sharedMesh.vertexCount,bounds=e.GetComponent<MeshFilter>().sharedMesh.bounds.size.ToString()}).ToArray()});}
 }
 Free(p);Set(p,"<Weapon>k__BackingField",WeaponPresets.Longsword);Set(p,"_state","WeaponAct");Set(p,"_actPhase","Hold");Set(p,"_actPhaseTime",.1f);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());Capture(camera,"shield-left-hold");
 Free(p);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());camera.orthographicSize=3.6f;Telegraph.CreatingOwner=null;
 foreach(bool darkness in new[]{false,true})foreach(string shape in new[]{"circle","half","rect"}){
  Telegraph.AboveDark=darkness;var at=(Vector2)p.transform.position;var center=at-Vector2.right*2.65f;
  var tele=shape=="circle"?Telegraph.Circle(center,3f,1f):shape=="half"?Telegraph.HalfDisc(center,Vector2.right,3f,1f):Telegraph.Rect(at-new Vector2(3,.75f),Vector2.right,6,2,1);shapes.Add(tele);tele.Drive(.9f);Capture(camera,"floor-overlap-"+shape+"-"+darkness);
  var ground=tele.GetComponentsInChildren<SpriteRenderer>();var actors=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.enabled&&s.sprite&&!s.name.Contains("Shadow")).ToArray();checks.Add(new{shape,darkness,phase="floor-overlap",groundOrders=ground.Select(s=>s.sortingOrder).ToArray(),actorMinimum=actors.Min(s=>s.sortingOrder),allBelowActors=ground.All(g=>actors.All(a=>a.sortingLayerID==g.sortingLayerID&&a.sortingOrder>g.sortingOrder))});UnityEngine.Object.DestroyImmediate(tele.gameObject);
 }
 }finally{foreach(var t in shapes)if(t)UnityEngine.Object.DestroyImmediate(t.gameObject);Telegraph.CreatingOwner=owner;Telegraph.AboveDark=above;foreach(var f in fields)f.Key.SetValue(p,f.Value);angle.SetValue(rig,oldAngle);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());camera.transform.position=position;camera.orthographicSize=size;EditorApplication.isPaused=paused;}
 var result=new{method="Original Unity camera and production lighting. Temporary visual states and telegraphs; no physical or synthetic input. All player fields, flags, camera and pause restored.",checks};File.WriteAllText(Out+"/visual-review.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
