using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Demo6.Core.Loot;using Newtonsoft.Json;
public static class V052EquipmentReview {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;
 const string Out="검증/v052-feedback";
 static void Set(PlayerController p,string n,object v){var f=typeof(PlayerController).GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 static void Capture(Camera c,string name){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(960,720,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(960,720,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,960,720),0,0);t.Apply();File.WriteAllBytes(Out+"/"+name+".png",t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)UnityEngine.Object.DestroyImmediate(t);}}
 public static object Run(){var p=PlayerController.Instance;var rig=TopDownView.PlayerRig;if(!p||rig==null)throw new Exception("Live original scene required");Directory.CreateDirectory(Out);var fields=typeof(PlayerController).GetFields(F).Where(x=>!x.IsInitOnly&&!x.IsLiteral).ToDictionary(x=>x,x=>x.GetValue(p));var catField=typeof(EquipmentVisualV049).GetField("_catalog",BindingFlags.Static|BindingFlags.NonPublic);var savedCat=catField.GetValue(null);var cat=JsonUtility.FromJson<EquipmentVisualV049.Catalog>(Resources.Load<TextAsset>("EquipmentV049/calibration").text);var allWeapons=cat.weapons;var cam=Camera.main;var pos=cam.transform.position;var size=cam.orthographicSize;var angle=typeof(TopDownPlayerRig).GetField("_angle",F);var savedAngle=angle.GetValue(rig);bool paused=EditorApplication.isPaused;var checks=new List<object>();
 try{EditorApplication.isPaused=true;Set(p,"_state","Free");Set(p,"_hurtTime",-999f);Set(p,"_execPoseAction",-999);Set(p,"_riposteActive",false);angle.SetValue(rig,0f);cam.transform.position=new Vector3(p.transform.position.x+.2f,p.transform.position.y,pos.z);cam.orthographicSize=1.35f;catField.SetValue(null,cat);
 foreach(var w in allWeapons){cat.weapons=new[]{w};Set(p,"<Weapon>k__BackingField",w.baseId=="wpn_longsword"?WeaponPresets.Longsword:w.baseId=="wpn_greatsword"?WeaponPresets.Greatsword:WeaponPresets.Twinblades);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());var tex=Resources.Load<Texture2D>(w.texture);var rendered=p.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.enabled&&!s.name.Contains("Thickness")&&s.sprite&&s.sprite.texture==tex).ToArray();var icon=EquipmentVisualV049.Icon(w.baseId,Grade.Common);checks.Add(new{type="weapon",w.key,passed=rendered.Length==(w.baseId=="wpn_twinblades"?2:1)&&icon&&w.sprite&&Mathf.Abs(w.sprite.pixelsPerUnit-w.ppu)<.01f,renderers=rendered.Length,sameTwinSprite=rendered.Length!=2||rendered[0].sprite==rendered[1].sprite,ppu=w.ppu,pivot=w.sprite?w.sprite.pivot.ToString():null});Capture(cam,"equipment-"+w.key);}
 cat.weapons=allWeapons;Set(p,"<Weapon>k__BackingField",WeaponPresets.Longsword);
 foreach(var id in new[]{"arm_leather","arm_chain"}){Set(p,"<Look>k__BackingField",new GearLook(id,"hlm_leather",null,null));rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());foreach(var armor in cat.armor.Where(a=>a.baseId==id||a.part=="head")){var tex=Resources.Load<Texture2D>(armor.texture);var visible=p.GetComponentsInChildren<SpriteRenderer>().Count(s=>s.enabled&&s.sprite&&s.sprite.texture==tex);checks.Add(new{type="armor",armor.baseId,armor.part,passed=visible==1,renderers=visible});}Capture(cam,"armor-"+id);}
 Set(p,"<Look>k__BackingField",fields[typeof(PlayerController).GetField("<Look>k__BackingField",F)]);
 for(int i=0;i<10;i++){float t=i/60f;Set(p,"_state","WeaponAct");Set(p,"_actPhase",t<.12f?"Raise":"Hold");Set(p,"_actPhaseTime",t<.12f?t:0f);Set(p,"_stateTime",t);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());Capture(cam,"guard-sequence-"+i.ToString("00"));}
 foreach(var kind in new[]{"hit","block","parry"}){var textures=Enumerable.Range(1,10).Select(i=>Resources.Load<Texture2D>("ContactReactionV046/"+kind+"/frame_"+i.ToString("00"))).ToArray();checks.Add(new{type="contactTextures",kind,passed=textures.All(t=>t&&t.width==512&&t.height==512),loaded=textures.Count(t=>t)});}
 }finally{catField.SetValue(null,savedCat);foreach(var x in fields)x.Key.SetValue(p,x.Value);angle.SetValue(rig,savedAngle);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());cam.transform.position=pos;cam.orthographicSize=size;EditorApplication.isPaused=paused;}
 var result=new{method="Actual original Unity render with temporary appearance/pose states. No input, inventory changes, physics or gameplay transitions tested. All fields, catalog, camera, pause restored.",checks};File.WriteAllText(Out+"/equipment-final.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
