using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;using Object=UnityEngine.Object;
public static class V052GaitReview {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/v052-feedback";
 static void Set(object p,Type type,string n,object v){var f=type.GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 static void Capture(Camera c,string n){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1280,720,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(1280,720,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,1280,720),0,0);t.Apply();File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)Object.DestroyImmediate(t);}}
 public static object Run(){var p=PlayerController.Instance;var rig=TopDownView.PlayerRig;if(!p||rig==null)throw new Exception("Original Play required");if(OgreBrain.Current)throw new Exception("Live boss preserved");var fields=typeof(PlayerController).GetFields(F).Where(x=>!x.IsInitOnly&&!x.IsLiteral).ToDictionary(x=>x,x=>x.GetValue(p));var initial=new HashSet<GameObject>(Object.FindObjectsByType<GameObject>());var paused=EditorApplication.isPaused;var random=UnityEngine.Random.state;var cam=Camera.main;var cp=cam.transform.position;float size=cam.orthographicSize;var body=p.GetComponent<Rigidbody2D>();var pp=p.transform.position;var vel=body.linearVelocity;var angle=typeof(TopDownPlayerRig).GetField("_angle",F);var oldAngle=angle.GetValue(rig);var walk=(CuteWalkV22)typeof(TopDownPlayerRig).GetField("_walk",F).GetValue(rig);var checks=new List<object>();OgreBrain ogre=null;
 try{EditorApplication.isPaused=true;cam.orthographicSize=1.6f;Set(p,typeof(PlayerController),"_state","Free");Set(p,typeof(PlayerController),"_hurtTime",-999f);Set(p,typeof(PlayerController),"<Weapon>k__BackingField",WeaponPresets.Twinblades);angle.SetValue(rig,0f);Set(p,typeof(PlayerController),"_facing",Vector2.right);body.linearVelocity=Vector2.right*2;rig.FirstAttackArt.Stop();walk.Reset(pp);
 for(int i=0;i<90;i++){p.transform.position=pp+Vector3.right*i/60f*2;cam.transform.position=new Vector3(p.transform.position.x+.25f,p.transform.position.y,cp.z);rig.Drive(1f/60f,TopDownView.CurrentArt());if(i>=40&&i<50)Capture(cam,"twin-walk-"+(i-40).ToString("00"));if(i%5==0){var a=rig.FirstAttackArt;checks.Add(new{phase="twin-gait",i,walk.Amount,left=walk.Left.ToString(),right=walk.Right.ToString(),walk.ShoulderTurn,bladeBase=a.BladeBase.ToString()});}}
 p.transform.position=pp;body.linearVelocity=vel;walk.Reset(pp);foreach(var f in fields)f.Key.SetValue(p,f.Value);angle.SetValue(rig,oldAngle);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());
 var at=(Vector2)pp+Vector2.right*3;ogre=(OgreBrain)EnemySpawner.Create(MonsterKind.Ogre,2,at);ogre.NoReward=true;typeof(Enemy).GetProperty("Aware",F).SetValue(ogre,true);Set(ogre,typeof(Enemy),"Facing",Vector2.down);Set(ogre,typeof(Enemy),"DesiredVelocity",Vector2.down);foreach(var mb in ogre.GetComponents<MonoBehaviour>())mb.enabled=false;ogre.GetComponent<Rigidbody2D>().simulated=false;var or=ogre.GetComponentInChildren<OgreArtRig>();or.enabled=false;cam.orthographicSize=3.8f;
 for(int i=0;i<180;i++){ogre.transform.position=(Vector3)at+Vector3.down*i/144f;cam.transform.position=ogre.transform.position+new Vector3(0,-.5f,cp.z);or.Sample(1f/144f);typeof(YSort).GetMethod("LateUpdate",F).Invoke(ogre.GetComponent<YSort>(),null);if(i>=100&&i<110)Capture(cam,"ogre-walk-"+(i-100).ToString("00"));if(i%8==0)checks.Add(new{phase="ogre-gait",i,or.Gait.Amount,or.Gait.Cycle,or.TorsoYawDegrees,or.HeadYawDegrees});}
 var tele=Telegraph.Circle((Vector2)ogre.transform.position+Vector2.right*2.4f,3,1);tele.Drive(.9f);Capture(cam,"ogre-floor-overlap");checks.Add(new{phase="ogre-floor",floor=tele.GetComponentsInChildren<SpriteRenderer>().Max(s=>s.sortingOrder),actor=or.GetComponentsInChildren<SpriteRenderer>().Where(s=>s.enabled).Min(s=>s.sortingOrder)});
 }finally{if(ogre){Set(ogre,typeof(OgreBrain),"_fightActive",false);typeof(OgreBrain).GetMethod("CancelAll",F).Invoke(ogre,null);}foreach(var go in Object.FindObjectsByType<GameObject>())if(go&&!initial.Contains(go))Object.DestroyImmediate(go);foreach(var f in fields)f.Key.SetValue(p,f.Value);p.transform.position=pp;body.linearVelocity=vel;walk.Reset(pp);angle.SetValue(rig,oldAngle);cam.transform.position=cp;cam.orthographicSize=size;UnityEngine.Random.state=random;EditorApplication.isPaused=paused;rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());}
 var result=new{method="Synthetic render-position/gait sampling in original scene and production lighting. No keyboard/mouse input. Player fields, body position/velocity, camera and pause restored; temporary Ogre/telegraph removed.",checks};File.WriteAllText(Out+"/gait-review.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
