using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using Demo6.Game;using Newtonsoft.Json;
public static class V054FinalGuardObserve {public static object Start(){if(!Application.isPlaying||!PlayerController.Instance)throw new Exception("Live original scene required");if(GameObject.Find("V054 final guard read-only observer"))throw new Exception("Already observing");new GameObject("V054 final guard read-only observer").AddComponent<V054FinalGuardObserver>();return "Observing right-click guard for 90 seconds without changing pose, Play, input or camera";}}
public sealed class V054FinalGuardObserver:MonoBehaviour {
 const string Out="검증/v054-guard";const BindingFlags F=BindingFlags.Instance|BindingFlags.NonPublic;readonly List<object> trace=new List<object>();float end;int events,pictures;string prior;bool saving;
 void Awake(){Directory.CreateDirectory(Out);end=Time.realtimeSinceStartup+90;InputSystem.onEvent+=OnInput;StartCoroutine(ObserveFrames());}
 void OnInput(InputEventPtr e,InputDevice d){if(d is Mouse&&d.native&&(e.IsA<StateEvent>()||e.IsA<DeltaStateEvent>()))events++;}
 IEnumerator ObserveFrames(){while(Time.realtimeSinceStartup<end){yield return new WaitForEndOfFrame();var p=PlayerController.Instance;var art=TopDownView.PlayerRig?.FirstAttackArt;if(!p||art==null)continue;var f=(FirstAttackArtV042.Frame)typeof(FirstAttackArtV042).GetField("_currentFrame",F).GetValue(art);var sr=art.ShieldSurface;var rendered=(SpriteRenderer[])typeof(FirstAttackArtV042).GetField("_parts",F).GetValue(art);string key=p.ActPhase+"/"+art.ClipId+"/"+art.FrameIndex;bool changed=key!=prior;
 if(p.InWeaponAct && p.ActKind.ToString()=="Guard" || (prior!=null && prior.StartsWith("Lower/") && changed)){string capture=null;if(changed&&pictures<60){capture="native-final-"+pictures++.ToString("00")+".png";var tex=ScreenCapture.CaptureScreenshotAsTexture();File.WriteAllBytes(Out+"/"+capture,tex.EncodeToPNG());Destroy(tex);}var shieldParts=f?.parts.Where(x=>x.name.Contains("shield")).Select(x=>new{name=x.name,rendererEnabled=rendered[x.layer].enabled,position=rendered[x.layer].transform.position.ToString()}).ToArray();trace.Add(new{time=Time.realtimeSinceStartup,frame=Time.frameCount,native=Mouse.current?.native,held=Mouse.current?.rightButton.isPressed,phase=p.ActPhase.ToString(),phaseTime=p.ActPhaseTime,clip=art.ClipId,cel=art.FrameIndex,visualTime=art.VisualTime,left=f?.left,shield=sr?sr.bounds.center.ToString():null,shieldParts,capture});}prior=key;if(changed)Flush();}
 File.WriteAllText(Out+"/native-guard.json",JsonConvert.SerializeObject(new{method="Passive native-input and final rendered-frame observation; no injected events/poses/camera change",events,pictures,trace},Formatting.Indented));Destroy(gameObject);}
 void Flush(){File.WriteAllText(Out+"/native-final.json",JsonConvert.SerializeObject(new{utc=DateTime.UtcNow.ToString("O"),method="Passive native mouse + rendered state observation; no injected input",events,pictures,trace},Formatting.Indented));} void OnDestroy(){InputSystem.onEvent-=OnInput;Flush();}
}
