using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;using Object=UnityEngine.Object;using GamePlayer=Demo6.Game.PlayerController;
public static class V055OverlapReview {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/v055-shield/overlap";
 static void Set(object p,Type t,string n,object v){var f=t.GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 static void Shot(Camera c,string n){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1920,1080,24);var t=new Texture2D(1920,1080,TextureFormat.RGB24,false);try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t.ReadPixels(new Rect(0,0,1920,1080),0,0);t.Apply();File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);Object.DestroyImmediate(t);}}
 public static object Run(){var p=GamePlayer.Instance;var rig=TopDownView.PlayerRig;if(!p||OgreBrain.Current)throw new Exception("Need original player without a live Ogre; existing boss preserved");Directory.CreateDirectory(Out);var initial=new HashSet<GameObject>(Object.FindObjectsByType<GameObject>());var fields=typeof(GamePlayer).GetFields(F).Where(f=>!f.IsInitOnly&&!f.IsLiteral).ToDictionary(f=>f,f=>f.GetValue(p));var paused=EditorApplication.isPaused;var random=UnityEngine.Random.state;var camera=Camera.main;var pos=camera.transform.position;var angle=typeof(TopDownPlayerRig).GetField("_angle",F);var oldAngle=angle.GetValue(rig);OgreBrain ogre=null;var checks=new List<object>();
 try{EditorApplication.isPaused=true;Set(p,typeof(GamePlayer),"_state","WeaponAct");Set(p,typeof(GamePlayer),"_actPhase","Hold");Set(p,typeof(GamePlayer),"_actPhaseTime",.1f);Set(p,typeof(GamePlayer),"_hurtTime",-999f);Set(p,typeof(GamePlayer),"<Weapon>k__BackingField",WeaponPresets.Longsword);angle.SetValue(rig,0f);Set(p,typeof(GamePlayer),"_facing",Vector2.right);typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());camera.transform.position=new Vector3(p.Position.x+.5f,p.Position.y,pos.z);
 ogre=(OgreBrain)EnemySpawner.Create(MonsterKind.Ogre,2,p.Position+Vector2.right*1.25f);ogre.NoReward=true;foreach(var mb in ogre.GetComponents<MonoBehaviour>())mb.enabled=false;ogre.GetComponent<Rigidbody2D>().simulated=false;var art=ogre.GetComponentInChildren<OgreArtRig>();art.enabled=false;Set(ogre,typeof(Enemy),"Facing",Vector2.down);Set(ogre,typeof(Enemy),"DesiredVelocity",Vector2.zero);
 foreach(var y in new[]{-.8f,0f,.8f}){ogre.transform.position=p.transform.position+new Vector3(.9f,y,0);art.Sample(0);typeof(YSort).GetMethod("LateUpdate",F).Invoke(ogre.GetComponent<YSort>(),null);HitEffects.WallDust(p.Position+new Vector2(.45f,.25f),Vector2.right,6);var fx=Object.FindAnyObjectByType<ImportedFxV056>();foreach(var ps in fx.GetComponentsInChildren<ParticleSystem>())ps.Simulate(.07f,false,false,true);Shot(camera,"actor-y-"+y.ToString("F1",System.Globalization.CultureInfo.InvariantCulture));checks.Add(new{y,shieldSort=rig.FirstAttackArt.ShieldSurface.sortingOrder,ogreOrders=art.GetComponentsInChildren<SpriteRenderer>().Where(r=>r.enabled).Select(r=>r.sortingOrder).Distinct().ToArray(),groundFxOrders=fx.GetComponentsInChildren<ParticleSystemRenderer>().Select(r=>r.sortingOrder).ToArray()});Object.DestroyImmediate(fx.gameObject);}
 }finally{if(ogre){Set(ogre,typeof(OgreBrain),"_fightActive",false);typeof(OgreBrain).GetMethod("CancelAll",F).Invoke(ogre,null);}foreach(var go in Object.FindObjectsByType<GameObject>())if(go&&!initial.Contains(go))Object.DestroyImmediate(go);foreach(var f in fields)f.Key.SetValue(p,f.Value);angle.SetValue(rig,oldAngle);camera.transform.position=pos;typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());UnityEngine.Random.state=random;EditorApplication.isPaused=paused;}
 var result=new{method="Temporary original Ogre art overlap front/center/back, ground FX under both actors, production camera/light; all temporary objects removed and player/camera/random restored",checks};File.WriteAllText(Out+"/runtime.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
