using GamePlayer = Demo6.Game.PlayerController;
using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;
public static class V055DownReview {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/v055-shield/down-stand";
 static void Set(GamePlayer p,string n,object v){var f=typeof(GamePlayer).GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 static void Capture(Camera c,string n){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1280,720,24);Texture2D t=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t=new Texture2D(1280,720,TextureFormat.RGBA32,false);t.ReadPixels(new Rect(0,0,1280,720),0,0);t.Apply();File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(t)UnityEngine.Object.DestroyImmediate(t);}}
 public static object Run(){var p=GamePlayer.Instance;var rig=TopDownView.PlayerRig;if(!p||rig==null)throw new Exception("Original Play required");var fields=typeof(GamePlayer).GetFields(F).Where(x=>!x.IsInitOnly&&!x.IsLiteral).ToDictionary(x=>x,x=>x.GetValue(p));var camera=Camera.main;var position=camera.transform.position;var size=camera.orthographicSize;var paused=EditorApplication.isPaused;var angle=typeof(TopDownPlayerRig).GetField("_angle",F);var oldAngle=angle.GetValue(rig);var checks=new List<object>();
 try{EditorApplication.isPaused=true;Set(p,"_hurtTime",-999f);Set(p,"<Weapon>k__BackingField",WeaponPresets.Longsword);angle.SetValue(rig,0f);camera.transform.position=new Vector3(p.transform.position.x+.25f,p.transform.position.y,position.z);
 foreach(var phase in new[]{"Idle","Raise","Hold","Lower","Down","Stand"}){
  Set(p,"_state",phase=="Down"||phase=="Stand"?"Down":phase=="Idle"?"Free":"WeaponAct");Set(p,"_downTimer",.25f);if(phase!="Idle"&&phase!="Down"&&phase!="Stand")Set(p,"_actPhase",phase);Set(p,"_actPhaseTime",phase=="Raise"?.07f:phase=="Lower"?.08f:.1f);rig.FirstAttackArt.Stop();typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.Drive(0,TopDownView.CurrentArt());if(phase=="Stand"){Set(p,"_state","Free");typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.Drive(.1f,TopDownView.CurrentArt());}
  camera.orthographicSize=1.5f;Capture(camera,"shield-"+phase+"-detail");camera.orthographicSize=size;Capture(camera,"shield-"+phase+"-game-scale");var shield=rig.FirstAttackArt.ShieldSurface;checks.Add(new{phase,clip=rig.FirstAttackArt.ClipId,shieldResource=shield?shield.sprite.name:null,bounds=shield?shield.bounds.size.ToString():null,sorting=shield?shield.sortingOrder:0});
 }
 camera.orthographicSize=1.5f;for(int i=0;i<10;i++){float t=i/60f;Set(p,"_state","WeaponAct");Set(p,"_actPhase",t<.12f?"Raise":"Hold");Set(p,"_actPhaseTime",t<.12f?t:t-.12f);rig.FirstAttackArt.Stop();typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.Drive(1f/60f,TopDownView.CurrentArt());Capture(camera,"guard-continuous-"+i.ToString("00"));}
 }finally{foreach(var x in fields)x.Key.SetValue(p,x.Value);angle.SetValue(rig,oldAngle);camera.transform.position=position;camera.orthographicSize=size;EditorApplication.isPaused=paused;rig.FirstAttackArt.Stop();typeof(YSort).GetMethod("LateUpdate",F).Invoke(p.GetComponent<YSort>(),null);rig.Drive(0,TopDownView.CurrentArt());}
 var result=new{method="Original production camera/light; sampled visual poses, not input. 10 consecutive 60 Hz Raise-to-Hold samples. All fields, camera and pause restored.",checks};File.WriteAllText(Out+"/shield-runtime.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
