using GamePlayer = Demo6.Game.PlayerController;
using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Newtonsoft.Json;
public static class V055ShieldReview {
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;const string Out="검증/v055-shield";
 static void Set(GamePlayer p,string n,object v){var f=typeof(GamePlayer).GetField(n,F);if(f.FieldType.IsEnum&&v is string)v=Enum.Parse(f.FieldType,(string)v);f.SetValue(p,v);}
 static Texture2D Shot(Camera c){var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(1280,720,24);var t=new Texture2D(1280,720,TextureFormat.RGB24,false);try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t.ReadPixels(new Rect(0,0,1280,720),0,0);t.Apply();return t;}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);}}
 static void Save(Texture2D t,string n){File.WriteAllBytes(Out+"/"+n+".png",t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}
 static void Tile(Texture2D board,int index,Texture2D shot){board.SetPixels((index%10)*192,board.height-176-(index/10)*176,192,176,shot.GetPixels(544,272,192,176));UnityEngine.Object.DestroyImmediate(shot);}
 public static object Run(){var p=GamePlayer.Instance;var rig=TopDownView.PlayerRig;if(!p||rig==null)throw new Exception("Original Play required");Directory.CreateDirectory(Out);var fields=typeof(GamePlayer).GetFields(F).Where(x=>!x.IsInitOnly&&!x.IsLiteral).ToDictionary(x=>x,x=>x.GetValue(p));var camera=Camera.main;var position=camera.transform.position;var size=camera.orthographicSize;var paused=EditorApplication.isPaused;var angle=typeof(TopDownPlayerRig).GetField("_angle",F);var oldAngle=angle.GetValue(rig);var checks=new List<object>();var ys=p.GetComponent<YSort>();var errors=new List<string>();Application.LogCallback logger=(s,t,l)=>{if(l==LogType.Error||l==LogType.Exception)errors.Add(s);};Application.logMessageReceived+=logger;
 Action<string,float,bool,float> pose=(phase,t,boss,deg)=>{Set(p,"_state",phase=="Idle"?"Free":"WeaponAct");if(phase!="Idle")Set(p,"_actPhase",phase);Set(p,"_actPhaseTime",t);Set(p,"_guardRecoilBoss",boss);Set(p,"_facing",new Vector2(Mathf.Cos(deg*Mathf.Deg2Rad),Mathf.Sin(deg*Mathf.Deg2Rad)));angle.SetValue(rig,deg);typeof(YSort).GetMethod("LateUpdate",F).Invoke(ys,null);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());};
 try{EditorApplication.isPaused=true;Set(p,"_hurtTime",-999f);Set(p,"<Weapon>k__BackingField",WeaponPresets.Longsword);Set(p,"_actKind",WeaponActKind.Guard);camera.transform.position=new Vector3(p.transform.position.x,p.transform.position.y,position.z);
 var lib=JsonUtility.FromJson<CharacterMotionV045.Library>(Resources.Load<TextAsset>("CharacterMotionV045/clips").text);var ids=new[]{"sword-guard-raise","sword-guard-lower","sword-guard-recoil","sword-guard-boss-recoil"};int tile=0;var board=new Texture2D(1920,1584,TextureFormat.RGB24,false);
 foreach(var id in ids){var clip=lib.clips.First(c=>c.id==id);string phase=id.EndsWith("raise")?"Raise":id.EndsWith("lower")?"Lower":"Recoil";foreach(var f in clip.frames){pose(phase,Mathf.Min(f.t,clip.duration-.00001f),id.Contains("boss"),0);var a=rig.FirstAttackArt;Tile(board,tile++,Shot(camera));var rendered=(SpriteRenderer[])typeof(FirstAttackArtV042).GetField("_parts",F).GetValue(a);var current=(FirstAttackArtV042.Frame)typeof(FirstAttackArtV042).GetField("_currentFrame",F).GetValue(a);checks.Add(new{id,t=f.t,clip=a.ClipId,cel=a.FrameIndex,shieldRenderers=current.parts.Count(x=>x.name.Contains("shield")&&rendered[x.layer].enabled),parts=a.VisiblePartCount,expected=a.ExpectedPartCount});}}
 board.Apply();Save(board,"all-native-frames-game-scale");
 board=new Texture2D(1920,880,TextureFormat.RGB24,false);tile=0;foreach(var deg in new[]{0f,45f,90f,135f,180f,225f,270f,315f})foreach(var phase in new[]{"Idle","Raise","Hold","Recoil","Boss","Lower"}){pose(phase=="Boss"?"Recoil":phase,phase=="Hold"?.1f:.06f,phase=="Boss",deg);Tile(board,tile++,Shot(camera));if(phase=="Hold")Save(Shot(camera),"hold-direction-"+deg);}
 board.Apply();Save(board,"directions-game-scale");
 for(int i=0;i<10;i++){float t=i/60f;pose(t<.12f?"Raise":"Hold",t<.12f?t:t-.12f,false,0);Save(Shot(camera),"guard-continuous-"+i.ToString("00"));}
 foreach(var phase in new[]{"Idle","Raise","Hold","Recoil","Lower"}){pose(phase,.06f,false,0);camera.orthographicSize=1.5f;Save(Shot(camera),"detail-"+phase);camera.orthographicSize=size;}
 }finally{foreach(var x in fields)x.Key.SetValue(p,x.Value);angle.SetValue(rig,oldAngle);camera.transform.position=position;camera.orthographicSize=size;typeof(YSort).GetMethod("LateUpdate",F).Invoke(ys,null);rig.FirstAttackArt.Stop();rig.Drive(0,TopDownView.CurrentArt());EditorApplication.isPaused=paused;Application.logMessageReceived-=logger;}
 var result=new{utc=DateTime.UtcNow.ToString("O"),method="Original scene production camera/light. Synthetic visual-state samples, no input injection. Full 81 native frames and 8 directions. Native-size crop boards; camera position centered only; zoomed supplementary detail. All player fields, camera and pause restored.",checks,errors};File.WriteAllText(Out+"/guard-runtime.json",JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
