local root=[[E:/personalProject/Demo3/demo6/아트/정수리-질감수정-v10]]
local pc=app.pixelColor
local function clamp(n,a,b)return math.max(a,math.min(b,n))end
local function pix(r,g,b,a)return pc.rgba(clamp(math.floor(r+.5),0,255),clamp(math.floor(g+.5),0,255),clamp(math.floor(b+.5),0,255),clamp(math.floor(a+.5),0,255))end
local function open(id)local s=app.open(root..'/generated/'..id..'.png');local im=Image(s.spec);im:drawSprite(s,1);s:close();return im end
local function sprite(w,h)local s=Sprite(w,h,ColorMode.RGB);s:deleteLayer(s.layers[1]);return s end
local function add(s,name,im,at)local l=s:newLayer();l.name=name;s:newCel(l,1,im,at or Point(0,0));return l end
local function merged(s)local im=Image(s.spec);im:drawSprite(s,1);return im end
local function poly(x,y,p)local c=false;local j=#p;for i=1,#p do local a,b=p[i],p[j];if (a[2]>y)~=(b[2]>y) and x<(b[1]-a[1])*(y-a[2])/(b[2]-a[2])+a[1] then c=not c end;j=i end;return c end
local function split(im,names,which)local s=sprite(im.width,im.height);local layers={};for _,n in ipairs(names)do local l=s:newLayer();l.name=n;layers[#layers+1]=s:newCel(l,1,Image(s.spec),Point(0,0)).image end;for y=0,im.height-1 do for x=0,im.width-1 do local p=im:getPixel(x,y);if pc.rgbaA(p)>0 then local i=which(x,y,p);if i then layers[i]:drawPixel(x,y,p)end end end end;return s end
local manifests={};local exports={}
local function save(s,id,notes)local out=merged(s);local dir=root..'/layers/'..id;app.fs.makeAllDirectories(dir);local meta={width=s.width,height=s.height,layers={}};for _,l in ipairs(s.layers)do local c=l:cel(1);if c then local im=Image(s.spec);im:drawImage(c.image,c.position);local file=dir..'/'..l.name..'.rgba';local f=io.open(file,'wb');f:write(im.bytes);f:close();im:saveAs(dir..'/'..l.name..'.png');table.insert(meta.layers,{name=l.name,x=0,y=0,width=s.width,height=s.height,file=file,visible=l.isVisible})end end;local f=io.open(dir..'/composite.rgba','wb');f:write(out.bytes);f:close();f=io.open(dir..'/psd-layers.json','w');f:write(json.encode(meta));f:close();out:saveAs(root..'/PNG/'..id..'.png');s:saveAs(root..'/'..id..'-master-v010.aseprite');table.insert(manifests,{id=id,width=s.width,height=s.height,layers=#s.layers,notes=notes});return out end
local function sample(im,x,y)local ix,iy=math.floor(x),math.floor(y);local fx,fy=x-ix,y-iy;local r,g,b,a=0,0,0,0;for j=0,1 do for i=0,1 do if ix+i>=0 and ix+i<im.width and iy+j>=0 and iy+j<im.height then local p=im:getPixel(ix+i,iy+j);local w=(i==0 and 1-fx or fx)*(j==0 and 1-fy or fy);local wa=w*pc.rgbaA(p);a=a+wa;r=r+pc.rgbaR(p)*wa;g=g+pc.rgbaG(p)*wa;b=b+pc.rgbaB(p)*wa end end end;if a<.1 then return 0 end;return pix(r/a,g/a,b/a,a)end
local function output(id,im,w,h,map,ppu,pivot)local out=Image(w,h,ColorMode.RGB);for y=0,h-1 do for x=0,w-1 do local sx,sy=map(x+.5,y+.5);out:drawPixel(x,y,sample(im,sx,sy))end end;out:saveAs(root..'/runtime-PNG/'..id..'.png');table.insert(exports,{id=id,width=w,height=h,ppu=ppu,pivot=pivot or {.5,.5}});return out end
local function cropout(id,im,rect,w,h,ppu,pivot)return output(id,im,w,h,function(x,y)return rect[1]+x/w*rect[3]-.5,rect[2]+y/h*rect[4]-.5 end,ppu,pivot)end
app.fs.makeAllDirectories(root..'/PNG');app.fs.makeAllDirectories(root..'/runtime-PNG')
-- Native source pixels are preserved; these selections separate visible painted parts, not unseen back surfaces.
local body=open('body-soft-native');local helm={{617,459},{716,446},{845,478},{925,538},{993,617},{984,646},{923,698},{886,754},{779,797},{676,789},{606,747},{569,678},{567,571}}
local bs=split(body,{'01-underarmor','02-shoulder-left','03-shoulder-right','04-helmet'},function(x,y)if poly(x,y,helm)then return 4 elseif y<449 then return 2 elseif y>797 then return 3 else return 1 end end);save(bs,'hero-body','Native 1254px source; helmet and both shoulders split on visible outlines. No hidden surface reconstruction.');bs.layers[4].isVisible=false;local torso=merged(bs);bs.layers[1].isVisible=false;bs.layers[2].isVisible=false;bs.layers[3].isVisible=false;bs.layers[4].isVisible=true;local head=merged(bs);local function bodymap(x,y)return 665+(x-160)*1080/256,625+(y-160)*1080/256 end;output('body_leather',torso,320,320,bodymap,256);output('helm_leather',head,320,320,bodymap,256);bs:close()
local cape=open('cape-original');local cs=split(cape,{'01-cloth-upper','02-cloth-middle','03-cloth-lower','04-collar'},function(x,y)if x>1025 then return 4 elseif y<400 then return 1 elseif y>625 then return 3 else return 2 end end);save(cs,'hero-cape','Native generated cloth, visible fold regions separated; no upscaling.');cropout('short_cape',cape,{280,104,960,810},320,224,256,{.88,.5});cs:close()
local wall=open('wall-soft-native');local ws=split(wall,{'01-west-rocks','02-midwest-rocks','03-mideast-rocks','04-east-rocks'},function(x,y)return math.min(4,math.floor(x/(wall.width/4))+1)end);save(ws,'mine-rocks','Native painted rocky strip, four editable visible rock groups; placement compositions below reuse/mirror groups.');ws:close()
-- Wall strips keep physical lengths. Alpha only adds a small craggy visual fringe; collision remains 1 unit.
local function wallout(id,len,seed,vertical)local w,h=math.floor(len*128+.5),180;local im=Image(w,h,ColorMode.RGB);for y=0,h-1 do for x=0,w-1 do local seg=math.floor(x/490);local u=x%490;local sx=(seed*271+seg*733+(seg%2==0 and u or 490-u)*2.1)%1840+155;local sy=164+y/h*405;local p=sample(wall,sx,sy);im:drawPixel(x,y,p)end end;if vertical then local v=Image(h,w,ColorMode.RGB);for y=0,h-1 do for x=0,w-1 do v:drawPixel(h-y-1,x,im:getPixel(x,y))end end;im=v end;im:saveAs(root..'/runtime-PNG/'..id..'.png');table.insert(exports,{id=id,width=im.width,height=im.height,ppu=128,pivot={.5,.5}})end
wallout('wall_h29',29,1,false);wallout('wall_v17',17,2,true);wallout('wall_v6a',6.5,3,true);wallout('wall_v6b',6.5,4,true)
local pillars=open('pillars-original');local pils=split(pillars,{'01-pier-west','02-pier-east'},function(x,y)return x<pillars.width/2 and 1 or 2 end);save(pils,'mine-pillars','Two separately painted closed silhouettes; not square crops of a wall.');cropout('pillar_a',pillars,{135,43,780,720},180,180,128);cropout('pillar_b',pillars,{1080,50,800,720},180,180,128);cropout('rubble',pillars,{135,43,780,720},136,110,128);pils:close()
-- Four distinct native ground regions, no enlargement. 182x104 overlap gives 3136x1792, exactly 112px per world unit.
local function seam(old,im,ox,oy,vertical)
 local width=vertical and 182 or 104;local height=vertical and im.height or im.width;local back={};local prev={}
 for row=0,height-1 do local cur={};back[row]={};for col=4,width-5 do local x=vertical and col or row;local y=vertical and row or col;local a=old:getPixel(ox+x,oy+y);local b=im:getPixel(x,y);local cost=math.abs(pc.rgbaR(a)-pc.rgbaR(b))+math.abs(pc.rgbaG(a)-pc.rgbaG(b))+math.abs(pc.rgbaB(a)-pc.rgbaB(b));local best=0;local at=col;if row>0 then best=1e12;for j=math.max(4,col-2),math.min(width-5,col+2)do local v=prev[j]+math.abs(j-col)*1.5;if v<best then best=v;at=j end end end;cur[col]=cost+best;back[row][col]=at end;prev=cur end
 local at=4;for col=5,width-5 do if prev[col]<prev[at]then at=col end end;local out={};for row=height-1,0,-1 do out[row]=at;at=back[row][at]end;return out
end
local fs=sprite(3136,1792);local floors={open('floor-soft-native'),open('floor-1'),open('floor-2'),open('floor-3')};for i,im in ipairs(floors)do if im.width>1659 then im=Image(im,Rectangle(0,0,1659,948))end;local ix=(i-1)%2;local iy=math.floor((i-1)/2);local ox=ix*1477;local oy=iy*844;local old=merged(fs);local sv=ix==1 and seam(old,im,ox,oy,true)or nil;local sh=iy==1 and seam(old,im,ox,oy,false)or nil;local m=Image(im);for y=0,m.height-1 do for x=0,m.width-1 do local a=1;if sv then a=a*clamp((x-sv[y]+1)/2,0,1)end;if sh then a=a*clamp((y-sh[x]+1)/2,0,1)end;if a<1 then local p=m:getPixel(x,y);m:drawPixel(x,y,pix(pc.rgbaR(p),pc.rgbaG(p),pc.rgbaB(p),a*255))end end end;add(fs,'0'..i..'-painted-ground-region',m,Point(ox,oy))end
local ground=save(fs,'entry-floor','3136x1792 native detail mosaic of four repainted native 1659x948 regions. 112 PPU. Content-matched overlap seams, no blur or finishing filter; originals retained. No 4K detail restoration claimed.');ground:saveAs(root..'/runtime-PNG/entry_floor.png');table.insert(exports,{id='entry_floor',width=3136,height=1792,ppu=112,pivot={.5,.5}});fs:close()

local im=open('arch-original');local ar=split(im,{'01-west-stones','02-east-stones','03-earth-timber-spill'},function(x,y)if x<im.width*.25 then return 1 elseif x>im.width*.76 then return 2 else return 3 end end);save(ar,'blocked-arch','Native repainted worn stone and quiet earth; visible regions separated.');cropout('blocked_arch',im,{0,0,im.width,im.height},640,320,128);ar:close()
local f=io.open(root..'/manifest.json','w');f:write(json.encode(manifests));f:close();f=io.open(root..'/runtime-manifest.json','w');f:write(json.encode(exports));f:close();print('v9: '..#manifests..' native layered master collections; '..#exports..' runtime sprites')
