using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;
public static class V10NativeGui {
 delegate bool EnumProc(IntPtr h,IntPtr p);
 [DllImport("user32.dll")]static extern bool EnumWindows(EnumProc cb,IntPtr p);
 [DllImport("user32.dll")]static extern bool EnumChildWindows(IntPtr h,EnumProc cb,IntPtr p);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr h,out uint pid);
 [DllImport("user32.dll")]static extern int GetClassName(IntPtr h,StringBuilder b,int n);
 [DllImport("user32.dll")]static extern bool GetWindowRect(IntPtr h,out Bounds r);
 [DllImport("user32.dll")]static extern bool PostMessage(IntPtr h,uint msg,IntPtr w,IntPtr l);
 [StructLayout(LayoutKind.Sequential)]struct Bounds{public int x,y,r,b; public override string ToString()=>x+","+y+","+(r-x)+","+(b-y);}
 public static object Inspect(){if(!Application.dataPath.Contains("topdown-v10-review-isolated"))throw new Exception("Owned clone only");var list=new List<object>();uint own=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumProc inspect=(h,p)=>{GetWindowThreadProcessId(h,out uint id);if(id==own){var b=new StringBuilder(200);GetClassName(h,b,200);GetWindowRect(h,out var r);list.Add(new{handle=h.ToInt64(),cls=b.ToString(),rect=r.ToString()});}return true;};EnumWindows((h,p)=>{GetWindowThreadProcessId(h,out uint id);if(id==own){inspect(h,p);EnumChildWindows(h,inspect,p);}return true;},IntPtr.Zero);return list;}
 public static async Task<object> Click(){if(!Application.dataPath.Contains("topdown-v10-review-isolated"))throw new Exception("Owned clone only");var t=typeof(Editor).Assembly.GetType("UnityEditor.GameView");var v=EditorWindow.GetWindow(t);var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic;var r=(Rect)t.GetProperty("targetInParent",flags).GetValue(v);var source=DungeonHud.UtilityRect(0).center*DungeonUi.Scale;var at=r.position+Vector2.Scale(source,new Vector2(r.width/Screen.width,r.height/Screen.height));IntPtr target=IntPtr.Zero;uint own=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumWindows((h,p)=>{GetWindowThreadProcessId(h,out uint id);if(id==own)EnumChildWindows(h,(child,a)=>{GetWindowRect(child,out var b);if(Math.Abs(b.x-v.position.x)<3&&Math.Abs(b.y-v.position.y)<3)target=child;return true;},p);return true;},IntPtr.Zero);if(target==IntPtr.Zero)throw new Exception("GameView HWND not found");var l=(IntPtr)((int)at.x|((int)at.y<<16));PostMessage(target,0x200,IntPtr.Zero,l);await Task.Delay(200);PostMessage(target,0x201,(IntPtr)1,l);await Task.Delay(160);PostMessage(target,0x202,IntPtr.Zero,l);await Task.Delay(500);return new{target=target.ToInt64(),at=at.ToString(),modal=DungeonUi.Modal};}
}
