using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using UnityEngine.Rendering.Universal;using Demo6.Game;
public static class V10PlayChecks {
 const string Root="E:/personalProject/Demo3/demo6/검증/정수리-질감수정-v10";
 const BindingFlags F=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;
 static void Guard(){if(!Application.dataPath.Contains("topdown-v10-review-isolated")||!EditorApplication.isPlaying||!DungeonRoot.Instance||TopDownView.PlayerRig==null||!TopDownView.PlayerRig.Applied)throw new Exception("Owned isolated Dungeon Play required");}
 sealed class InputScope:IDisposable {
  public Vector2 Aim=Vector2.up;public Key[] Keys=Array.Empty<Key>();public ushort Buttons;
  readonly InputActionMap actionMap; readonly UnityEngine.InputSystem.Utilities.ReadOnlyArray<InputDevice>? previousDevices; readonly Keyboard keyboard;readonly Mouse mouse;readonly List<InputDevice> enabled=new List<InputDevice>();readonly InputSettings settings;readonly InputSettings.BackgroundBehavior bg;readonly InputSettings.EditorInputBehaviorInPlayMode editor;
  public InputScope(){settings=InputSystem.settings;bg=settings.backgroundBehavior;editor=settings.editorInputBehaviorInPlayMode;settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;settings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;foreach(var d in InputSystem.devices.ToArray())if((d is Keyboard||d is Mouse)&&d.enabled){enabled.Add(d);InputSystem.DisableDevice(d);}keyboard=InputSystem.AddDevice<Keyboard>("V10ReviewKeyboard");mouse=InputSystem.AddDevice<Mouse>("V10ReviewMouse");actionMap=(InputActionMap)typeof(PlayerInputReader).GetField("_map",F).GetValue(PlayerController.Instance.GetComponent<PlayerInputReader>());previousDevices=actionMap.devices;actionMap.devices=new InputDevice[]{keyboard,mouse};InputSystem.onBeforeUpdate+=Feed;}
  void Feed(){if(!PlayerController.Instance||!Camera.main)return;Vector2 cursor=Camera.main.WorldToScreenPoint(PlayerController.Instance.transform.position+(Vector3)(Aim*4));InputSystem.QueueStateEvent(keyboard,new KeyboardState(Keys));InputSystem.QueueStateEvent(mouse,new MouseState{position=cursor,buttons=Buttons});}
  public void Dispose(){InputSystem.onBeforeUpdate-=Feed;actionMap.devices=previousDevices;InputSystem.RemoveDevice(keyboard);InputSystem.RemoveDevice(mouse);foreach(var d in enabled)if(d.added)InputSystem.EnableDevice(d);settings.backgroundBehavior=bg;settings.editorInputBehaviorInPlayMode=editor;}
 }
 sealed class SizeScope:IDisposable {
  readonly Type gt;readonly EditorWindow view;readonly PropertyInfo index;readonly object group,entry;readonly int previous;
  public SizeScope(int w,int h){var ass=typeof(Editor).Assembly;gt=ass.GetType("UnityEditor.GameView");view=Resources.FindObjectsOfTypeAll(gt).Cast<EditorWindow>().FirstOrDefault()??EditorWindow.GetWindow(gt);index=gt.GetProperty("selectedSizeIndex",F);previous=(int)index.GetValue(view);var sizes=typeof(ScriptableSingleton<>).MakeGenericType(ass.GetType("UnityEditor.GameViewSizes")).GetProperty("instance").GetValue(null);group=sizes.GetType().GetMethod("GetGroup").Invoke(sizes,new object[]{GameViewSizeGroupType.Standalone});entry=Activator.CreateInstance(ass.GetType("UnityEditor.GameViewSize"),new object[]{Enum.ToObject(ass.GetType("UnityEditor.GameViewSizeType"),1),w,h,"V9 temporary paired check"});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{entry});index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();}
  public void Dispose(){index.SetValue(view,previous);foreach(var f in group.GetType().GetFields(F))if(f.GetValue(group)is IList list&&!list.IsReadOnly)for(int i=list.Count-1;i>=0;i--)if(ReferenceEquals(list[i],entry))list.RemoveAt(i);view.Repaint();}
 }
 static void Shot(string file,int width,int height){var c=Camera.main;var old=c.targetTexture;var active=RenderTexture.active;var rt=RenderTexture.GetTemporary(width,height,24);Texture2D tex=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex=new Texture2D(width,height,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,width,height),0,0);tex.Apply();File.WriteAllBytes(file,tex.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);if(tex)UnityEngine.Object.DestroyImmediate(tex);}}
 static string LightState()=>string.Join("|",UnityEngine.Object.FindObjectsByType<Light2D>().OrderBy(l=>l.GetEntityId().ToString()).Select(l=>l.GetEntityId()+":"+l.transform.position+":"+l.intensity+":"+l.color));
 static string WallState()=>string.Join("|",UnityEngine.Object.FindObjectsByType<Collider2D>().Where(c=>c.gameObject.layer==Layers.Wall).OrderBy(c=>c.GetEntityId().ToString()).Select(c=>c.GetEntityId()+":"+c.transform.position+":"+c.bounds));
 public static async Task<object> Compare(string label="default",int height=1080,bool lightLamp=false){
  Guard();bool inv=Tuning.Invincible;Tuning.Invincible=true;int width=height==720?1280:1920;var p=PlayerController.Instance;var origin=p.Position;bool paused=EditorApplication.isPaused;string folder=Root+"/paired-"+label+"/"+height;Directory.CreateDirectory(folder);var rows=new List<object>();string walls=WallState();EditorApplication.LockReloadAssemblies();try{using(var input=new InputScope())using(var size=new SizeScope(width,height)){Application.runInBackground=true;EditorApplication.isPaused=false;await Task.Delay(900);var lamp=UnityEngine.Object.FindObjectsByType<WallLamp>().First(l=>l.name=="WallLamp f1.E.lamp");if(lightLamp&&!lamp.Lit){p.Teleport(new Vector2(-5,21.7f));Camera.main.GetComponent<DungeonCamera>().Snap();input.Aim=Vector2.up;await Task.Delay(300);input.Keys=new[]{Key.F};await Task.Delay(1500);input.Keys=Array.Empty<Key>();await Task.Delay(100);if(!lamp.Lit)throw new Exception("Normal F hold did not light lamp");}
  foreach(var spot in new[]{new{name="entry",at=new Vector2(-6,16)},new{name="pillar",at=new Vector2(-8,11.4f)},new{name="lamp",at=new Vector2(-5,21)}}){p.Teleport(spot.at);Camera.main.GetComponent<DungeonCamera>().Snap();input.Aim=Vector2.up;await Task.Delay(750);EditorApplication.isPaused=true;int frame=Time.frameCount;string lights=LightState();var swaps=new List<(SpriteRenderer sr,Sprite after,Sprite before)>();foreach(var sr in UnityEngine.Object.FindObjectsByType<SpriteRenderer>()){if(!sr.sprite)continue;string path=AssetDatabase.GetAssetPath(sr.sprite);if(!path.Contains("TopDownPilotV9/"))continue;var before=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/ReviewV10/Before/"+Path.GetFileName(path));if(before)swaps.Add((sr,sr.sprite,before));}
  try{foreach(var v in swaps)v.sr.sprite=v.before;Shot(folder+"/"+spot.name+"-before.png",width,height);foreach(var v in swaps)v.sr.sprite=v.after;Shot(folder+"/"+spot.name+"-after.png",width,height);}finally{foreach(var v in swaps)if(v.sr)v.sr.sprite=v.after;}
  rows.Add(new{spot=spot.name,position=p.Position.ToString(),facing=p.FacingDirection.ToString(),lampLit=lamp.Lit,frameStart=frame,frameEnd=Time.frameCount,lightsIdentical=lights==LightState(),collidersIdentical=walls==WallState(),swaps=swaps.Count,camera=Camera.main.transform.position.ToString(),size=Camera.main.orthographicSize});EditorApplication.isPaused=false;await Task.Delay(150);ScreenCapture.CaptureScreenshot(folder+"/"+spot.name+"-game.png");await Task.Delay(350);}
  }}finally{Tuning.Invincible=inv;p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();EditorApplication.isPaused=paused;EditorApplication.UnlockReloadAssemblies();}var result=new{label,width,height,rows,wallsUnchanged=walls==WallState()};File.WriteAllText(folder+"/checks.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
 public static async Task<object> All(){await Compare("default",720,false);await Compare("default",1080,false);await Compare("lamp-lit",720,true);await Compare("lamp-lit",1080,true);return "12 v9/v10 same-frame pairs complete";}
public static async Task<object> Actions(){Guard();bool inv=Tuning.Invincible;Tuning.Invincible=true;var p=PlayerController.Instance;var origin=p.Position;bool paused=EditorApplication.isPaused;string folder=Root+"/actions";Directory.CreateDirectory(folder);var seen=new HashSet<string>();var shots=new List<object>();var errors=new List<string>();Application.LogCallback log=(m,s,t)=>{if(t==LogType.Error||t==LogType.Exception)errors.Add(m);};Application.logMessageReceived+=log;EditorApplication.LockReloadAssemblies();float maxLag=0,maxDrag=0;try{using(var input=new InputScope())using(var size=new SizeScope(1920,1080)){EditorApplication.isPaused=false;p.Teleport(new Vector2(-3,17));Camera.main.GetComponent<DungeonCamera>().Snap();await Task.Delay(300);
 for(int i=0;i<8;i++){float a=i*Mathf.PI/4;input.Aim=new Vector2(Mathf.Cos(a),Mathf.Sin(a));await Task.Delay(300);Shot(folder+"/direction-"+i+".png",1920,1080);shots.Add(new{kind="direction",i,facing=p.FacingDirection.ToString(),pose=p.Pose.ToString()});}
 var start=p.Position;input.Keys=new[]{Key.W};for(int i=0;i<5;i++){await Task.Delay(120);seen.Add(p.Pose.ToString());var cape=p.GetComponentInChildren<TopDownCape>();if(cape){maxLag=Mathf.Max(maxLag,Mathf.Abs(cape.TailLag));maxDrag=Mathf.Max(maxDrag,cape.TailDrag.magnitude);}Shot(folder+"/walk-"+i+".png",1920,1080);}input.Keys=Array.Empty<Key>();float moved=Vector2.Distance(start,p.Position);await Task.Delay(250);
 foreach(string action in new[]{"attack","whirl","wave","dodge"}){input.Aim=Vector2.up;input.Buttons=(ushort)(action=="attack"?1:action=="whirl"?2:0);input.Keys=action=="wave"?new[]{Key.Q}:action=="dodge"?new[]{Key.Space}:Array.Empty<Key>();for(int i=0;i<7;i++){await Task.Delay(80);seen.Add(p.Pose.ToString());Shot(folder+"/"+action+"-"+i+".png",1920,1080);shots.Add(new{kind=action,i,pose=p.Pose.ToString(),position=p.Position.ToString()});if(i==0&&action!="attack"){input.Buttons=0;input.Keys=Array.Empty<Key>();}}input.Buttons=0;input.Keys=Array.Empty<Key>();await Task.Delay(1500);}var result=new{moved,observedPoses=seen.ToArray(),maxCapeLag=maxLag,maxCapeDrag=maxDrag,shots,errors};File.WriteAllText(folder+"/checks.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;}}finally{Tuning.Invincible=inv;p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();EditorApplication.isPaused=paused;Application.logMessageReceived-=log;EditorApplication.UnlockReloadAssemblies();}}
}
