const fs=require('fs'),crypto=require('crypto');
const ev='검증/오우거-팔교정-v029',art='아트/오우거-팔교정-v029';
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const before=JSON.parse(fs.readFileSync('검증/오브젝트-잔여-v026/original-play/before.json'));
const changed=before.filter(x=>fs.existsSync(x.path)&&hash(x.path)!==x.sha256).map(x=>x.path),deleted=before.filter(x=>!fs.existsSync(x.path)).map(x=>x.path);
const all=[];function walk(d){for(const x of fs.readdirSync(d,{withFileTypes:true})){let p=d+'/'+x.name;if(x.isDirectory())walk(p);else all.push(p)}}for(const d of ['Assets','Packages','ProjectSettings'])walk(d);
const seen=new Set(before.map(x=>x.path)),added=all.filter(x=>!seen.has(x));
function gif(p){const b=fs.readFileSync(p);let at=13+((b[10]&128)?3*(1<<((b[10]&7)+1)):0),frames=0,delays=[];const skip=()=>{while(b[at])at+=b[at]+1;at++};while(at<b.length){let tag=b[at++];if(tag===0x3b)break;if(tag===0x21){let kind=b[at++];if(kind===0xf9)delays.push(b.readUInt16LE(at+2)*10);skip()}else if(tag===0x2c){let flags=b[at+8];at+=9;if(flags&128)at+=3*(1<<((flags&7)+1));at++;skip();frames++;}else throw Error('Unexpected GIF tag '+tag);}return{file:p,frames,delaysMs:delays,totalMs:delays.reduce((a,b)=>a+b,0)}}
const gifs=['A-slam','D-sweep'].map(n=>gif(art+'/'+n+'-before-after-normal-10f.gif'));
const clips=fs.readdirSync(ev+'/frames').map(n=>{const tr=JSON.parse(fs.readFileSync(ev+'/frames/'+n+'/trace.json'));const picked=tr.filter((f,i)=>f.saved>(i?tr[i-1].saved:0));return{clip:n,frames:tr.length,sourceFrames:picked.map(f=>f.frameIndex),consecutive:picked.length===10&&picked.every((f,i)=>!i||f.frameIndex===picked[i-1].frameIndex+1),maxUpperScale:Math.max(...tr.map(f=>f.upperScale)),maxForeScale:Math.max(...tr.map(f=>f.foreScale)),rest:tr.at(-1).state};});
const pre=fs.readFileSync('AgentScripts/v13_validate.js','utf8').split('const ref=')[0];const png=new Function('require',pre+'return png;')(require);
const a=png(art+'/ogre-v029-neutral.png'),b=png(art+'/ogre-v029-reopened.png');let pixelDifference=0;for(let i=0;i<a.rgba.length;i++)if(a.rgba[i]!==b.rgba[i])pixelDifference++;
const old=png(ev+'/backup/upper_R_rounded_styled.png'),now=png('Assets/Resources/OgreApproved/upper_R_rounded_styled.png');let alphaChangedPixels=0,colorChangedPixels=0;for(let i=0;i<old.rgba.length;i+=4){if(old.rgba[i+3]!==now.rgba[i+3])alphaChangedPixels++;if(old.rgba[i]!==now.rgba[i]||old.rgba[i+1]!==now.rgba[i+1]||old.rgba[i+2]!==now.rgba[i+2])colorChangedPixels++;}
const result={changed,deleted,added,gifs,clips,native:{canvas:[a.w,a.h],reopenChannelDifferences:pixelDifference,alphaChangedPixels,colorChangedPixels},gameSizeBasis:{measuredIn:'original CombatTest Play, prior to props verification',pixelWidth:1496,pixelHeight:1080,orthographicSize:9.565508,pixelsPerUnit:56.45283,reviewPixelsPerUnit:640/8.3,comparisonTilePixels:469,roundingErrorUnderPixels:1},limits:['Controlled brain sampling is not a user keyboard/mouse test.','GIF timing alternates 20/30ms to retain the 250ms total of ten 40Hz frames.','Visual acceptance by the user has not been claimed.']};
fs.writeFileSync(ev+'/final-audit.json',JSON.stringify(result,null,2));
const ownedChanges=['Assets/Resources/OgreApproved/upper_R_rounded_styled.png','Assets/Scripts/Game/Art/TopDown/OgreArtRig.cs'];
result.ownedChanges=ownedChanges;result.concurrentChangesObserved=changed.filter(p=>!ownedChanges.includes(p));result.concurrentChangesPolicy='Observed only; not edited or reverted by this arm correction task.';
fs.writeFileSync(ev+'/final-audit.json',JSON.stringify(result,null,2));
if(ownedChanges.some(p=>!changed.includes(p))||added.length||deleted.length||pixelDifference||gifs.some(g=>g.frames!==10||g.totalMs!==250)||clips.some(c=>!c.consecutive||c.maxUpperScale>1.0001))throw Error('Audit failed');
let p='검증/오브젝트-잔여-v026/original/current-status.json',status=JSON.parse(fs.readFileSync(p));status.originalRuntimeReview='Completed in original DungeonTest Play: applied lantern/chain visible and lit; actual InteractionSystem selection+Use opened temporary null-id wood/iron chests; no duplicate rewards, no virtual input.';status.originalRuntimeEvidence='검증/오브젝트-잔여-v026/original-play/props-play-result.json';status.originalUnityState='Restored TestLauncher Edit, Play=false, Pause=false, dirty=false; all native devices enabled';fs.writeFileSync(p,JSON.stringify(status,null,2)+'\n');
p='작업물안내.ko.md';let text=fs.readFileSync(p,'utf8').replace('[원본 연결·모션·10프레임 미리보기](아트/오우거-인게임-v027/적용상태.txt)','[팔 교정·정상 속도 전후 비교](아트/오우거-팔교정-v029/적용상태.txt)').replace('원본 적용·11개 패턴/상태 검증 완료.','v029 팔 길이·회전·겹침 교정 적용. 11개 패턴/상태 재검증.').replace('등불·사슬·상자는 기존 격리 검증을 통과했으나 **원본 Play 재검증은 입력 확인 후 진행**한다.','등불·사슬·상자는 **원본 DungeonTest Play 검증 완료**. 기존 광원 반응과 실제 상호작용 경로의 닫힘→열림을 확인했다. 가상 입력은 사용하지 않았으며 실제 키보드 입력 성공을 대신 주장하지 않는다.').replace('최신 코드는 원본 `Assets`와 v027 적용 상태를 따른다.','최신 코드는 원본 `Assets`와 v029 팔 교정 적용 상태를 따른다. v027 미리보기는 교정 전·4배 느린 재생 기록이다.');fs.writeFileSync(p,text);
console.log(JSON.stringify({changed,added,deleted,gifs,native:result.native,totalSampledFrames:clips.reduce((a,c)=>a+c.frames,0)},null,2));
