const fs=require('fs');let s=fs.readFileSync('AgentScripts/MapV32Integration.cs','utf8');
function r(a,b){if(!s.includes(a))throw Error(a);s=s.replace(a,b);}
s=s.replaceAll('MapV32Integration','MapV32Composition');
r('Root+"검증/맵-화풍정리-v032/"','Root+"검증/맵-화풍정리-v032/composition/"');
r('(string)p["expectedTargetSha256"],"Target changed; preserve concurrent work"','(string)p["sourceSha256"],"Installed target changed; preserve concurrent work"');
r('bool applied=false,success=false;GameObject review=null;','bool applied=false,success=false;var tempArt=new List<UnityEngine.Object>();GameObject review=null;');
r('var allSprites=Object.FindObjectsByType<SpriteRenderer>();','var allSprites=Object.FindObjectsByType<SpriteRenderer>();');
r('var worldColliders=Object.FindObjectsByType<Collider2D>();','var installedFloor=floors[0].sprite;var installedArch=arches[0].sprite;\n            Sprite OldSprite(string filename,Sprite installed)\n            {\n                var tex=new Texture2D(2,2,TextureFormat.RGBA32,installed.texture.mipmapCount>1);tex.LoadImage(File.ReadAllBytes(Root+"검증/맵-화풍정리-v032/backup/"+filename));tex.filterMode=installed.texture.filterMode;tex.wrapMode=installed.texture.wrapMode;tex.anisoLevel=installed.texture.anisoLevel;\n                var sprite=Sprite.Create(tex,new Rect(0,0,tex.width,tex.height),Vector2.one*.5f,installed.pixelsPerUnit,0,SpriteMeshType.FullRect);tempArt.Add(sprite);tempArt.Add(tex);return sprite;\n            }\n            var oldFloor=OldSprite("floor.png",installedFloor);var oldArch=OldSprite("blocked_arch.png",installedArch);\n            foreach(var sr in floors)sr.sprite=oldFloor;foreach(var sr in arches)sr.sprite=oldArch;\n            var worldColliders=Object.FindObjectsByType<Collider2D>();');
r('var art=dungeon.ProjectArt.topDown;','var visibility=Object.FindObjectsByType<Renderer>().Where(r=>r.name=="Vision veil"||r.name=="Vision memory fog").ToDictionary(r=>r,r=>r.enabled);foreach(var pair in visibility)pair.Key.enabled=false;\n            var art=dungeon.ProjectArt.topDown;');
r('var places=new[]{new Vector2(-3,18),new Vector2(0,18),new Vector2(6,18)};','Vector2 anchor=dungeon.Player.Position;var places=new[]{anchor+new Vector2(0,2.6f),anchor+new Vector2(2.4f,1.2f),anchor+new Vector2(6,3)};');
r('Telegraph.Circle(new Vector2(-3,16.5f),1.2f,1)','Telegraph.Circle(anchor+new Vector2(0,1.8f),1.2f,1)');
r('Telegraph.HalfDisc(new Vector2(6,16.5f),Vector2.down,3,1)','Telegraph.HalfDisc(anchor+new Vector2(6,1.2f),Vector2.down,3,1)');
r('Telegraph.Rect(new Vector2(-9,11.3f),Vector2.right,7.55f,1.2f,1)','Telegraph.Rect(anchor+new Vector2(-4,-2.7f),Vector2.right,7.55f,1.2f,1)');
r('applied=true;foreach(var p in plan){File.Copy(Root+(string)p["source"],Root+(string)p["target"],true);AssetDatabase.ImportAsset((string)p["target"],ImportAssetOptions.ForceSynchronousImport|ImportAssetOptions.ForceUpdate);}','foreach(var sr in floors)sr.sprite=installedFloor;foreach(var sr in arches)sr.sprite=installedArch;');
r('cam.transform.position=gamePosition;Capture(cam,"map-after-game.png"','foreach(var pair in visibility)if(pair.Key)pair.Key.enabled=pair.Value;\n            cam.transform.position=gamePosition;Capture(cam,"map-after-game.png"');
r('changedPNGs=Paths','checkedInstalledPNGs=Paths');
r('comparison="1920x1080 actual Unity render, camera size 8; existing lights frozen identically; three temporary approved actor models plus v031 warnings, no collision or AI; unstaged actual game views also saved"','comparison="1920x1080 actual Unity render, camera size 8; existing lights frozen identically; ONLY vision veil and memory fog hidden for art review, restored for game views; three temporary approved actor models plus v031 warnings, no collision or AI; textures switched in memory, no asset writes"');
r('if(review)Object.Destroy(review);foreach(var t in telegraphs)if(t)t.Cancel();','if(review)Object.Destroy(review);foreach(var t in telegraphs)if(t)t.Cancel();foreach(var a in tempArt)if(a)Object.Destroy(a);');
// The composition pass is read-only on Assets. Remove the integration rollback branch entirely.
const start=s.indexOf('            if(applied&&!success)foreach(var p in plan)');const end=s.indexOf('            throw;',start);s=s.slice(0,start)+s.slice(end);
fs.mkdirSync('검증/맵-화풍정리-v032/composition',{recursive:true});fs.writeFileSync('AgentScripts/MapV32Composition.cs',s);console.log('Read-only asset comparison helper prepared. Existing actual lights preserved; visibility overlays hidden only for labelled review capture.');
