const fs=require('fs'),crypto=require('crypto');const ev='검증/맵-화풍정리-v032',art='아트/맵-화풍정리';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const baseline=JSON.parse(fs.readFileSync(ev+'/before.json'));
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]);}
const prev=new Set(baseline.map(x=>x.path));const changed=baseline.filter(x=>fs.existsSync(x.path)&&sha(x.path)!==x.sha256).map(x=>x.path),deleted=baseline.filter(x=>!fs.existsSync(x.path)).map(x=>x.path),added=['Assets','Packages','ProjectSettings'].flatMap(walk).filter(x=>!prev.has(x));
const targets=JSON.parse(fs.readFileSync(art+'/apply-map.json'));const expected=new Set(targets.map(x=>x.target));
const integration=JSON.parse(fs.readFileSync(ev+'/integration-result.json'));const composition=JSON.parse(fs.readFileSync(ev+'/composition/integration-result.json'));const restored=JSON.parse(fs.readFileSync(ev+'/composition/runtime-restored.json'));
const runtimeBefore=JSON.parse(fs.readFileSync(ev+'/composition/runtime-before.json'));
const imageNames=['map-v032-unity-lighting-before-after.png','map-v032-actual-game-before-after.png','arch-v032-unity-before-after.png'];
const images=imageNames.map(n=>{const b=fs.readFileSync(art+'/'+n);return{path:art+'/'+n,width:b.readUInt32BE(16),height:b.readUInt32BE(20),sha256:sha(art+'/'+n)};});
const data={changed,added,deleted,onlyTwoRequestedPNGsChanged:changed.length===2&&changed.every(p=>expected.has(p)),metasUnchanged:targets.every(t=>sha(t.target+'.meta')===sha(ev+'/backup/'+t.target.split('/').pop()+'.meta')),applied:targets.map(t=>({target:t.target,sha256:sha(t.target),matchesDeliveredArt:sha(t.target)===t.sourceSha256})),integration,composition,images,restored,latestPresetRestored:restored.floor===runtimeBefore.floor&&restored.weapon===runtimeBefore.weapon,notes:['UI proposal files were not read, copied or applied.','Comparison art review hides only two vision-overlay renderers; actual gameplay comparison preserves visibility/fog.','No map generator, collider, lighting, character, VFX, code, scene, prefab or project settings files changed.','Temporary seeded DungeonTest profile was used and original ProfileCarry references restored.']};
fs.writeFileSync(ev+'/final-audit.json',JSON.stringify(data,null,2));
if(!data.onlyTwoRequestedPNGsChanged||added.length||deleted.length||!data.metasUnchanged||data.applied.some(x=>!x.matchesDeliveredArt)||!integration.success||!composition.success||!restored.profileReferenceRestored||!data.latestPresetRestored||!restored.devices.every(d=>d.native&&d.enabled))throw Error('Final integration audit failed');
console.log(JSON.stringify({changed,added,deleted,metaUnchanged:data.metasUnchanged,gameplayAndLightingUnchanged:true,images,restored:{scene:restored.scene,preset:restored.preset,floor:restored.floor,weapon:restored.weapon,profileRestored:restored.profileReferenceRestored,inputNativeEnabled:true}},null,2));
