local root=[[E:/personalProject/Demo3/demo6/아트/정수리-시안적용-v9]]
local pc=app.pixelColor
local function clamp(n,a,b)return math.max(a,math.min(b,n))end
local function pix(r,g,b,a)return pc.rgba(clamp(math.floor(r+.5),0,255),clamp(math.floor(g+.5),0,255),clamp(math.floor(b+.5),0,255),clamp(math.floor(a+.5),0,255))end
local function open(id)local s=app.open(root..'/generated/'..id..'.png');local im=Image(s.spec);im:drawSprite(s,1);s:close();return im end
local function sprite(w,h)local s=Sprite(w,h,ColorMode.RGB);s:deleteLayer(s.layers[1]);return s end
local function add(s,name,im,at)local l=s:newLayer();l.name=name;s:newCel(l,1,im,at or Point(0,0));return l end
local function merged(s)local im=Image(s.spec);im:drawSprite(s,1);return im end
local function poly(x,y,p)local c=false;local j=#p;for i=1,#p do local a,b=p[i],p[j];if (a[2]>y)~=(b[2]>y) and x<(b[1]-a[1])*(y-a[2])/(b[2]-a[2])+a[1] then c=not c end;j=i end;return c end
local function split(im,names,which)local s=sprite(im.width,im.height);local layers={};for _,n in ipairs(names)do local l=s:newLayer();l.name=n;layers[#layers+1]=s:newCel(l,1,Image(s.spec),Point(0,0)).image end;for y=0,im.height-1 do for x=0,im.width-1 do local p=im:getPixel(x,y);if pc.rgbaA(p)>0 then local i=which(x,y,p);if i then layers[i]:drawPixel(x,y,p)end end end end;return s end
local manifests={};local exports={}
local function save(s,id,notes)local out=merged(s);local dir=root..'/layers/'..id;app.fs.makeAllDirectories(dir);local meta={width=s.width,height=s.height,layers={}};for _,l in ipairs(s.layers)do local c=l:cel(1);if c then local im=Image(s.spec);im:drawImage(c.image,c.position);local file=dir..'/'..l.name..'.rgba';local f=io.open(file,'wb');f:write(im.bytes);f:close();im:saveAs(dir..'/'..l.name..'.png');table.insert(meta.layers,{name=l.name,x=0,y=0,width=s.width,height=s.height,file=file,visible=l.isVisible})end end;local f=io.open(dir..'/composite.rgba','wb');f:write(out.bytes);f:close();f=io.open(dir..'/psd-layers.json','w');f:write(json.encode(meta));f:close();out:saveAs(root..'/PNG/'..id..'.png');s:saveAs(root..'/'..id..'-master-v009.aseprite');table.insert(manifests,{id=id,width=s.width,height=s.height,layers=#s.layers,notes=notes});return out end
local function sample(im,x,y)local ix,iy=math.floor(x),math.floor(y);local fx,fy=x-ix,y-iy;local r,g,b,a=0,0,0,0;for j=0,1 do for i=0,1 do if ix+i>=0 and ix+i<im.width and iy+j>=0 and iy+j<im.height then local p=im:getPixel(ix+i,iy+j);local w=(i==0 and 1-fx or fx)*(j==0 and 1-fy or fy);local wa=w*pc.rgbaA(p);a=a+wa;r=r+pc.rgbaR(p)*wa;g=g+pc.rgbaG(p)*wa;b=b+pc.rgbaB(p)*wa end end end;if a<.1 then return 0 end;return pix(r/a,g/a,b/a,a)end
local function output(id,im,w,h,map,ppu,pivot)local out=Image(w,h,ColorMode.RGB);for y=0,h-1 do for x=0,w-1 do local sx,sy=map(x+.5,y+.5);out:drawPixel(x,y,sample(im,sx,sy))end end;out:saveAs(root..'/runtime-PNG/'..id..'.png');table.insert(exports,{id=id,width=w,height=h,ppu=ppu,pivot=pivot or {.5,.5}});return out end
local function cropout(id,im,rect,w,h,ppu,pivot)return output(id,im,w,h,function(x,y)return rect[1]+x/w*rect[3]-.5,rect[2]+y/h*rect[4]-.5 end,ppu,pivot)end

local f=io.open(root..'/manifest.json','r');manifests=json.decode(f:read('*a'));f:close();f=io.open(root..'/runtime-manifest.json','r');exports=json.decode(f:read('*a'));f:close()
for i=#manifests,1,-1 do if manifests[i].id=='blocked-arch' then table.remove(manifests,i)end end;for i=#exports,1,-1 do if exports[i].id=='blocked_arch' then table.remove(exports,i)end end
local im=open('arch-original');local s=split(im,{'01-west-stones','02-east-stones','03-earth-timber-spill'},function(x,y)if x<im.width*.25 then return 1 elseif x>im.width*.76 then return 2 else return 3 end end);save(s,'blocked-arch','Native overhead blocked passage; visible side stones and central debris split, no unseen surfaces reconstructed.');cropout('blocked_arch',im,{0,0,im.width,im.height},640,320,128);s:close()
f=io.open(root..'/manifest.json','w');f:write(json.encode(manifests));f:close();f=io.open(root..'/runtime-manifest.json','w');f:write(json.encode(exports));f:close();print('Added native blocked arch')
