using System;using System.IO;using System.Collections.Generic;using UnityEngine;using UnityEditor;using Demo6.Game;
public static class VfxV6Art {
 const string Root="아트/이펙트/전투-v6",Dest="Assets/Art/EffectsV6";
 static readonly List<object> Parts=new List<object>();
 static float Soft(float d,float width)=>Mathf.Clamp01(.5f-d/width);
 static float Arc(Vector2 p,float degrees,float thickness,int layer){float a=Mathf.Atan2(p.y,p.x)*Mathf.Rad2Deg;float u=(a+degrees*.5f)/degrees;if(u<=0||u>=1)return 0;float taper=Mathf.Pow(u,.72f)*Mathf.Clamp01((1-u)/.065f);float edge=.88f+.011f*Mathf.Sin(a*.055f);float w=thickness*(.18f+.82f*taper);float r=p.magnitude;float profile=layer==0?Mathf.Exp(-Mathf.Pow((r-edge+w*.65f)/(w*1.7f+.008f),2))*.12f:layer==1?Soft(Mathf.Abs(r-(edge-w*.5f))-w*.5f,.014f)*.70f:Soft(Mathf.Abs(r-edge+.006f)-.005f,.009f)*.75f*Mathf.Clamp01((u-.3f)*1.7f);return profile*taper;}
 static float Sample(string id,Vector2 p,int layer){
  if(id=="arc_long")return Arc(p,120,.085f,layer);
  if(id=="arc_heavy")return Arc(p,150,.16f,layer);
  if(id=="arc_twin")return Arc(p,90,.042f,layer);
  if(id=="whirl"){float value=0;for(int i=0;i<3;i++){float a=(i*120f+18f)*Mathf.Deg2Rad;Vector2 q=new Vector2(p.x*Mathf.Cos(a)-p.y*Mathf.Sin(a),p.x*Mathf.Sin(a)+p.y*Mathf.Cos(a));value=Mathf.Max(value,Arc(q,99,i==0?.065f:.04f,layer)*(i==0?1:.7f));}return value;}
  if(id=="dust"){float a=Mathf.Atan2(p.y,p.x),r=p.magnitude;float edge=.71f+.065f*Mathf.Sin(a*3+.3f)+.028f*Mathf.Sin(a*7);float broken=Mathf.Clamp01(.28f+.65f*Mathf.Sin(a*3+.9f));float w=layer==0?.095f:layer==1?.040f:.014f;return Mathf.Exp(-Mathf.Pow((r-edge)/w,2))*broken*(layer==0?.16f:layer==1?.37f:.17f);}
  if(id=="wave"){float y=p.y,x=p.x;float center=.66f-1.32f*y*y;float fade=Mathf.Pow(Mathf.Clamp01(1-y*y),.7f);float width=(layer==0?.31f:layer==1?.11f:.024f)*fade;float q=x-center+(layer==0?.18f:0);return Mathf.Exp(-q*q/Mathf.Max(.00001f,width*width))*fade*(layer==0?.12f:layer==1?.65f:.85f);}
  if(id=="thrust"||id=="mark"){float x=p.x,y=p.y;float taper=Mathf.Pow(Mathf.Clamp01(1-Mathf.Abs(x)),id=="mark"?.6f:.9f);float center=.14f*Mathf.Sin(x*2.6f)*(id=="mark"?1:.2f);float width=(layer==0?.46f:layer==1?.22f:.055f)*taper;return Soft(Mathf.Abs(y-center)-width,.035f)*taper*(layer==0?.12f:layer==1?.58f:.9f);}
  if(id=="chip"){float width=Mathf.Clamp01((p.x+.94f)/1.5f)*.53f;float end=Soft(p.x-.58f,.06f);float a=Soft(Mathf.Abs(p.y+.08f*p.x)-width,.05f)*end;return a*(layer==0?.12f:layer==1?.9f:Mathf.Clamp01((p.y+.03f)*4)*.4f);}
  if(id=="beam"){float y=(p.y+1)*.5f;float taper=Mathf.Pow(1-y,1.5f)*Mathf.Clamp01(y/.025f);float width=layer==0?.63f:layer==1?.22f:.065f;return Mathf.Exp(-p.x*p.x/(width*width))*taper*(layer==0?.16f:layer==1?.30f:.48f);}
  return 0;
 }
 static void Write(string id,int w,int h,Vector2 pivot){string dir=Root+"/layers/"+id;Directory.CreateDirectory(dir);Directory.CreateDirectory(Root+"/PNG");Directory.CreateDirectory(Root+"/runtime-PNG");Directory.CreateDirectory(Dest);var composite=new Color[w*h];var names=new[]{"01-soft-mass","02-main-stroke","03-edge"};var colors=new[]{new Color(.52f,.50f,.45f),new Color(.82f,.81f,.77f),new Color(.98f,.98f,.94f)};
  for(int layer=0;layer<3;layer++){var pixels=new Color[w*h];for(int y=0;y<h;y++)for(int x=0;x<w;x++){int i=y*w+x;Vector2 p=new Vector2((x+.5f)/w*2-1,(y+.5f)/h*2-1);float alpha=Sample(id,p,layer);if(alpha<1f/255)continue;Color src=colors[layer];src.a=alpha;pixels[i]=src;var dst=composite[i];float a=src.a+dst.a*(1-src.a);composite[i]=new Color((src.r*src.a+dst.r*dst.a*(1-src.a))/a,(src.g*src.a+dst.g*dst.a*(1-src.a))/a,(src.b*src.a+dst.b*dst.a*(1-src.a))/a,a);}Save(pixels,w,h,dir+"/"+names[layer]+".png");}
  Save(composite,w,h,Root+"/PNG/"+id+".png");var half=new Color[w*h/4];for(int y=0;y<h/2;y++)for(int x=0;x<w/2;x++){Color c=Color.clear;float a=0;for(int j=0;j<2;j++)for(int k=0;k<2;k++){var s=composite[(2*y+j)*w+2*x+k];c.r+=s.r*s.a;c.g+=s.g*s.a;c.b+=s.b*s.a;a+=s.a;}half[y*(w/2)+x]=a>0?new Color(c.r/a,c.g/a,c.b/a,a/4):Color.clear;}Save(half,w/2,h/2,Root+"/runtime-PNG/"+id+".png");File.Copy(Root+"/runtime-PNG/"+id+".png",Dest+"/"+id+".png",true);Parts.Add(new{id,width=w,height=h,masterPPU=512,runtimePPU=256,pivot=new[]{pivot.x,pivot.y},layers=names});
 }
 static void Save(Color[] px,int w,int h,string path){var t=new Texture2D(w,h,TextureFormat.RGBA32,false);t.SetPixels(px);t.Apply();File.WriteAllBytes(path,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}
 public static object Build(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");Parts.Clear();foreach(string id in new[]{"arc_long","arc_heavy","arc_twin","whirl","dust"})Write(id,1024,1024,Vector2.one*.5f);Write("wave",384,1024,Vector2.one*.5f);Write("thrust",1536,192,Vector2.one*.5f);Write("mark",512,96,Vector2.one*.5f);Write("chip",128,64,Vector2.one*.5f);Write("beam",256,1024,new Vector2(.5f,0));File.WriteAllText(Root+"/manifest.json",Newtonsoft.Json.JsonConvert.SerializeObject(Parts,Newtonsoft.Json.Formatting.Indented));AssetDatabase.Refresh();foreach(string file in Directory.GetFiles(Dest,"*.png")){var i=(TextureImporter)AssetImporter.GetAtPath(file.Replace('\\','/'));i.textureType=TextureImporterType.Sprite;i.spriteImportMode=SpriteImportMode.Single;i.spritePixelsPerUnit=256;i.alphaIsTransparency=true;i.sRGBTexture=true;i.mipmapEnabled=true;i.filterMode=FilterMode.Trilinear;i.wrapMode=TextureWrapMode.Clamp;i.textureCompression=TextureImporterCompression.Uncompressed;i.maxTextureSize=2048;var settings=new TextureImporterSettings();i.ReadTextureSettings(settings);settings.spriteMeshType=SpriteMeshType.FullRect;settings.spriteAlignment=(int)SpriteAlignment.Custom;settings.spritePivot=Path.GetFileNameWithoutExtension(file)=="beam"?new Vector2(.5f,0):Vector2.one*.5f;i.SetTextureSettings(settings);i.SaveAndReimport();}return new{parts=Parts.Count,root=Root};}
 public static object Bind(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");var set=AssetDatabase.LoadAssetAtPath<CombatArtSet>("Assets/Data/Combat/CombatArtSet.asset");var so=new SerializedObject(set);var effects=so.FindProperty("effects");var mapping=new Dictionary<string,string>{{"arcLong","arc_long"},{"arcHeavy","arc_heavy"},{"arcTwin","arc_twin"},{"thrust","thrust"},{"whirl","whirl"},{"wave","wave"},{"impactDust","dust"},{"rewardBeam","beam"},{"slashMark","mark"}};foreach(var pair in mapping)effects.FindPropertyRelative(pair.Key).objectReferenceValue=AssetDatabase.LoadAssetAtPath<Sprite>(Dest+"/"+pair.Value+".png");var sparks=effects.FindPropertyRelative("sparks");sparks.arraySize=1;sparks.GetArrayElementAtIndex(0).objectReferenceValue=AssetDatabase.LoadAssetAtPath<Sprite>(Dest+"/chip.png");so.ApplyModifiedPropertiesWithoutUndo();AssetDatabase.SaveAssetIfDirty(set);return new{bound=mapping.Count+1};}
}
