using System;using System.Reflection;using System.Collections;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEditor;using Demo6.Game;using Demo6.Core.Combat;using Demo6.Core.Loot;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;
public static class VfxV6Review {
 public static async Task<object> Run(int height=720,string phase="before",string scenario="skills") {
  if(!EditorApplication.isPlaying||DungeonUi.ModalOpen||!PlayerController.Instance||!Inventory.Instance)throw new Exception("Unblocked Play required");
  EditorApplication.LockReloadAssemblies();
  const BindingFlags flags=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var assembly=typeof(Editor).Assembly;var type=assembly.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(type).Cast<EditorWindow>().First();var index=type.GetProperty("selectedSizeIndex",flags);int originalIndex=(int)index.GetValue(view);var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var sizes=typeof(ScriptableSingleton<>).MakeGenericType(sizesType).GetProperty("instance").GetValue(null);var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{GameViewSizeGroupType.Standalone});var size=Activator.CreateInstance(assembly.GetType("UnityEditor.GameViewSize"),new object[]{Enum.ToObject(assembly.GetType("UnityEditor.GameViewSizeType"),1),height==720?1280:1920,height,"V6 temporary review"});group.GetType().GetMethod("AddCustomSize").Invoke(group,new[]{size});
  var originals=InputSystem.devices.Where(d=>d is Keyboard||d is Mouse).Select(d=>new{d,enabled=d.enabled}).ToArray();var originalSettings=InputSystem.settings;if(!originalSettings){originalSettings=UnityEngine.ScriptableObject.CreateInstance<InputSettings>();InputSystem.settings=originalSettings;}string settingsPath=AssetDatabase.GetAssetPath(originalSettings);var saved=UnityEngine.Object.Instantiate(originalSettings);var review=UnityEngine.Object.Instantiate(originalSettings);InputSystem.settings=review;review.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;review.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;var oldK=Keyboard.current;var oldM=Mouse.current;var kb=InputSystem.AddDevice<Keyboard>("V6ReviewKeyboard");var mouse=InputSystem.AddDevice<Mouse>("V6ReviewMouse");Action current=()=>{kb.MakeCurrent();mouse.MakeCurrent();};InputSystem.onAfterUpdate+=current;
  var p=PlayerController.Instance;Vector2 origin=p.Position;int hp=p.Health.Current,potions=p.Potions;var carry=new Demo6.Core.Dungeon.CarryData();Inventory.Instance.ExportTo(carry);var fixtures=new List<Enemy>();var drops=new List<LootDrop>();var rows=new List<object>();var errors=new List<string>();Application.LogCallback log=(m,s,t)=>{if(t==LogType.Error||t==LogType.Exception)errors.Add(m);};Application.logMessageReceived+=log;
  string root=$"검증/이펙트-개선-v6/{phase}/{height}/{scenario}";Directory.CreateDirectory(root);int frame=0;
  void Point(Vector2 pos,int buttons=0)=>InputSystem.QueueStateEvent(mouse,new MouseState{position=pos,buttons=(ushort)buttons});
  async Task Press(Key key){InputSystem.QueueStateEvent(kb,new KeyboardState(key));await Task.Delay(90);InputSystem.QueueStateEvent(kb,new KeyboardState());await Task.Delay(90);}
  async Task Frames(string name,int n,int delay=60){for(int i=0;i<n;i++){ScreenCapture.CaptureScreenshot(Path.GetFullPath(root+"/"+name+"-"+(frame++).ToString("D3")+".png"));rows.Add(new{sequence=name,frame=Time.frameCount,time=Time.time,real=Time.unscaledTime,weapon=p.Weapon.id,combo=p.ComboIndex,pose=p.Pose.ToString(),poseTime=p.PoseTime,hp=p.Health.Current,swings=UnityEngine.Object.FindObjectsByType<SwingVisual>().Length,waves=UnityEngine.Object.FindObjectsByType<SwordWave>().Length,alive=fixtures.Count(e=>e&&!e.Dead),enemyHp=fixtures.Select(e=>e?e.Health.Current:0).ToArray()});await Task.Delay(delay);}}
  try{foreach(var d in originals)if(d.enabled)InputSystem.DisableDevice(d.d);InputSystem.EnableDevice(kb);InputSystem.EnableDevice(mouse);current();index.SetValue(view,(int)group.GetType().GetMethod("GetTotalCount").Invoke(group,null)-1);view.Repaint();await Task.Delay(350);p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();Point(new Vector2(Screen.width*.67f,Screen.height*.5f));await Task.Delay(150);
   if(scenario.StartsWith("burst3")){await Press(Key.Digit3);var target=EnemySpawner.Create(MonsterKind.Boar,1,origin+Vector2.right*1.3f);target.NoReward=true;target.Health.Init(4000,0);fixtures.Add(target);Point(Camera.main.WorldToScreenPoint(target.Position),1);float until=Time.realtimeSinceStartup+5f;while((p.Pose.ToString()!="Attack"||p.ComboIndex!=3||p.PoseTime<p.PoseHitTime-.02f)&&Time.realtimeSinceStartup<until){Point(Camera.main.WorldToScreenPoint(target.Position),1);await Task.Delay(15);}var recorder=new GameObject("V6 burst capture").AddComponent<VfxV6FrameCollector>();try{await recorder.Capture(64,()=>rows.Add(new{sequence="spin-burst",frame=Time.frameCount,time=Time.time,real=Time.unscaledTime,weapon=p.Weapon.id,combo=p.ComboIndex,pose=p.Pose.ToString(),poseTime=p.PoseTime,hp=p.Health.Current,swings=UnityEngine.Object.FindObjectsByType<SwingVisual>().Length,waves=UnityEngine.Object.FindObjectsByType<SwordWave>().Length,alive=fixtures.Count(e=>e&&!e.Dead),enemyHp=fixtures.Select(e=>e?e.Health.Current:0).ToArray()}));Point(new Vector2(Screen.width*.65f,Screen.height*.5f));await recorder.Save(root);}finally{UnityEngine.Object.Destroy(recorder.gameObject);}}
   else if(scenario=="skills"){InputSystem.QueueStateEvent(kb,new KeyboardState(Key.Q));await Frames("wave",12,45);InputSystem.QueueStateEvent(kb,new KeyboardState());Point(new Vector2(Screen.width*.65f,Screen.height*.5f),2);await Frames("whirl",12,45);Point(new Vector2(Screen.width*.65f,Screen.height*.5f));}
   else if(scenario=="reward"){int j=0;foreach(Grade g in Enum.GetValues(typeof(Grade))){Vector2 at=origin+new Vector2((j++-2)*1.3f,1.4f);drops.Add(LootDrop.Spawn(new GearItem("wpn_greatsword",g,11,1100,0),at,at,0));}await Frames("landing",20,60);await Task.Delay(700);await Frames("settled",4,80);}
   else if(scenario=="hurt"){var e=EnemySpawner.Create(MonsterKind.Rat,1,origin+Vector2.right*.65f);e.NoReward=true;fixtures.Add(e);await Frames("enemy-attack",65,60);}
   else {int digit=int.Parse(scenario);await Press(digit==1?Key.Digit1:digit==2?Key.Digit2:Key.Digit3);Point(new Vector2(Screen.width*.66f,Screen.height*.5f),1);await Frames("miss-combo",digit==2?64:50,55);Point(new Vector2(Screen.width*.66f,Screen.height*.5f));await Task.Delay(700);
    p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();var target=EnemySpawner.Create(MonsterKind.Boar,1,origin+Vector2.right*1.3f);target.NoReward=true;fixtures.Add(target);target.Health.Init(1800,0);Point(Camera.main.WorldToScreenPoint(target.Position),1);for(int i=0;i<64;i++){if(target&&!target.Dead)Point(Camera.main.WorldToScreenPoint(target.Position),1);await Frames("hit-combo",1,55);}Point(new Vector2(Screen.width*.66f,Screen.height*.5f));await Task.Delay(700);
    var rat=EnemySpawner.Create(MonsterKind.Rat,1,p.Position+Vector2.right*1.1f);rat.NoReward=true;fixtures.Add(rat);Point(Camera.main.WorldToScreenPoint(rat.Position),1);await Frames("kill",24,55);Point(new Vector2(Screen.width*.66f,Screen.height*.5f));await Frames("corpse",3,150);
   }
  }finally{Application.logMessageReceived-=log;InputSystem.onAfterUpdate-=current;foreach(var e in fixtures)if(e)e.Remove();foreach(var d in drops)if(d)UnityEngine.Object.Destroy(d.gameObject);Inventory.Instance.ImportFrom(carry);p.RestoreVitals(hp,potions);p.Teleport(origin);Camera.main.GetComponent<DungeonCamera>().Snap();InputSystem.RemoveDevice(kb);InputSystem.RemoveDevice(mouse);foreach(var d in originals)if(d.enabled)InputSystem.EnableDevice(d.d);oldK?.MakeCurrent();oldM?.MakeCurrent();InputSystem.settings=string.IsNullOrEmpty(settingsPath)?saved:AssetDatabase.LoadAssetAtPath<InputSettings>(settingsPath);index.SetValue(view,originalIndex);foreach(var field in group.GetType().GetFields(flags)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--)if(ReferenceEquals(list[i],size))list.RemoveAt(i);}view.Repaint();EditorApplication.UnlockReloadAssemblies();}
  var result=new{scenario,phase,resolution=height,frames=rows,errors,input="Actual PlayerInputReader with temporary virtual InputSystem devices; no physical input claim. Fixtures are disposable Play-only EnemySpawner and LootDrop instances; damage calls are never invoked directly."};File.WriteAllText(root+"/sequence.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return new{scenario,phase,height,frames=rows.Count,errors};
 }
}

public sealed class VfxV6FrameCollector:MonoBehaviour {readonly List<RenderTexture> images=new List<RenderTexture>();public Task Capture(int count,Action record){var done=new TaskCompletionSource<bool>();StartCoroutine(Collect(count,record,done));return done.Task;}IEnumerator Collect(int count,Action record,TaskCompletionSource<bool> done){for(int i=0;i<count;i++){yield return new WaitForEndOfFrame();var rt=new RenderTexture(Screen.width,Screen.height,0,RenderTextureFormat.ARGB32);rt.Create();ScreenCapture.CaptureScreenshotIntoRenderTexture(rt);images.Add(rt);record();}done.SetResult(true);}public async Task Save(string root){var previous=RenderTexture.active;try{for(int i=0;i<images.Count;i++){var rt=images[i];RenderTexture.active=rt;var t=new Texture2D(rt.width,rt.height,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);t.Apply();File.WriteAllBytes(root+"/spin-burst-"+i.ToString("D3")+".png",t.EncodeToPNG());UnityEngine.Object.Destroy(t);await Task.Delay(1);}}finally{RenderTexture.active=previous;}}void OnDestroy(){foreach(var rt in images){rt.Release();UnityEngine.Object.Destroy(rt);}images.Clear();}}
