using System;using System.Reflection;using System.Collections;using System.Linq;using System.IO;using UnityEngine;using UnityEditor;using UnityEngine.InputSystem;
public static class VfxV6EditorState {
 public static object Audit(bool repair=false){
  if(repair){foreach(var device in InputSystem.devices.Where(d=>d.name.StartsWith("V6Review")).ToArray())InputSystem.RemoveDevice(device);}
  if(repair&&(!InputSystem.settings||InputSystem.settings.editorInputBehaviorInPlayMode==InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView)){if(EditorApplication.isPlaying)throw new Exception("Edit mode required for missing default settings repair");InputSystem.settings=ScriptableObject.CreateInstance<InputSettings>();}
  const BindingFlags f=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;var a=typeof(Editor).Assembly;var t=a.GetType("UnityEditor.GameView");var v=Resources.FindObjectsOfTypeAll(t).Cast<EditorWindow>().First();var sizes=a.GetType("UnityEditor.GameViewSizes");var instance=typeof(ScriptableSingleton<>).MakeGenericType(sizes).GetProperty("instance").GetValue(null);var group=sizes.GetMethod("GetGroup").Invoke(instance,new object[]{GameViewSizeGroupType.Standalone});if(repair)foreach(var field in group.GetType().GetFields(f)){if(!(field.GetValue(group)is IList list)||list.IsReadOnly)continue;for(int i=list.Count-1;i>=0;i--){var o=list[i];var text=o.GetType().GetProperty("baseText",f)?.GetValue(o)?.ToString();if(text=="V6 temporary review")list.RemoveAt(i);}}
  var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();var result=new{playing=EditorApplication.isPlaying,compiling=EditorApplication.isCompiling,scene=scene.name,dirty=scene.isDirty,gameViewIndex=t.GetProperty("selectedSizeIndex",f).GetValue(v),settingsAlive=(bool)InputSystem.settings,focus=InputSystem.settings?InputSystem.settings.editorInputBehaviorInPlayMode.ToString():"missing",background=InputSystem.settings?InputSystem.settings.backgroundBehavior.ToString():"missing",devices=InputSystem.devices.Select(d=>new{name=d.name,enabled=d.enabled}).ToArray()};Directory.CreateDirectory("검증/이펙트-개선-v6");File.WriteAllText("검증/이펙트-개선-v6/editor-state.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
