using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using Demo6.Game;
public static class VfxV6Regression {
 const BindingFlags Flags=BindingFlags.Instance|BindingFlags.NonPublic;
 public static object Run(){if(EditorApplication.isPlaying)throw new Exception("Edit mode only");var rows=new List<object>();void Check(string name,bool pass,object detail=null){rows.Add(new{name,pass,detail});}var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene();bool dirty=scene.isDirty;var preview=EditorSceneManager.NewPreviewScene();
  try{var set=AssetDatabase.LoadAssetAtPath<CombatArtSet>("Assets/Data/Combat/CombatArtSet.asset");foreach(var field in new[]{"arcLong","arcHeavy","arcTwin","thrust","whirl","wave","impactDust","rewardBeam","slashMark"}){var sprite=typeof(EffectArt).GetField(field).GetValue(set.effects) as Sprite;Check("bound-"+field,sprite, sprite?AssetDatabase.GetAssetPath(sprite):"missing");}
   foreach(string id in new[]{"arc_long","arc_heavy","arc_twin","whirl","dust"}){var t=new Texture2D(2,2);t.LoadImage(File.ReadAllBytes("Assets/Art/EffectsV6/"+id+".png"));var px=t.GetPixels32();int n=px.Count(c=>c.a>128);Check("open-center-"+id,t.GetPixel(t.width/2,t.height/2).a==0 && n<px.Length*.12f,new{centerAlpha=t.GetPixel(t.width/2,t.height/2).a,opaqueFraction=n/(float)px.Length});UnityEngine.Object.DestroyImmediate(t);}
   var go=new GameObject("V6 flash regression");UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(go,preview);var sr=go.AddComponent<SpriteRenderer>();var flash=go.AddComponent<SpriteFlash>();flash.target=sr;flash.baseColor=new Color(.2f,.15f,.1f);flash.Flash(Color.white,.2f);float first=sr.color.r;typeof(SpriteFlash).GetField("_flashLeft",Flags).SetValue(flash,.05f);typeof(SpriteFlash).GetMethod("Apply",Flags).Invoke(flash,null);float tail=sr.color.r;Check("flash-fades-within-existing-window",first>tail&&tail>flash.baseColor.r,new{first,tail});flash.StopAll();Check("flash-returns-to-base",sr.color==flash.baseColor);
   var hitGo=new GameObject("V6 hit regression");UnityEngine.SceneManagement.SceneManager.MoveGameObjectToScene(hitGo,preview);var hits=hitGo.AddComponent<HitEffects>();typeof(HitEffects).GetMethod("Awake",Flags).Invoke(hits,null);typeof(HitEffects).GetMethod("SlashMark",Flags).Invoke(hits,new object[]{Vector2.zero,Vector2.right,.25f,false});var mark=hitGo.GetComponentsInChildren<SpriteRenderer>().Single(r=>r.enabled);Check("small-enemy-mark-fits-body",mark.bounds.size.x<=.46f && mark.bounds.size.y<=.46f,new{size=mark.bounds.size.ToString()});
   var runtime=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/EffectsV6/wave.png");Check("wave-output-size",runtime.texture.width==192&&runtime.texture.height==512,new{runtime.texture.width,runtime.texture.height});
  }finally{EditorSceneManager.ClosePreviewScene(preview);}
  Check("scene-preserved",scene==UnityEngine.SceneManagement.SceneManager.GetActiveScene()&&scene.isDirty==dirty,new{scene=scene.name,dirty=scene.isDirty});int failed=rows.Count(x=>(bool)x.GetType().GetProperty("pass").GetValue(x)==false);var result=new{total=rows.Count,failed,rows};File.WriteAllText("검증/이펙트-개선-v6/effect-regression.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
 }
}
