using System;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using Demo5.FrontEnd;
public static class BuildQuietFacilities {
 static void Rect(RectTransform r,float x,float y,float w,float h){r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);}
 static void Line(Transform p,string name,float x,float y,float w,float h){var g=new GameObject(name,typeof(RectTransform),typeof(Image));g.transform.SetParent(p,false);Rect((RectTransform)g.transform,x,y,w,h);var i=g.GetComponent<Image>();i.color=new Color(.9f,.81f,.59f,.85f);i.raycastTarget=false;}
 static void Apply(Button b,float x,float y,float w,float h,string title){Rect((RectTransform)b.transform,x,y,w,h);b.transition=Selectable.Transition.None;var old=b.GetComponent<SettlementHotspot>();var caption=old.Label;UnityEngine.Object.DestroyImmediate(old);foreach(var i in b.GetComponentsInChildren<Image>(true))if(i.gameObject!=caption&& !i.transform.IsChildOf(caption.transform)){i.color=Color.clear;var o=i.GetComponent<Outline>();if(o)UnityEngine.Object.DestroyImmediate(o);}b.GetComponent<Image>().raycastTarget=true;
 Rect((RectTransform)caption.transform,(w-220)/2,h+8,220,44);var t=caption.GetComponentInChildren<Text>(true);Rect(t.rectTransform,8,0,204,44);t.fontSize=25;t.text=title;t.alignment=TextAnchor.MiddleCenter;foreach(var g in caption.GetComponentsInChildren<Graphic>(true))g.raycastTarget=false;caption.SetActive(false);
 var f=new GameObject("FocusCorners",typeof(RectTransform));f.transform.SetParent(b.transform,false);Rect((RectTransform)f.transform,0,0,w,h);float len=20;foreach(bool right in new[]{false,true})foreach(bool bottom in new[]{false,true}){float xx=right?w-len:0,yy=bottom?h-2:0;Line(f.transform,"Horizontal",xx,yy,len,2);Line(f.transform,"Vertical",right?w-2:0,bottom?h-len:0,2,len);}f.SetActive(false);var focus=b.gameObject.AddComponent<SettlementFacilityFocus>();focus.Button=b;focus.Focus=f;focus.Caption=caption;}
 public static string Run(){const string path="Assets/Prefabs/Settlement/SettlementScreen.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var c=root.GetComponent<SettlementController>();Apply(c.Bed,450,300,285,180,"잠자리");Apply(c.Stock,785,318,210,158,"식수 · 조리");Apply(c.Workbench,1115,292,290,220,"작업대");Apply(c.Cabinet,720,700,250,105,"공용 창고");Apply(c.Exit,1720,365,175,300,"외부 탐험");Apply(c.Development.ResearchButton,1020,565,195,140,"연구대");var hint=new GameObject("FacilityHelp",typeof(RectTransform),typeof(Text));hint.transform.SetParent(c.Main.transform,false);Rect((RectTransform)hint.transform,32,748,560,32);var t=hint.GetComponent<Text>();t.font=c.NoticeBody.font;t.fontSize=22;t.color=new Color(.87f,.84f,.74f);t.text="시설에 마우스 올리기 · Alt: 시설 이름 보기";t.raycastTarget=false;PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Settlement furniture hit areas and focus-only captions created; shared hotspot prefab untouched.";}
}
