using System;
using System.IO;
using UnityEditor;
using UnityEngine.Rendering.Universal;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class BuildExpeditionArrival {
 const string P="Assets/Prefabs/Settlement/",A="Assets/Art/PartySelection/",E="Assets/Art/ExpeditionPlan/";static Font font;
 static RectTransform R(string n,Transform p,float x,float y,float w,float h){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 static Image I(string n,Transform p,float x,float y,float w,float h,string path=null){var im=R(n,p,x,y,w,h).gameObject.AddComponent<Image>();if(path!=null)im.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(path);im.raycastTarget=false;return im;}
 static Text T(string n,Transform p,float x,float y,float w,float h,string s,int size=30,bool light=false){var t=R(n,p,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontStyle=FontStyle.Normal;t.fontSize=size;t.text=s;t.color=light?new Color(.96f,.93f,.85f):new Color(.045f,.065f,.06f);t.alignment=TextAnchor.MiddleLeft;t.raycastTarget=false;return t;}
 static Button B(string n,Transform p,float x,float y,float w,float h,string label,int size=32){var im=I(n,p,x,y,w,h,A+"footer-paper.png");im.raycastTarget=true;var b=im.gameObject.AddComponent<Button>();b.targetGraphic=im;T("Label",im.transform,6,0,w-12,h,label,size).alignment=TextAnchor.MiddleCenter;return b;}
 static GameObject Save(GameObject g,string name){var asset=PrefabUtility.SaveAsPrefabAsset(g,P+name+".prefab");Object.DestroyImmediate(g);return asset;}
 static Sprite S(string name)=>AssetDatabase.LoadAssetAtPath<Sprite>(E+name+".png");
 static SpriteRenderer SR(string name,Transform parent,string path,int order,Vector3 position,Vector2 size){
  var g=new GameObject(name,typeof(SpriteRenderer));g.transform.SetParent(parent,false);g.transform.localPosition=position;var s=g.GetComponent<SpriteRenderer>();s.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(path);s.sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>("Assets/Settings/StandeeSpriteLit.mat");s.sortingOrder=order;g.transform.localScale=new Vector3(size.x/s.sprite.bounds.size.x,size.y/s.sprite.bounds.size.y,1);return s;
 }
 public static string Build(){
  if(EditorApplication.isPlaying)throw new Exception("Stop first");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene changes");
  font=AssetDatabase.LoadAssetAtPath<Font>("Assets/funflow_font/TWD-AS_FUNFLOW SURVIVOR_Font/펀플로 생존자.ttf");AssetDatabase.Refresh();string background="Assets/Art/ExpeditionArrival/arcade-clean.png";var importer=(TextureImporter)AssetImporter.GetAtPath(background);importer.textureType=TextureImporterType.Sprite;importer.spritePixelsPerUnit=100;importer.mipmapEnabled=false;importer.maxTextureSize=4096;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.SaveAndReimport();
  var pawn=new GameObject("FieldPawn");SR("Base",pawn.transform,"Assets/Art/Settlement/base-white.png",20,Vector3.zero,new Vector2(1.02f,.28f));SR("Body",pawn.transform,"Assets/Art/Settlement/standee-scout.png",21,new Vector3(0,.04f,0),new Vector2(1.12f,1.99f));var pawnAsset=Save(pawn,"FieldPawn");
  var root=R("ExpeditionArrivalPanel",null,0,0,1920,1080);var c=root.gameObject.AddComponent<ExpeditionArrivalPanel>();c.View=root.gameObject;var main=R("Main",root,0,0,1920,1080);c.Main=main.gameObject.AddComponent<CanvasGroup>();
  I("DayPaper",main,80,36,204,110,A+"count-paper.png");c.Clock=T("Clock",main,104,42,156,96,"",32);
  I("PlacePaper",main,308,36,320,110,A+"card-paper.png");c.Place=T("Place",main,332,42,272,96,"",32);
  I("ResourcePaper",main,1190,36,390,86,A+"card-paper.png").color=new Color(.14f,.18f,.18f);c.Resources=T("Resources",main,1214,39,342,80,"",28,true);
  I("RiskPaper",main,1600,36,240,86,A+"footer-paper.png").color=new Color(.86f,.61f,.52f);T("Risk",main,1624,40,192,78,"위험 · 미확인",30);
  var hotspot=AssetDatabase.LoadAssetAtPath<GameObject>(P+"FacilityHotspot.prefab");c.Objects=new Button[4];string[] titles={"물자 상자","낡은 탁자","오락기","출입문"},icons={"storage","work","journal","exit"};Vector2[] pos={new Vector2(1090,411),new Vector2(1470,481),new Vector2(655,327),new Vector2(1780,358)};
  for(int i=0;i<4;i++){var g=(GameObject)PrefabUtility.InstantiatePrefab(hotspot,main);g.name="Inspect_"+i;((RectTransform)g.transform).anchoredPosition=new Vector2(pos[i].x,-pos[i].y);g.transform.Find("Icon").GetComponent<Image>().sprite=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/Settlement/icon-"+icons[i]+".png");g.transform.Find("Caption/Text").GetComponent<Text>().text=titles[i];c.Objects[i]=g.GetComponent<Button>();}
  c.ObjectNames=titles;c.ObjectDescriptions=new[]{"뚜껑이 닫힌 물자 상자다.\n아직 안에 무엇이 있는지는 알 수 없다.","먼지 쌓인 컵과 종이가 놓여 있다.\n누군가 이곳에서 머물렀던 흔적이다.","전원이 끊긴 오락기다.\n주변에는 깨진 부품이 흩어져 있다.","밖으로 이어지는 출입문이다.\n이 방에서 거점으로 귀환할 수 있다."};
  I("ArrivalPaper",main,80,776,480,148,A+"card-paper.png");T("ArrivalTitle",main,104,786,432,47,"주변 살펴보기",35);c.Status=T("Status",main,104,840,432,68,"",27);
  var vp=R("Members",main,600,754,1240,178);vp.gameObject.AddComponent<RectMask2D>();vp.gameObject.AddComponent<Image>().color=Color.clear;c.MemberContent=R("Content",vp,0,0,1240,172);var layout=c.MemberContent.gameObject.AddComponent<HorizontalLayoutGroup>();layout.spacing=14;layout.childControlWidth=layout.childControlHeight=layout.childForceExpandWidth=layout.childForceExpandHeight=false;c.MemberContent.gameObject.AddComponent<ContentSizeFitter>().horizontalFit=ContentSizeFitter.FitMode.PreferredSize;var scroll=vp.gameObject.AddComponent<ScrollRect>();scroll.viewport=vp;scroll.content=c.MemberContent;scroll.horizontal=true;scroll.vertical=false;scroll.movementType=ScrollRect.MovementType.Clamped;c.MemberPrefab=AssetDatabase.LoadAssetAtPath<ExpeditionMemberCard>(P+"ExpeditionMemberCard.prefab");
  c.Return=B("Return",main,80,952,410,78,"거점으로 귀환",34);I("Icon",c.Return.transform,22,22,26,34,A+"icon-left.png").preserveAspect=true;T("Hint",main,600,959,1240,64,"대원 카드를 누르면 챙겨 온 물건을 확인합니다.",27,true);
  var modal=R("FieldInformationPopup",null,0,0,1920,1080);var dim=I("Dim",modal,0,0,1920,1080);dim.color=new Color(0,0,0,.72f);dim.raycastTarget=true;I("Paper",modal,460,205,1000,650,A+"card-paper.png");T("Title",modal,510,235,900,70,"",43);T("Body",modal,510,329,900,330,"",31);B("Back",modal,510,727,410,78,"돌아가기",34);B("Confirm",modal,1000,727,410,78,"귀환",34).GetComponent<Image>().color=new Color(.76f,.86f,.68f);
  var ma=Save(modal.gameObject,"FieldInformationPopup");var popup=(GameObject)PrefabUtility.InstantiatePrefab(ma,root);c.Popup=popup;c.PopupTitle=popup.transform.Find("Title").GetComponent<Text>();c.PopupBody=popup.transform.Find("Body").GetComponent<Text>();c.PopupBack=popup.transform.Find("Back").GetComponent<Button>();c.ReturnConfirm=popup.transform.Find("Confirm").GetComponent<Button>();popup.SetActive(false);
  var fade=I("TravelFade",root,0,0,1920,1080);fade.color=Color.black;fade.raycastTarget=true;c.Fade=fade.gameObject.AddComponent<CanvasGroup>();fade.gameObject.SetActive(false);c.PawnPrefab=pawnAsset;c.Scout=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/Settlement/standee-scout.png");c.Medic=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/Settlement/standee-medic.png");
  var screenAsset=Save(root.gameObject,"ExpeditionArrivalPanel");
  // Add departure button to the existing nested review prefab.
  var review=PrefabUtility.LoadPrefabContents(P+"ExpeditionPackingReview.prefab");try{var old=review.transform.Find("Depart");if(old)Object.DestroyImmediate(old.gameObject);B("Depart",review.transform,1000,790,410,78,"출발",36).GetComponent<Image>().color=new Color(.76f,.86f,.68f);PrefabUtility.SaveAsPrefabAsset(review,P+"ExpeditionPackingReview.prefab");}finally{PrefabUtility.UnloadPrefabContents(review);}
  var packing=PrefabUtility.LoadPrefabContents(P+"ExpeditionPackingPanel.prefab");try{var pc=packing.GetComponent<ExpeditionPackingPanel>();pc.Depart=pc.Review.transform.Find("Depart").GetComponent<Button>();PrefabUtility.SaveAsPrefabAsset(packing,P+"ExpeditionPackingPanel.prefab");}finally{PrefabUtility.UnloadPrefabContents(packing);}
  var screen=PrefabUtility.LoadPrefabContents(P+"SettlementScreen.prefab");try{var old=screen.transform.Find("ExpeditionArrivalPanel");if(old)Object.DestroyImmediate(old.gameObject);var go=(GameObject)PrefabUtility.InstantiatePrefab(screenAsset,screen.transform);screen.GetComponent<SettlementController>().ArrivalPanel=go.GetComponent<ExpeditionArrivalPanel>();go.SetActive(false);PrefabUtility.SaveAsPrefabAsset(screen,P+"SettlementScreen.prefab");}finally{PrefabUtility.UnloadPrefabContents(screen);}
  var scene=EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");var oldWorld=GameObject.Find("ExpeditionWorld");if(oldWorld)Object.DestroyImmediate(oldWorld);var world=new GameObject("ExpeditionWorld");SR("Arcade",world.transform,background,0,Vector3.zero,new Vector2(19.2f,10.8f));var ambient=new GameObject("Ambient",typeof(Light2D));ambient.transform.SetParent(world.transform,false);ambient.GetComponent<Light2D>().lightType=Light2D.LightType.Global;ambient.GetComponent<Light2D>().intensity=.96f;
  var entrance=new GameObject("EntranceLight",typeof(Light2D));entrance.transform.SetParent(world.transform,false);entrance.transform.localPosition=new Vector3(7.2f,1.8f,0);var light=entrance.GetComponent<Light2D>();light.lightType=Light2D.LightType.Point;light.intensity=.23f;light.color=new Color(.78f,.88f,1);light.pointLightOuterRadius=3;
  var pawns=new GameObject("Pawns");pawns.transform.SetParent(world.transform,false);PrefabUtility.SaveAsPrefabAssetAndConnect(world,P+"ExpeditionWorld.prefab",InteractionMode.AutomatedAction);
  var owner=Object.FindAnyObjectByType<SettlementController>();var arrival=owner.ArrivalPanel;arrival.World=world;arrival.PawnRoot=pawns.transform;arrival.SettlementWorld=GameObject.Find("SettlementWorld");PrefabUtility.RecordPrefabInstancePropertyModifications(arrival);world.SetActive(false);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();return "Departure, arcade arrival UI, reusable field popup/pawn and URP world saved.";
 }
}
