using System;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using Demo5.FrontEnd;using Object=UnityEngine.Object;
public static class BuildOpeningChapter {
 static RectTransform R(string name,Transform parent,float x,float y,float w,float h){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 static Text T(string name,Transform parent,float x,float y,float w,float h,Font font,int size){var t=R(name,parent,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontSize=size;t.color=new Color(.05f,.07f,.06f);t.alignment=TextAnchor.UpperLeft;t.raycastTarget=false;return t;}
 public static string Run(){if(EditorApplication.isPlaying)throw new Exception("Stop isolated Play first");const string path="Assets/Prefabs/Settlement/SettlementScreen.prefab";const string popupPath="Assets/Prefabs/Settlement/OpeningChapterPanel.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var c=root.GetComponent<SettlementController>();var opening=root.GetComponent<SettlementOpeningChapter>();if(!opening)opening=root.AddComponent<SettlementOpeningChapter>();c.Opening=opening;
 var view=R("OpeningChapterPanel",null,0,0,1920,1080);view.gameObject.AddComponent<PopupBackgroundHud>();var dim=R("Dim",view,0,0,1920,1080).gameObject.AddComponent<Image>();dim.color=new Color(0,0,0,.97f);var heading=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Settlement/PopupHeading.prefab"),view);heading.GetComponentInChildren<Text>().text="첫 생활 · 기록";PrefabUtility.RecordPrefabInstancePropertyModifications(heading.GetComponentInChildren<Text>());
 var paper=R("Paper",view,530,260,860,560).gameObject.AddComponent<Image>();paper.sprite=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/PartySelection/card-paper.png");paper.raycastTarget=false;
 T("EventTitle",view,574,294,772,64,c.NoticeTitle.font,40);var body=T("EventBody",view,574,370,772,400,c.NoticeTitle.font,30);body.lineSpacing=.86f;
 var back=R("Back",view,80,974,410,76).gameObject.AddComponent<Image>();back.sprite=c.Advance.GetComponent<Image>().sprite;var button=back.gameObject.AddComponent<Button>();button.targetGraphic=back;var label=T("Label",back.transform,12,0,386,76,c.NoticeTitle.font,28);label.alignment=TextAnchor.MiddleCenter;label.text="정착지로 돌아가기";
 var asset=PrefabUtility.SaveAsPrefabAsset(view.gameObject,popupPath);Object.DestroyImmediate(view.gameObject);var old=root.transform.Find("OpeningChapterPanel");if(old)Object.DestroyImmediate(old.gameObject);var panel=(GameObject)PrefabUtility.InstantiatePrefab(asset,root.transform);opening.View=panel;opening.EventTitle=panel.transform.Find("EventTitle").GetComponent<Text>();opening.EventBody=panel.transform.Find("EventBody").GetComponent<Text>();opening.Back=panel.transform.Find("Back").GetComponent<Button>();panel.SetActive(false);PrefabUtility.SaveAsPrefabAsset(root,path);
 }finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Settlement chapter attached with separate reusable popup: common heading, 97% dim, paper/ink palette and bottom-left footer. No combat/expedition assets modified.";}
}


