using System.Linq;using UnityEngine;using UnityEngine.UI;using UnityEditor;using Demo5.FrontEnd;using Object=UnityEngine.Object;
public static class BuildTabbedFieldBags {
 static Font font;static Sprite paper;static Color cream=new Color(.95f,.92f,.82f),ink=new Color(.05f,.07f,.06f);
 static void R(Transform t,float x,float y,float w,float h){var r=(RectTransform)t;r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);}
 static RectTransform N(string name,Transform p,float x,float y,float w,float h){var go=new GameObject(name,typeof(RectTransform));go.transform.SetParent(p,false);R(go.transform,x,y,w,h);return(RectTransform)go.transform;}
 static Image I(string n,Transform p,float x,float y,float w,float h,Sprite sprite,Color color){var i=N(n,p,x,y,w,h).gameObject.AddComponent<Image>();i.sprite=sprite;i.color=color;i.raycastTarget=false;return i;}
 static Text T(string n,Transform p,float x,float y,float w,float h,string text,int size=24, bool dark=false){var t=N(n,p,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontSize=size;t.text=text;t.color=dark?ink:cream;t.alignment=TextAnchor.MiddleLeft;t.verticalOverflow=VerticalWrapMode.Overflow;t.raycastTarget=false;return t;}
 static void Move(Component c,Transform p,float x,float y,float w,float h){c.transform.SetParent(p,false);c.gameObject.SetActive(true);R(c.transform,x,y,w,h);}
 static void TextMove(Text t,Transform p,float x,float y,float w,float h,int size,Color color){Move(t,p,x,y,w,h);t.fontSize=size;t.color=color;t.verticalOverflow=VerticalWrapMode.Overflow;}
 static void ButtonMove(Button b,Transform p,float x,float y,float w,float h,int size){Move(b,p,x,y,w,h);var t=b.GetComponentInChildren<Text>();R(t.transform,8,0,w-16,h);t.alignment=TextAnchor.MiddleCenter;t.fontSize=size;t.verticalOverflow=VerticalWrapMode.Overflow;}
 static ExpeditionMemberCard Card(string name,float width,bool recipient){var root=N(name,null,0,0,width,76);var c=root.gameObject.AddComponent<ExpeditionMemberCard>();c.Paper=root.gameObject.AddComponent<Image>();c.Paper.sprite=paper;c.Button=root.gameObject.AddComponent<Button>();c.Button.targetGraphic=c.Paper;c.Portrait=I("Portrait",root,12,12,50,50,null,Color.white);c.Portrait.preserveAspect=true;c.Name=T("Name",root,76,recipient?2:0,width-90,recipient?38:76,"",24,true);if(recipient)c.State=T("State",root,76,39,width-90,32,"",18,true);var path="Assets/Prefabs/Settlement/"+name+".prefab";var asset=PrefabUtility.SaveAsPrefabAsset(root.gameObject,path);Object.DestroyImmediate(root.gameObject);return asset.GetComponent<ExpeditionMemberCard>();}
 static RectTransform Scroll(Transform root,string name,float x,float y,float w,float h,bool tabs){var r=N(name,root,x,y,w,h);var hit=r.gameObject.AddComponent<Image>();hit.color=Color.clear;var mask=r.gameObject.AddComponent<RectMask2D>();var s=r.gameObject.AddComponent<ScrollRect>();var c=N("Content",r,0,0,w-(tabs?0:24),h-(tabs?16:0));s.content=c;s.viewport=r;s.horizontal=tabs;s.vertical=!tabs;s.movementType=ScrollRect.MovementType.Clamped;s.scrollSensitivity=30;
 var fit=c.gameObject.AddComponent<ContentSizeFitter>();if(tabs){var layout=c.gameObject.AddComponent<HorizontalLayoutGroup>();layout.spacing=16;layout.childControlWidth=layout.childControlHeight=layout.childForceExpandWidth=layout.childForceExpandHeight=false;fit.horizontalFit=ContentSizeFitter.FitMode.PreferredSize;}else{var grid=c.gameObject.AddComponent<GridLayoutGroup>();grid.cellSize=new Vector2(328,76);grid.spacing=new Vector2(16,12);grid.constraint=GridLayoutGroup.Constraint.FixedColumnCount;grid.constraintCount=2;fit.verticalFit=ContentSizeFitter.FitMode.PreferredSize;}
 var track=I("Rail",r,tabs?0:w-12,tabs?h-8:0,tabs?w:12,tabs?6:h,null,new Color(.7f,.72f,.62f,.25f));track.raycastTarget=true;var bar=track.gameObject.AddComponent<Scrollbar>();var handle=I("Handle",track.transform,0,0,0,0,null,new Color(.96f,.77f,.4f));bar.handleRect=handle.rectTransform;bar.targetGraphic=handle;bar.direction=tabs?Scrollbar.Direction.LeftToRight:Scrollbar.Direction.BottomToTop;if(tabs){s.horizontalScrollbar=bar;s.horizontalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;}else{s.verticalScrollbar=bar;s.verticalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;}return c;}
 public static string Run(){const string path="Assets/Prefabs/Settlement/ExpeditionBagPanel.prefab";var go=PrefabUtility.LoadPrefabContents(path);try{var b=go.GetComponent<ExpeditionBagPanel>();var w=b.Workspace.transform;font=b.LeftTitle.font;paper=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/PartySelection/footer-paper.png");
 var sections=w.Cast<Transform>().Where(t=>t.name=="Section").ToArray();foreach(Transform child in w)child.gameObject.SetActive(false);var old=w.Find("TabLayout");if(old)Object.DestroyImmediate(old.gameObject);var root=N("TabLayout",w,0,0,1920,1080);
 Move(sections[0],root,80,248,1000,696);Move(sections[1],root,1104,248,748,696);sections[2].gameObject.SetActive(false);
 T("Hint",root,670,36,1170,66,"대원 탭 → 물품 선택 → 받을 동료 이름을 누르면 전달",24);
 b.MemberPrefab=Card("FieldBagOwnerTab",264,false);b.RecipientPrefab=Card("FieldBagRecipient",328,true);b.LeftMembers=Scroll(root,"OwnerTabs",80,132,1772,94,true);b.RightMembers=Scroll(root,"Recipients",1128,728,700,188,false);
 I("BagHeading",root,104,520,670,62,paper,Color.white);TextMove(b.LeftTitle,root,122,520,634,62,29,ink);TextMove(b.LeftCapacity,root,828,520,226,62,27,cream);b.LeftCapacity.alignment=TextAnchor.MiddleRight;
 b.Roster=AssetDatabase.LoadAssetAtPath<PartyRoster>("Assets/Data/PartyRoster.asset");
 b.ProfilePortrait=I("ProfilePortrait",root,120,292,108,146,null,Color.white);b.ProfilePortrait.preserveAspect=true;
 var portraitFit=b.ProfilePortrait.gameObject.AddComponent<BattlePortraitFit>();portraitFit.Crops=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Settlement/BattleTurnCard.prefab").GetComponent<BattleTurnCard>().Portrait.GetComponent<BattlePortraitFit>().Crops;
 b.ProfileName=T("ProfileName",root,252,267,354,48,"",34);b.ProfileRole=T("ProfileRole",root,252,315,354,38,"",23);b.ProfileHealth=T("ProfileHealth",root,252,355,354,36,"",23);b.ProfileHealthBar=I("ProfileHealthBar",root,252,398,344,14,null,new Color(.44f,.67f,.45f));b.ProfileState=T("ProfileState",root,252,424,354,38,"",22);
 b.ProfileTrait=T("ProfileTrait",root,632,268,420,120,"",22);b.ProfileCharacteristics=T("ProfileCharacteristics",root,632,399,420,92,"",20);
 I("ProfileDivider",root,104,502,952,2,null,new Color(.8f,.8f,.65f,.25f));
 var items=b.LeftItems.GetComponentInParent<ScrollRect>(true);Move(items,root,104,602,952,310);R(b.LeftItems,0,0,928,310);var grid=b.LeftItems.GetComponent<GridLayoutGroup>();grid.constraintCount=6;grid.cellSize=new Vector2(126,126);grid.spacing=new Vector2(24,20);grid.childAlignment=TextAnchor.UpperLeft;if(items.verticalScrollbar){R(items.verticalScrollbar.transform,938,0,12,310);items.verticalScrollbar.handleRect.sizeDelta=Vector2.zero;}
 TextMove(b.EmptyLeft,root,126,660,906,100,27,cream);I("DetailHeading",root,1128,270,700,62,paper,Color.white);TextMove(b.DetailTitle,root,1146,270,664,62,29,ink);
 Move(b.DetailIcon,root,1128,354,94,104);TextMove(b.Description,root,1248,344,560,114,23,cream);
 TextMove(b.UseHint,root,1128,474,700,82,21,cream);ButtonMove(b.Use,root,1128,570,700,58,27);
 T("RecipientsHeading",root,1128,652,220,42,"동료에게 전달",26);ButtonMove(b.Minus,root,1374,650,48,46,26);TextMove(b.Quantity,root,1432,650,66,46,26,cream);b.Quantity.alignment=TextAnchor.MiddleCenter;ButtonMove(b.Plus,root,1508,650,48,46,26);ButtonMove(b.Max,root,1572,650,104,46,22);T("RecipientHint",root,1128,696,688,30,"받을 이름을 누르면 선택한 수량을 바로 건넵니다.",18);
 TextMove(b.EmptyRight,root,1128,766,676,80,24,cream);
 ButtonMove(b.Back,root,80,974,410,76,30);TextMove(b.Message,root,550,974,1302,76,23,cream);b.Transfer.gameObject.SetActive(false);
 PrefabUtility.SaveAsPrefabAsset(go,path);AssetDatabase.SaveAssets();return "Saved owner tabs + one bag + click-name recipients. Removed dual bags, pages and transfer confirmation button.";
 }finally{PrefabUtility.UnloadPrefabContents(go);}}
}
