using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using Demo5.FrontEnd;
public static class BuildSettlementRecords {
 static RectTransform R(string n,Transform p,float x,float y,float w,float h){var g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);var r=(RectTransform)g.transform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 static Text T(string n,Transform p,float x,float y,float w,float h,Text template,int size){var t=UnityEngine.Object.Instantiate(template,p);t.name=n;var r=t.rectTransform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);t.fontSize=size;t.alignment=TextAnchor.UpperLeft;t.lineSpacing=.86f;t.text="";t.raycastTarget=false;t.gameObject.SetActive(true);return t;}
 static Button B(string n,Transform p,float x,float y,float w,float h,SettlementOpeningChapter o,string label){var b=UnityEngine.Object.Instantiate(o.Back,p);b.name=n;b.onClick=new Button.ButtonClickedEvent();var r=(RectTransform)b.transform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);var t=b.GetComponentInChildren<Text>();t.rectTransform.anchorMin=Vector2.zero;t.rectTransform.anchorMax=Vector2.one;t.rectTransform.offsetMin=new Vector2(16,4);t.rectTransform.offsetMax=new Vector2(-16,-4);t.fontSize=26;t.alignment=TextAnchor.MiddleLeft;t.text=label;return b;}
 public static string Run(){const string path="Assets/Prefabs/Settlement/SettlementScreen.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var o=root.GetComponent<SettlementOpeningChapter>();var old=root.transform.Find("SettlementRecords");if(old)UnityEngine.Object.DestroyImmediate(old.gameObject);var view=R("SettlementRecords",null,0,0,1920,1080);view.gameObject.AddComponent<PopupBackgroundHud>();var dim=R("Dim",view,0,0,1920,1080).gameObject.AddComponent<Image>();dim.color=new Color(0,0,0,.97f);var heading=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Settlement/PopupHeading.prefab"),view);heading.GetComponentInChildren<Text>().text="정착지 · 기록";PrefabUtility.RecordPrefabInstancePropertyModifications(heading.GetComponentInChildren<Text>());var paper=R("Paper",view,330,230,1260,620).gameObject.AddComponent<Image>();paper.sprite=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/PartySelection/card-paper.png");paper.raycastTarget=false;T("ListHeading",view,374,266,280,56,o.EventTitle,28).text="남긴 기록";
 var nav=R("Tabs",view,374,330,280,330);var layout=nav.gameObject.AddComponent<VerticalLayoutGroup>();layout.spacing=12;layout.childControlWidth=layout.childControlHeight=true;layout.childForceExpandWidth=true;layout.childForceExpandHeight=false;string[] names={"정착 기록","접힌 관리표","첫 생활","밤의 두드림"};for(int i=0;i<4;i++){var b=B("Tab"+i,nav,0,0,280,64,o,names[i]);b.gameObject.AddComponent<LayoutElement>().preferredHeight=64;}
 var line=R("Divider",view,682,266,2,536).gameObject.AddComponent<Image>();line.color=new Color(.3f,.27f,.19f,.25f);line.raycastTarget=false;T("Title",view,720,266,816,62,o.EventTitle,38);T("Body",view,720,352,816,380,o.EventBody,28);T("Status",view,720,790,816,48,o.EventBody,21);B("Continue",view,720,734,480,58,o,"미결 사건 이어서 확인");B("ReturnReport",view,374,734,280,58,o,"최근 귀환 기록 ›");B("Back",view,80,974,410,76,o,"정착지로 돌아가기").GetComponentInChildren<Text>().alignment=TextAnchor.MiddleCenter;
 var asset=PrefabUtility.SaveAsPrefabAsset(view.gameObject,"Assets/Prefabs/Settlement/SettlementRecords.prefab");UnityEngine.Object.DestroyImmediate(view.gameObject);var panel=(GameObject)PrefabUtility.InstantiatePrefab(asset,root.transform);o.RecordsView=panel;o.RecordTabs=new Button[4];for(int i=0;i<4;i++)o.RecordTabs[i]=panel.transform.Find("Tabs/Tab"+i).GetComponent<Button>();o.RecordTitle=panel.transform.Find("Title").GetComponent<Text>();o.RecordBody=panel.transform.Find("Body").GetComponent<Text>();o.RecordStatus=panel.transform.Find("Status").GetComponent<Text>();o.RecordsBack=panel.transform.Find("Back").GetComponent<Button>();o.RecordsReturn=panel.transform.Find("ReturnReport").GetComponent<Button>();o.RecordsContinue=panel.transform.Find("Continue").GetComponent<Button>();panel.SetActive(false);PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Settlement records prefab: discovered-entry list, narrative detail, pending-event link and existing return report.";}
}

