using System;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class ConnectSearchStatus
{
 public static string Run(){if(EditorApplication.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Stop and preserve dirty scene");var catalog=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Settlement/SettlementScreen.prefab").GetComponent<SettlementController>();string path=AssetDatabase.GetAssetPath(catalog.ArrivalPanel.gameObject);var g=PrefabUtility.LoadPrefabContents(path);try{var a=g.GetComponentInChildren<ExpeditionArrivalPanel>(true);var s=a.GetComponent<ExpeditionSearchStatus>()??a.gameObject.AddComponent<ExpeditionSearchStatus>();s.Arrival=a;s.Labels=new Text[catalog.ArrivalPanel.Loot.Sites.Length];for(int i=0;i<s.Labels.Length;i++){if(a.Loot.Sites[i].Room<0)continue;var old=a.Objects[i].transform.Find("SearchStatus");if(old)Object.DestroyImmediate(old.gameObject);var card=new GameObject("SearchStatus",typeof(RectTransform),typeof(Image));card.transform.SetParent(a.Objects[i].transform,false);var r=card.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=new Vector2(.5f,0);r.pivot=new Vector2(.5f,1);r.anchoredPosition=new Vector2(0,-8);r.sizeDelta=new Vector2(190,38);var bg=card.GetComponent<Image>();bg.color=new Color(.045f,.065f,.065f,.96f);bg.raycastTarget=false;var label=new GameObject("Label",typeof(RectTransform),typeof(Text));label.transform.SetParent(card.transform,false);var lr=label.GetComponent<RectTransform>();lr.anchorMin=Vector2.zero;lr.anchorMax=Vector2.one;lr.offsetMin=new Vector2(6,0);lr.offsetMax=new Vector2(-6,0);var t=label.GetComponent<Text>();t.font=a.Status.font;t.fontSize=22;t.alignment=TextAnchor.MiddleCenter;t.text="미수색";t.raycastTarget=false;s.Labels[i]=t;}PrefabUtility.SaveAsPrefabAsset(g,path);}finally{PrefabUtility.UnloadPrefabContents(g);}path=AssetDatabase.GetAssetPath(catalog.ExpeditionPanel.gameObject);g=PrefabUtility.LoadPrefabContents(path);try{var c=g.GetComponentInChildren<ExpeditionPlanPanel>(true);c.Unknown.fontSize=22;c.Unknown.alignment=TextAnchor.UpperLeft;c.Unknown.rectTransform.anchoredPosition=new Vector2(1475,-546);c.Unknown.rectTransform.sizeDelta=new Vector2(338,76);c.UnknownHeading=c.transform.Find("UnknownLabel").GetComponent<Text>();c.UnknownHeading.text="현장 안내";c.UnknownHeading.rectTransform.anchoredPosition=new Vector2(1475,-501);c.transform.Find("Rule2").GetComponent<RectTransform>().anchoredPosition=new Vector2(1475,-490);for(int i=0;i<c.ResourceImages.Length;i++){var r=c.ResourceImages[i].rectTransform;r.pivot=new Vector2(.5f,.5f);r.anchoredPosition=new Vector2(1559.5f+169*i,-409.5f);r.sizeDelta=new Vector2(65,71);c.ResourceNames[i].rectTransform.anchoredPosition=new Vector2(1475+169*i,-442);}PrefabUtility.SaveAsPrefabAsset(g,path);}finally{PrefabUtility.UnloadPrefabContents(g);}AssetDatabase.SaveAssets();return "Recorded search states shown on field objects and expedition plan; no reward reset or new random rolls.";}
}
