using System;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.Rendering;using UnityEditor;using UnityEditor.SceneManagement;using Demo5.FrontEnd;
public static class PolishFacilityGrowth {
 const string Folder="Assets/Art/Settlement/Geometry";static Material mat;
 static GameObject Shape(Transform p,string name,Color c,int order,params float[] xy){var g=new GameObject(name,typeof(MeshFilter),typeof(MeshRenderer));g.transform.SetParent(p,false);var m=new Mesh{name=name};m.vertices=Enumerable.Range(0,xy.Length/2).Select(i=>new Vector3(xy[2*i],xy[2*i+1],0)).ToArray();m.colors=m.vertices.Select(v=>c.linear).ToArray();var tri=new List<int>();for(int i=1;i<m.vertexCount-1;i++)tri.AddRange(new[]{0,i,i+1});m.triangles=tri.ToArray();m.RecalculateBounds();string path=Folder+"/"+name+".asset";var old=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(old){EditorUtility.CopySerialized(m,old);UnityEngine.Object.DestroyImmediate(m);m=old;}else AssetDatabase.CreateAsset(m,path);g.GetComponent<MeshFilter>().sharedMesh=m;var r=g.GetComponent<MeshRenderer>();r.sharedMaterial=mat;r.sortingOrder=order;return g;}
 static void Strip(Transform p,string n,Color c,int o,float x,float y,float w,float h){Shape(p,n,c,o,x,y,x+w,y,x+w,y+h,x,y+h);}
 static Transform Group(Transform p,string name,int order){var old=p.Find(name);if(old)UnityEngine.Object.DestroyImmediate(old.gameObject);var g=new GameObject(name,typeof(SortingGroup));g.transform.SetParent(p,false);g.GetComponent<SortingGroup>().sortingOrder=order;return g.transform;}
 public static string Run(){mat=AssetDatabase.LoadAssetAtPath<Material>("Assets/Settings/SettlementProp.mat");mat.SetColor("_Color",new Color(.92f,.94f,.95f,1));EditorUtility.SetDirty(mat);const string path="Assets/Prefabs/Settlement/SettlementWorld.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var world=root.GetComponentInChildren<SettlementDevelopmentWorld>(true);var crates=world.StorageCrates.transform;var d=Group(crates,"SurfaceDetails",30);Color dark=new Color(.10f,.12f,.11f,1),wood=new Color(.34f,.32f,.24f,1),metal=new Color(.28f,.32f,.31f,1);
 for(int i=1;i<=3;i++){Strip(d,"StockSlatA"+i,dark,i,-2.30f,-2.68f+i*.105f,1.05f,.014f);Strip(d,"StockSlatB"+i,dark,5+i,-1.16f,-2.57f+i*.09f,.74f,.012f);}for(int i=0;i<2;i++){float x=-2.27f+i*.89f;Strip(d,"StockBraceA"+i,wood,12+i,x,-2.66f,.09f,.40f);Strip(d,"StockRivetA"+i,metal,16+i,x+.03f,-2.35f,.025f,.025f);}Shape(d,"StockLidSeam",dark,20,-2.02f,-2.23f,-2.005f,-2.23f,-1.785f,-1.86f,-1.80f,-1.86f);
 var upgrade=Group(crates,"WarehouseReinforced",40);world.WarehouseUpgrade=upgrade.gameObject;for(int i=0;i<2;i++){Strip(upgrade,"StockReinforcement"+i,metal,0,-2.30f,-2.64f+i*.31f,1.05f,.045f);Strip(upgrade,"StockReinforcementB"+i,metal,1,-1.16f,-2.54f+i*.27f,.74f,.04f);}
 var temp=Group(world.transform,"TemporaryStock",730);world.TemporaryStock=temp.gameObject;Shape(temp,"StockGroundCloth",new Color(.27f,.28f,.23f,.85f),0,-2.3f,-2.66f,-.38f,-2.66f,-.12f,-2.2f,-2.04f,-2.2f);Shape(temp,"StockFoldedBundle",new Color(.38f,.36f,.28f,1),1,-2.05f,-2.50f,-1.22f,-2.50f,-1.06f,-2.20f,-1.83f,-2.20f);Strip(temp,"StockBundleTie",dark,2,-1.64f,-2.50f,.05f,.28f);
 var desk=Group(world.ResearchTable.transform,"DeskDetails",40);Strip(desk,"ResearchTopEdge",wood,0,.61f,-1.64f,1.83f,.025f);Strip(desk,"ResearchLegBrace",metal,1,.82f,-2.03f,1.38f,.055f);Shape(desk,"ResearchPencil",new Color(.58f,.45f,.23f,1),2,1.79f,-1.56f,1.82f,-1.56f,2.0f,-1.2f,1.97f,-1.2f);
 var plan=Group(world.ResearchPlan.transform,"PlanDetails",5);for(int i=0;i<3;i++)Shape(plan,"ResearchPlanFold"+i,new Color(.35f,.40f,.35f,.7f),i,.88f+i*.44f,-2.1f,.895f+i*.44f,-2.1f,1.1f+i*.44f,-1.67f,1.085f+i*.44f,-1.67f);
 PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Removed double-dark tint; added wooden slats, hardware, research details, temporary stock bundle and level 2 reinforcement.";}
}
