using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class VerifyLifeSupplies {
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static SettlementController Owner()=>Object.FindAnyObjectByType<SettlementController>();
 static int Stock(SettlementController c,string id)=>c.CraftPanel.Materials.First(m=>m.Id==id).Initial;
 // A facility takes a press only inside its drawn outline (SettlementFacilityFocus), which can miss the rect centre: aim inside it (as
 // VerifyFacilityContours does).
 static Vector2 At(Button b,Camera cam){var r=(RectTransform)b.transform;var pos=RectTransformUtility.WorldToScreenPoint(cam,r.TransformPoint(r.rect.center));var f=b.GetComponent<SettlementFacilityFocus>();if(!f||f.IsRaycastLocationValid(pos,cam))return pos;for(int y=1;y<10;y++)for(int x=1;x<10;x++){var test=RectTransformUtility.WorldToScreenPoint(cam,r.TransformPoint(new Vector3(r.rect.xMin+r.rect.width*x/10,r.rect.yMax-r.rect.height*y/10,0)));if(f.IsRaycastLocationValid(test,cam))return test;}throw new Exception("No hit outline "+b.name);}
 static async Task Tap(Button b){await Task.Delay(60);Check(b&&b.IsActive()&&b.IsInteractable(),"Unavailable "+(b?b.name:"null"));Canvas.ForceUpdateCanvases();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=At(b,b.GetComponentInParent<Canvas>().worldCamera),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name+" by "+(hits.Count>0?hits[0].gameObject.name:"none"));ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(90);}
 static void Bounds(GameObject g){Canvas.ForceUpdateCanvases();foreach(var t in g.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Text overflow "+t.name+": "+t.preferredHeight+"/"+t.rectTransform.rect.height);}
 static string Compare(CampaignSaveData s){s.SavedUtc="2000-01-01T00:00:00Z";return JsonUtility.ToJson(s);}
 static async Task Queue(SettlementController c,string id,int worker,int count=1){await Tap(c.Workbench);c.CraftPanel.FocusRecipe(id);await Tap(c.CraftPanel.WorkerRows[worker].Button);for(int i=1;i<count;i++)await Tap(c.CraftPanel.Plus);Bounds(c.CraftPanel.View);await Tap(c.CraftPanel.Confirm);}
 static InventorySlot Row(IEnumerable<InventorySlot> rows,string name)=>rows.First(r=>r.GetComponentsInChildren<Text>().Any(t=>t.text==name));
 // Fixture (2026-09-26, run after VerifyFieldTurnPlan.Enter): a new game starts with no workbench or bed and an empty stock (도입
 // 0→1→2→5; the bench comes after the opening chapter's first return). These checks are about later play: the opening chapter is off,
 // the stock room, the bed (sleep) and the workbench are restored and the old starting stock is granted (wood 2 · rope 3 · scrap 3 ·
 // cloth 2 · food 6 · water 4 · can 2 · raw water 2).
 static async Task LaterPlay(SettlementController c){if(c.Opening)c.Opening.State.Enabled=false;var d=c.Development.State;d.Warehouse=Math.Max(1,d.Warehouse);d.Workbench=true;d.Bed=true;foreach(var (id,count) in new[]{("wood",2),("rope",3),("scrap",3),("cloth",2),("food",6),("water",4),("can",2),("raw-water",2)}){var m=c.CraftPanel.Materials.First(x=>x.Id==id);m.Initial=Math.Max(m.Initial,count);}c.RefreshResources();await Task.Delay(200);/* the settlement buttons follow on the next LateUpdate */}
 // An old slot file in the save envelope (CampaignSaveStore: magic, payload, SHA-256 of the payload).
 [Serializable] sealed class Envelope{public string Magic,Payload,Hash;}
 static void WriteOld(CampaignSaveData data){string payload=JsonUtility.ToJson(data),hash;using(var sha=System.Security.Cryptography.SHA256.Create())hash=Convert.ToBase64String(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(payload)));Directory.CreateDirectory(CampaignSaveStore.DirectoryPath);File.WriteAllText(CampaignSaveStore.SlotPath(0),JsonUtility.ToJson(new Envelope{Magic="NEIGHBOR-NOT-SAVE",Payload=payload,Hash=hash}),new System.Text.UTF8Encoding(false));}
 public static async Task<string> Flow(){
  CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/LifeVerification-"+Guid.NewGuid().ToString("N"));
  var c=Owner();await LaterPlay(c);var p=c.Campaign.Party.ToArray();Check(Stock(c,"raw-water")==2&&Stock(c,"bandage")==0,"Life fixture stock");
  var v2=CampaignPersistence.Capture(c);v2.Version=2;v2.Materials=v2.Materials.Where(m=>!CampaignPersistence.LifeIds.Contains(m.Id)).ToArray();/* the old slot below: before the life supplies */
  int time=c.Campaign.MinuteOfDay;await Tap(c.Workbench);c.CraftPanel.FocusRecipe("water");Bounds(c.CraftPanel.View);await Tap(c.CraftPanel.CloseButton);Check(c.Campaign.MinuteOfDay==time&&Stock(c,"raw-water")==2,"Inspect spent water/time");
  await Queue(c,"water",0);Check(c.CraftPanel.Available("raw-water")==1&&c.CraftPanel.Available("wood")==1&&!c.InventoryPanel.MoveFor(p[1],"raw-water",2,true),"Purification reservation");c.Campaign.AdvanceSettlementTime(5);time=c.Campaign.MinuteOfDay;
  await Tap(c.Workbench);await Tap(c.CraftPanel.OrderRows[0].Cancel);await Tap(c.CraftPanel.CancelNo);Check(c.CraftPanel.Orders.Count==1,"Cancel dismissal removed water job");await Tap(c.CraftPanel.OrderRows[0].Cancel);await Tap(c.CraftPanel.CancelYes);Check(Stock(c,"raw-water")==2&&c.CraftPanel.Available("wood")==2&&c.Campaign.MinuteOfDay==time,"Partial cancel changed stock/time");await Tap(c.CraftPanel.CloseButton);
  await Queue(c,"water",0);await Queue(c,"bandage",1,2);Check(c.CraftPanel.Available("water")==2&&c.CraftPanel.Available("cloth")==0,"Bandage reservation");Check(!c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Busy workers departed");
  c.Campaign.AdvanceSettlementTime(5);var snapshot=CampaignPersistence.Capture(c);string expected=Compare(snapshot);Check(CampaignSaveStore.Write(0,snapshot,c,out var error),error);var disk=CampaignSaveStore.Read(0,c);Check(disk.CanLoad&&Compare(disk.Data)==expected,"Life roundtrip: "+disk.Error);
  var bad=CampaignPersistence.Capture(c);bad.Materials.First(m=>m.Id=="raw-water").Count=0;Check(!CampaignSaveStore.Write(1,bad,c,out _),"Over-reserved water accepted");
  string currentPath=CampaignSaveStore.TestDirectory;
  // Old slot files: the Temp fixtures other runs left (SystemMenu/CookingRestart, written by older builds) do not survive an editor restart,
  // so a v2 file (before the life supplies) is built here from this campaign's opening state; the others are read when they exist.
  string built=Path.GetFullPath("Temp/LifeVerification-old-"+Guid.NewGuid().ToString("N"));CampaignSaveStore.TestDirectory=built;WriteOld(v2);CampaignSaveStore.TestDirectory=currentPath;int oldFiles=0;
  foreach(var path in new[]{built,"Temp/SystemMenuVerification","Temp/CookingRestartVerification"}){try{CampaignSaveStore.TestDirectory=Path.GetFullPath(path);if(!File.Exists(CampaignSaveStore.SlotPath(0)))continue;oldFiles++;string before=File.ReadAllText(CampaignSaveStore.SlotPath(0));var old=CampaignSaveStore.Read(0,c);Check(old.CanLoad&&old.Data.Version==CampaignPersistence.CurrentVersion,"Old file migration: "+old.Error);Check(old.Data.Materials.Where(m=>CampaignPersistence.LifeIds.Contains(m.Id)).All(m=>m.Count==0),"Migration granted life materials");Check(File.ReadAllText(CampaignSaveStore.SlotPath(0))==before,"Reading rewrote old file");}finally{CampaignSaveStore.TestDirectory=currentPath;}}Check(oldFiles>0,"No old slot file read");
  var missing=CampaignPersistence.Capture(c);missing.Version=2;missing.Materials=missing.Materials.Where(m=>m.Id!="water").ToArray();bool refused=false;try{CampaignPersistence.Upgrade(missing,c);}catch(InvalidOperationException){refused=true;}Check(refused,"v2 missing base water accepted");
  CampaignPersistence.Prepare(disk.Data,c);SceneManager.LoadScene("Settlement");await Task.Delay(700);c=Owner();p=c.Campaign.Party.ToArray();Check(Compare(CampaignPersistence.Capture(c))==expected,"Life job restore differs");
  c.Campaign.AdvanceSettlementTime(15);Check(Stock(c,"water")==5&&Stock(c,"raw-water")==1&&Stock(c,"wood")==1&&Stock(c,"bandage")==0&&c.CraftPanel.Orders.Count==1,"Purification completion");c.Campaign.AdvanceSettlementTime(10);Check(Stock(c,"bandage")==2&&Stock(c,"water")==3&&Stock(c,"cloth")==0,"Bandage completion");c.Campaign.AdvanceSettlementTime(30);Check(Stock(c,"bandage")==2&&Stock(c,"water")==3,"Duplicate production");
  Check(c.InventoryPanel.MoveFor(p[0],"bandage",2,true),"Pack bandages");p[0].Health=p[0].MaxHealth-2;/* one bandage (+2) heals to full (역할 밸런스: 체력 6, no longer 3) */await Tap(c.Cabinet);await Tap(Row(c.InventoryPanel.BagRows,"붕대").Button);Bounds(c.InventoryPanel.View);Check(c.InventoryPanel.Use.GetComponentInChildren<Text>().text=="치료","Settlement treatment verb");time=c.Campaign.MinuteOfDay;await Tap(c.InventoryPanel.Use);Check(p[0].Health==p[0].MaxHealth&&c.InventoryPanel.CountFor(p[0],"bandage")==1&&c.Campaign.MinuteOfDay==time+10,"Settlement bandage cost/time/healing");Check(!c.InventoryPanel.UseSelected(),"Full health consumed bandage");p[0].Health=0;Check(!c.InventoryPanel.UseSelected(),"Bandage revived");p[0].Health=1;await Tap(c.InventoryPanel.CloseButton);
  await Tap(c.Bed);await Tap(c.WorkPanel.Rows[0].Button);await Tap(c.WorkPanel.Confirm);await Tap(c.Cabinet);await Tap(Row(c.InventoryPanel.BagRows,"붕대").Button);Check(!c.InventoryPanel.UseSelected(),"Busy patient treated");await Tap(c.InventoryPanel.CloseButton);await Tap(c.Bed);await Tap(c.WorkPanel.Rows[0].Button);await Tap(c.WorkPanel.Confirm);Check(!c.IsAssigned(p[0]),"Rest cancellation");
  Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Treatment expedition");await Task.Delay(900);await Tap(c.ArrivalPanel.Cards[0].Button);var bags=c.ArrivalPanel.FieldBags;await Tap(Row(bags.LeftRows,"붕대").Button);Bounds(bags.View);Check(bags.Use.GetComponentInChildren<Text>().text.EndsWith("치료 · "+bags.QueueSuffix,StringComparison.Ordinal),"Field treatment verb (the member's next-turn action): "+bags.Use.GetComponentInChildren<Text>().text);
  int turns=c.ArrivalPanel.Rooms.Turns,noise=c.ArrivalPanel.Rooms.Noise;time=c.Campaign.MinuteOfDay;int other=p[1].Health;
  c.ArrivalPanel.Popup.SetActive(true);Check(!c.InventoryPanel.UseFieldItem(p[0],"bandage"),"Treatment over modal");c.ArrivalPanel.Popup.SetActive(false);Check(!c.InventoryPanel.UseFieldItem(p[1],"bandage"),"Consumed another member's bandage");
  // 말 놓기: the use is queued as the member's action; it happens on '턴 진행' (one turn, no noise).
  await Tap(bags.Use);Check(p[0].Health==1&&c.InventoryPanel.CountFor(p[0],"bandage")==1&&c.ArrivalPanel.Rooms.Turns==turns&&c.ArrivalPanel.Threat.Planner.UseQueued(0,"bandage")&&bags.Use.GetComponentInChildren<Text>().text==string.Format(bags.QueuedLabel,p[0].Name),"Field treatment queued, nothing yet");
  await Tap(bags.Back);FieldIdleConfirm.AutoAccept=true;Check(await FieldPawnTest.Turn(c.ArrivalPanel),"'턴 진행'");
  Check(p[0].Health==3&&p[1].Health==other&&c.InventoryPanel.CountFor(p[0],"bandage")==0&&c.ArrivalPanel.Rooms.Turns==turns+1&&c.Campaign.MinuteOfDay==time+10&&c.ArrivalPanel.Rooms.Noise==noise,"Field treatment transaction");Check(!c.InventoryPanel.UseFieldItem(p[0],"bandage"),"Repeated treatment");await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);
  p[0].Health=p[0].MaxHealth;/* at full health (체력 6 since the role balance; the field bandage left 3) */await Tap(c.Bed);await Tap(c.WorkPanel.Rows[0].Button);Check(!c.WorkPanel.Confirm.interactable&&c.WorkPanel.Effect.text.EndsWith("+0"),"Full health rest misleading");await Tap(c.WorkPanel.CloseButton);p[1].Health=p[1].MaxHealth-1;await Tap(c.Bed);await Tap(c.WorkPanel.Rows[1].Button);await Tap(c.WorkPanel.Sleep);Check(c.WorkPanel.Effect.text.EndsWith("+1"),"Rest preview exceeds missing HP");Bounds(c.WorkPanel.View);await Tap(c.WorkPanel.Confirm);c.Campaign.AdvanceSettlementTime(120);Check(p[1].Health==p[1].MaxHealth&&c.WorkPanel.Orders.Count==0,"Rest completion");
  Check(CampaignSaveStore.Write(2,CampaignPersistence.Capture(c),c,out error),error);
  return "PASS: purification/bandage craft and cancellation, shared reservations, parallel jobs + full disk restore, old-file migrations ("+oldFiles+" files) without grants/file writes, invalid stock rejection, once-only output, settlement and field treatment with per-bag ownership/time/max-health/busy/dead/modal guards, rest real-heal preview and completion.";
 }
 public static async Task<string> CraftPreview(){var c=Owner();await Tap(c.Workbench);c.CraftPanel.FocusRecipe("water");c.CraftPanel.RecipeScroll.verticalNormalizedPosition=0;await Tap(c.CraftPanel.WorkerRows[0].Button);Bounds(c.CraftPanel.View);return "Purification preview ready.";}
 public static string BandagePreview(){var c=Owner();c.CraftPanel.FocusRecipe("bandage");c.CraftPanel.RecipeScroll.verticalNormalizedPosition=0;Bounds(c.CraftPanel.View);return "Bandage recipe and shortage guide ready.";}
 public static async Task<string> RestPreview(){var c=Owner();if(c.CraftPanel.IsOpen)c.CraftPanel.Close();c.Campaign.Party.First().Health=2;await Tap(c.Bed);await Tap(c.WorkPanel.Rows[0].Button);await Tap(c.WorkPanel.Sleep);Bounds(c.WorkPanel.View);return "Sleep preview clamps +3 base healing to actual missing +1.";}
 public static async Task<string> TreatmentPreview(){
  var c=Owner();var s=CampaignSaveStore.Read(0,c);Check(s.CanLoad,s.Error);CampaignPersistence.Prepare(s.Data,c);SceneManager.LoadScene("Settlement");await Task.Delay(700);c=Owner();c.Campaign.AdvanceSettlementTime(30);c.Campaign.Party.First().Health=1;await Tap(c.Cabinet);await Tap(c.InventoryPanel.Tabs[3]);await Tap(Row(c.InventoryPanel.StockRows,"붕대").Button);Bounds(c.InventoryPanel.View);return "Crafted bandages in stock; treatment preview ready.";
 }
 public static async Task<string> FieldPreview(){var c=Owner();c.InventoryPanel.Close();var p=c.Campaign.Party.ToArray();Check(c.InventoryPanel.MoveFor(p[0],"bandage",1,true),"Pack for preview");Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Field preview begin");await Task.Delay(900);await Tap(c.ArrivalPanel.Cards[0].Button);await Tap(Row(c.ArrivalPanel.FieldBags.LeftRows,"붕대").Button);Bounds(c.ArrivalPanel.FieldBags.View);return "Actual crafted bandage in explorer bag; field treatment preview ready.";}
 public static async Task<string> WaterSupply(){
  var c=Owner();var p=c.Campaign.Party.ToArray();c.ArrivalPanel.FieldBags.Close();var loot=c.ArrivalPanel.Loot;Check(loot.Sites[0].Drops.Any(d=>d.Id=="raw-water"&&d.Chance==85),"Raw water source absent");{var water=loot.Sites[0].Drops.First(d=>d.Id=="raw-water"&&d.Chance==85);water.Chance=100;/* pinned: 정밀 +15 is gone */try{for(int i=0;i<3&&!loot.State(0).Complete;i++)Check(loot.Advance(0,1,p[0]),"Water search progress");}finally{water.Chance=85;}}Check(loot.State(0).Complete&&loot.State(0).Loot["raw-water"]==3,"Raw water fixture found");loot.Open(0);await Task.Delay(100);await Tap(Row(loot.FieldRows,"미정수 물").Button);await Tap(loot.Max);await Tap(loot.Transfer);Check(c.InventoryPanel.CountFor(p[0],"raw-water")==3,"Water bag transfer");await Tap(loot.Back);if(loot.LeaveReview.activeSelf)await Tap(loot.LeaveConfirm);await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);int raw=Stock(c,"raw-water");Check(c.InventoryPanel.MoveFor(p[0],"raw-water",3,false)&&Stock(c,"raw-water")==raw+3,"Water into stock");
  var s=CampaignPersistence.Capture(c);CampaignPersistence.Prepare(s,c);SceneManager.LoadScene("Settlement");await Task.Delay(700);c=Owner();p=c.Campaign.Party.ToArray();Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Water revisit");await Task.Delay(900);Check(!c.ArrivalPanel.Loot.Advance(0,2,p[0])&&(!c.ArrivalPanel.Loot.State(0).Loot.TryGetValue("raw-water",out int n)||n==0),"Water rerolled");await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);
  return "PASS: actual raw-water search drop -> distribution -> bag -> return -> stock; restored completed site does not reroll water.";
 }
 public static string SaveRestartFixture(){var c=Owner();var saved=CampaignSaveStore.Read(0,c);Check(saved.CanLoad,saved.Error);CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/LifeRestartVerification");Check(CampaignSaveStore.Write(0,saved.Data,c,out var error),error);return "Isolated v3 unfinished purification/bandage fixture saved.";}
 public static async Task<string> Restart(){CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/LifeRestartVerification");SceneManager.LoadScene("StartMenu");await Task.Delay(650);var t=Object.FindAnyObjectByType<TitleMenuController>();await Tap(t.ContinueButton);await Task.Delay(700);var c=Owner();Check(c.CraftPanel.Orders.Count==2&&c.CraftPanel.Orders.Any(o=>o.Recipe.Id=="water"&&o.Minutes==15)&&c.CraftPanel.Orders.Any(o=>o.Recipe.Id=="bandage"&&o.Minutes==25),"Restart lost production jobs");c.Campaign.AdvanceSettlementTime(25);Check(Stock(c,"bandage")==2&&Stock(c,"water")==3&&Stock(c,"raw-water")==1,"Restart wrong output/costs");c.Campaign.AdvanceSettlementTime(30);Check(Stock(c,"bandage")==2&&Stock(c,"water")==3,"Restart duplicate output");return "PASS: fresh Play -> title Continue -> v3 partial purification/bandage jobs -> once-only costs and products.";}
}
