using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using Demo5.FrontEnd;
public static class VerifySettlementFrames {
 static SettlementController C=>UnityEngine.Object.FindAnyObjectByType<SettlementController>();
 static void Check(bool v,string s){if(!v)throw new Exception(s);}
 static async Task Tap(Button b){Check(b.IsActive()&&b.IsInteractable(),"Unavailable "+b.name);Canvas.ForceUpdateCanvases();var cam=b.GetComponentInParent<Canvas>().worldCamera;cam?.Render();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(cam,r.TransformPoint(r.rect.center))};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(100);}
 static string Audit(GameObject v,params Button[] buttons){Check(C.Main.alpha==0,"HUD visible");Check(v.transform.Find("PopupHeading").gameObject.activeInHierarchy,"Heading missing");Canvas.ForceUpdateCanvases();foreach(var t in v.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Clipped "+t.name+": "+t.text);foreach(var b in buttons){var r=(RectTransform)b.transform;Check(Math.Abs(-r.anchoredPosition.y+r.rect.height-1050)<1,"Footer "+b.name);}return "PASS heading, hidden HUD, text bounds, footer baseline, real pointer clicks.";}
 public static async Task<string> Inventory(){await Tap(C.Cabinet);return Audit(C.InventoryPanel.View,C.InventoryPanel.CloseButton);}
 public static async Task<string> Craft(){await Tap(C.InventoryPanel.CloseButton);Check(C.Main.alpha==1,"HUD restore inventory");await Tap(C.Workbench);await Tap(C.CraftPanel.RecipeRows[0].Button);await Tap(C.CraftPanel.WorkerRows[0].Button);return Audit(C.CraftPanel.View,C.CraftPanel.CloseButton,C.CraftPanel.Confirm);}
 public static async Task<string> Rest(){await Tap(C.CraftPanel.CloseButton);Check(C.Main.alpha==1,"HUD restore craft");await Tap(C.Bed);await Tap(C.WorkPanel.Rows[1].Button);await Tap(C.WorkPanel.Sleep);return Audit(C.WorkPanel.View,C.WorkPanel.CloseButton,C.WorkPanel.Confirm);}
 public static async Task<string> Register(){await Tap(C.WorkPanel.Confirm);Check(!C.WorkPanel.IsOpen&&C.Main.alpha==1,"Rest registration close");Check(C.WorkPanel.Orders.Count==1,"Rest order missing");return "PASS rest order registration and HUD restoration.";}
 public static async Task<string> CancelDialog(){await Tap(C.WorkPanel.CloseButton);await Tap(C.Workbench);await Tap(C.CraftPanel.OrderRows[0].Cancel);Check(C.CraftPanel.CancelPopup.activeSelf,"Cancel not open");Canvas.ForceUpdateCanvases();foreach(var t in C.CraftPanel.CancelPopup.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Cancel clipped "+t.name);return "PASS populated cancel dialog text bounds and click.";}
 public static async Task<string> KeepOrder(){await Tap(C.CraftPanel.CancelNo);Check(C.CraftPanel.OrderRows.Count==1,"Keep lost order");await Tap(C.CraftPanel.CloseButton);Check(C.Main.alpha==1,"HUD restore");return "PASS keep order and close.";}
 public static async Task<string> CraftQueued(){var c=C.CraftPanel;await Tap(c.RecipeRows[1].Button);await Tap(c.WorkerRows[0].Button);await Tap(c.Confirm);await Tap(C.Workbench);Check(c.OrderRows.Count==1,"Missing order");var p=(RectTransform)c.View.transform.Find("Workspace/OrdersPaper");foreach(var path in new[]{"Count","Empty","Hint"}){var r=(RectTransform)p.Find(path);Check(r.anchoredPosition.x+r.rect.width<=p.rect.width-24,"Paper right inset "+path);}foreach(var row in c.OrderRows){var r=(RectTransform)row.transform;Check(r.rect.width<=c.OrderContent.rect.width,"Order outside list");foreach(var t in row.GetComponentsInChildren<Text>()){Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Order text height "+t.name);Check(t.rectTransform.anchoredPosition.x+t.rectTransform.rect.width<=r.rect.width-12,"Order right inset "+t.name);}}return Audit(c.View,c.CloseButton,c.Confirm);}
}
