using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEngine.SceneManagement;using Demo5.FrontEnd;
public static class VerifyNightEvent {
 static SettlementController C()=>UnityEngine.Object.FindAnyObjectByType<SettlementController>();static void Check(bool x,string m){if(!x)throw new Exception(m);}
 static async Task Tap(Button b){await Task.Delay(100);Canvas.ForceUpdateCanvases();Check(b.IsActive()&&b.IsInteractable(),"Unavailable "+b.name);var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(150);}
 static int Time()=>C().Campaign.Day*1440+C().Campaign.MinuteOfDay;
 static async Task Reload(CampaignSaveData data){CampaignPersistence.Prepare(data,C());SceneManager.LoadScene("Settlement");await Task.Delay(650);}
 static async Task RoundTrip(){var c=C();CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/NightEventVerification");try{Check(CampaignSaveStore.Write(0,CampaignPersistence.Capture(c),c,out string error),error);var read=CampaignSaveStore.Read(0,c);Check(read.CanLoad,read.Error);await Reload(read.Data);}finally{CampaignSaveStore.TestDirectory=null;}}
 static void Fits(){var o=C().Opening;Canvas.ForceUpdateCanvases();foreach(var t in new[]{o.NightBody,o.NightResult})Check(t.preferredHeight<=t.rectTransform.rect.height,"Overflow "+t.name+" "+t.preferredHeight);Check(C().Main.alpha==0,"HUD visible");}
 public static async Task<string> Ready(){var c=C();Check(c.Opening.State.Complete&&!c.Opening.NightAvailable,"Day gate");var old=CampaignPersistence.Capture(c);old.Version=11;CampaignPersistence.Upgrade(old,c);Check(old.Version==CampaignPersistence.CurrentVersion&&!old.Opening.NightHeard&&old.Opening.NightChoice==0,"Migration");c.Campaign.AdvanceSettlementTime(1200-c.Campaign.MinuteOfDay);await Task.Delay(150);Check(c.Opening.NightAvailable,"Night gate");int before=Time();await Tap(c.Introduction.Action);Check(c.Opening.State.NightHeard&&Time()==before,"Opening cost time");Fits();await Tap(c.Opening.NightBack);Check(Time()==before&&c.Opening.Active,"Defer cost time");await RoundTrip();Check(C().Opening.State.NightHeard&&C().Opening.State.NightChoice==0,"Deferred save");File.WriteAllText("Temp/NightEventBeforeChoice.json",JsonUtility.ToJson(CampaignPersistence.Capture(C())));await Tap(C().Introduction.Action);Fits();return "PASS daytime gating, v11 migration, 20:00 trigger, defer without cost, disk save/load pending state, popup bounds.";}
 static async Task Choose(int choice){var c=C();var o=c.Opening;int before=Time();string materials=JsonUtility.ToJson(new Counts{Values=c.CraftPanel.Materials.Select(m=>m.Initial).ToArray()});await Tap(choice==1?o.NightListen:o.NightLook);Check(o.State.NightChoice==choice&&Time()-before==(choice==1?15:30),"Choice time");Check(JsonUtility.ToJson(new Counts{Values=c.CraftPanel.Materials.Select(m=>m.Initial).ToArray()})==materials,"Unexpected material cost");int logs=c.ActivityLog.Count(x=>x.StartsWith("밤의 기록"));o.ResolveNight(choice);Check(Time()-before==(choice==1?15:30)&&c.ActivityLog.Count(x=>x.StartsWith("밤의 기록"))==logs,"Duplicate resolution");Fits();}
 [Serializable]class Counts{public int[] Values;}
 public static async Task<string> Branches(){await Choose(1);await Tap(C().Opening.NightBack);await RoundTrip();Check(C().Opening.State.NightChoice==1&&!C().Opening.Active,"Resolved replayed");var invalid=CampaignPersistence.Capture(C());invalid.Opening.NightChoice=3;bool rejected=false;try{CampaignPersistence.Validate(invalid,C());}catch(InvalidOperationException){rejected=true;}Check(rejected,"Invalid choice accepted");await Reload(JsonUtility.FromJson<CampaignSaveData>(File.ReadAllText("Temp/NightEventBeforeChoice.json")));await Tap(C().Introduction.Action);await Choose(2);return "PASS both choices (15/30 minutes), no item cost, duplicate prevention, resolved save/load no replay, corrupt choice rejection, result fits.";}
 public static async Task<string> Finish(){await Tap(C().Opening.NightBack);await RoundTrip();Check(C().Opening.State.NightChoice==2&&!C().Opening.Active&&C().Main.interactable,"Final restore");return "PASS second branch disk restore and normal settlement interaction.";}
}
