using System;using System.Linq;using System.Threading.Tasks;using UnityEngine;using UnityEngine.EventSystems;using UnityEngine.UI;using System.Collections.Generic;using Demo5.FrontEnd;
public static class VerifyPaintedFacilities {
 static SettlementController C()=>UnityEngine.Object.FindAnyObjectByType<SettlementController>();
 public static async Task<string> Run(){var c=C();var world=UnityEngine.Object.FindAnyObjectByType<SettlementDevelopmentWorld>();c.Development.State.Warehouse=2;c.Development.State.Research=true;await Task.Delay(200);foreach(var b in new[]{c.Cabinet,c.Development.ResearchButton}){var f=b.GetComponent<SettlementFacilityFocus>();if(!f.Artwork||!f.Artwork.gameObject.activeInHierarchy)throw new Exception("Artwork missing");var tex=f.Artwork.sprite.texture;if(!tex.isReadable||tex.GetPixel(0,0).a>.01f)throw new Exception("No transparent exterior");var cam=b.GetComponentInParent<Canvas>().worldCamera;var bounds=f.Artwork.sprite.bounds;Vector2 found=Vector2.zero;bool hit=false,empty=false;for(int y=1;y<10;y++)for(int x=1;x<10;x++){var local=new Vector3(bounds.min.x+bounds.size.x*x/10,bounds.min.y+bounds.size.y*y/10,0);var screen=RectTransformUtility.WorldToScreenPoint(cam,f.Artwork.transform.TransformPoint(local));bool valid=f.IsRaycastLocationValid(screen,cam);if(valid&&!hit){found=screen;hit=true;}if(!valid)empty=true;}if(!hit||!empty)throw new Exception("Alpha hit testing failed");var e=new PointerEventData(EventSystem.current){position=found,button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);if(hits.Count==0||hits[0].gameObject.GetComponentInParent<Button>()!=b)throw new Exception("Art click blocked");ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(100);if(b==c.Cabinet)c.InventoryPanel.Close();else c.CraftPanel.Close();EventSystem.current.SetSelectedGameObject(null);f.OnPointerEnter(null);await Task.Delay(100);var block=new MaterialPropertyBlock();f.Artwork.GetPropertyBlock(block);if(block.GetFloat("_Highlight")<.5f)throw new Exception("No alpha highlight");f.OnPointerExit(null);await Task.Delay(100);f.Artwork.GetPropertyBlock(block);if(block.GetFloat("_Highlight")!=0)throw new Exception("Idle highlight must be hidden");}return "PASS transparent originals, alpha click/empty-space rejection, warehouse/research open-close and hover outline. Saved state unchanged.";}
 public static async Task<string> Hover(){var c=C();c.Development.ResearchButton.GetComponent<SettlementFacilityFocus>().OnPointerEnter(null);await Task.Delay(100);return "Research artwork highlighted";}
}



