using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
namespace Demo5.FrontEnd {
 public sealed partial class SettlementOpeningChapter {
  public GameObject RecordsView;
  public Button[] RecordTabs;
  public Button RecordsBack, RecordsReturn, RecordsContinue;
  public Text RecordTitle, RecordBody, RecordStatus;
  void InitializeRecords(){if(!RecordsView)return;RecordsView.SetActive(false);RecordsBack.onClick.AddListener(Close);RecordsReturn.onClick.AddListener(()=>{Close();owner.ReturnPanel.Open();});RecordsContinue.onClick.AddListener(()=>{Close();OpenNight();});for(int i=0;i<RecordTabs.Length;i++){int index=i;RecordTabs[i].onClick.AddListener(()=>SelectRecord(index));}}
  public void OpenRecords(){if(!RecordsView||IsOpen||!owner.Main.interactable||owner.Campaign==null)return;returnFocus=owner.Journal.gameObject;RecordTabs[0].gameObject.SetActive(true);RecordTabs[1].gameObject.SetActive(State.ClueRead);RecordTabs[2].gameObject.SetActive(State.Complete);RecordTabs[3].gameObject.SetActive(State.NightHeard);var story=owner.ArrivalPanel?owner.ArrivalPanel.Story:null;if(RecordTabs.Length>4){RecordTabs[4].gameObject.SetActive(story&&story.HasRecord);if(story)RecordTabs[4].GetComponentInChildren<Text>().text=story.State.Stage>=2?"장도윤":"오락기 뒤의 사람";}RecordsReturn.gameObject.SetActive(owner.ReturnPanel&&owner.ReturnPanel.HasReport);owner.Main.interactable=owner.Main.blocksRaycasts=false;RecordsView.SetActive(true);SelectRecord(RecordTabs.Length>4&&story&&story.HasRecord?4:State.NightHeard?3:State.Complete?2:State.ClueRead?1:0);EventSystem.current?.SetSelectedGameObject(RecordsBack.gameObject);}
  public void SelectRecord(int index){if(!RecordsView||!RecordsView.activeSelf||index<0||index>=RecordTabs.Length||!RecordTabs[index].gameObject.activeSelf)return;foreach(var b in RecordTabs)b.GetComponent<Image>().color=b==RecordTabs[index]?new Color(1,.8f,.43f):Color.white;RecordsContinue.gameObject.SetActive(index==3&&State.NightHeard&&State.NightChoice==0);RecordStatus.text="열람에는 시간이 들지 않습니다.";switch(index){case 4:{var story=owner.ArrivalPanel?owner.ArrivalPanel.Story:null;if(story&&story.HasRecord){RecordTitle.text=story.RecordTitle;RecordBody.text=story.RecordBody();RecordStatus.text="직접 확인한 이름과 대화만 기록합니다 · 열람 0분";}break;}case 0:RecordTitle.text="우리의 정착지";RecordBody.text=owner.Campaign.Home.Name+"에서 생활하고 있다.\n\n<size=23><color=#4D5145>함께 지내는 사람들</color></size>\n"+string.Join(" · ",owner.Campaign.Party.Select(p=>p.Name))+"\n\n확인한 단서와 겪은 사건을 이곳에 모은다.\n새로운 기록은 직접 발견한 뒤에 나타난다.";break;case 1:RecordTitle.text="접힌 관리표";RecordBody.text="작업대 서랍에서 발견한 오래된 기록.\n\n<size=23><color=#4D5145>비축 장소</color></size>\n폐상가 · 복도 끝 보관실 — 물과 통조림\n\n<size=23><color=#4D5145>덧붙인 경고</color></size>\n<color=#713C29>‘안에서 두드려도 대답하지 말 것.’</color>\n\n지렛대로 보관실 철문을 열 수 있었다.";if(!State.SurveyReturned)RecordBody.text=RecordBody.text.Replace("열 수 있었다.","열 수 있을 것 같다.");break;case 2:RecordTitle.text="첫 생활을 이어갈 준비";RecordBody.text="회수한 재료로 창고와 작업대를 복구했다.\n직접 만든 지렛대로 보관실도 확인했다.\n\n<size=23><color=#4D5145>남은 의문</color></size>\n관리표의 경고는 누가 남겼을까?\n\n잠자리와 조리대를 복구하고\n다음 외출을 준비하며 생활을 이어간다.";break;case 3:RecordTitle.text="문밖에서, 세 번";if(State.NightChoice==0){RecordBody.text="문 너머에서 같은 간격의 두드림이 들렸다.\n관리표의 경고가 떠올랐다.\n\n<size=23><color=#4D5145>현재 상태</color></size>\n확인 방법을 아직 결정하지 않았다.\n\n아래 버튼으로 사건을 이어서 확인할 수 있다.";RecordStatus.text="미결 사건 · 아직 선택한 행동이 없습니다.";}else{bool listen=State.NightChoice==1;RecordBody.text="<size=23><color=#4D5145>우리가 선택한 행동</color></size>\n"+(listen?"대답 없이 귀 기울였다. · 15분":"불빛을 가리고 창으로 살폈다. · 30분")+"\n\n<size=23><color=#4D5145>확인한 단서</color></size>\n"+(listen?"두드림은 매번 같은 간격으로 반복됐다.":"문밖에는 아무도 없었다.\n먼지 위에는 발자국도 남지 않았다.")+"\n\n문을 열지 않았다. 한동안 기다리자 소리가 멎었다.\n그 이유는 아직 모른다.";RecordStatus.text="완료한 사건 · 선택과 결과만 다시 읽습니다.";}break;}}
 }
}
