import{initialStory,choicesFor,advanceStory}from'./story-core.mjs';
const $=id=>document.getElementById(id);let state=initialStory(),history=[];
try{const [data,manifest]=await Promise.all(['story.json','manifest.json'].map(async p=>{const r=await fetch(p);if(!r.ok)throw Error(p+' '+r.status);return r.json()}));
function render(){const n=data.steps[state.step],screen=manifest.screens.find(s=>s.id===n.screen);if(!screen)throw Error('Missing UI reference');$('frame').src='../../../'+screen.preview;$('frame').alt=n.title;$('title').textContent=n.title;$('purpose').textContent=n.purpose;$('direction').textContent=n.direction;$('intent').textContent='대사집에 전달할 목적: '+n.dialogue_intent;$('actions').replaceChildren();document.body.dataset.step=state.step;
const facts=['기존 책 보유 · 사진을 남기고 싶은 바람 유지'];if(state.flags.arrived)facts.push('캠핑카: 편의점 앞');if(state.flags.water_checked)facts.push('물 확보 장면 확인');if(state.flags.food_checked)facts.push('식량 확보 장면 확인');if(state.flags.notice_read)facts.push('대피 안내 열람');if(state.flags.pencils_owned)facts.push('색연필 선확보 사례');$('facts').textContent=facts.join(' / ');
if(state.step==='return')$('intent').textContent='대사집에 전달할 목적: '+(n.dialogue_intent_by_notice?.[state.flags.notice_read?'read':'unread']??n.dialogue_intent);
if(state.step==='kitchen')$('direction').textContent=n.direction+(state.flags.materials_checked?' 재료를 먼저 살핀 경로: 그때 본 부품을 떠올리는 반응을 연결한다.':' 재료 미확인 경로: 다음 탐색에서 부품을 살필 이유만 남긴다.');
choicesFor(data,state).forEach((a,i)=>{const b=document.createElement('button');b.textContent=a.label;b.onclick=()=>{history.push(structuredClone(state));state=advanceStory(data,state,i);render()};$('actions').append(b)});$('ending').hidden=!n.ending;$('ending').textContent=n.ending==='ready_to_deliver'?'1일 차 낮 콘티 끝 · 다음은 기존 책에 그릴 준비와 색연필 전달':'1일 차 낮 콘티 끝 · 다음은 색연필 확보 → 기존 책에 첫 그림';$('back').disabled=!history.length;}
$('back').onclick=()=>{if(history.length){state=history.pop();render()}};$('restart').onclick=()=>{state=initialStory();history=[];render()};$('frame').onerror=()=>{$('error').textContent='장면 참고 이미지를 불러오지 못했습니다.'};render();}catch(e){$('error').textContent='검토 파일 오류: '+e.message}
