using System;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class BuildSettlementCraft
{
    const string P="Assets/Prefabs/Settlement/",A="Assets/Art/PartySelection/",C="Assets/Art/CraftWorkPanel/";
    static Font font;
    static RectTransform R(string n,Transform p,float x,float y,float w,float h){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
    static Image I(string n,Transform p,float x,float y,float w,float h,string path){var im=R(n,p,x,y,w,h).gameObject.AddComponent<Image>();if(path!=null)im.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(path);im.raycastTarget=false;return im;}
    static Text T(string n,Transform p,float x,float y,float w,float h,string value,int size=32,bool light=false){var t=R(n,p,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontStyle=FontStyle.Bold;t.fontSize=size;t.text=value;t.color=light?new Color(.96f,.93f,.85f):new Color(.045f,.065f,.06f);t.raycastTarget=false;return t;}
    static Button B(string n,Transform p,float x,float y,float w,float h,string label,int size=34){var im=I(n,p,x,y,w,h,A+"footer-paper.png");im.raycastTarget=true;var b=im.gameObject.AddComponent<Button>();b.targetGraphic=im;T("Label",im.transform,6,0,w-12,h,label,size).alignment=TextAnchor.MiddleCenter;return b;}
    static Sprite S(string name)=>AssetDatabase.LoadAssetAtPath<Sprite>(C+name+".png");
    static GameObject Save(GameObject g,string name){var asset=PrefabUtility.SaveAsPrefabAsset(g,P+name+".prefab");Object.DestroyImmediate(g);return asset;}
    static RectTransform Stack(string name,Transform parent,float x,float y,float w,float h,float gap){var r=R(name,parent,x,y,w,h);var l=r.gameObject.AddComponent<VerticalLayoutGroup>();l.spacing=gap;l.childControlHeight=false;l.childControlWidth=false;l.childForceExpandHeight=false;l.childForceExpandWidth=false;var f=r.gameObject.AddComponent<ContentSizeFitter>();f.verticalFit=ContentSizeFitter.FitMode.PreferredSize;return r;}
    static ScrollRect Scroll(string name,Transform parent,float x,float y,float w,float h,float rowW,float gap,out RectTransform content){var viewport=R(name,parent,x,y,w,h);viewport.gameObject.AddComponent<RectMask2D>();var hit=viewport.gameObject.AddComponent<Image>();hit.color=Color.clear;content=Stack("Content",viewport,0,0,rowW,h,gap);var sc=viewport.gameObject.AddComponent<ScrollRect>();sc.viewport=viewport;sc.content=content;sc.horizontal=false;sc.movementType=ScrollRect.MovementType.Clamped;sc.scrollSensitivity=36;var rail=I("Rail",viewport,w-8,0,8,h,null);rail.color=new Color(.7f,.68f,.6f,.2f);var handle=I("Handle",rail.transform,0,0,8,60,A+"footer-paper.png");handle.raycastTarget=true;var sb=rail.gameObject.AddComponent<Scrollbar>();sb.targetGraphic=handle;sb.handleRect=handle.rectTransform;sb.direction=Scrollbar.Direction.BottomToTop;sc.verticalScrollbar=sb;sc.verticalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;return sc;}
    static SettlementCraftPanel.Cost Cost(string id,int count)=>new SettlementCraftPanel.Cost{MaterialId=id,Count=count};
    static SettlementCraftPanel.Material Mat(string id,string name,int count,Sprite icon)=>new SettlementCraftPanel.Material{Id=id,Name=name,Initial=count,Icon=icon};
    static SettlementCraftPanel.Recipe Recipe(string id,string name,string description,int category,int minutes,Sprite icon,params SettlementCraftPanel.Cost[] costs)=>new SettlementCraftPanel.Recipe{Id=id,Name=name,Description=description,Category=category,Minutes=minutes,Icon=icon,Costs=costs};
    public static string Build(){
        if(EditorApplication.isPlaying)throw new Exception("Stop Play first");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene changes");
        font=AssetDatabase.LoadAssetAtPath<Font>("Assets/Art/FrontEnd/Fonts/Gaegu/Gaegu-Bold.ttf");AssetDatabase.Refresh();foreach(var path in Directory.GetFiles(C,"*.png")){var importer=(TextureImporter)AssetImporter.GetAtPath(path.Replace('\\','/'));importer.textureType=TextureImporterType.Sprite;importer.spriteImportMode=SpriteImportMode.Single;importer.alphaIsTransparency=true;importer.mipmapEnabled=false;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.SaveAndReimport();}
        var row=I("CraftRecipeRow",null,0,0,346,72,A+"footer-paper.png");row.raycastTarget=true;var choice=row.gameObject.AddComponent<CraftChoiceRow>();choice.Paper=row;choice.Button=row.gameObject.AddComponent<Button>();choice.Button.targetGraphic=row;choice.Icon=I("Icon",row.transform,14,11,54,48,null);choice.Icon.preserveAspect=true;choice.Label=T("Name",row.transform,83,0,213,72,"간이 지렛대",32);choice.Label.alignment=TextAnchor.MiddleLeft;choice.Check=I("Selected",row.transform,303,21,27,28,A+"selected-check.png");choice.Check.preserveAspect=true;var recipePrefab=Save(row.gameObject,"CraftRecipeRow");
        row=I("CraftWorkerRow",null,0,0,408,69,A+"footer-paper.png");row.raycastTarget=true;choice=row.gameObject.AddComponent<CraftChoiceRow>();choice.Paper=row;choice.Button=row.gameObject.AddComponent<Button>();choice.Button.targetGraphic=row;choice.Icon=I("Portrait",row.transform,14,7,49,54,null);choice.Icon.preserveAspect=true;choice.Label=T("Name",row.transform,78,0,181,69,"동료",30);choice.Label.alignment=TextAnchor.MiddleLeft;choice.State=T("State",row.transform,258,0,92,69,"대기",25);choice.State.alignment=TextAnchor.MiddleCenter;choice.Check=I("Selected",row.transform,363,22,28,28,A+"selected-check.png");choice.Check.preserveAspect=true;var workerPrefab=Save(row.gameObject,"CraftWorkerRow");
        row=I("CraftCostRow",null,0,0,577,52,A+"footer-paper.png");var costRow=row.gameObject.AddComponent<CraftCostRow>();costRow.Paper=row;costRow.Icon=I("Icon",row.transform,12,6,48,40,null);costRow.Icon.preserveAspect=true;costRow.Label=T("Name",row.transform,80,0,324,52,"나무 판자",32);costRow.Label.alignment=TextAnchor.MiddleLeft;costRow.Count=T("Count",row.transform,418,0,143,52,"0 / 2",32);costRow.Count.alignment=TextAnchor.MiddleRight;var costPrefab=Save(row.gameObject,"CraftCostRow");
        row=I("CraftOrderRow",null,0,0,634,118,A+"footer-paper.png");var order=row.gameObject.AddComponent<CraftOrderRow>();order.Icon=I("Icon",row.transform,14,18,58,58,null);order.Icon.preserveAspect=true;order.Title=T("Title",row.transform,87,8,407,43,"작업",32);order.Member=T("Member",row.transform,87,53,226,35,"동료",28);order.Status=T("Status",row.transform,303,53,194,35,"예약 · 30분",27);order.Cancel=B("Cancel",row.transform,522,25,92,61,"취소",28);order.Cancel.GetComponent<Image>().color=new Color(.95f,.65f,.58f);var line=I("ProgressTrack",row.transform,87,96,410,6,null);line.color=new Color(.14f,.19f,.17f,.35f);var orderPrefab=Save(row.gameObject,"CraftOrderRow");
        var root=R("CraftWorkPanel",null,0,0,1920,1080);var c=root.gameObject.AddComponent<SettlementCraftPanel>();c.View=root.gameObject;c.HideWhileOpen=new GameObject[0];c.RecipePrefab=recipePrefab.GetComponent<CraftChoiceRow>();c.WorkerPrefab=workerPrefab.GetComponent<CraftChoiceRow>();c.CostPrefab=costPrefab.GetComponent<CraftCostRow>();c.OrderPrefab=orderPrefab.GetComponent<CraftOrderRow>();
        var blocker=I("InputBlocker",root,0,0,1920,1080,null);blocker.color=new Color(0,0,0,.08f);blocker.raycastTarget=true;var workspace=R("Workspace",root,0,0,1920,1080);c.Workspace=workspace.gameObject.AddComponent<CanvasGroup>();
        var panel=I("Workshop",workspace,38,345,1095,695,A+"card-paper.png");panel.color=new Color(.11f,.14f,.15f,.98f);var edge=panel.gameObject.AddComponent<Outline>();edge.effectColor=new Color(.5f,.5f,.42f,.5f);edge.effectDistance=new Vector2(1,-1);
        I("HeadingPaper",panel.transform,0,-22,230,73,A+"count-paper.png");T("Heading",panel.transform,30,-17,205,63,"작업대",44);c.CloseButton=B("Close",panel.transform,1020,13,53,53,"×",46);c.CloseButton.GetComponent<Image>().color=new Color(1,1,1,.12f);c.CloseButton.transform.Find("Label").GetComponent<Text>().color=new Color(.96f,.93f,.85f);
        c.Tabs=new Button[3];string[] labels={"제작","수리","개선"},icons={C+"craft.png",C+"repair.png",C+"upgrade.png"};for(int i=0;i<3;i++){c.Tabs[i]=B("Category_"+i,panel.transform,24,78+i*82,162,72,labels[i],34);I("Icon",c.Tabs[i].transform,17,16,42,42,icons[i]).preserveAspect=true;var label=(RectTransform)c.Tabs[i].transform.Find("Label");label.anchoredPosition=new Vector2(66,0);label.sizeDelta=new Vector2(86,72);}
        c.RecipeContent=Stack("Recipes",panel.transform,204,78,346,236,10);I("VerticalRule",panel.transform,558,61,2,262,null).color=new Color(.8f,.8f,.7f,.2f);
        I("ItemPaper",panel.transform,575,70,168,204,A+"card-paper.png");c.DetailIcon=I("ItemIcon",panel.transform,593,96,132,153,null);c.DetailIcon.preserveAspect=true;I("ItemHeading",panel.transform,765,70,302,58,A+"count-paper.png");c.DetailTitle=T("ItemTitle",panel.transform,784,69,280,59,"간이 지렛대",35);c.DetailDescription=T("Description",panel.transform,768,142,292,74,"간단하지만 유용한 도구입니다.",28,true);
        T("QuantityLabel",panel.transform,768,220,292,38,"제작 수량",29,true);c.Minus=B("Minus",panel.transform,770,265,61,52,"−",40);c.QuantityText=T("Quantity",panel.transform,844,265,132,52,"1",36,true);c.QuantityText.alignment=TextAnchor.MiddleCenter;c.Plus=B("Plus",panel.transform,991,265,66,52,"+",40);
        I("HorizontalRule",panel.transform,24,340,1040,2,null).color=new Color(.8f,.8f,.7f,.3f);T("WorkerHeading",panel.transform,34,351,408,51,"작업자 배정",33,true);c.WorkerScroll=Scroll("Workers",panel.transform,34,414,424,237,408,8,out c.WorkerContent);
        T("CostHeading",panel.transform,480,351,260,51,"필요 재료",33,true);T("CostColumns",panel.transform,793,351,263,51,"사용 가능 / 필요",27,true).alignment=TextAnchor.MiddleRight;c.CostContent=Stack("Costs",panel.transform,480,414,577,170,7);c.Duration=T("Duration",panel.transform,36,649,408,37,"예상 시간 30분",27,true);c.Confirm=B("StartWork",panel.transform,480,603,577,73,"재료 부족",40);c.Confirm.GetComponent<Image>().color=new Color(.61f,.83f,.62f);c.ConfirmLabel=c.Confirm.transform.Find("Label").GetComponent<Text>();
        var jobs=I("OrdersPaper",workspace,1180,563,690,455,A+"card-paper.png");I("Heading",jobs.transform,0,-20,272,70,A+"count-paper.png");T("Title",jobs.transform,20,-15,252,64,"예약한 작업",37);c.OrderCount=T("Count",jobs.transform,566,17,90,43,"0건",30);c.OrderCount.alignment=TextAnchor.MiddleRight;c.OrderScroll=Scroll("Orders",jobs.transform,24,74,650,286,634,12,out c.OrderContent);c.EmptyOrders=T("Empty",jobs.transform,42,158,606,110,"아직 등록한 작업이 없습니다.\n담당자와 재료를 확인해 주세요.",31);c.EmptyOrders.alignment=TextAnchor.MiddleCenter;T("Hint",jobs.transform,30,378,630,56,"예약 취소 시 재료를 모두 돌려놓습니다.",27);
        var modal=R("CancelConfirmation",root,0,0,1920,1080);c.CancelPopup=modal.gameObject;var dim=I("Dim",modal,0,0,1920,1080,null);dim.color=new Color(0,0,0,.62f);dim.raycastTarget=true;var paper=I("Paper",modal,585,340,750,405,A+"card-paper.png");T("Title",paper.transform,40,27,670,60,"작업 예약 취소",43);c.CancelMessage=T("Message",paper.transform,40,104,670,188,"",32);c.CancelNo=B("Keep",paper.transform,43,313,304,66,"유지",33);c.CancelYes=B("Cancel",paper.transform,401,313,304,66,"예약 취소",33);c.CancelYes.GetComponent<Image>().color=new Color(1,.66f,.59f);modal.gameObject.SetActive(false);
        var generic=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/icon-supplies.png");c.Materials=new[]{Mat("wood","나무 판자",2,S("wood")),Mat("rope","밧줄",3,S("rope")),Mat("nails","못",0,S("nails")),Mat("scrap","고철",3,generic),Mat("cloth","천 조각",2,generic)};
        c.Recipes=new[]{Recipe("prybar","간이 지렛대","잠긴 틈을 벌릴 때 쓰는\n간단한 도구입니다.",0,30,S("prybar"),Cost("wood",2),Cost("rope",1),Cost("nails",2)),Recipe("nails","간이 못","고철을 다듬어 만드는\n수리용 못입니다.",0,15,S("nails"),Cost("scrap",1)),Recipe("rope","밧줄","천 조각을 엮어\n튼튼한 끈을 만듭니다.",0,20,S("rope"),Cost("cloth",2)),Recipe("repair-bed","침대 수리","헐거운 침대 틀을\n단단하게 고정합니다.",1,45,S("repair"),Cost("wood",2),Cost("nails",2)),Recipe("upgrade-bench","작업대 개선","도구를 펼칠 공간을\n넓히고 보강합니다.",2,90,S("upgrade"),Cost("wood",4),Cost("nails",4),Cost("rope",1))};
        var asset=Save(root.gameObject,"CraftWorkPanel");var screen=PrefabUtility.LoadPrefabContents(P+"SettlementScreen.prefab");try{var old=screen.transform.Find("CraftWorkPanel");if(old)Object.DestroyImmediate(old.gameObject);var go=(GameObject)PrefabUtility.InstantiatePrefab(asset,screen.transform);var owner=screen.GetComponent<SettlementController>();owner.CraftPanel=go.GetComponent<SettlementCraftPanel>();owner.CraftPanel.HideWhileOpen=new[]{screen.transform.Find("Main/Roster").gameObject,screen.transform.Find("Main/ArrivalNotice").gameObject,screen.transform.Find("Main/PreviousRoster").gameObject,screen.transform.Find("Main/NextRoster").gameObject};PrefabUtility.RecordPrefabInstancePropertyModifications(owner.CraftPanel);go.SetActive(false);PrefabUtility.SaveAsPrefabAsset(screen,P+"SettlementScreen.prefab");}finally{PrefabUtility.UnloadPrefabContents(screen);}
        AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Craft UI 06 connected: recipe/category/quantity/worker/cost/queue and nested cancellation; component prefabs saved.";
    }
}
