using System;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class BuildLoot {
 const string P="Assets/Prefabs/Settlement/",A="Assets/Art/PartySelection/";static Font font;
 static RectTransform R(string n,Transform p,float x,float y,float w,float h){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 static Image I(string n,Transform p,float x,float y,float w,float h,string path=null){var im=R(n,p,x,y,w,h).gameObject.AddComponent<Image>();if(path!=null)im.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(path);im.raycastTarget=false;return im;}
 static Text T(string n,Transform p,float x,float y,float w,float h,string s,int size=28,bool light=true){var t=R(n,p,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontStyle=FontStyle.Normal;t.fontSize=size;t.text=s;t.color=light?new Color(.96f,.93f,.85f):new Color(.045f,.065f,.06f);t.alignment=TextAnchor.MiddleLeft;t.raycastTarget=false;return t;}
 static Button B(string n,Transform p,float x,float y,float w,float h,string label,int size=32){var im=I(n,p,x,y,w,h,A+"footer-paper.png");im.raycastTarget=true;var b=im.gameObject.AddComponent<Button>();b.targetGraphic=im;T("Label",im.transform,8,0,w-16,h,label,size,false).alignment=TextAnchor.MiddleCenter;return b;}
 static GameObject Save(GameObject g,string name){var asset=PrefabUtility.SaveAsPrefabAsset(g,P+name+".prefab");Object.DestroyImmediate(g);return asset;}
 static ScrollRect Grid(string name,Transform p,float x,float y,float w,float h,out RectTransform content,int columns){var r=R(name,p,x,y,w,h);r.gameObject.AddComponent<RectMask2D>();r.gameObject.AddComponent<Image>().color=Color.clear;content=R("Content",r,0,0,w-15,h);var grid=content.gameObject.AddComponent<GridLayoutGroup>();grid.cellSize=new Vector2(127,120);grid.spacing=new Vector2(10,12);grid.constraint=GridLayoutGroup.Constraint.FixedColumnCount;grid.constraintCount=columns;var fit=content.gameObject.AddComponent<ContentSizeFitter>();fit.verticalFit=ContentSizeFitter.FitMode.PreferredSize;var sc=r.gameObject.AddComponent<ScrollRect>();sc.viewport=r;sc.content=content;sc.horizontal=false;sc.movementType=ScrollRect.MovementType.Clamped;sc.scrollSensitivity=36;var rail=I("Rail",r,w-7,0,7,h);rail.color=new Color(.7f,.68f,.6f,.2f);var handle=I("Handle",rail.transform,0,0,7,50,A+"footer-paper.png");handle.raycastTarget=true;var sb=rail.gameObject.AddComponent<Scrollbar>();sb.targetGraphic=handle;sb.handleRect=handle.rectTransform;sb.direction=Scrollbar.Direction.BottomToTop;sc.verticalScrollbar=sb;sc.verticalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;var hint=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(P+"ScrollMoreHint.prefab"),r);hint.GetComponent<ScrollMoreIndicator>().Scroll=sc;PrefabUtility.RecordPrefabInstancePropertyModifications(hint.GetComponent<ScrollMoreIndicator>());return sc;}

 public static string Build(){
 if(EditorApplication.isPlaying)throw new Exception("Stop first");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene");
 font=AssetDatabase.LoadAssetAtPath<Font>("Assets/funflow_font/TWD-AS_FUNFLOW SURVIVOR_Font/펀플로 생존자.ttf");
 var root=R("ExpeditionLootPanel",null,0,0,1920,1080);var c=root.gameObject.AddComponent<ExpeditionLootPanel>();c.View=root.gameObject;
 var dim=I("Dim",root,0,0,1920,1080);dim.color=new Color(0,0,0,.70f);dim.raycastTarget=true;var main=R("Workspace",root,0,0,1920,1080);c.Workspace=main.gameObject.AddComponent<CanvasGroup>();
 I("MainPaper",main,70,150,1780,785,A+"card-paper.png").color=new Color(.1f,.14f,.14f);
 I("TitlePaper",main,96,166,620,75,A+"footer-paper.png");c.Title=T("Title",main,116,168,580,71,"발견한 물건",38,false);
 T("Hint",main,770,174,1000,55,"물건을 나누어 담거나 현장에 남겨둘 수 있습니다.",29);
 var vp=R("Members",main,600,252,1200,132);vp.gameObject.AddComponent<RectMask2D>();vp.gameObject.AddComponent<Image>().color=Color.clear;c.Members=R("Content",vp,0,0,1200,126);var layout=c.Members.gameObject.AddComponent<HorizontalLayoutGroup>();layout.spacing=12;layout.childControlWidth=layout.childControlHeight=layout.childForceExpandWidth=layout.childForceExpandHeight=false;c.Members.gameObject.AddComponent<ContentSizeFitter>().horizontalFit=ContentSizeFitter.FitMode.PreferredSize;var scroll=vp.gameObject.AddComponent<ScrollRect>();scroll.viewport=vp;scroll.content=c.Members;scroll.horizontal=true;scroll.vertical=false;scroll.movementType=ScrollRect.MovementType.Clamped;c.MemberPrefab=AssetDatabase.LoadAssetAtPath<ExpeditionMemberCard>(P+"SearchWorkerCard.prefab");
 foreach(var box in new[]{new Vector4(100,410,460,500),new Vector4(580,410,610,500),new Vector4(1210,410,610,500)}){I("Section",main,box.x,box.y,box.z,box.w,A+"card-paper.png").color=new Color(.20f,.24f,.23f);}
 I("FieldHeadingPaper",main,120,426,320,65,A+"footer-paper.png");T("FieldHeading",main,140,426,280,65,"현장 보관함",35,false);
 I("BagHeadingPaper",main,600,426,395,65,A+"footer-paper.png");c.BagTitle=T("BagTitle",main,620,426,355,65,"개인 가방",32,false);c.Capacity=T("Capacity",main,1015,430,150,60,"",31);c.Capacity.alignment=TextAnchor.MiddleRight;
 Grid("FieldItems",main,124,516,424,370,out c.FieldContent,3);Grid("BagItems",main,604,516,565,370,out c.BagContent,4);c.SlotPrefab=AssetDatabase.LoadAssetAtPath<InventorySlot>(P+"InventorySlot.prefab");c.Empty=T("Empty",main,145,625,355,110,"남은 물건이 없습니다.",30);c.Empty.alignment=TextAnchor.MiddleCenter;
 I("DetailTitlePaper",main,1234,426,350,65,A+"footer-paper.png");c.DetailTitle=T("DetailTitle",main,1254,426,310,65,"물건 선택",35,false);c.DetailIcon=I("DetailIcon",main,1250,514,126,142);c.DetailIcon.preserveAspect=true;c.Description=T("Description",main,1400,514,390,135,"",28);
 T("QuantityHeading",main,1238,665,270,38,"옮길 수량",29);c.Minus=B("Minus",main,1238,710,70,58,"−",40);c.Quantity=T("Quantity",main,1320,710,110,58,"1",34);c.Quantity.alignment=TextAnchor.MiddleCenter;c.Plus=B("Plus",main,1442,710,70,58,"+",40);c.Max=B("Max",main,1530,710,125,58,"최대",28);
 c.Message=T("Message",main,1238,788,560,78,"",28);c.Transfer=B("Transfer",main,1310,952,410,78,"선택 가져오기",32);c.Transfer.GetComponent<Image>().color=new Color(.76f,.86f,.68f);c.Back=B("Back",main,80,952,410,78,"돌아가기",34);
 var modal=R("LeaveLootReview",null,0,0,1920,1080);var md=I("Dim",modal,0,0,1920,1080);md.color=new Color(0,0,0,.72f);md.raycastTarget=true;I("Paper",modal,460,250,1000,550,A+"card-paper.png");T("Title",modal,510,285,900,70,"남은 물건을 두고 나갈까요?",40,false);T("Body",modal,510,380,900,230,"",31,false);B("Cancel",modal,510,680,410,78,"계속 정리");B("Confirm",modal,1000,680,410,78,"두고 나가기");var ma=Save(modal.gameObject,"LeaveLootReview");var mg=(GameObject)PrefabUtility.InstantiatePrefab(ma,root);c.LeaveReview=mg;c.LeaveBody=mg.transform.Find("Body").GetComponent<Text>();c.LeaveCancel=mg.transform.Find("Cancel").GetComponent<Button>();c.LeaveConfirm=mg.transform.Find("Confirm").GetComponent<Button>();mg.SetActive(false);
 c.Sites=new[]{new ExpeditionLootPanel.Site{Drops=new[]{D("supplies",2,85),D("scrap",3,70),D("cloth",2,65),D("rope",1,45)}},new ExpeditionLootPanel.Site{Drops=new[]{D("cloth",2,75),D("nails",3,60)}},new ExpeditionLootPanel.Site{RequiredTool="prybar",Drops=new[]{D("scrap",3,85),D("ammo",2,30)}}};
 var asset=Save(root.gameObject,"ExpeditionLootPanel");var a=PrefabUtility.LoadPrefabContents(P+"ExpeditionArrivalPanel.prefab");try{var old=a.transform.Find("ExpeditionLootPanel");if(old)Object.DestroyImmediate(old.gameObject);var go=(GameObject)PrefabUtility.InstantiatePrefab(asset,a.transform);var panel=a.GetComponent<ExpeditionArrivalPanel>();panel.Loot=go.GetComponent<ExpeditionLootPanel>();go.SetActive(false);panel.Fade.transform.SetAsLastSibling();PrefabUtility.SaveAsPrefabAsset(a,P+"ExpeditionArrivalPanel.prefab");}finally{PrefabUtility.UnloadPrefabContents(a);}
 EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");AssetDatabase.SaveAssets();return "Loot screen, scrollable field/bag grids, quantity and leave confirmation saved.";
 }
 static ExpeditionLootPanel.Drop D(string id,int n,int chance)=>new ExpeditionLootPanel.Drop{Id=id,Count=n,Chance=chance};
}
