using System;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class BuildSettlementInventory {
 const string P="Assets/Prefabs/Settlement/",A="Assets/Art/PartySelection/",IPath="Assets/Art/Inventory/"; static Font font;
 static RectTransform R(string n,Transform p,float x,float y,float w,float h){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 static Image I(string n,Transform p,float x,float y,float w,float h,string path=null){var im=R(n,p,x,y,w,h).gameObject.AddComponent<Image>();if(path!=null)im.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(path);im.raycastTarget=false;return im;}
 static Text T(string n,Transform p,float x,float y,float w,float h,string v,int size=30,bool light=false){var t=R(n,p,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontStyle=FontStyle.Bold;t.fontSize=size;t.text=v;t.color=light?new Color(.96f,.93f,.85f):new Color(.045f,.065f,.06f);t.raycastTarget=false;t.alignment=TextAnchor.MiddleLeft;return t;}
 static Button B(string n,Transform p,float x,float y,float w,float h,string label,int size=32){var im=I(n,p,x,y,w,h,A+"footer-paper.png");im.raycastTarget=true;var b=im.gameObject.AddComponent<Button>();b.targetGraphic=im;T("Label",im.transform,6,0,w-12,h,label,size).alignment=TextAnchor.MiddleCenter;return b;}
 static GameObject Save(GameObject g,string n){var asset=PrefabUtility.SaveAsPrefabAsset(g,P+n+".prefab");Object.DestroyImmediate(g);return asset;}
 static InventorySlot Slot(string name,float w,float h,bool member){var im=I(name,null,0,0,w,h,A+"card-paper.png");im.raycastTarget=true;var c=im.gameObject.AddComponent<InventorySlot>();c.Paper=im;c.Button=im.gameObject.AddComponent<Button>();c.Button.targetGraphic=im;c.Icon=I("Icon",im.transform,member?42:28,10,member?90:77,member?88:69);c.Icon.preserveAspect=true;c.Label=T("Name",im.transform,6,member?103:83,w-12,member?37:30,"",member?30:24);c.Label.alignment=TextAnchor.MiddleCenter;c.Count=T("Count",im.transform,w-45,55,37,33,"",26);c.Count.alignment=TextAnchor.MiddleRight;c.Selection=im.gameObject.AddComponent<Outline>();c.Selection.effectColor=new Color(1,.75f,.22f);c.Selection.effectDistance=new Vector2(3,-3);c.Selection.enabled=false;return c;}
 static ScrollRect Grid(string name,Transform p,float x,float y,float w,float h,out RectTransform content){var r=R(name,p,x,y,w,h);r.gameObject.AddComponent<RectMask2D>();r.gameObject.AddComponent<Image>().color=Color.clear;content=R("Content",r,0,0,w-15,h);var grid=content.gameObject.AddComponent<GridLayoutGroup>();grid.cellSize=new Vector2(127,120);grid.spacing=new Vector2(10,12);grid.constraint=GridLayoutGroup.Constraint.FixedColumnCount;grid.constraintCount=4;var fit=content.gameObject.AddComponent<ContentSizeFitter>();fit.verticalFit=ContentSizeFitter.FitMode.PreferredSize;var sc=r.gameObject.AddComponent<ScrollRect>();sc.viewport=r;sc.content=content;sc.horizontal=false;sc.movementType=ScrollRect.MovementType.Clamped;sc.scrollSensitivity=36;var rail=I("Rail",r,w-7,0,7,h);rail.color=new Color(.7f,.68f,.6f,.2f);var handle=I("Handle",rail.transform,0,0,7,50,A+"footer-paper.png");handle.raycastTarget=true;var sb=rail.gameObject.AddComponent<Scrollbar>();sb.targetGraphic=handle;sb.handleRect=handle.rectTransform;sb.direction=Scrollbar.Direction.BottomToTop;sc.verticalScrollbar=sb;sc.verticalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;var hint=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(P+"ScrollMoreHint.prefab"),r);hint.GetComponent<ScrollMoreIndicator>().Scroll=sc;PrefabUtility.RecordPrefabInstancePropertyModifications(hint.GetComponent<ScrollMoreIndicator>());return sc;}
 static void Panel(string name,Transform p,float x,float y,float w,float h){var im=I(name,p,x,y,w,h,A+"card-paper.png");im.color=new Color(.11f,.14f,.15f,.97f);var edge=im.gameObject.AddComponent<Outline>();edge.effectColor=new Color(.57f,.57f,.49f,.5f);edge.effectDistance=new Vector2(1,-1);}
 static void Heading(string n,Transform p,float x,float y,float w,string label,string icon){I(n+"Paper",p,x,y,w,76,A+"count-paper.png");if(icon!=null)I(n+"Icon",p,x+17,y+13,48,48,icon).preserveAspect=true;T(n,p,x+(icon!=null?81:18),y+6,w-(icon!=null?90:30),63,label,36);}
 static SettlementInventoryPanel.Item Item(string id,string name,string description,int category,string icon)=>new SettlementInventoryPanel.Item{Id=id,Name=name,Description=description,Category=category,Icon=AssetDatabase.LoadAssetAtPath<Sprite>(icon)};
 public static string Build(){
  if(EditorApplication.isPlaying)throw new Exception("Stop Play first");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene changes");font=AssetDatabase.LoadAssetAtPath<Font>("Assets/Art/FrontEnd/Fonts/Gaegu/Gaegu-Bold.ttf");AssetDatabase.Refresh();foreach(var file in Directory.GetFiles(IPath,"*.png")){var imp=(TextureImporter)AssetImporter.GetAtPath(file.Replace('\\','/'));imp.textureType=TextureImporterType.Sprite;imp.spriteImportMode=SpriteImportMode.Single;imp.alphaIsTransparency=true;imp.mipmapEnabled=false;imp.textureCompression=TextureImporterCompression.Uncompressed;imp.SaveAndReimport();}
  var slot=Slot("InventorySlot",127,120,false);var slotAsset=Save(slot.gameObject,"InventorySlot");var card=Slot("InventoryMemberCard",175,145,true);var cardAsset=Save(card.gameObject,"InventoryMemberCard");
  var root=R("InventoryPanel",null,0,0,1920,1080);var c=root.gameObject.AddComponent<SettlementInventoryPanel>();c.View=root.gameObject;c.HideWhileOpen=new GameObject[0];c.SlotPrefab=slotAsset.GetComponent<InventorySlot>();var blocker=I("InputBlocker",root,0,0,1920,1080);blocker.color=new Color(0,0,0,.2f);blocker.raycastTarget=true;var ws=R("Workspace",root,0,0,1920,1080);c.Workspace=ws.gameObject.AddComponent<CanvasGroup>();
  c.CloseButton=B("Close",ws,1802,27,86,65,"×",56);c.MemberCards=new InventorySlot[6];for(int i=0;i<6;i++){var obj=(GameObject)PrefabUtility.InstantiatePrefab(cardAsset,ws);obj.name="Member_"+i;((RectTransform)obj.transform).anchoredPosition=new Vector2(386+i*198,-76);c.MemberCards[i]=obj.GetComponent<InventorySlot>();}c.PrevMember=B("PreviousMember",ws,299,113,73,72,"‹",55);c.NextMember=B("NextMember",ws,1570,113,73,72,"›",55);
  Panel("StockPanel",ws,97,245,633,714);Panel("BagPanel",ws,825,245,603,714);Panel("DetailPanel",ws,1440,257,422,702);
  Heading("StockTitle",ws,116,262,315,"공용 창고","Assets/Art/Settlement/icon-storage.png");c.Tabs=new Button[4];string[] tabs={"전체","식량","도구","재료"};for(int i=0;i<4;i++)c.Tabs[i]=B("Tab_"+i,ws,130+i*143,356,135,56,tabs[i],30);
  c.StockScroll=Grid("StockItems",ws,128,432,573,491,out c.StockContent);c.EmptyStock=T("EmptyStock",ws,145,581,529,100,"옮길 수 있는 물자가 없습니다.",29,true);c.EmptyStock.alignment=TextAnchor.MiddleCenter;
  I("BagHeadingPaper",ws,851,277,394,78,A+"count-paper.png");I("BagIcon",ws,867,292,50,48,IPath+"bag.png").preserveAspect=true;c.BagTitle=T("BagTitle",ws,933,282,299,68,"개인 가방",30);c.Capacity=T("Capacity",ws,1252,289,153,54,"",28,true);c.Capacity.alignment=TextAnchor.MiddleRight;c.BagScroll=Grid("BagItems",ws,859,398,548,480,out c.BagContent);
  c.ToBag=B("ToBag",ws,744,548,72,66,"→",48);c.ToStock=B("ToStock",ws,744,633,72,66,"←",48);
  Heading("ToolTitle",ws,1463,281,364,"손 도구 가방",IPath+"flashlight.png");for(int i=0;i<2;i++){var im=I("ToolSlot_"+i,ws,1470+i*184,389,168,155,A+"card-paper.png");im.color=new Color(.32f,.35f,.34f,.68f);T("Empty",im.transform,9,42,150,62,"—",44,true).alignment=TextAnchor.MiddleCenter;T("Label",ws,1470+i*184,551,168,44,"미장착",27,true).alignment=TextAnchor.MiddleCenter;}
  I("DetailTitlePaper",ws,1469,626,356,58,A+"count-paper.png");c.DetailTitle=T("DetailTitle",ws,1485,630,330,50,"물건 선택",32);c.DetailIcon=I("DetailIcon",ws,1477,704,75,86);c.DetailIcon.preserveAspect=true;c.Description=T("Description",ws,1565,701,271,107,"",26,true);c.Location=T("Source",ws,1474,802,364,38,"",25,true);
  var use=B("Use",ws,1469,849,142,79,"사용",32);use.interactable=false;c.Move=B("Move",ws,1625,849,211,79,"가방에 넣기",28);
  I("NoticePaper",ws,751,977,700,68,A+"count-paper.png").color=new Color(.75f,.89f,.76f);c.Notice=T("Notice",ws,775,984,650,52,"거점에서만 창고와 이동 가능.",29);c.Notice.alignment=TextAnchor.MiddleCenter;
  var modal=R("QuantityPopup",root,0,0,1920,1080);c.QuantityPopup=modal.gameObject;var dim=I("Dim",modal,0,0,1920,1080);dim.color=new Color(0,0,0,.65f);dim.raycastTarget=true;I("Paper",modal,590,335,740,410,A+"card-paper.png");c.QuantityTitle=T("Title",modal,630,354,660,65,"옮기기",40);c.QuantityHint=T("Hint",modal,630,429,660,87,"",29);c.Minus=B("Minus",modal,760,530,66,58,"−",38);c.QuantityValue=T("Quantity",modal,840,530,155,58,"1",38);c.QuantityValue.alignment=TextAnchor.MiddleCenter;c.Plus=B("Plus",modal,1010,530,66,58,"+",38);c.Max=B("Max",modal,1120,530,135,58,"최대",29);c.Cancel=B("Cancel",modal,632,635,302,75,"취소",33);c.Confirm=B("Confirm",modal,984,635,302,75,"옮기기",33);modal.gameObject.SetActive(false);
  string craft="Assets/Art/CraftWorkPanel/";c.Items=new[]{Item("supplies","보급품","동료들의 생활에 쓰는\n공용 보급 물자입니다.",1,"Assets/Art/HomeSelection/icon-supplies.png"),Item("ammo","탄약","외부 원정에 대비해\n챙겨 두는 탄약입니다.",2,"Assets/Art/HomeSelection/icon-ammo.png"),Item("wood","나무 판자","시설 수리와 도구\n제작에 쓰는 재료입니다.",3,craft+"wood.png"),Item("rope","밧줄","물건을 묶거나\n수리에 쓰는 끈입니다.",3,craft+"rope.png"),Item("nails","못","나무와 부품을\n고정하는 재료입니다.",3,craft+"nails.png"),Item("scrap","고철","못이나 작은 부품을\n만들 수 있습니다.",3,IPath+"scrap.png"),Item("cloth","천 조각","엮어서 끈을 만들 수\n있는 천 조각입니다.",3,IPath+"cloth.png")};
  var asset=Save(root.gameObject,"InventoryPanel");var screen=PrefabUtility.LoadPrefabContents(P+"SettlementScreen.prefab");try{var old=screen.transform.Find("InventoryPanel");if(old)Object.DestroyImmediate(old.gameObject);var obj=(GameObject)PrefabUtility.InstantiatePrefab(asset,screen.transform);var owner=screen.GetComponent<SettlementController>();owner.InventoryPanel=obj.GetComponent<SettlementInventoryPanel>();owner.InventoryPanel.HideWhileOpen=new[]{screen.transform.Find("Main/Roster").gameObject,screen.transform.Find("Main/ArrivalNotice").gameObject,screen.transform.Find("Main/PreviousRoster").gameObject,screen.transform.Find("Main/NextRoster").gameObject,owner.Advance.gameObject,owner.Journal.gameObject,screen.transform.Find("Main/ResourceHud").gameObject};PrefabUtility.RecordPrefabInstancePropertyModifications(owner.InventoryPanel);obj.SetActive(false);PrefabUtility.SaveAsPrefabAsset(screen,P+"SettlementScreen.prefab");}finally{PrefabUtility.UnloadPrefabContents(screen);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Inventory screen and reusable slot/member prefabs saved; approved UI01 layout connected.";
 }
}
