using System;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class BuildExpeditionPlan {
 const string P="Assets/Prefabs/Settlement/",A="Assets/Art/PartySelection/",E="Assets/Art/ExpeditionPlan/";static Font font;
 static RectTransform R(string n,Transform p,float x,float y,float w,float h){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 static Image I(string n,Transform p,float x,float y,float w,float h,string path=null){var im=R(n,p,x,y,w,h).gameObject.AddComponent<Image>();if(path!=null)im.sprite=AssetDatabase.LoadAssetAtPath<Sprite>(path);im.raycastTarget=false;return im;}
 static Text T(string n,Transform p,float x,float y,float w,float h,string s,int size=30,bool light=false){var t=R(n,p,x,y,w,h).gameObject.AddComponent<Text>();t.font=font;t.fontStyle=FontStyle.Normal;t.fontSize=size;t.text=s;t.color=light?new Color(.96f,.93f,.85f):new Color(.045f,.065f,.06f);t.alignment=TextAnchor.MiddleLeft;t.raycastTarget=false;return t;}
 static Button B(string n,Transform p,float x,float y,float w,float h,string label,int size=32){var im=I(n,p,x,y,w,h,A+"footer-paper.png");im.raycastTarget=true;var b=im.gameObject.AddComponent<Button>();b.targetGraphic=im;T("Label",im.transform,6,0,w-12,h,label,size).alignment=TextAnchor.MiddleCenter;return b;}
 static GameObject Save(GameObject g,string name){var asset=PrefabUtility.SaveAsPrefabAsset(g,P+name+".prefab");Object.DestroyImmediate(g);return asset;}
 static Sprite S(string name)=>AssetDatabase.LoadAssetAtPath<Sprite>(E+name+".png");
 public static string Build(){
  if(EditorApplication.isPlaying)throw new Exception("Stop Play first");for(int i=0;i<UnityEngine.SceneManagement.SceneManager.sceneCount;i++)if(UnityEngine.SceneManagement.SceneManager.GetSceneAt(i).isDirty)throw new Exception("Unsaved scene changes");font=AssetDatabase.LoadAssetAtPath<Font>("Assets/funflow_font/TWD-AS_FUNFLOW SURVIVOR_Font/펀플로 생존자.ttf");AssetDatabase.Refresh();foreach(var file in Directory.GetFiles(E,"*.png")){var imp=(TextureImporter)AssetImporter.GetAtPath(file.Replace('\\','/'));imp.textureType=TextureImporterType.Sprite;imp.spriteImportMode=SpriteImportMode.Single;imp.alphaIsTransparency=true;imp.mipmapEnabled=false;imp.maxTextureSize=4096;imp.textureCompression=TextureImporterCompression.Uncompressed;imp.SaveAndReimport();}
  var row=I("ExpeditionMemberCard",null,0,0,272,172,A+"card-paper.png");row.raycastTarget=true;var card=row.gameObject.AddComponent<ExpeditionMemberCard>();card.Paper=row;card.Button=row.gameObject.AddComponent<Button>();card.Button.targetGraphic=row;card.Portrait=I("Portrait",row.transform,12,14,89,103);card.Portrait.preserveAspect=true;card.Name=T("Name",row.transform,112,7,148,40,"동료",29);card.Role=T("Role",row.transform,112,45,148,33,"",21);var track=I("HealthTrack",row.transform,112,82,140,13);track.color=new Color(.1f,.15f,.15f);card.HealthFill=I("HealthFill",track.transform,1,1,138,11,A+"count-paper.png");card.HealthFill.color=new Color(.43f,.7f,.45f);card.HealthFill.type=Image.Type.Filled;card.HealthFill.fillMethod=Image.FillMethod.Horizontal;card.Health=T("HealthText",row.transform,112,96,148,26,"",22);I("StatePaper",row.transform,12,131,248,32,A+"footer-paper.png").color=new Color(.78f,.8f,.73f);card.State=T("State",row.transform,48,131,203,32,"참여 선택",25);card.State.alignment=TextAnchor.MiddleCenter;card.Check=I("Check",row.transform,22,135,24,24,A+"selected-check.png");var memberPrefab=Save(row.gameObject,"ExpeditionMemberCard");
  var marker=R("ExpeditionMapMarker",null,0,0,134,139);var hit=marker.gameObject.AddComponent<Image>();hit.color=Color.clear;var markerButton=marker.gameObject.AddComponent<Button>();markerButton.targetGraphic=hit;var pin=R("Pin",marker,25,0,84,104).gameObject.AddComponent<MapPinGraphic>();pin.color=new Color(.88f,.84f,.73f);pin.raycastTarget=false;var outline=pin.gameObject.AddComponent<Outline>();outline.effectColor=new Color(.06f,.09f,.09f);outline.effectDistance=new Vector2(3,-3);I("PlaceIcon",marker,49,25,38,42).preserveAspect=true;I("NamePaper",marker,0,101,134,38,A+"count-paper.png");T("Name",marker,5,101,124,38,"장소",27).alignment=TextAnchor.MiddleCenter;var markerPrefab=Save(marker.gameObject,"ExpeditionMapMarker");
  var root=R("ExpeditionPlanPanel",null,0,0,1920,1080);var c=root.gameObject.AddComponent<ExpeditionPlanPanel>();c.View=root.gameObject;c.HideWhileOpen=new GameObject[0];c.MemberPrefab=memberPrefab.GetComponent<ExpeditionMemberCard>();c.MaximumParty=6;
  var background=I("Background",root,0,0,1920,1080,A+"teal-texture.png");background.raycastTarget=true;background.color=new Color(.74f,.79f,.8f);I("HeadingPaper",root,80,44,360,116,A+"card-paper.png");T("Title",root,109,52,310,64,"원정 계획",49);T("Subtitle",root,110,111,310,40,"어디로 향할까요?",28);I("DatePaper",root,1650,55,190,90,A+"count-paper.png");c.Clock=T("Clock",root,1673,61,145,78,"DAY 1\n09:00",29);
  var map=I("Map",root,80,166,1100,474,E+"map-clean.png");c.Markers=new Button[4];c.PinFills=new Graphic[4];c.MarkerPapers=new Image[4];string[] names={"거점","폐상가","편의점","창고"},icons={"pin-home","pin-mall","pin-store","pin-warehouse"};Vector2[] points={new Vector2(128,125),new Vector2(436,55),new Vector2(794,135),new Vector2(526,276)};
  for(int i=0;i<4;i++){var go=(GameObject)PrefabUtility.InstantiatePrefab(markerPrefab,map.transform);go.name="Marker_"+i;((RectTransform)go.transform).anchoredPosition=new Vector2(points[i].x,-points[i].y);go.transform.Find("PlaceIcon").GetComponent<Image>().sprite=S(icons[i]);go.transform.Find("Name").GetComponent<Text>().text=names[i];c.Markers[i]=go.GetComponent<Button>();c.PinFills[i]=go.transform.Find("Pin").GetComponent<MapPinGraphic>();c.MarkerPapers[i]=go.transform.Find("NamePaper").GetComponent<Image>();}
  I("DetailsPaper",root,1200,166,640,474,A+"card-paper.png");I("PlaceTitlePaper",root,1220,177,236,70,A+"count-paper.png");c.PlaceName=T("PlaceName",root,1241,183,194,59,"폐상가",43);I("PhotoPaper",root,1220,254,236,313,A+"footer-paper.png");c.Picture=I("Picture",root,1227,260,220,300);c.Picture.preserveAspect=true;c.Description=T("Description",root,1227,571,220,46,"",23);c.Description.alignment=TextAnchor.MiddleCenter;
  I("TravelIcon",root,1475,213,32,32,E+"clock.png").preserveAspect=true;c.Travel=T("Travel",root,1520,207,295,47,"",25);I("RiskIcon",root,1475,264,32,32,E+"risk.png").preserveAspect=true;c.Risk=T("Risk",root,1520,258,295,47,"",29);I("Rule",root,1475,318,338,2).color=new Color(.12f,.16f,.14f,.3f);T("ResourcesLabel",root,1475,329,338,42,"주요 자원",28);c.ResourceImages=new[]{I("Resource_0",root,1527,374,65,71),I("Resource_1",root,1696,374,65,71)};foreach(var icon in c.ResourceImages)icon.preserveAspect=true;c.Resources=T("Resources",root,1475,450,338,38,"",27);c.Resources.alignment=TextAnchor.MiddleCenter;c.ResourceNames=new[]{T("ResourceName_0",root,1475,450,169,38,"",27),T("ResourceName_1",root,1644,450,169,38,"",27)};foreach(var label in c.ResourceNames)label.alignment=TextAnchor.MiddleCenter;I("Rule2",root,1475,501,338,2).color=new Color(.12f,.16f,.14f,.3f);T("UnknownLabel",root,1475,510,338,40,"알려지지 않은 위험",27);c.Unknown=T("Unknown",root,1475,553,338,64,"",25);
  var band=I("MemberBand",root,80,660,1760,250,A+"card-paper.png");band.color=new Color(.11f,.14f,.15f,.97f);I("MemberHeading",root,104,667,235,43,A+"count-paper.png");T("MemberTitle",root,120,667,208,43,"생존자 목록",31);c.Hint=T("Hint",root,365,667,1427,43,"원정에 참여할 대원을 선택하세요.",26,true);
  var viewport=R("Members",root,104,716,1712,181);viewport.gameObject.AddComponent<RectMask2D>();viewport.gameObject.AddComponent<Image>().color=Color.clear;c.MemberContent=R("Content",viewport,0,0,1712,172);var layout=c.MemberContent.gameObject.AddComponent<HorizontalLayoutGroup>();layout.spacing=12;layout.childControlWidth=false;layout.childControlHeight=false;layout.childForceExpandWidth=false;layout.childForceExpandHeight=false;var fit=c.MemberContent.gameObject.AddComponent<ContentSizeFitter>();fit.horizontalFit=ContentSizeFitter.FitMode.PreferredSize;c.MemberScroll=viewport.gameObject.AddComponent<ScrollRect>();c.MemberScroll.viewport=viewport;c.MemberScroll.content=c.MemberContent;c.MemberScroll.horizontal=true;c.MemberScroll.vertical=false;c.MemberScroll.scrollSensitivity=40;c.MemberScroll.movementType=ScrollRect.MovementType.Clamped;var rail=I("Rail",viewport,0,174,1712,7);rail.color=new Color(.7f,.68f,.6f,.2f);var handle=I("Handle",rail.transform,0,0,100,7,A+"footer-paper.png");handle.raycastTarget=true;var sb=rail.gameObject.AddComponent<Scrollbar>();sb.targetGraphic=handle;sb.handleRect=handle.rectTransform;sb.direction=Scrollbar.Direction.LeftToRight;c.MemberScroll.horizontalScrollbar=sb;c.MemberScroll.horizontalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;
  c.Back=B("Back",root,80,952,410,78,"돌아가기",34);I("Icon",c.Back.transform,22,22,26,34,A+"icon-left.png").preserveAspect=true;var bLabel=(RectTransform)c.Back.transform.Find("Label");bLabel.anchoredPosition=new Vector2(65,0);bLabel.sizeDelta=new Vector2(290,78);
  I("SelectionPaper",root,514,952,892,78,A+"card-paper.png").color=new Color(.11f,.14f,.15f,.97f);c.Selection=T("Selection",root,536,960,848,62,"선택한 대원 없음",27,true);c.Selection.alignment=TextAnchor.MiddleCenter;c.Pack=B("Pack",root,1430,952,410,78,"짐 꾸리기",37);c.Pack.GetComponent<Image>().color=new Color(.76f,.86f,.68f);c.PackLabel=c.Pack.transform.Find("Label").GetComponent<Text>();
  c.HomePictures=new[]{AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/garage.png"),AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/house.png"),AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/clinic.png")};c.Destinations=new[]{new ExpeditionPlanPanel.Destination{Id="home",Name="거점",IsHome=true,OneWayMinutes=0,Risk="안전",Resources="공용 물자",ResourceLabels=new[]{"공용 물자"},Description="돌아와 쉴 수 있는 곳",Unknown="동료들이 머무는 거점입니다.",Picture=AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/garage.png"),ResourceIcons=new[]{AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/icon-supplies.png")}},new ExpeditionPlanPanel.Destination{Id="mall",Name="폐상가",OneWayMinutes=20,Risk="보통",Resources="물 / 부품",ResourceLabels=new[]{"물","부품"},Description="비어 있는 상가 건물",Unknown="무엇이 기다리고 있을까요?",Picture=S("mall-photo"),ResourceIcons=new[]{S("water"),S("parts")}},new ExpeditionPlanPanel.Destination{Id="store",Name="편의점",OneWayMinutes=10,Risk="낮음",Resources="식량 / 생활용품",ResourceLabels=new[]{"식량","생활용품"},Description="외관은 아직 미확인",Unknown="남아 있는 물자는 현장에서\n확인할 수 있습니다.",Picture=S("pin-store"),ResourceIcons=new[]{AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Art/HomeSelection/icon-supplies.png"),S("parts")}},new ExpeditionPlanPanel.Destination{Id="warehouse",Name="창고",Accessible=false,OneWayMinutes=0,Risk="미확인",Resources="정보 없음",Description="아직 경로가 없는 장소",Unknown="주변에서 경로를 찾아야 합니다.",Picture=S("pin-warehouse"),ResourceIcons=new Sprite[0]}};
  var asset=Save(root.gameObject,"ExpeditionPlanPanel");var screen=PrefabUtility.LoadPrefabContents(P+"SettlementScreen.prefab");try{var old=screen.transform.Find("ExpeditionPlanPanel");if(old)Object.DestroyImmediate(old.gameObject);var obj=(GameObject)PrefabUtility.InstantiatePrefab(asset,screen.transform);var owner=screen.GetComponent<SettlementController>();owner.ExpeditionPanel=obj.GetComponent<ExpeditionPlanPanel>();owner.ExpeditionPanel.HideWhileOpen=new[]{owner.Main.gameObject};PrefabUtility.RecordPrefabInstancePropertyModifications(owner.ExpeditionPanel);obj.SetActive(false);PrefabUtility.SaveAsPrefabAsset(screen,P+"SettlementScreen.prefab");}finally{PrefabUtility.UnloadPrefabContents(screen);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "UI02 expedition map + party selection and reusable cards/markers saved.";
 }
}
