using System.Linq;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using Demo5.FrontEnd;
public static class InstallPaintedFacilities {
 static Material material;
 static Sprite Import(string path){AssetDatabase.ImportAsset(path,ImportAssetOptions.ForceUpdate);var t=(TextureImporter)AssetImporter.GetAtPath(path);t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.spritePixelsPerUnit=100;t.alphaIsTransparency=true;t.isReadable=true;t.mipmapEnabled=false;t.textureCompression=TextureImporterCompression.Uncompressed;t.maxTextureSize=2048;var settings=new TextureImporterSettings();t.ReadTextureSettings(settings);settings.spriteMeshType=SpriteMeshType.FullRect;t.SetTextureSettings(settings);t.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Sprite>(path);}
 static SpriteRenderer Artwork(GameObject group,Sprite sprite,float x,float y,float width){var old=group.transform.Find("PaintedArtwork");if(old)Object.DestroyImmediate(old.gameObject);foreach(var r in group.GetComponentsInChildren<Renderer>(true))r.enabled=false;var g=new GameObject("PaintedArtwork",typeof(SpriteRenderer));g.transform.SetParent(group.transform,false);var sr=g.GetComponent<SpriteRenderer>();sr.sprite=sprite;sr.sharedMaterial=material;sr.sortingOrder=50;sr.color=new Color(.62f,.65f,.66f,1);g.transform.position=new Vector3((x-960)/100,(540-y)/100,0);float scale=width/100/sprite.bounds.size.x;g.transform.localScale=Vector3.one*scale;return sr;}
 static void Bounds(Button b,float x,float y,float width,Sprite s){float h=width*s.rect.height/s.rect.width;var r=(RectTransform)b.transform;r.anchoredPosition=new Vector2(x-width/2,-y+h/2);r.sizeDelta=new Vector2(width,h);}
 public static string Run(){var crate=Import("Assets/Art/Settlement/FacilitiesV2/storage-crates-v4.png");var desk=Import("Assets/Art/Settlement/FacilitiesV2/research-desk-v4.png");const string mp="Assets/Settings/FacilityPaintedSprite.mat";material=AssetDatabase.LoadAssetAtPath<Material>(mp);if(!material){material=new Material(Shader.Find("Demo5/FacilityPaintedSprite"));AssetDatabase.CreateAsset(material,mp);}const string wp="Assets/Prefabs/Settlement/SettlementWorld.prefab";var root=PrefabUtility.LoadPrefabContents(wp);try{var w=root.GetComponentInChildren<SettlementDevelopmentWorld>(true);w.StockArtwork=Artwork(w.StorageCrates,crate,838,756,244);w.ResearchArtwork=Artwork(w.ResearchTable,desk,1124,707,254);foreach(var r in w.WarehouseUpgrade.GetComponentsInChildren<Renderer>(true)){r.enabled=false;r.sortingOrder=60;}var group=w.WarehouseUpgrade.GetComponent<UnityEngine.Rendering.SortingGroup>();if(group)group.sortingOrder=60;PrefabUtility.SaveAsPrefabAsset(root,wp);}finally{PrefabUtility.UnloadPrefabContents(root);}const string sp="Assets/Prefabs/Settlement/SettlementScreen.prefab";root=PrefabUtility.LoadPrefabContents(sp);try{foreach(var focus in root.GetComponentsInChildren<SettlementFacilityFocus>(true))focus.IdleOpacity=0f;var c=root.GetComponent<SettlementController>();Bounds(c.Cabinet,838,756,244,crate);Bounds(c.Development.ResearchButton,1124,707,254,desk);var f=c.Cabinet.GetComponent<SettlementFacilityFocus>();var r=(RectTransform)c.Cabinet.transform;float left=r.anchoredPosition.x,top=-r.anchoredPosition.y;f.UnrestoredPaths=new[]{new SettlementFacilityFocus.Path{Points=new[]{new Vector2(730-left,806-top),new Vector2(922-left,806-top),new Vector2(939-left,760-top),new Vector2(756-left,760-top)}}};PrefabUtility.SaveAsPrefabAsset(root,sp);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();EditorSceneManager.OpenScene("Assets/Scenes/Settlement.unity");return "Painted source sprites installed with alpha outline shader and alpha hit tests. Geometry retained disabled as fallback.";}
}


