using System;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class PolishWorkScrolling
{
 static void Rect(Component c,float x,float y,float w,float h){var r=(RectTransform)c.transform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);}
 static RectTransform New(string name,Transform parent){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);return r;}
 static Button Arrow(Transform parent,string name,float x,float y,bool up){var old=parent.Find(name);if(old)Object.DestroyImmediate(old.gameObject);var r=New(name,parent);Rect(r,x,y,24,28);var im=r.gameObject.AddComponent<Image>();im.color=new Color(.09f,.12f,.13f);var b=r.gameObject.AddComponent<Button>();b.targetGraphic=im;var colors=b.colors;colors.highlightedColor=new Color(1,.82f,.43f);colors.pressedColor=new Color(.75f,.55f,.18f);colors.disabledColor=new Color(.55f,.55f,.55f,.7f);b.colors=colors;var ar=New("Arrow",r);Rect(ar,4,7,16,14);var shape=ar.gameObject.AddComponent<RoundedDownArrow>();shape.color=new Color(1,.8f,.32f);shape.raycastTarget=false;if(up){ar.pivot=new Vector2(.5f,.5f);ar.anchoredPosition=new Vector2(12,-14);ar.localRotation=Quaternion.Euler(0,0,180);}return b;}
 static void Polish(ScrollRect s){
  var root=(RectTransform)s.transform;var pos=root.anchoredPosition;float width=s.content.rect.width,height=root.rect.height;if(s.name=="Workers")height=199;if(s.name=="RecipeViewport"){width=324;s.content.sizeDelta=new Vector2(width,s.content.sizeDelta.y);}
  foreach(var hint in s.GetComponentsInChildren<ScrollMoreIndicator>(true))Object.DestroyImmediate(hint.gameObject);
  foreach(var mask in s.GetComponents<RectMask2D>())Object.DestroyImmediate(mask);
  var viewport=root.Find("ContentWindow") as RectTransform;if(!viewport){viewport=New("ContentWindow",root);viewport.gameObject.AddComponent<RectMask2D>();var hit=viewport.gameObject.AddComponent<Image>();hit.color=Color.clear;}
  Rect(viewport,0,0,width,height);s.content.SetParent(viewport,false);s.content.anchoredPosition=Vector2.zero;s.viewport=viewport;root.sizeDelta=new Vector2(width+30,height);root.anchoredPosition=pos;
  var bar=s.verticalScrollbar;bar.transform.SetParent(root,false);Rect(bar,width+7,34,16,height-68);var track=bar.GetComponent<Image>();track.sprite=null;track.color=new Color(.045f,.06f,.07f,.95f);var handle=bar.targetGraphic as Image;handle.sprite=null;handle.color=new Color(.95f,.68f,.22f);var hr=bar.handleRect;hr.sizeDelta=new Vector2(0,0);var colors=bar.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1,1,.7f);colors.pressedColor=new Color(1,.8f,.4f);bar.colors=colors;s.verticalScrollbarVisibility=ScrollRect.ScrollbarVisibility.AutoHide;s.scrollSensitivity=50;
  var nav=s.GetComponent<ScrollNavigation>()??s.gameObject.AddComponent<ScrollNavigation>();nav.Scroll=s;nav.Up=Arrow(root,"ScrollUp",width+3,0,true);nav.Down=Arrow(root,"ScrollDown",width+3,height-28,false);
 }
 static void TuneRows(){foreach(string name in new[]{"CraftRecipeRow","CraftWorkerRow"}){string path="Assets/Prefabs/Settlement/"+name+".prefab";var g=PrefabUtility.LoadPrefabContents(path);try{var row=g.GetComponent<CraftChoiceRow>();var root=(RectTransform)g.transform;if(name=="CraftRecipeRow"){float delta=root.rect.width-324;root.sizeDelta=new Vector2(324,72);row.Label.rectTransform.sizeDelta-=new Vector2(delta,0);row.Check.rectTransform.anchoredPosition-=new Vector2(delta,0);}else{root.sizeDelta=new Vector2(408,61);Rect(row.Label,78,0,181,61);Rect(row.State,258,0,92,61);Rect(row.Icon,14,6,49,49);Rect(row.Check,363,16.5f,28,28);}PrefabUtility.SaveAsPrefabAsset(g,path);}finally{PrefabUtility.UnloadPrefabContents(g);}}} public static string Run(){if(EditorApplication.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Stop Play and preserve dirty scene");TuneRows();foreach(var name in new[]{"CookingPanel","CraftWorkPanel"}){string path="Assets/Prefabs/Settlement/"+name+".prefab";var g=PrefabUtility.LoadPrefabContents(path);try{foreach(var s in g.transform.Find("Workspace").GetComponentsInChildren<ScrollRect>(true))Polish(s);var cook=g.GetComponent<SettlementCookingPanel>();var duration=cook?cook.Duration:g.GetComponent<SettlementCraftPanel>().Duration;var effect=cook?cook.TraitEffect:g.GetComponent<SettlementCraftPanel>().TraitEffect;duration.fontSize=28;effect.fontSize=26;Rect(duration,80,624,364,56);Rect(effect,480,624,600,56);var heading=duration.transform.parent.Find("WorkerHeading").GetComponent<Text>();heading.text="담당자 · 시간 효과";heading.fontSize=28;heading.alignment=TextAnchor.MiddleLeft;PrefabUtility.SaveAsPrefabAsset(g,path);}finally{PrefabUtility.UnloadPrefabContents(g);}}AssetDatabase.SaveAssets();return "Two work screens: dedicated dark/gold scroll rails and clickable arrows, clipped content separated, worker list clear of time footer, aligned readable effect sizes.";}
}
