using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using UnityEngine.EventSystems;
using Demo5.FrontEnd;
using Demo5.NightRun;
using Object=UnityEngine.Object;
public static class VerifyRecruitment
{
 static SettlementController Owner()=>Object.FindAnyObjectByType<SettlementController>();
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static void Bounds(GameObject g){Canvas.ForceUpdateCanvases();foreach(var t in g.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Text overflow "+t.name+": "+t.text);}
 static async Task Tap(Button b){await Task.Delay(80);Check(b&&b.IsActive()&&b.IsInteractable(),"Unavailable "+b?.name);Canvas.ForceUpdateCanvases();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(100);}
 static async Task Reload(int slot){var c=Owner();var disk=CampaignSaveStore.Read(slot,c);Check(disk.CanLoad,disk.Error);CampaignPersistence.Prepare(disk.Data,c);SceneManager.LoadScene("Settlement");await Task.Delay(800);}
 static void Save(int slot){var c=Owner();Check(CampaignSaveStore.Write(slot,CampaignPersistence.Capture(c),c,out var error),error);}
 static async Task Join(){var v=Owner().VisitorPanel;await Tap(v.OpenButton);await Tap(v.InspectRecruit);Bounds(v.View);await Tap(v.RecruitAction);Bounds(v.Review);await Tap(v.Confirm);await Tap(v.Back);}
 public static async Task<string> Fresh(){CampaignPersistence.ClearPending();PartySelectionSession.Clear();SceneManager.LoadScene("PartySelection");await Task.Delay(700);var p=Object.FindAnyObjectByType<PartySelectionController>();await Tap(p.Cards[0].Button);await Tap(p.Cards[2].Button);await Tap(p.Continue);await Task.Delay(600);var h=Object.FindAnyObjectByType<HomeSelectionController>();await Tap(h.Cards[0].Button);await Tap(h.Continue);await Task.Delay(600);return "Fresh scout/medic settlement ready.";}
 public static async Task<string> Flow(){
  CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/RecruitmentVerification");var c=Owner();c.Campaign.AdvanceSettlementTime(720-c.Campaign.MinuteOfDay);var v=c.VisitorPanel;Check(v.IsPresent&&v.RecruitId=="mechanic","First candidate");Save(0);await Reload(0);c=Owner();v=c.VisitorPanel;Check(v.RecruitId=="mechanic","Candidate changed on load");
  int minute=c.Campaign.MinuteOfDay;var stock=c.CraftPanel.Materials.ToDictionary(m=>m.Id,m=>m.Initial);await Tap(v.OpenButton);Bounds(v.View);await Tap(v.InspectRecruit);Bounds(v.View);await Tap(v.RecruitAction);Bounds(v.Review);await Tap(v.Cancel);Check(c.Campaign.Party.Count()==2&&v.RecruitPage.activeSelf,"Cancel joined/closed page");await Tap(v.RecruitBack);await Tap(v.Back);await Join();
  Check(c.Campaign.Party.Count()==3&&PartySelectionSession.Selected.SequenceEqual(new[]{"scout","medic","mechanic"}),"Joined identity");Check(v.HasRecruited&&!v.IsPresent&&c.Campaign.MinuteOfDay==minute,"Visitor/time outcome");Check(stock.All(x=>c.CraftPanel.Materials.First(m=>m.Id==x.Key).Initial==x.Value),"Merchant stock gifted");v.Commit();Check(!c.RecruitResident("mechanic")&&c.Campaign.Party.Count()==3,"Duplicate admission");Check(c.StandeeObjects.Count(g=>g.activeSelf)==3,"Standees missing");Check(c.Members.Count(m=>m.gameObject.activeSelf)==3&&c.Members.Any(m=>m.gameObject.activeSelf&&m.Name.text=="정비공"),"Roster page");
  var member=c.Campaign.Party.Last();Check(c.InventoryPanel.SlotsFor(member)==0,"New bag not empty");c.CraftPanel.Materials.First(m=>m.Id=="wood").Initial=20;Check(c.InventoryPanel.MoveFor(member,"wood",1,true),"New bag allocation");await Tap(c.Members.First(m=>m.gameObject.activeSelf&&m.Name.text=="정비공").BagButton);Check(c.InventoryPanel.MemberIndex==2&&c.InventoryPanel.BagTitle.text.Contains("정비공"),"New bag UI");Bounds(c.InventoryPanel.View);await Tap(c.InventoryPanel.CloseButton);
  c.CookingPanel.Open();await Task.Delay(150);Check(c.CookingPanel.WorkerRows.Count==3,"Cooking roster stale");await Tap(c.CookingPanel.WorkerRows[2].Button);Check(c.CookingPanel.SelectedWorker==2,"Cooking worker selection");await Tap(c.CookingPanel.Back);
  await Tap(c.CraftPanel.HousingButton);await Tap(c.CraftPanel.WorkerRows[2].Button);await Tap(c.CraftPanel.Confirm);Check(c.CraftPanel.Orders.Single().Member==member,"New builder failed");c.Campaign.AdvanceSettlementTime(10);Save(1);await Reload(1);c=Owner();v=c.VisitorPanel;member=c.Campaign.Party.Last();Check(v.HasRecruited&&!v.IsPresent&&c.InventoryPanel.CountFor(member,"wood")==1&&c.CraftPanel.Orders.Single().Member==member&&c.CraftPanel.Orders.Single().Minutes==35,"Joined save restore");
  var bad=CampaignPersistence.Capture(c);bad.Visitor.Recruited=false;Check(!CampaignSaveStore.Write(2,bad,c,out _),"Invalid joined flag accepted");bad=CampaignPersistence.Capture(c);bad.Visitor.RecruitId="missing";Check(!CampaignSaveStore.Write(2,bad,c,out _),"Unknown candidate accepted");var old=CampaignPersistence.Capture(c);old.Version=6;old.Visitor.RecruitId=null;old.Visitor.Recruited=false;CampaignPersistence.Upgrade(old,c);Check(old.Version==7&&old.Members.Length==3&&old.Visitor.RecruitId=="cook","v6 migration");
  c.Campaign.AdvanceSettlementTime(2*1440-10);Check(v.IsPresent&&v.RecruitId=="cook","Next candidate");await Tap(v.OpenButton);await Tap(v.InspectRecruit);Check(!v.RecruitAction.interactable,"Full housing allowed");v.RequestRecruit();Check(!v.Review.activeSelf&&c.Campaign.Party.Count()==3,"Full bypass");Bounds(v.View);await Tap(v.RecruitBack);await Tap(v.StartTrade);Check(v.Trade.activeSelf,"Full capacity blocked trade");await Tap(v.TradeBack);await Tap(v.Back);
  foreach(var m in c.CraftPanel.Materials)m.Initial=20;await Tap(c.CraftPanel.HousingButton);await Tap(c.CraftPanel.WorkerRows[2].Button);await Tap(c.CraftPanel.Confirm);c.Campaign.AdvanceSettlementTime(90);Check(c.CraftPanel.ResidentCapacity==5,"Housing expansion");
  await Tap(v.OpenButton);await Tap(v.InspectRecruit);await Tap(v.RecruitAction);c.Campaign.AdvanceSettlementTime(2*1440);await Tap(v.Confirm);Check(c.Campaign.Party.Count()==3&&!v.Review.activeSelf,"Stale visit confirmation joined");await Tap(v.RecruitBack);await Tap(v.Back);await Join();Check(c.Campaign.Party.Count()==4,"Expanded recruitment");
  c.Campaign.AdvanceSettlementTime(2*1440);await Tap(v.OpenButton);await Tap(v.InspectRecruit);await Tap(v.RecruitAction);int places=c.CraftPanel.SideRoomPlaces;c.CraftPanel.SideRoomPlaces=1;await Tap(v.Confirm);Check(c.Campaign.Party.Count()==4,"Capacity changed after quote");c.CraftPanel.SideRoomPlaces=places;await Tap(v.RecruitBack);await Tap(v.Back);await Join();Check(c.Campaign.Party.Count()==5&&c.StandeeObjects.Count(g=>g.activeSelf)==5,"Fifth resident");
  c.Campaign.AdvanceSettlementTime(2*1440);await Tap(v.OpenButton);await Tap(v.InspectRecruit);Check(!v.RecruitAction.interactable&&v.RecruitId=="guard","Five capacity boundary");Bounds(v.View);await Tap(v.RecruitBack);await Tap(v.Back);Check(c.ArrivalPanel.Begin(new[]{c.Campaign.Party.Last()},c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Recruited expedition");for(int wait=0;wait<30&&c.ArrivalPanel.InTransit;wait++)await Task.Delay(100);Check(!c.ArrivalPanel.InTransit,"Arrival transition stuck");Check(c.ArrivalPanel.Participants.Single()==c.Campaign.Party.Last(),"Wrong explorer");await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);Save(2);Bounds(c.Main.gameObject);
  return "PASS: candidate persistence, real click cancel/confirm, empty bag, no stock gift, 3/3 and 5/5 limits, stale visit/capacity revalidation, 3/4/5 visible residents, new bag/cooking/build worker/expedition, partial work reload, v6 migration, corrupt visitor rejection.";
 }
 public static async Task<string> Restart(){CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/RecruitmentVerification");SceneManager.LoadScene("StartMenu");await Task.Delay(650);await Tap(Object.FindAnyObjectByType<TitleMenuController>().ContinueButton);await Task.Delay(800);var c=Owner();Check(c.Campaign.Party.Count()==5&&PartySelectionSession.Selected.Distinct().Count()==5&&c.StandeeObjects.Count(g=>g.activeSelf)==5&&c.CraftPanel.ResidentCapacity==5,"Fresh Play load");return "PASS: fresh Play title Continue restored five residents and housing.";}
 public static async Task<string> Preview(){await Reload(0);var v=Owner().VisitorPanel;await Tap(v.OpenButton);await Tap(v.InspectRecruit);Bounds(v.View);return "Candidate preview ready.";}
 public static async Task<string> ConfirmPreview(){await Tap(Owner().VisitorPanel.RecruitAction);Bounds(Owner().VisitorPanel.Review);return "Confirmation preview ready.";}
 public static async Task<string> JoinedPreview(){await Reload(1);return "Three residents preview ready.";}
 public static string Cleanup(){CampaignSaveStore.TestDirectory=null;return "Test directory cleared.";}
}
