using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
// 말 놓기 (2026-09-25): the 07 window opens with a right press (read only: 돌아가기 only); the finds open after two pawns on the crate and
// '턴 진행' (FieldPawnTest).
public static class VerifyPopupFrames {
 static void Check(bool v,string s){if(!v)throw new Exception(s);}
 static async Task Tap(Button b){Check(b.IsActive()&&b.IsInteractable(),"Unavailable "+b.name);Canvas.ForceUpdateCanvases();b.GetComponentInParent<Canvas>().worldCamera?.Render();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(100);}
 static SettlementController C=>Object.FindAnyObjectByType<SettlementController>();
 static string Audit(GameObject view,CanvasGroup hud,params Button[] buttons){Check(hud.alpha==0,"Background HUD visible");Check(view.transform.Find("PopupHeading").gameObject.activeInHierarchy,"Missing header");Canvas.ForceUpdateCanvases();foreach(var t in view.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Text clipped: "+t.name+" "+t.text);foreach(var b in buttons){var r=(RectTransform)b.transform;Check(Math.Abs(-r.anchoredPosition.y+r.rect.height-1050)<.1f,"Footer baseline: "+b.name);}return "PASS: header, hidden background HUD, text bounds, footer baseline.";}
 public static async Task<string> Time(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */await Tap(C.Advance);return Audit(C.TimePanel.View,C.Main,C.TimePanel.CloseButton,C.TimePanel.Confirm);}
 public static async Task<string> Search(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */await Tap(C.TimePanel.CloseButton);Check(C.Main.alpha==1,"Settlement HUD restore");var a=C.ArrivalPanel;/* bag fixture: '보급품' is gone (밸런스 1차) and a new game starts with an empty stock, so one bandage is granted and packed */var bandage=C.CraftPanel.Materials.First(x=>x.Id=="bandage");bandage.Initial=Math.Max(bandage.Initial,1);Check(C.InventoryPanel.MoveFor(C.Campaign.Party.First(),"bandage",1,true),"Bag fixture");Check(a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Departure");await Task.Delay(850);for(int i=0;i<60&&!FieldPawnTest.Ready(a);i++)await Task.Delay(50);Check(FieldPawnTest.Detail(a,0)&&a.Search.ReadOnly,"07 (read only)");return Audit(a.Search.View,a.Main,a.Search.Back);}
 public static async Task<string> Bags(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */var a=C.ArrivalPanel;await Tap(a.Search.Back);Check(a.Main.alpha==1,"Field HUD restore");await Tap(a.Cards[0].Button);return Audit(a.FieldBags.View,a.Main,a.FieldBags.Back,a.FieldBags.Transfer);}
 public static async Task<string> Loot(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */var a=C.ArrivalPanel;await Tap(a.FieldBags.Back);Check(a.Main.alpha==1,"Bag close HUD restore");for(int i=0;i<60&&!FieldPawnTest.Ready(a);i++)await Task.Delay(50);Check(FieldPawnTest.Coop(a,0),"Two pawns on the crate");/* 함께: one turn */await Task.Delay(250);await Tap(a.Threat.Planner.TurnButton);await Task.Delay(200);Check(a.Loot.IsOpen,"Loot didn't open");return Audit(a.Loot.View,a.Main,new[]{a.Loot.Back,a.Loot.Transfer,a.Loot.TakeAll}.Where(b=>b!=null).ToArray());}
 public static async Task<string> Return(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */var a=C.ArrivalPanel;await Tap(a.Loot.Back);if(a.Loot.LeaveReview.activeSelf)await Tap(a.Loot.LeaveConfirm);Check(a.Main.alpha==1,"Loot close HUD restore");await Tap(a.Return);await Tap(a.ReturnConfirm);return Audit(C.ReturnPanel.View,C.Main,C.ReturnPanel.Back,C.ReturnPanel.InspectBags,C.ReturnPanel.StoreAll);}
 public static async Task<string> Close(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */await Tap(C.ReturnPanel.Back);Check(C.Main.alpha==1,"Return close HUD restore");return "PASS all five popup open/close transitions.";}
}
