using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using Demo5.FrontEnd;
using Object=UnityEngine.Object;
public static class VerifyCooking {
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static SettlementController Owner()=>Object.FindAnyObjectByType<SettlementController>();
 static async Task Tap(Button b){await Task.Delay(60);Check(b&&b.IsActive()&&b.IsInteractable(),"Unavailable "+(b?b.name:"null"));Canvas.ForceUpdateCanvases();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name+" by "+(hits.Count>0?hits[0].gameObject.name:"none"));ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(90);}
 static void Bounds(GameObject g){Canvas.ForceUpdateCanvases();foreach(var t in g.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Text overflow "+t.name+": "+t.preferredHeight+"/"+t.rectTransform.rect.height);}
 static int Total(SettlementController c,string id)=>c.CraftPanel.Materials.First(m=>m.Id==id).Initial;
 static string Compare(CampaignSaveData s){s.SavedUtc="2000-01-01T00:00:00Z";return JsonUtility.ToJson(s);}
 static async Task Queue(SettlementController c,int tab,int worker){await Tap(c.Stock);await Tap(c.CookingPanel.Tabs[tab]);await Tap(c.CookingPanel.WorkerRows[worker].Button);await Tap(c.CookingPanel.Confirm);}
 public static async Task<string> Flow(){
  CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/CookingVerification-"+Guid.NewGuid().ToString("N"));
  var c=Owner();var p=c.Campaign.Party.ToArray();Check(Total(c,"food")==6&&Total(c,"meal")==0,"Prefab stock missing");
  int time=c.Campaign.MinuteOfDay;await Tap(c.Stock);Bounds(c.CookingPanel.gameObject);await Tap(c.CookingPanel.Back);Check(Total(c,"food")==6&&c.Campaign.MinuteOfDay==time,"Inspection side effect");
  await Queue(c,0,0);Check(c.CookingPanel.Orders.Count==1&&c.IsAssigned(p[0]),"No cooking reservation");Check(Total(c,"food")==6&&c.InventoryPanel.StockCount("food")==4,"Reservation consumed or unavailable stock wrong");Check(!c.InventoryPanel.MoveFor(p[1],"food",5,true),"Reserved food moved");
  await Tap(c.Stock);Check(!c.CookingPanel.WorkerRows[0].Button.interactable,"Duplicate worker allowed");Bounds(c.CookingPanel.gameObject);await Tap(c.CookingPanel.OrderRows[0].Cancel);Check(!c.CookingPanel.Workspace.interactable,"Cancel not modal");Bounds(c.CookingPanel.CancelPopup);await Tap(c.CookingPanel.CancelNo);Check(c.CookingPanel.Orders.Count==1,"Cancel dismissal removed job");await Tap(c.CookingPanel.OrderRows[0].Cancel);await Tap(c.CookingPanel.CancelYes);Check(c.CookingPanel.Orders.Count==0&&c.InventoryPanel.StockCount("food")==6&&!c.IsAssigned(p[0]),"Cancel did not release stock/worker");await Tap(c.CookingPanel.Back);
  await Queue(c,0,0);await Tap(c.Workbench);c.CraftPanel.FocusRecipe("nails");await Tap(c.CraftPanel.WorkerRows[1].Button);await Tap(c.CraftPanel.Confirm);
  c.Campaign.AdvanceSettlementTime(10);Check(c.CookingPanel.Orders[0].Minutes==10&&c.TimePanel.NextCompletion()==5,"Concurrent next completion");
  var snapshot=CampaignPersistence.Capture(c);string expected=Compare(snapshot);Check(CampaignSaveStore.Write(0,snapshot,c,out var error),"Write: "+error);var disk=CampaignSaveStore.Read(0,c);Check(disk.CanLoad,"Read: "+disk.Error);Check(Compare(disk.Data)==expected,"Disk state differs");
  var invalid=CampaignPersistence.Capture(c);invalid.Cooking[0].MemberId=invalid.Craft[0].MemberId;Check(!CampaignSaveStore.Write(1,invalid,c,out _),"Duplicate worker save accepted");invalid=CampaignPersistence.Capture(c);invalid.Materials.First(m=>m.Id=="food").Count=1;Check(!CampaignSaveStore.Write(1,invalid,c,out _),"Over-reserved save accepted");
  var legacy=CampaignPersistence.Capture(c);legacy.Version=1;legacy.Cooking=null;legacy.Materials=legacy.Materials.Where(m=>!CampaignPersistence.FoodIds.Contains(m.Id)).ToArray();CampaignPersistence.Upgrade(legacy,c);Check(legacy.Version==CampaignPersistence.CurrentVersion&&legacy.Cooking.Length==0&&legacy.Materials.Where(m=>CampaignPersistence.FoodIds.Contains(m.Id)).All(m=>m.Count==0),"v1 migration added stock or jobs");
  var missing=CampaignPersistence.Capture(c);missing.Version=1;missing.Materials=missing.Materials.Where(m=>m.Id!="wood").ToArray();bool refused=false;try{CampaignPersistence.Upgrade(missing,c);}catch(InvalidOperationException){refused=true;}Check(refused,"Migration accepted missing old stock");
  CampaignPersistence.Prepare(disk.Data,c);SceneManager.LoadScene("Settlement");await Task.Delay(750);c=Owner();p=c.Campaign.Party.ToArray();Check(Compare(CampaignPersistence.Capture(c))==expected,"Restored state differs");
  int wood=Total(c,"wood"),nails=Total(c,"nails");c.Campaign.AdvanceSettlementTime(10);Check(c.CookingPanel.Orders.Count==0&&Total(c,"meal")==2&&Total(c,"food")==4&&Total(c,"wood")==wood-1,"Completion costs/rewards");Check(Total(c,"nails")==nails+1,"Parallel craft completion");c.Campaign.AdvanceSettlementTime(30);Check(Total(c,"meal")==2,"Duplicate food reward");
  await Queue(c,1,1);Check(c.InventoryPanel.StockCount("meal")==1&&c.InventoryPanel.StockCount("cloth")==Total(c,"cloth")-1,"Packing ingredients not reserved");c.Campaign.AdvanceSettlementTime(10);Check(Total(c,"ration")==1&&Total(c,"meal")==1,"Ration output");
  p[0].Health=p[0].MaxHealth-1;await Tap(c.Cabinet);var index=Array.IndexOf(c.InventoryPanel.Items.Where(i=>c.InventoryPanel.StockCount(i.Id)>0).ToArray(),c.InventoryPanel.Items.First(i=>i.Id=="meal"));await Tap(c.InventoryPanel.StockRows[index].Button);Bounds(c.InventoryPanel.gameObject);time=c.Campaign.MinuteOfDay;await Tap(c.InventoryPanel.Use);Check(p[0].Health==p[0].MaxHealth&&Total(c,"meal")==0&&c.Campaign.MinuteOfDay==time+10,"Meal use incorrect");Check(!c.InventoryPanel.UseSelected(),"Repeated use at full health");await Tap(c.InventoryPanel.CloseButton);
  int cans=Total(c,"can");time=c.Campaign.MinuteOfDay;await Queue(c,2,0);Check(Total(c,"can")==cans-1&&Total(c,"meal")==1&&c.Campaign.MinuteOfDay==time&&c.CookingPanel.Orders.Count==0,"Instant can cooking");
  Check(c.InventoryPanel.MoveFor(p[0],"ration",1,true),"Ration packing");p[0].Health=p[0].MaxHealth-1;Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Expedition begin");await Task.Delay(900);await Tap(c.ArrivalPanel.Cards[0].Button);var bags=c.ArrivalPanel.FieldBags;await Tap(bags.LeftRows.First(r=>r.GetComponentsInChildren<Text>().Any(t=>t.text=="원정 도시락")).Button);Bounds(bags.gameObject);int turns=c.ArrivalPanel.Rooms.Turns,noise=c.ArrivalPanel.Rooms.Noise;time=c.Campaign.MinuteOfDay;await Tap(bags.Use);Check(p[0].Health==p[0].MaxHealth&&c.InventoryPanel.CountFor(p[0],"ration")==0&&c.ArrivalPanel.Rooms.Turns==turns+1&&c.Campaign.MinuteOfDay==time+c.ArrivalPanel.Rooms.MinutesPerTurn&&c.ArrivalPanel.Rooms.Noise==noise,"Field eating transaction");Check(!c.InventoryPanel.UseFieldFood(p[0],"ration"),"Repeat eating allowed");Check(c.ArrivalPanel.Cards[0].Health.text==p[0].Health+" / "+p[0].MaxHealth,"Field HP HUD stale");await Tap(bags.Back);await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);
  Check(CampaignSaveStore.Write(2,CampaignPersistence.Capture(c),c,out error),"Return save: "+error);
  await Queue(c,0,0);await Tap(c.Stock);Bounds(c.CookingPanel.gameObject);
  return "PASS: real UI cooking/cancel, shared reservations and worker exclusions, parallel craft/time, disk roundtrip, v1 migration with zero grants, invalid-state rejection, once-only completion, ration production and bag transfer, settlement meal/full-health guard, instant cans, field eating once with time/noise/HP HUD, return save. Cooking queue ready for capture.";
 }
 public static string ShowFood(){var c=Owner();c.CookingPanel.Close();c.InventoryPanel.Open();return "Inventory ready.";}
 public static async Task<string> FoodPreview(){var c=Owner();c.CookingPanel.Close();c.Campaign.AdvanceSettlementTime(20);var p=c.Campaign.Party.First();p.Health=p.MaxHealth-1;await Tap(c.Cabinet);var visible=c.InventoryPanel.Items.Where(i=>c.InventoryPanel.StockCount(i.Id)>0).ToArray();await Tap(c.InventoryPanel.StockRows[Array.FindIndex(visible,i=>i.Id=="meal")].Button);Bounds(c.InventoryPanel.gameObject);return "Actual completed meals selected; damaged test character shows the food-use preview.";}
 public static async Task<string> FieldPreview(){var c=Owner();c.InventoryPanel.Close();await Queue(c,1,1);c.Campaign.AdvanceSettlementTime(10);var p=c.Campaign.Party.ToArray();Check(c.InventoryPanel.MoveFor(p[0],"ration",1,true),"Preview pack ration");Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Preview expedition");await Task.Delay(900);await Tap(c.ArrivalPanel.Cards[0].Button);await Tap(c.ArrivalPanel.FieldBags.LeftRows.First(r=>r.GetComponentsInChildren<Text>().Any(t=>t.text=="원정 도시락")).Button);Bounds(c.ArrivalPanel.FieldBags.gameObject);return "Actual crafted and packed ration selected in the expedition bag; eating preview ready.";}
 public static async Task<string> LegacyAndRestartFixture(){
  var c=Owner();if(c.ArrivalPanel.FieldBags.IsOpen)c.ArrivalPanel.FieldBags.Close();if(c.ArrivalPanel.IsOpen){await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);}if(c.CookingPanel.IsOpen)c.CookingPanel.Close();
  string previous=CampaignSaveStore.TestDirectory;
  try{CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/SystemMenuVerification");var old=CampaignSaveStore.Read(0,c);Check(old.CanLoad&&old.Data.Version==CampaignPersistence.CurrentVersion&&old.Data.Cooking.Length==0,"Actual prior-version file migration: "+old.Error);}finally{CampaignSaveStore.TestDirectory=previous;}
  // Preserve the unfinished-job snapshot from Flow in a stable isolated directory.
  var saved=CampaignSaveStore.Read(0,c);Check(saved.CanLoad,"Fixture source invalid");CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/CookingRestartVerification");Check(CampaignSaveStore.Write(0,saved.Data,c,out var error),error);
  return "PASS: real existing v1 slot migrates. Isolated cooking restart fixture saved.";
 }
 public static async Task<string> Restart(){CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/CookingRestartVerification");SceneManager.LoadScene("StartMenu");await Task.Delay(650);var title=Object.FindAnyObjectByType<TitleMenuController>();await Tap(title.ContinueButton);await Task.Delay(750);var c=Owner();Check(c.CookingPanel.Orders.Count==1&&c.CookingPanel.Orders[0].Minutes==10&&c.CraftPanel.Orders.Count==1,"Restart jobs missing");int food=Total(c,"food"),meal=Total(c,"meal");c.Campaign.AdvanceSettlementTime(10);Check(Total(c,"food")==food-2&&Total(c,"meal")==meal+2,"Restart completion");c.Campaign.AdvanceSettlementTime(20);Check(Total(c,"meal")==meal+2,"Restart duplicate completion");return "PASS: fresh Play -> title Continue -> disk cooking restore -> exactly-once completion.";}
 public static async Task<string> TimePreview(){var c=Owner();var s=CampaignSaveStore.Read(0,c);Check(s.CanLoad,s.Error);CampaignPersistence.Prepare(s.Data,c);SceneManager.LoadScene("Settlement");await Task.Delay(700);c=Owner();await Tap(c.Advance);await Tap(c.TimePanel.Choices[3]);Bounds(c.TimePanel.View);Check(c.TimePanel.NextCompletion()==5,"Next completion changed");return "Time UI shows simultaneous craft and cooking; next completion preview ready.";}
 public static async Task<string> BatchAndSupply(){
  var c=Owner();var p=c.Campaign.Party.ToArray();
  await Tap(c.Stock);await Tap(c.CookingPanel.Plus);await Tap(c.CookingPanel.WorkerRows[0].Button);await Tap(c.CookingPanel.Confirm);
  Check(c.CookingPanel.Orders[0].OutputCount==4&&c.CookingPanel.Orders[0].Minutes==40&&c.CraftPanel.Available("wood")==0,"Batch amounts");
  Check(!c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Cook left on expedition");
  await Tap(c.Workbench);c.CraftPanel.FocusRecipe("repair-bed");await Tap(c.CraftPanel.WorkerRows[1].Button);Check(!c.CraftPanel.Confirm.interactable,"Craft reused cooking wood");await Tap(c.CraftPanel.CloseButton);
  c.Campaign.AdvanceSettlementTime(15);int time=c.Campaign.MinuteOfDay;
  await Tap(c.Stock);await Tap(c.CookingPanel.OrderRows[0].Cancel);await Tap(c.CookingPanel.CancelYes);Check(Total(c,"food")==6&&Total(c,"wood")==2&&c.CookingPanel.Orders.Count==0&&c.Campaign.MinuteOfDay==time,"Partial cancel consumed/refunded wrong amount or rewound time");
  await Tap(c.CookingPanel.Plus);await Tap(c.CookingPanel.WorkerRows[0].Button);await Tap(c.CookingPanel.Confirm);await Tap(c.Advance);await Tap(c.TimePanel.Choices[3]);Check(c.TimePanel.NextCompletion()==40,"Batch next completion");await Tap(c.TimePanel.Confirm);Check(Total(c,"meal")==4&&Total(c,"food")==2,"Batch completion");await Tap(c.TimePanel.CloseButton);
  Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Supply trip");await Task.Delay(900);var loot=c.ArrivalPanel.Loot;Check(loot.Sites[0].Drops.Any(d=>d.Id=="food"&&d.Chance==85),"Food source absent");for(int i=0;i<3;i++)Check(loot.Advance(0,2,p[0]),"Slow food search");Check(loot.State(0).Loot["food"]==2,"Slow search guaranteed food");loot.Open(0);await Task.Delay(100);await Tap(loot.FieldRows.First(r=>r.GetComponentsInChildren<Text>().Any(t=>t.text=="식재료")).Button);await Tap(loot.Max);await Tap(loot.Transfer);Check(c.InventoryPanel.CountFor(p[0],"food")==2&&loot.State(0).Loot["food"]==0,"Food distribution");await Tap(loot.Back);if(loot.LeaveReview.activeSelf)await Tap(loot.LeaveConfirm);
  await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);Check(c.InventoryPanel.MoveFor(p[0],"food",2,false)&&Total(c,"food")==4,"Bring ingredients to stock");
  var snapshot=CampaignPersistence.Capture(c);CampaignPersistence.Prepare(snapshot,c);SceneManager.LoadScene("Settlement");await Task.Delay(700);c=Owner();p=c.Campaign.Party.ToArray();Check(c.ArrivalPanel.Begin(p,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Revisit");await Task.Delay(900);Check(!c.ArrivalPanel.Loot.Advance(0,2,p[0])&&(!c.ArrivalPanel.Loot.State(0).Loot.TryGetValue("food",out int remaining)||remaining==0),"Revisit rerolled food");await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.Back);
  await Tap(c.Stock);Bounds(c.CookingPanel.gameObject);
  return "PASS: batch scaling, cook cannot depart, craft shares reserved wood, partial cancel preserves elapsed time and releases exact stock, next-completion UI, food search -> loot distribution -> bag -> return -> shared stock, restored site cannot reroll food. Empty cooking queue ready.";
 }
}
