using System;using System.Linq;using System.Threading.Tasks;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using Demo5.FrontEnd;using Demo5.NightRun;using Object=UnityEngine.Object;
public static class VerifyTabbedBags {
 static void Check(bool v,string s){if(!v)throw new Exception(s);}
 static async Task Tap(Button b){Check(b.IsActive()&&b.IsInteractable(),"Unavailable "+b.name);Canvas.ForceUpdateCanvases();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(120);}
 static Task Pick(ExpeditionBagPanel b,SettlementInventoryPanel inv,string id)=>Tap(b.LeftRows.First(r=>r.Label.text==inv.Items.First(i=>i.Id==id).Name).Button);
 public static async Task<string> Flow(){var c=Object.FindAnyObjectByType<SettlementController>();var a=c.ArrivalPanel;var inv=c.InventoryPanel;var people=c.Campaign.Party.ToArray();Check(a.Begin(people,c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Departure");await Task.Delay(900);Check(inv.TransferField(people[0],"ammo",2,true)&&inv.TransferField(people[0],"bandage",2,true)&&inv.TransferField(people[0],"cloth",4,true),"Fixture");await Tap(a.Cards[0].Button);var b=a.FieldBags;
 Check(b.ProfileName.text==people[0].Name&&b.ProfileTrait.text.Length>0&&!b.Transfer.gameObject.activeSelf,"Profile and no transfer footer");await Pick(b,inv,"ammo");Check(!b.Use.gameObject.activeSelf,"Ammo not usable");int turn=a.Rooms.Turns,noise=a.Rooms.Noise;await Tap(b.RightCards.Single().Button);Check(inv.CountFor(people[0],"ammo")==1&&inv.CountFor(people[1],"ammo")==1&&a.Rooms.Turns==turn&&a.Rooms.Noise==noise,"Name tap transfer");
 await Tap(b.LeftCards[1].Button);Check(b.Source==people[1]&&b.ProfileName.text==people[1].Name&&b.ProfileRole.text.Contains("간병"),"Tab updates profile");await Pick(b,inv,"ammo");await Tap(b.RightCards.Single().Button);Check(inv.CountFor(people[0],"ammo")==2&&inv.CountFor(people[1],"ammo")==0,"Reverse transfer by name");
 await Tap(b.LeftCards[0].Button);await Pick(b,inv,"bandage");int hp=people[0].Health;await Tap(b.Use);Check(people[0].Health>hp&&inv.CountFor(people[0],"bandage")==1&&a.Rooms.Turns==turn+1&&b.ProfileHealth.text.Contains(people[0].Health+" /"),"Use updates profile");return "PASS: real pointer owner tabs, status/trait updates, click-name forward/reverse transfer without time/noise, use consumes item and updates health, no transfer confirmation footer.";}
 public static async Task<string> Six(){var c=Object.FindAnyObjectByType<SettlementController>();var a=c.ArrivalPanel;var b=a.FieldBags;b.Close();c.InventoryPanel.TransferField(a.Participants[0],"bandage",1,true);var people=a.Participants.ToList();for(int i=people.Count;i<6;i++){var d=c.Roster.Candidates.First(x=>!people.Any(p=>p.Name==x.DisplayName));people.Add(new Adventurer(d.DisplayName,d.RoleTitle,d.TraitDescription,d.Health,d.Aim,d.BagCapacity));var card=Object.Instantiate(a.MemberPrefab,a.MemberContent);card.Portrait.sprite=d.Portrait;a.Cards.Add(card);}typeof(ExpeditionArrivalPanel).GetField("people",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(a,people.ToArray());b.Open(0);await Task.Delay(250);Check(b.LeftCards.Count==6&&b.RightCards.Count==5,"Six owners/five recipients");await Tap(b.LeftCards[5].Button);Check(b.ProfileName.text==people[5].Name&&b.ProfileCharacteristics.text.Length>0,"Sixth profile");await Tap(b.LeftCards[0].Button);await Pick(b,c.InventoryPanel,"bandage");Check(b.RightCards.All(r=>r.Name.text!=b.Source.Name),"No self transfer");return "PASS: six visible owner tabs, sixth profile, five recipients, self omitted. UI fixture only.";}
 public static async Task<string> EdgeCases(){var c=Object.FindAnyObjectByType<SettlementController>();var a=c.ArrivalPanel;var b=a.FieldBags;Check(a.Participants.Count==6,"Run Six first");var scroll=b.RightMembers.GetComponentInParent<ScrollRect>();scroll.verticalNormalizedPosition=0;await Task.Delay(200);var receiver=a.Participants[5];int before=c.InventoryPanel.CountFor(receiver,"bandage");await Tap(b.RightCards.Last().Button);Check(c.InventoryPanel.CountFor(receiver,"bandage")==before+1,"Last scrolled recipient receives");b.Close();typeof(ExpeditionArrivalPanel).GetField("people",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(a,new[]{c.Campaign.Party.First()});b.Open(0);await Task.Delay(200);Check(b.LeftCards.Count==1&&b.RightCards.Count==0&&b.EmptyRight.gameObject.activeSelf,"Solo empty receiver state");await Pick(b,c.InventoryPanel,"cloth");await Tap(b.Max);Check(b.Quantity.text=="4","Maximum quantity");await Tap(b.Minus);Check(b.Quantity.text=="3","Reduce quantity");Restore();return "PASS: scroll to fifth recipient and transfer, solo profile/no receivers, quantity max/minus, real party restored.";}
 public static string Restore(){var c=Object.FindAnyObjectByType<SettlementController>();var a=c.ArrivalPanel;a.FieldBags.View.SetActive(false);typeof(ExpeditionArrivalPanel).GetField("people",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).SetValue(a,c.Campaign.Party.ToArray());while(a.Cards.Count>c.Campaign.Party.Count()){var card=a.Cards[a.Cards.Count-1];a.Cards.RemoveAt(a.Cards.Count-1);Object.Destroy(card.gameObject);}a.FieldBags.Open(0);return "Actual party restored.";}
}



