using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using Demo5.FrontEnd;
using Demo5.NightRun;
public static class VerifyDevelopment
{
 static SettlementController C()=>UnityEngine.Object.FindAnyObjectByType<SettlementController>();
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
 static async Task Tap(Button b){await Task.Delay(80);Canvas.ForceUpdateCanvases();Check(b&&b.IsActive()&&b.IsInteractable(),"Unavailable: "+b?.name);var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name+" by "+hits.FirstOrDefault().gameObject?.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(100);}
 static async Task RoundTrip(){var c=C();var data=CampaignPersistence.Capture(c);CampaignSaveStore.TestDirectory=System.IO.Path.GetFullPath("Temp/DevelopmentVerification");try{Check(CampaignSaveStore.Write(0,data,c,out string error),error);var read=CampaignSaveStore.Read(0,c);Check(read.CanLoad,read.Error);CampaignPersistence.Prepare(read.Data,c);}finally{CampaignSaveStore.TestDirectory=null;}SceneManager.LoadScene("Settlement");await Task.Delay(500);}
 public static async Task<string> Fresh(){var roster=C().Roster;Check(roster.Candidates.Select(x=>x.DisplayName).Distinct().Count()==6&&roster.Candidates.All(x=>!string.IsNullOrEmpty(x.WorkLine)),"Profiles missing");PartySelectionSession.Clear();var campaign=new CampaignState(roster.Candidates.Select(x=>new Adventurer(x.DisplayName,x.RoleTitle,x.Description,x.Health,x.Aim,x.BagCapacity)).ToArray(),true);campaign.Toggle(0);campaign.Toggle(1);campaign.ConfirmParty();campaign.Settle(0);PartySelectionSession.Selected.AddRange(new[]{"scout","mechanic"});PartySelectionSession.Pending=campaign;SceneManager.LoadScene("Settlement");await Task.Delay(500);var c=C();Check(c.Introduction.Step==0&&c.CraftPanel.Materials.All(m=>m.Initial==0)&&c.CraftPanel.BenchLevel==0,"Fresh state");c.CraftPanel.Open();Check(!c.CraftPanel.IsOpen,"Bypass intro");await Tap(c.Introduction.Action);await Tap(c.Introduction.Action);Check(c.CraftPanel.Available("wood")==0&&c.CraftPanel.Available("cloth")==1,"Free construction material");await RoundTrip();c=C();Check(c.Introduction.Step==2&&c.CraftPanel.Available("cloth")==1,"Intro save duplicate");await Tap(c.Introduction.Action);await Tap(c.Bed);Check(!c.WorkPanel.Sleep.interactable,"Ground sleeping unlocked");await Tap(c.WorkPanel.Rows[0].Button);await Tap(c.WorkPanel.Confirm);Check(c.WorkPanel.Orders.Single().Minutes==60,"Ground rest duration");await Finish();await Tap(c.Cabinet);await Tap(c.InventoryPanel.CloseButton);c=C();Check(c.Introduction.Step==5&&c.Exit.IsActive()&&!c.Development.State.Workbench,"First trip gating");await Tap(c.Development.OpenButton);c.CraftPanel.FocusRecipe("build-bench");await Tap(c.CraftPanel.WorkerRows[0].Button);Check(!c.CraftPanel.Confirm.interactable,"Restoration without salvage");c.CraftPanel.FocusRecipe("research-tools");Check(!c.CraftPanel.Confirm.interactable,"Research before desk");await Tap(c.CraftPanel.CloseButton);return "PASS named fresh party, empty resources, ground rest, UI intro, save round-trip, first expedition before crafting, restoration/research gates";}
 static async Task Finish(){var c=C();if(c.TimePanel.NextCompletion()==0)return;await Tap(c.Advance);await Tap(c.TimePanel.Choices[3]);await Tap(c.TimePanel.Confirm);await Tap(c.TimePanel.CloseButton);}
 public static async Task<string> FirstTrip(){var c=C();var a=c.ArrivalPanel;Check(a.Begin(c.Campaign.Party.ToArray(),c.ExpeditionPanel.Destinations.First(d=>d.Id=="mall")),"Begin field");for(int i=0;i<80&&a.InTransit;i++)await Task.Delay(80);Check(a.Loot.CanSearch(0,a.Participants[0]),"Starter crate requires tool");
  // Fixture: the crate's partial rows (wood 3@50, scrap 2@50) are pinned to 100% for this roll so BuildFirst's exact-cost path is deterministic; restored below.
  var crate=a.Loot.Sites[0].Drops;int[] chances=crate.Select(d=>d.Chance).ToArray();foreach(var d in crate)d.Chance=100;
  try{for(int i=0;i<3;i++)Check(a.Loot.Advance(0,2,a.Participants[0],0),"Search turn "+i);}finally{for(int i=0;i<chances.Length;i++)crate[i].Chance=chances[i];}
  a.Loot.Open(0);Check(a.Loot.IsOpen,"Loot unavailable");foreach(string id in new[]{"wood","scrap","cloth"}){var name=c.InventoryPanel.Items.First(x=>x.Id==id).Name;await Tap(a.Loot.FieldRows.First(r=>r.Label.text==name).Button);await Tap(a.Loot.Max);await Tap(a.Loot.Transfer);}Check(a.Loot.State(0).Loot.Values.All(n=>n==0),"Loot not transferred");await Tap(a.Loot.Back);await Tap(a.Return);await Tap(a.ReturnConfirm);await Tap(c.ReturnPanel.StoreAll);Check(c.Development.StockUsed==12,"Temporary capacity not enforced");Check(c.Campaign.Party.Sum(p=>c.InventoryPanel.Items.Sum(i=>c.InventoryPanel.CountFor(p,i.Id)))>0,"Overflow discarded");await Tap(c.ReturnPanel.Back);Check(c.Introduction.Step==10,"Return intro completion");return "PASS crate search (partial rows pinned to 100%), loot UI, return, partial unpack at 12, retained bag overflow";}
 public static async Task<string> BuildFirst(){var c=C(); // Rebalance the limited temporary stock using real transfers to guarantee a warehouse recipe fits.
  var p=c.Campaign.Party.First();foreach(var m in c.CraftPanel.Materials.ToArray())if(m.Id!="wood"&&m.Id!="scrap"&&m.Initial>0){var who=c.Campaign.Party.First(x=>c.InventoryPanel.TransferLimit(x,m.Id,true)>0);Check(c.InventoryPanel.MoveFor(who,m.Id,m.Initial,true),"Withdraw before build");}
  int wood=c.CraftPanel.Available("wood");if(wood>2)Check(c.InventoryPanel.MoveFor(c.Campaign.Party.First(x=>c.InventoryPanel.TransferLimit(x,"wood",true)>=wood-2),"wood",wood-2,true),"Trim wood");foreach(var id in new[]{"scrap"})if(c.CraftPanel.Available(id)<1){var who=c.Campaign.Party.First(x=>c.InventoryPanel.CountFor(x,id)>0);Check(c.InventoryPanel.MoveFor(who,id,1,false),"Deposit scrap");}
  await Queue("build-stock");c=C();Check(!c.Development.IsDone("build-stock")&&c.CraftPanel.UnderConstruction("build-stock"),"Reservation completed early");await RoundTrip();c=C();Check(c.CraftPanel.UnderConstruction("build-stock")&&!c.Development.IsDone("build-stock"),"Pending build restore");await Finish();c=C();Check(c.Development.Capacity==40&&c.CraftPanel.Available("wood")==0&&c.CraftPanel.Available("scrap")==0,"Exact warehouse cost");foreach(var member in c.Campaign.Party)foreach(var item in c.InventoryPanel.Items){int count=c.InventoryPanel.TransferLimit(member,item.Id,false);if(count>0)Check(c.InventoryPanel.MoveFor(member,item.Id,count,false),"Unpack after warehouse");}
  await Queue("build-bench");await Finish();await Queue("build-bed");await Finish();await Queue("build-research");await Finish();c=C();Check(c.Development.State.Research&&c.CraftPanel.BedLevel==1&&c.CraftPanel.BenchLevel==1,"Built states");await Tap(c.Bed);Check(c.WorkPanel.Sleep.interactable,"Bed failed to unlock sleep");await Tap(c.WorkPanel.CloseButton);await RoundTrip();Check(C().Development.State.Research,"Completed restore");return "PASS recovered materials (pinned crate roll) built warehouse/workbench/bed/research desk; reserved+completed file saves; exact costs, expanded storage, sleep unlock";}
 static async Task Queue(string id){var c=C();if(c.Development.IsDone(id)||c.CraftPanel.FacilityDone(c.CraftPanel.Recipes.First(r=>r.Id==id)))return;await Tap(c.Development.OpenButton);c.CraftPanel.FocusRecipe(id);await Task.Delay(100);await Tap(c.CraftPanel.WorkerRows.First(r=>r.Button.IsInteractable()).Button);await Tap(c.CraftPanel.Confirm);Check(c.CraftPanel.UnderConstruction(id),"Not queued "+id);}
 public static async Task<string> ResearchAndLegacy(){var c=C(); // Isolated research/capacity regression fixture, separate from the real recovered-material path above.
  if(c.CraftPanel.IsOpen)c.CraftPanel.Close();foreach(var m in c.CraftPanel.Materials)m.Initial=30;
  await Queue("research-tools");await Finish();Check(c.Development.State.Tools,"Research result");await Tap(c.Development.OpenButton);c.CraftPanel.FocusRecipe("research-tools");await Tap(c.CraftPanel.WorkerRows[0].Button);Check(!c.CraftPanel.Confirm.interactable,"Repeated research");await Tap(c.CraftPanel.CloseButton);
  await Queue("research-comfort");await Finish();await Queue("research-storage");await Finish();await Queue("expand-stock");await Finish();await Queue("build-cooker");await Finish();await Queue("upgrade-bench");await Finish();await Queue("repair-bed");await Finish();await Queue("upgrade-cooker");await Finish();Check(c.Development.Capacity==80&&c.CraftPanel.BedLevel==2&&c.CraftPanel.BenchLevel==2&&c.CraftPanel.CookerLevel==2,"Final upgrades");
  var data=CampaignPersistence.Capture(c);data.Version=9;data.IntroductionStep=10;data.Development=null;data.Members[0].Name="탐험가 1";data.Members[1].Name="사용자이름";CampaignPersistence.Upgrade(data,c);Check(data.Version==CampaignPersistence.CurrentVersion&&data.Development.Workbench&&data.Development.Cooker&&data.Development.Bed&&data.Development.Tools&&data.Development.Comfort,"Legacy facilities");Check(data.Members[0].Name=="윤서진"&&data.Members[1].Name=="사용자이름","Legacy names");await RoundTrip();c=C();Check(c.Development.Capacity==80&&c.Development.State.Tools,"Final save");return "PASS research gates, repeat prevention, all upgrades, v9 migration preserves unlocked facilities/custom names; final v10 save round-trip";
 }
 public static async Task<string> Facing(){var c=C();var face=UnityEngine.Object.FindObjectsByType<PawnFacing>().First();var foot=face.Foot.GetComponent<SpriteRenderer>();Vector3 before=face.transform.position;try{face.Face(true);face.ResetTracking();face.transform.position+=Vector3.left*.2f;await Task.Delay(80);Check(face.Body.flipX&&!foot.flipX,"Left flip/base");face.transform.position+=Vector3.right*.2f;await Task.Delay(80);Check(!face.Body.flipX,"Right flip");face.transform.position+=Vector3.up*.2f;await Task.Delay(80);Check(!face.Body.flipX,"Vertical changed direction");}finally{face.transform.position=before;face.ResetTracking();}return "PASS body-only horizontal facing; base fixed; vertical movement preserves orientation";}
 public static async Task<string> Screenshot(){var c=C();foreach(var m in c.CraftPanel.Materials)m.Initial=Math.Min(m.Initial,2);await Tap(c.Development.OpenButton);c.CraftPanel.FocusRecipe("build-research");Canvas.ForceUpdateCanvases();foreach(var t in new[]{c.CraftPanel.DetailTitle,c.CraftPanel.DetailDescription,c.CraftPanel.Duration,c.CraftPanel.ConfirmLabel})Check(t.preferredHeight<=t.rectTransform.rect.height+2,"Text clipped "+t.name);return "Ready facility screenshot";}
}
