using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Threading.Tasks;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEngine.SceneManagement;using UnityEditor;using Demo5.FrontEnd;using Demo5.NightRun;using Object=UnityEngine.Object;
public static class VerifyRemainingUI {
 const string Shots="Assets/Screenshots/UIAudit/";
 static SettlementController C=>Object.FindAnyObjectByType<SettlementController>();
 static void Check(bool b,string m){if(!b)throw new Exception(m);}
 static async Task Tap(Button b){await Task.Delay(100);Check(b&&b.IsActive()&&b.IsInteractable(),"Unavailable "+b?.name);Canvas.ForceUpdateCanvases();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name+" by "+hits.FirstOrDefault().gameObject?.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(150);}
 static void Fits(Text t){Canvas.ForceUpdateCanvases();Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Clipped "+t.name+" "+t.preferredHeight+" > "+t.rectTransform.rect.height+" : "+t.text);}
 static async Task Shot(string name){ScreenCapture.CaptureScreenshot(Shots+name+".png");await Task.Delay(350);}
 static async Task Load(int count=2,bool bags=false){
  var catalog=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Settlement/SettlementScreen.prefab").GetComponent<SettlementController>();
  var s=JsonUtility.FromJson<CampaignSaveData>(File.ReadAllText("Temp/TutorialClaritySave/resume.json"));s.IntroductionStep=10;s.Visitor=new SavedVisitor();s.Opening.Enabled=false;s.Opening.Complete=false;s.Opening.NightHeard=false;s.Opening.NightChoice=0;s.Rest=Array.Empty<SavedRest>();s.Craft=Array.Empty<SavedCraft>();s.Cooking=Array.Empty<SavedCooking>();s.SideRoomConnected=s.SideRoomReady=true;s.Development.Tools=true;s.Development.Research=true;s.Development.Workbench=true;
  // The fixture has already visited the mall, so its next visit is the awake site board; mark the one-time board intro as seen (save v13) so it does not cover these checks.
  s.Version=CampaignPersistence.CurrentVersion;s.SiteBoards=new[]{new SavedSiteBoard{Id="mall",Remembered="",IntroShown=true}};
  var pair=new[]{"scout","medic"};var candidates=count==2?pair.Select(id=>catalog.Roster.Candidates.First(c=>c.Id==id)):catalog.Roster.Candidates.Take(count);
  s.Members=candidates.Select(d=>new SavedMember{Id=d.Id,Name=d.DisplayName,Role=d.RoleTitle,Description=d.Description,Health=d.Health-1,Maximum=d.Health,Aim=d.Aim,Capacity=d.BagCapacity,Bag=bags?new[]{new SavedCount{Id="bandage",Count=2},new SavedCount{Id="water",Count=2},new SavedCount{Id="ration",Count=2}}:Array.Empty<SavedCount>()}).ToArray();
  CampaignPersistence.Prepare(s,catalog);SceneManager.LoadScene("Settlement");await Task.Delay(700);
 }
 public static async Task<string> Rest(){await Load();C.WorkPanel.Open();await Tap(C.WorkPanel.Rows[0].Button);foreach(var t in C.WorkPanel.View.GetComponentsInChildren<Text>())Fits(t);await Shot("61-rest-grouped");await Tap(C.WorkPanel.Confirm);Check(C.WorkPanel.Orders.Count==1,"Rest did not reserve");C.WorkPanel.Open();await Tap(C.WorkPanel.Rows[0].Button);foreach(var t in C.WorkPanel.View.GetComponentsInChildren<Text>())Fits(t);await Tap(C.WorkPanel.Confirm);Check(C.WorkPanel.Orders.Count==0,"Rest cancellation failed");await Load(6);C.WorkPanel.Open();await Task.Delay(150);var nav=C.WorkPanel.Scroll.GetComponent<ScrollNavigation>();Check(nav.Down.gameObject.activeSelf&&nav.Down.interactable,"Missing six-person rest scroll");await Tap(nav.Down);await Tap(C.WorkPanel.Rows.Last().Button);await Shot("62-rest-six-last");C.WorkPanel.Close();return "PASS rest details fit, reservation/cancel, six-person scroll and actual last-person click.";}
 public static async Task<string> Packing(){await Load();var p=C.PackingPanel;var d=C.ExpeditionPanel.Destinations.First(x=>x.Id=="mall");p.Open(C.Campaign.Party.ToArray(),d,null);await Tap(p.Ready);Fits(p.Summary);Fits(p.DepartureNotice);Fits(p.ReviewDestination);Check(p.Summary.text.Contains("빈 가방")&&p.DepartureNotice.text.Contains(d.OneWayMinutes+"분"),"Missing empty/travel state");Check(!p.ReviewScroll.GetComponent<ScrollNavigation>().Down.gameObject.activeSelf,"Two empty bags unnecessarily overflow");await Shot("63-packing-two");await Tap(p.ReviewBack);p.Close();await Load(6,true);p=C.PackingPanel;p.Open(C.Campaign.Party.ToArray(),d,null);await Tap(p.Ready);Fits(p.DepartureNotice);var nav=p.ReviewScroll.GetComponent<ScrollNavigation>();Check(nav.Down.IsActive(),"Six-person review missing scrolling");for(int i=0;i<8&&nav.Down.IsInteractable();i++)await Tap(nav.Down);Check(p.ReviewScroll.verticalNormalizedPosition<.001f,"Cannot reach last member");await Shot("64-packing-six-bottom");await Tap(p.ReviewBack);p.Close();return "PASS two empty bags fit, six filled bags scroll to last member, fixed travel cost remains visible and return button works.";}
 public static async Task<string> Loot(){await Load(2,true);var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(x=>x.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);await Task.Delay(250);var s=a.Loot.State(0);s.Complete=s.Opened=true;s.Progress=s.Required=2;s.Loot.Clear();s.Loot["wood"]=10;a.Loot.Open(0);await Tap(a.Loot.FieldRows[0].Button);Check(!a.Loot.Transfer.IsInteractable(),"Full bag must block new type");Fits(a.Loot.Message);Check(a.Loot.Message.text.Contains("다른 대원"),"Missing recovery action");await Shot("65-loot-full-guidance");var second=a.Participants[1];C.InventoryPanel.TransferField(second,"ration",2,false);await Tap(a.Loot.Cards[1].Button);Check(a.Loot.Transfer.IsInteractable(),"Switching member did not permit transfer");await Tap(a.Loot.Transfer);Check(C.InventoryPanel.CountFor(second,"wood")==1,"Transfer failed");return "PASS full-bag reason + next action fit, alternate member accepts item and inventory updates.";}
 public static async Task<string> Recipients(){await Load(6,true);var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(x=>x.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);await Task.Delay(250);a.FieldBags.Open(0);var p=a.FieldBags;await Tap(p.LeftRows.First(r=>r.Label.text=="붕대").Button);Fits(p.UseHint);Fits(p.Message);var scroll=p.RightMembers.GetComponentInParent<ScrollRect>();var nav=scroll.GetComponent<ScrollNavigation>();Check(!nav.Down.IsActive(),"Five recipients should fit without scrolling");for(int i=0;i<8&&nav.Down.IsInteractable();i++)await Tap(nav.Down);int before=C.InventoryPanel.CountFor(a.Participants.Last(),"bandage");await Shot("66-bag-six-recipient");await Tap(p.RightCards.Last().Button);Check(C.InventoryPanel.CountFor(a.Participants.Last(),"bandage")==before+1,"Last recipient failed");await Tap(p.LeftCards.Last().Button);Check(p.Source==a.Participants.Last(),"Name tab failed");await Shot("67-bag-last-owner");return "PASS six name tabs, five recipients fit, last member direct transfer, profile changes with selected owner.";}
 public static async Task<string> SystemPanels(){await Load();C.GameMenu.Open();Check(Mathf.Abs(C.GameMenu.View.transform.Find("Dim").GetComponent<Image>().color.a-.97f)<.01f,"Menu dim");await Shot("68-menu-dim");await Tap(C.GameMenu.Settings);Check(Mathf.Abs(C.GameMenu.SettingsDialog.GetComponent<Image>().color.a-.97f)<.01f,"Settings dim");await Shot("69-settings-dim");await Tap(C.GameMenu.SettingsDialog.Cancel);CampaignSaveStore.TestDirectory=Path.GetFullPath("Temp/UIAuditSlots");try{await Tap(C.GameMenu.Save);Check(Mathf.Abs(C.GameMenu.SavePanel.transform.Find("Dim").GetComponent<Image>().color.a-.97f)<.01f,"Save dim");await Shot("70-save-dim");C.GameMenu.SavePanel.Close();}finally{CampaignSaveStore.TestDirectory=null;}C.GameMenu.Close();return "PASS menu/settings/save main dim .97, navigation restored, no player saves/settings written.";}
 static SettlementTutorialGuide G=>C.GetComponent<SettlementTutorialGuide>();
 public static async Task<string> GuideEdges(){
  await Load();C.Opening.State.Enabled=true;C.Opening.State.FirstReturn=true;C.WorkPanel.Open();await Tap(C.WorkPanel.Rows[0].Button);await Tap(C.WorkPanel.Confirm);C.WorkPanel.Open();await Tap(C.WorkPanel.Rows[0].Button);Check(G.Target==C.WorkPanel.CloseButton,"Tutorial asked to cancel an existing rest");await Shot("71-guide-rest-reserved");C.WorkPanel.Close();
  C.WorkPanel.Open();await Tap(C.WorkPanel.Rows[1].Button);await Tap(C.WorkPanel.Confirm);foreach(var m in C.CraftPanel.Materials)m.Initial=0;C.CraftPanel.Materials.First(m=>m.Id=="wood").Initial=2;C.CraftPanel.Materials.First(m=>m.Id=="scrap").Initial=1;C.Development.State.Warehouse=0;C.Opening.Evaluate();Check(C.Opening.ActionText=="작업 시간 확인","All-busy project did not route to time");
  await Load(2,true);var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(x=>x.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);C.Opening.State.Enabled=true;C.Opening.State.FirstReturn=false;C.Opening.State.Complete=false;
  var s=a.Loot.State(0);s.Complete=s.Opened=true;s.Progress=s.Required=2;s.Loot.Clear();s.Loot["wood"]=5;a.Loot.Open(0);await Task.Delay(250);Check(G.Target==a.Loot.Back,"Full party must offer leave");await Tap(G.Target);Check(G.Target==a.Loot.LeaveConfirm,"Full-party leave confirmation loops");Fits(G.Instruction);await Shot("72-guide-full-bags");await Tap(a.Loot.LeaveCancel);
  C.InventoryPanel.TransferField(a.Participants[1],"ration",2,false);await Tap(a.Loot.FieldRows[0].Button);Check(G.Target==a.Loot.Cards[1].Button,"No specific alternate carrier guide");await Tap(G.Target);Check(G.Target==a.Loot.Max,"No quantity guide after changing carrier");await Tap(G.Target);await Tap(G.Target);Check(C.InventoryPanel.CountFor(a.Participants[1],"wood")==5,"Guided carry failed");
  await Load();C.Opening.State.Enabled=true;C.Opening.State.FirstReturn=true;C.Development.State.Warehouse=1;C.Development.State.Workbench=true;C.Opening.State.ClueRead=false;C.Opening.Evaluate();C.Opening.Act();await Task.Delay(150);Check(C.Opening.View.activeSelf&&G.Target==C.Opening.Back,"Record close instruction missing");await Shot("73-guide-record");await Tap(G.Target);Check(!C.Opening.View.activeSelf,"Record close blocked");
  return "PASS reserved rest never suggests cancellation, all-busy projects route to time, full-party loot exit has no loop, specific alternate carrier and quantity transfer, management-record close guide.";
 }
 public static async Task<string> Resolutions(){
  const System.Reflection.BindingFlags F=System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance;
  var assembly=typeof(Editor).Assembly;var st=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(st);var sizes=singleton.GetProperty("instance",System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.Static).GetValue(null);var group=st.GetMethod("GetGroup",F).Invoke(sizes,new[]{st.GetProperty("currentGroupType",F).GetValue(sizes)});var view=EditorWindow.GetWindow(assembly.GetType("UnityEditor.GameView"));var selected=view.GetType().GetProperty("selectedSizeIndex",F);int original=(int)selected.GetValue(view);var results=new List<string>();
  try{foreach(var wh in new[]{new Vector2Int(1280,720),new Vector2Int(1920,1200),new Vector2Int(2560,1080)}){
   var sizeType=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");int count=(int)group.GetType().GetMethod("GetTotalCount",F).Invoke(group,null),index=-1;
   for(int i=0;i<count;i++){var size=group.GetType().GetMethod("GetGameViewSize",F).Invoke(group,new object[]{i});if((int)sizeType.GetProperty("width",F).GetValue(size)==wh.x&&(int)sizeType.GetProperty("height",F).GetValue(size)==wh.y){index=i;break;}}
   if(index<0){var size=Activator.CreateInstance(sizeType,F,null,new object[]{Enum.ToObject(kind,1),wh.x,wh.y,"Review "+wh.x+"x"+wh.y},null);group.GetType().GetMethod("AddCustomSize",F).Invoke(group,new[]{size});index=count;}
   selected.SetValue(view,index);view.Repaint();await Task.Delay(400);Check(Screen.width==wh.x&&Screen.height==wh.y,"Resolution not applied");
   await Load();C.Opening.State.Enabled=true;C.WorkPanel.Open();await Tap(C.WorkPanel.Rows[0].Button);Fits(G.Title);Fits(G.Instruction);await Shot("74-rest-"+wh.x+"x"+wh.y);await Tap(G.Target);Check(C.WorkPanel.Orders.Count==1,"Guided rest failed at "+wh);C.WorkPanel.Cancel(C.Campaign.Party.First());
   C.Opening.State.Enabled=false;C.PackingPanel.Open(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall"),null);await Tap(C.PackingPanel.Ready);Fits(C.PackingPanel.DepartureNotice);Fits(C.PackingPanel.ReviewDestination);await Shot("75-review-"+wh.x+"x"+wh.y);await Tap(C.PackingPanel.ReviewBack);C.PackingPanel.Close();
   await Load(6,true);var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);a.FieldBags.Open(0);await Tap(a.FieldBags.LeftRows.First(r=>r.Label.text=="붕대").Button);await Tap(a.FieldBags.RightCards.Last().Button);await Shot("76-six-bags-"+wh.x+"x"+wh.y);results.Add(wh.x+"x"+wh.y);
  }}finally{selected.SetValue(view,original);view.Repaint();}
  return "PASS actual UI raycasts and text fit for rest + tutorial, travel review, 6-person bag last-recipient transfer at "+string.Join(", ",results)+"; previous Game View size restored.";
 }
 [Serializable] class Envelope {public string Magic,Payload,Hash;}
 static string Encode(CampaignSaveData data){string payload=JsonUtility.ToJson(data);using(var sha=System.Security.Cryptography.SHA256.Create())return JsonUtility.ToJson(new Envelope{Magic="NEIGHBOR-NOT-SAVE",Payload=payload,Hash=Convert.ToBase64String(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(payload)))});}
 public static async Task<string> SaveFailures(){
  await Load(6,true);var owner=C;var saved=CampaignPersistence.Capture(C);string path=Path.GetFullPath("Temp/UIAuditSlots");Directory.CreateDirectory(path);CampaignSaveStore.TestDirectory=path;var files=Enumerable.Range(0,3).Select(i=>CampaignSaveStore.SlotPath(i)).ToArray();var original=files.Select(f=>File.Exists(f)?File.ReadAllBytes(f):null).ToArray();
  try{
   Check(CampaignSaveStore.Write(0,saved,C,out var error),error);File.WriteAllText(files[1],"{ invalid-save }");var future=JsonUtility.FromJson<CampaignSaveData>(JsonUtility.ToJson(saved));future.Version=999;File.WriteAllText(files[2],Encode(future));
   C.GameMenu.Open();await Tap(C.GameMenu.Load);var p=C.GameMenu.SavePanel;await Tap(p.Slots[1]);Check(!p.Action.IsInteractable()&&p.SlotDetails[1].text.Length>0,"Corrupt save selectable");await Tap(p.Slots[2]);Check(!p.Action.IsInteractable()&&p.SlotDetails[2].text.Contains("버전"),"Future version must explain failure");foreach(var t in p.SlotDetails)Fits(t);await Shot("77-load-errors");
   await Tap(p.Slots[0]);await Tap(p.Action);Check(p.Review.activeSelf,"Load confirmation absent");File.WriteAllText(files[0],"file changed after confirmation");await Tap(p.Confirm);Check(C==owner&&!p.Review.activeSelf&&!p.Action.IsInteractable()&&p.Hint.text.Length>0,"Stale save confirmation advanced scene");Fits(p.Hint);await Shot("78-load-changed-file");await Tap(p.Back);C.GameMenu.Close();
   Check(CampaignSaveStore.Write(0,saved,C,out error),error);var loaded=CampaignSaveStore.Read(0,C);Check(loaded.CanLoad,loaded.Error);Check(loaded.Data.Members.Length==6&&loaded.Data.Members.All(m=>m.Bag.Length==3),"Six-person save lost bags");
   var before=File.ReadAllBytes(files[0]);saved.Members[0].Health=-1;Check(!CampaignSaveStore.Write(0,saved,C,out error)&&File.ReadAllBytes(files[0]).SequenceEqual(before),"Invalid save replaced valid record");
  }finally{for(int i=0;i<files.Length;i++){if(original[i]!=null)File.WriteAllBytes(files[i],original[i]);else if(File.Exists(files[i]))File.Delete(files[i]);}CampaignSaveStore.TestDirectory=null;}
  return "PASS corrupt/future-version UI explains failure and blocks load; file changed after confirmation is re-read; invalid overwrite preserves valid file; six-person bags survive disk write/read. Test slots restored, player saves untouched.";
 }
 public static async Task<string> BattleIcon(){await Load(2,true);var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);var e=a.Encounter;e.OpenThreat("아이템 색상 검수", "감염자", null);await Task.Delay(200);await Tap(e.Fight);await Task.Delay(1500);await Tap(e.Battle.Items);await Task.Delay(200);Check(e.Battle.Drawer.DetailIcon.color==Color.white,"Original item art tinted black");await Shot("79-battle-item-colour");return "PASS existing battle item drawer retains source sprite colours; no combat rule changes.";}
 public static async Task<string> SixPersonReturn(){await Load(6,true);foreach(var material in C.CraftPanel.Materials)material.Initial=0;C.CraftPanel.Materials.First(m=>m.Id=="wood").Initial=C.Development.Capacity-2;var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);await Tap(a.Return);await Tap(a.ReturnConfirm);Check(C.ReturnPanel.IsOpen,"No return report");var p=C.ReturnPanel;Canvas.ForceUpdateCanvases();var memberNav=p.MemberScroll.GetComponent<ScrollNavigation>();Check(memberNav.Down.IsActive(),"No return scroll arrows");for(int n=0;n<4&&memberNav.Down.IsInteractable();n++)await Tap(memberNav.Down);Check(p.MemberScroll.verticalNormalizedPosition<.001f,"Cannot reach last returned member");p.Scroll.verticalNormalizedPosition=0;await Task.Delay(150);foreach(var t in p.View.GetComponentsInChildren<Text>())if(t.gameObject.activeInHierarchy)Fits(t);Check(p.MemberContent.childCount==6,"Return missing members");await Shot("80-return-six-bottom");int before=C.Campaign.Party.Sum(person=>C.InventoryPanel.CountFor(person,"bandage"))+C.InventoryPanel.StockCount("bandage");await Tap(p.StoreAll);int after=C.Campaign.Party.Sum(person=>C.InventoryPanel.CountFor(person,"bandage"))+C.InventoryPanel.StockCount("bandage");Check(before==after,"Store all changed totals");Check(!p.StoreAll.IsInteractable()&&p.Notice.text.Contains("가득"),"Full storage offers a useless action");Fits(p.Notice);await Shot("86-return-stock-full");await Tap(p.Back);C.ReturnPanel.Open();Check(before==C.Campaign.Party.Sum(person=>C.InventoryPanel.CountFor(person,"bandage"))+C.InventoryPanel.StockCount("bandage"),"Report reopened grants resources");await Tap(p.InspectBags);Check(C.InventoryPanel.IsOpen,"Return bag link failed");C.InventoryPanel.Close();return "PASS six-person return and item scroll to bottom, storage preserves totals, reopening grants nothing, bag link works.";}
 public static async Task<string> ManyWorkOrders(){await Load(6);var before=CampaignPersistence.Capture(C);before.Opening.Enabled=false;before.Opening.Complete=false;before.Rest=before.Members.Select((m,i)=>new SavedRest{MemberId=m.Id,Name="짧은 휴식",Minutes=30+i*15,Recovery=1}).ToArray();CampaignPersistence.Prepare(before,C);SceneManager.LoadScene("Settlement");await Task.Delay(500);C.TimePanel.Open();await Tap(C.TimePanel.Choices[3]);var nav=C.TimePanel.Scroll.GetComponent<ScrollNavigation>();Check(nav.Down.IsActive(),"No work-list arrows");for(int n=0;n<10&&nav.Down.IsInteractable();n++)await Tap(nav.Down);Check(C.TimePanel.Scroll.verticalNormalizedPosition<.001f,"Cannot reach last work result");await Task.Delay(100);foreach(var row in C.TimePanel.Content.GetComponentsInChildren<TimeWorkRow>()){Fits(row.Title);Fits(row.Detail);Fits(row.Result);}await Shot("81-time-six-orders");await Tap(C.TimePanel.Confirm);Check(C.WorkPanel.Orders.Count==5,"Only next completion must finish");foreach(var row in C.TimePanel.Content.GetComponentsInChildren<TimeWorkRow>()){Fits(row.Title);Fits(row.Detail);Fits(row.Result);}await Tap(C.TimePanel.CloseButton);return "PASS six simultaneous orders, scroll last result, next completion finishes one and keeps five pending.";}
 public static async Task<string> RecordsAndNight(){await Load(6);var o=C.Opening;o.State.Enabled=true;o.State.FirstReturn=o.State.ClueRead=o.State.SurveyReturned=o.State.Complete=true;C.Opening.OpenRecords();for(int i=0;i<3;i++){await Tap(o.RecordTabs[i]);Fits(o.RecordTitle);Fits(o.RecordBody);Fits(o.RecordStatus);}await Shot("82-records-six");await Tap(o.RecordsBack);C.Campaign.AdvanceSettlementTime((1200-C.Campaign.MinuteOfDay+1440)%1440);o.Evaluate();await Task.Delay(100);await Tap(C.Introduction.Action);Fits(o.NightBody);Fits(o.NightResult);await Shot("83-night-choice");int minute=C.Campaign.MinuteOfDay;await Tap(o.NightLook);Check(C.Campaign.MinuteOfDay==(minute+30)%1440&&o.State.NightChoice==2,"Night choice did not apply");Fits(o.NightBody);Fits(o.NightResult);await Shot("84-night-result");await Tap(o.NightBack);await Tap(C.Journal);Check(o.RecordTabs[3].gameObject.activeSelf&&!o.RecordsContinue.gameObject.activeSelf,"Resolved night state wrong");Fits(o.RecordBody);await Shot("85-night-record");await Tap(o.RecordsBack);return "PASS six-person records, night choice/result/body fit, 30-minute choice, resolved record without replay.";}
 public static async Task<string> ToolBagEdges(){
  await Load(2,true);C.Opening.State.Enabled=true;C.Opening.State.FirstReturn=C.Opening.State.ClueRead=true;C.Opening.State.SurveyReturned=false;C.Development.State.Warehouse=1;C.Development.State.Workbench=true;foreach(var m in C.CraftPanel.Materials)m.Initial=0;C.CraftPanel.Materials.First(m=>m.Id=="prybar").Initial=1;C.Opening.Evaluate();C.InventoryPanel.Open();await Task.Delay(150);
  bool max=false;for(int i=0;i<12&&!C.Campaign.Party.Any(p=>C.InventoryPanel.CountFor(p,"prybar")>0);i++){Check(G.Target,"Missing tool target "+G.Guidance);max|=G.Target==C.InventoryPanel.Max;await Tap(G.Target);}Check(max&&C.Campaign.Party.Any(p=>C.InventoryPanel.CountFor(p,"prybar")>0),"Full-bag guide did not empty a stack and take tool");await Shot("87-guide-tool-room");C.InventoryPanel.Close();
  await Load(2,true);C.Opening.State.Enabled=true;C.Opening.State.FirstReturn=C.Opening.State.ClueRead=true;C.Opening.State.SurveyReturned=false;C.Development.State.Warehouse=1;C.Development.State.Workbench=true;foreach(var m in C.CraftPanel.Materials)m.Initial=0;C.CraftPanel.Materials.First(m=>m.Id=="prybar").Initial=1;C.CraftPanel.Materials.First(m=>m.Id=="wood").Initial=C.Development.Capacity-2;C.Opening.Evaluate();C.InventoryPanel.Open();await Task.Delay(150);Check(G.Target==C.InventoryPanel.CloseButton&&G.Instruction.text.Contains("부족"),"Partial-stack storage would not free a slot");Fits(G.Instruction);await Shot("88-guide-no-room");C.InventoryPanel.Close();return "PASS both bags full: whole-stack Max -> store -> carry prybar; insufficient room to store a complete stack gives a clear recovery instruction without looping.";
 } public static async Task<string> ReturnManyItems(){
  await Load(6);var data=CampaignPersistence.Capture(C);var kinds=C.InventoryPanel.Items.Where(item=>item.Id!="ammo"&&item.Id!="supplies").Take(18).ToArray();for(int i=0;i<data.Members.Length;i++)data.Members[i].Bag=kinds.Skip(i*3).Take(3).Select(item=>new SavedCount{Id=item.Id,Count=1}).ToArray();CampaignPersistence.Prepare(data,C);SceneManager.LoadScene("Settlement");await Task.Delay(500);
  var a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);await Tap(a.Return);await Tap(a.ReturnConfirm);var p=C.ReturnPanel;var nav=p.Scroll.GetComponent<ScrollNavigation>();Check(nav.Down.IsActive(),"Many item types have no scroll control");for(int i=0;i<10&&nav.Down.IsInteractable();i++)await Tap(nav.Down);Check(p.Scroll.verticalNormalizedPosition<.001f,"Item list cannot reach bottom");foreach(var row in p.ItemContent.GetComponentsInChildren<ReturnItemRow>()){Fits(row.Name);Fits(row.Before);Fits(row.After);Fits(row.Change);}await Shot("89-return-many-items");await Tap(p.Back);
  await Load();a=C.ArrivalPanel;a.Begin(C.Campaign.Party.ToArray(),C.ExpeditionPanel.Destinations.First(d=>d.Id=="mall"));for(int i=0;i<70&&a.InTransit;i++)await Task.Delay(100);await Tap(a.Return);await Tap(a.ReturnConfirm);p=C.ReturnPanel;Check(!p.StoreAll.IsInteractable()&&p.EmptyItems.gameObject.activeInHierarchy,"Empty return state wrong");Check(!p.Scroll.GetComponent<ScrollNavigation>().Down.IsActive()&&!p.MemberScroll.GetComponent<ScrollNavigation>().Down.IsActive(),"Empty return has unnecessary scroll");await Shot("90-return-empty");await Tap(p.Back);C.TimePanel.Open();Check(C.TimePanel.NextCompletion()==0&&!C.TimePanel.Choices[3].IsInteractable(),"Empty work list offers next job");await Tap(C.TimePanel.CloseButton);return "PASS return with "+kinds.Length+" item types scrolls to last row, columns fit; two empty bags hide scroll and disable store; no next-completion action without work.";
 }}









