using System;using System.Linq;using System.Threading.Tasks;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEngine.SceneManagement;using Demo5.FrontEnd;using Demo5.NightRun;using Object=UnityEngine.Object;
public static class VerifyOpeningChapter {
 static SettlementController C()=>Object.FindAnyObjectByType<SettlementController>();
 static void Check(bool v,string s){if(!v)throw new Exception(s);}
 static async Task Tap(Button b){await Task.Delay(100);Canvas.ForceUpdateCanvases();Check(b&&b.IsActive()&&b.IsInteractable(),"Unavailable "+b?.name);var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);if(b.GetComponent<SettlementFacilityFocus>()&&(hits.Count==0||hits[0].gameObject.GetComponentInParent<Button>()!=b)){bool found=false;for(int y=1;y<10&&!found;y++)for(int x=1;x<10&&!found;x++){e.position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(new Vector3(r.rect.xMin+r.rect.width*x/10f,r.rect.yMin+r.rect.height*y/10f,0)));hits.Clear();EventSystem.current.RaycastAll(e,hits);found=hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b;}}Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name+" by "+hits.FirstOrDefault().gameObject?.name);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(100);}
 static async Task Finish(){var c=C();await Tap(c.Advance);await Tap(c.TimePanel.Choices[3]);await Tap(c.TimePanel.Confirm);await Tap(c.TimePanel.CloseButton);}
 static async Task RoundTrip(){var c=C();var saved=CampaignPersistence.Capture(c);CampaignSaveStore.TestDirectory=System.IO.Path.GetFullPath("Temp/OpeningChapterVerification");try{Check(CampaignSaveStore.Write(0,saved,c,out string error),error);var read=CampaignSaveStore.Read(0,c);Check(read.CanLoad,read.Error);CampaignPersistence.Prepare(read.Data,c);}finally{CampaignSaveStore.TestDirectory=null;}SceneManager.LoadScene("Settlement");await Task.Delay(650);}
 public static async Task<string> Fresh(){var roster=C().Roster;CampaignPersistence.ClearPending();PartySelectionSession.Clear();var campaign=new CampaignState(roster.Candidates.Select(x=>new Adventurer(x.DisplayName,x.RoleTitle,x.Description,x.Health,x.Aim,x.BagCapacity)).ToArray(),true);campaign.Toggle(0);campaign.Toggle(1);campaign.ConfirmParty();campaign.Settle(0);PartySelectionSession.Selected.AddRange(new[]{"scout","mechanic"});PartySelectionSession.Pending=campaign;SceneManager.LoadScene("Settlement");await Task.Delay(650);var c=C();Check(c.Opening.Active&&c.Introduction.Step==0&&c.CraftPanel.Materials.All(m=>m.Initial==0),"Fresh empty chapter");await Tap(c.Introduction.Action);await Tap(c.Introduction.Action);await RoundTrip();c=C();Check(c.Introduction.Step==2&&c.CraftPanel.Available("cloth")==1&&c.Opening.Active,"Fresh save restore");await Tap(c.Introduction.Action);await Tap(c.Bed);await Tap(c.WorkPanel.Rows[0].Button);await Tap(c.WorkPanel.Confirm);await Finish();await Tap(c.Cabinet);await Tap(c.InventoryPanel.CloseButton);Check(c.Introduction.Step==5&&c.Opening.GoalTitle.Contains("첫 외출"),"First goal");return "PASS new campaign, empty materials, intro UI, rest, save/restore and first expedition goal.";}
 static async Task Depart(){var c=C();await Tap(c.Introduction.Action);Check(c.ExpeditionPanel.IsOpen,"Goal opens expedition");var p=c.ExpeditionPanel;await Tap(p.Markers[Array.FindIndex(p.Destinations,d=>d.Id=="mall")]);foreach(var card in p.Cards.ToArray())if(!card.Check.gameObject.activeSelf)await Tap(card.Button);await Tap(p.Pack);await Tap(c.PackingPanel.Ready);await Tap(c.PackingPanel.Depart);for(int i=0;i<40&&c.ArrivalPanel.InTransit;i++)await Task.Delay(100);Check(c.ArrivalPanel.IsOpen,"Departure");}
 // 말 놓기 (2026-09-25): both visits place pawns (FieldPawnTest: two on the object = 함께) and pass turns with '턴 진행' only; the 07 window
 // (a right press) only shows. After a meeting the plan ends: the pawns are placed again.
 static async Task Ready(ExpeditionArrivalPanel a){for(int i=0;i<60&&!FieldPawnTest.Ready(a)&&!a.Encounter.IsOpen&&!a.Loot.IsOpen;i++)await Task.Delay(50);}
 static async Task Search(int site){var a=C().ArrivalPanel;var pl=a.Threat.Planner;await Ready(a);Check(FieldPawnTest.Detail(a,site)&&a.Search.IsOpen&&a.Search.ReadOnly,"07 read only "+site);await Tap(a.Search.Back);for(int i=0;i<8&&!(a.Loot.IsOpen&&a.Loot.Peek(site,out var s0)&&s0.Complete);i++){await Ready(a);if(!a.Loot.IsOpen&&!a.Encounter.IsOpen){if(FieldPawnTest.Check(a)?.RunFor(site)==null)Check(FieldPawnTest.Coop(a,site),"Pawns on "+a.ObjectNames[site]+": "+FieldPawnTest.Describe(a));await Task.Delay(250);await Tap(pl.TurnButton);}await Task.Delay(300);for(int wait=0;a.Encounter.IsOpen&&wait<20;wait++){await Tap(a.Encounter.Wait);await Tap(a.Encounter.Confirm);await Task.Delay(200);}Check(!a.Encounter.IsOpen,"Encounter did not clear");}Check(a.Loot.IsOpen&&a.Loot.Peek(site,out var s1)&&s1.Complete,"Search complete "+site);}
 static async Task TakeLoot(){var c=C();var a=c.ArrivalPanel;while(a.Loot.FieldRows.Count>0){var row=a.Loot.FieldRows[0];await Tap(row.Button);for(int k=0;!a.Loot.Transfer.interactable&&k<a.Loot.Cards.Count;k++)await Tap(a.Loot.Cards[k].Button);await Tap(a.Loot.Max);await Tap(a.Loot.Transfer);}await Tap(a.Loot.Back);}
 // Every pawn at the door onto `next` (the locked storage door needs the carried prybar), '턴 진행', the walk (ExpeditionRoomNavigation.Queue.cs).
 static async Task Move(ExpeditionArrivalPanel a,int next){await Ready(a);Check(FieldPawnTest.Gather(a,next),"Everyone at the door to "+next+": "+FieldPawnTest.Describe(a));await Tap(a.Threat.Planner.TurnButton);for(int i=0;i<80&&a.InTransit;i++)await Task.Delay(100);await Task.Delay(300);Check(a.Rooms.CurrentRoom==next,"Moved to "+next);}
 static async Task Return(){var c=C();await Tap(c.ArrivalPanel.Return);await Tap(c.ArrivalPanel.ReturnConfirm);await Tap(c.ReturnPanel.StoreAll);await Tap(c.ReturnPanel.Back);}
 // The crate's extra rows (50%) decide which kinds fit the 12-slot stock; pin them so the fixture follows one path (the chain itself only needs the 100% rows).
 public static async Task<string> FirstTrip(){await Depart();var crate=C().ArrivalPanel.Loot.Sites[0].Drops;var chances=crate.Select(d=>d.Chance).ToArray();try{for(int i=0;i<crate.Length;i++)crate[i].Chance=100;await Search(0);}finally{for(int i=0;i<crate.Length;i++)crate[i].Chance=chances[i];}await TakeLoot();await Return();var c=C();Check(c.Opening.State.FirstReturn&&!c.Opening.State.ClueRead&&c.Opening.GoalTitle.Contains("둘 자리"),"Return goal");Check(c.Development.StockUsed==12,"Capacity kept");await RoundTrip();Check(C().Opening.State.FirstReturn,"First return persisted");return "PASS actual plan/packing/departure/search/loot/return UI; stock cap and persistent next restoration goal.";}
 static async Task QueueGoal(string id){var c=C();c.Opening.Evaluate();await Tap(c.Introduction.Action);Check(c.CraftPanel.IsOpen,"Goal opens crafting "+id);await Tap(c.CraftPanel.WorkerRows.First(r=>r.Button.IsInteractable()).Button);await Tap(c.CraftPanel.Confirm);Check(c.CraftPanel.Orders.Any(o=>o.Recipe.Id==id),"Queued "+id);await Finish();}
 static void Unpack(){var c=C();foreach(var p in c.Campaign.Party)foreach(var i in c.InventoryPanel.Items){int n=c.InventoryPanel.TransferLimit(p,i.Id,false);if(n>0)Check(c.InventoryPanel.MoveFor(p,i.Id,n,false),"Unpack");}}
 public static async Task<string> RestoreFacilities(){var c=C();await Tap(c.Introduction.Action);Check(c.InventoryPanel.IsOpen,"Missing stock guides to inventory");await Tap(c.InventoryPanel.CloseButton);
 // Real inventory transfers only: free temporary shelf space, preserving every recovered item.
 foreach(var m in c.CraftPanel.Materials.ToArray())if(m.Initial>0){var p=c.Campaign.Party.First(x=>c.InventoryPanel.TransferLimit(x,m.Id,true)>=m.Initial);Check(c.InventoryPanel.MoveFor(p,m.Id,m.Initial,true),"Withdraw for sorting");}
 foreach(var pair in new[]{new{Id="wood",Count=2},new{Id="scrap",Count=1}}){var p=c.Campaign.Party.First(x=>c.InventoryPanel.CountFor(x,pair.Id)>=pair.Count);Check(c.InventoryPanel.MoveFor(p,pair.Id,pair.Count,false),"Deposit recipe");}
 await QueueGoal("build-stock");Unpack();await Task.Delay(150);await QueueGoal("build-bench");c=C();Check(c.Development.State.Warehouse==1&&c.Development.State.Workbench&&!c.Opening.State.ClueRead,"Facilities built from recovered supplies");await RoundTrip();c=C();Check(c.Opening.GoalTitle.Contains("첫 사건"),"Clue ready after reload");await Tap(c.Introduction.Action);Check(c.Opening.State.ClueRead&&c.Opening.EventTitle.text=="접힌 관리표","Clue read");return "PASS warehouse/workbench built only from actual salvage, overflow retained, save roundtrip, first narrative event opened.";}
 public static async Task<string> Tool(){var c=C();if(c.Opening.IsOpen)await Tap(c.Opening.Back);await RoundTrip();c=C();Check(c.Opening.State.ClueRead&&!c.Opening.State.Complete,"Clue preserved");await QueueGoal("rope");await QueueGoal("nails");await QueueGoal("nails");await QueueGoal("prybar");c=C();Check(c.InventoryPanel.StockCount("prybar")==1&&c.Opening.ActionText=="지렛대 챙기기","Crafted tool goal");await Tap(c.Introduction.Action);Check(c.InventoryPanel.IsOpen,"Tool packing opens bag");var inv=c.InventoryPanel;await Tap(inv.StockRows.First(r=>r.Label.text==inv.Items.First(i=>i.Id=="prybar").Name).Button);await Tap(inv.ToBag);await Tap(inv.Confirm);await Tap(inv.CloseButton);Check(c.Campaign.Party.Any(p=>inv.CountFor(p,"prybar")==1),"Tool actually carried");await RoundTrip();return "PASS clue persists without replay, rope/nails/prybar made from salvage, real UI packs tool, bag and goal persisted.";}
 public static async Task<string> SecondTrip(){FieldIdleConfirm.AutoAccept=true;await Depart();var a=C().ArrivalPanel;for(int i=0;i<20&&!a.Popup.activeSelf;i++)await Task.Delay(50);Check(a.Popup.activeSelf&&a.PopupTitle.text==a.Threat.IntroTitle,"Site board intro on the second visit");await Tap(a.PopupBack);await Move(a,1);await Move(a,2);Check(a.Rooms.StorageUnlocked&&a.Rooms.StorageVisited,"Storage opened with real tool");await Search(6);await TakeLoot();await Move(a,1);await Move(a,0);await Return();var c=C();Check(c.Opening.State.SurveyReturned&&!c.Opening.State.Complete,"Survey returned");await RoundTrip();c=C();Check(c.Opening.State.SurveyReturned,"Survey saved");await Tap(c.Introduction.Action);Check(c.Opening.State.Complete&&c.Opening.EventTitle.text=="첫 생활을 이어갈 준비","Chapter completion");return "PASS second expedition, carried prybar unlock, shelf search, retained loot, return, save/restore, chapter conclusion.";}
 public static string Frame(){var c=C();var o=c.Opening;Canvas.ForceUpdateCanvases();Check(o.IsOpen&&c.Main.alpha==0,"Popup hides HUD");Check(o.EventBody.preferredHeight<=o.EventBody.rectTransform.rect.height,"Body clipping");var r=(RectTransform)o.Back.transform;Check(r.anchoredPosition==new Vector2(80,-974)&&r.sizeDelta==new Vector2(410,76),"Common footer");return "PASS common frame, HUD hidden, footer alignment and complete body fits.";}
 public static async Task<string> Persistence(){var c=C();if(c.Opening.IsOpen)await Tap(c.Opening.Back);await RoundTrip();c=C();Check(c.Opening.State.Complete&&!c.Introduction.Action.gameObject.activeSelf,"No replay after completion");var save=CampaignPersistence.Capture(c);save.Version=10;save.Opening=null;CampaignPersistence.Upgrade(save,c);Check(save.Version==CampaignPersistence.CurrentVersion&&!save.Opening.Enabled&&save.StorageVisited&&save.Development.Workbench,"Legacy preserves progress without replay");save.Opening=new SavedOpeningChapter{Enabled=true,Complete=true};bool blocked=false;try{CampaignPersistence.Validate(save,c);}catch(InvalidOperationException){blocked=true;}Check(blocked,"Reject invalid chapter state");return "PASS completed goal stays hidden, v10 migration leaves established campaign alone, invalid completion rejected.";}
}


