using System;using System.Linq;using System.Threading.Tasks;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using Demo5.FrontEnd;
public static class VerifyQuietFacilities {
 static SettlementController C()=>UnityEngine.Object.FindAnyObjectByType<SettlementController>();
 static async Task Tap(Button b){await Task.Delay(100);Canvas.ForceUpdateCanvases();if(!b.IsActive()||!b.IsInteractable())throw new Exception("Unavailable "+b.name);var focus=b.GetComponent<SettlementFacilityFocus>();var r=focus?(RectTransform)focus.Caption.transform:(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);if(hits.Count==0||hits[0].gameObject.GetComponentInParent<Button>()!=b)throw new Exception("Blocked "+b.name+" by "+hits.FirstOrDefault().gameObject);ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(150);}
 public static async Task<string> Run(){var c=C();if(c.CraftPanel.IsOpen)c.CraftPanel.Close();await Tap(c.Bed);await Tap(c.WorkPanel.CloseButton);await Tap(c.Stock);await Tap(c.CookingPanel.IsOpen?c.CookingPanel.Back:c.CraftPanel.CloseButton);await Tap(c.Workbench);await Tap(c.CraftPanel.CloseButton);await Tap(c.Cabinet);await Tap(c.InventoryPanel.CloseButton);await Tap(c.Exit);await Tap(c.ExpeditionPanel.Back);EventSystem.current.SetSelectedGameObject(null);var f=c.Workbench.GetComponent<SettlementFacilityFocus>();f.OnPointerEnter(new PointerEventData(EventSystem.current));await Task.Delay(100);if(!f.Focus.activeSelf||!f.Caption.activeSelf)throw new Exception("Hover missing");f.OnPointerExit(null);await Task.Delay(100);if(f.Focus.activeSelf||!f.Caption.activeSelf)throw new Exception("Exit stuck");InputSystem.QueueStateEvent(Keyboard.current,new KeyboardState(Key.LeftAlt));await Task.Delay(200);if(c.Main.GetComponentsInChildren<SettlementFacilityFocus>().Any(x=>!x.Focus.activeSelf))throw new Exception("Alt caption missing");InputSystem.QueueStateEvent(Keyboard.current,new KeyboardState());await Task.Delay(200);if(c.Main.GetComponentsInChildren<SettlementFacilityFocus>().Any(x=>x.Focus.activeSelf||!x.Caption.activeSelf))throw new Exception("Caption stuck after Alt");return "PASS five furniture raycast clicks and close; hover/exit; Alt reveal/release. Persistent tags remain; no circular bubbles.";}
 public static string Hover(){C().Workbench.GetComponent<SettlementFacilityFocus>().OnPointerEnter(new PointerEventData(EventSystem.current));return "Workbench hovered";}
}



