using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Demo5.FrontEnd;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using Object=UnityEngine.Object;
// 말 놓기 (2026-09-25, 기획/탐험-말놓기-조작-재설계.md): the first visit's searches are two pawns on the object (co-op) and '턴 진행' (a second
// press in the same moment costs nothing); the random encounter rolls once per search turn; the 07 window (a right press) only shows.
public static class VerifyEncounter {
 static void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 // A window that just opened lays out over a few frames: wait (≤1 s) until the button is up and takes the press.
 static async Task Settle(Button b){for(int w=0;w<20;w++){if(b&&b.IsActive()&&b.IsInteractable()){Canvas.ForceUpdateCanvases();var rr=(RectTransform)b.transform;var ee=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,rr.TransformPoint(rr.rect.center))};var hh=new List<RaycastResult>();EventSystem.current.RaycastAll(ee,hh);if(hh.Count>0&&hh[0].gameObject.GetComponentInParent<Button>()==b)return;}await Task.Delay(50);}}
 static async Task Tap(Button b){await Settle(b);Check(b.IsActive()&&b.IsInteractable(),"Unavailable "+b.name);Canvas.ForceUpdateCanvases();var r=(RectTransform)b.transform;var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(b.GetComponentInParent<Canvas>().worldCamera,r.TransformPoint(r.rect.center)),button=PointerEventData.InputButton.Left};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==b,"Blocked "+b.name+" by "+(hits.Count>0?hits[0].gameObject.name:"none"));ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);await Task.Delay(80);}
 static void Bounds(GameObject root){Canvas.ForceUpdateCanvases();foreach(var t in root.GetComponentsInChildren<Text>())Check(t.preferredHeight<=t.rectTransform.rect.height+1,"Text overflow "+t.name+": "+t.preferredHeight+" / "+t.rectTransform.rect.height);}




 static async Task<SettlementController> Depart(){var c=Object.FindAnyObjectByType<SettlementController>();await Tap(c.Exit);foreach(var card in c.ExpeditionPanel.Cards)if(!card.Check.gameObject.activeSelf)await Tap(card.Button);await Tap(c.ExpeditionPanel.Pack);await Tap(c.PackingPanel.Ready);await Tap(c.PackingPanel.Depart);await Task.Delay(950);return c;}
 static async Task Ready(ExpeditionArrivalPanel a){for(int i=0;i<60&&!FieldPawnTest.Ready(a);i++)await Task.Delay(50);Check(FieldPawnTest.Ready(a),"Board not ready");}
 // One '턴 진행' (pressed twice in one moment: one turn) with the pawns where they stand. s: unused (the 07 window no longer runs turns).
 static async Task Tick(ExpeditionSearchPanel s){var a=Object.FindAnyObjectByType<SettlementController>().ArrivalPanel;await Task.Delay(250);var turn=a.Threat.Planner.TurnButton;await Tap(turn);turn.onClick.Invoke();await Task.Delay(150);}
 static async Task Coop(ExpeditionArrivalPanel a,int site){await Ready(a);Check(FieldPawnTest.Coop(a,site),"Two pawns on "+a.ObjectNames[site]+": "+FieldPawnTest.Describe(a));}
 static async Task Select(ExpeditionLootPanel l,string name,bool bag=false){await Tap((bag?l.BagRows:l.FieldRows).First(r=>r.Label.text==name).Button);}

 public static async Task<string> Flow(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */var c=await Depart();var a=c.ArrivalPanel;var e=a.Encounter;var s=a.Search;int baseChance=e.BaseChance,maxChance=e.MaximumChance,wait=e.WaitChance,threshold=e.NoiseThreshold,warnAt=e.WarnSearches,grace=e.GraceSearches;var turnsBefore=a.Loot.Sites.Select(x=>x.Turns).ToArray();
 try{e.BaseChance=e.MaximumChance=100;e.NoiseThreshold=0;e.WarnSearches=1;e.GraceSearches=2;/* this flow counts two grace searches (balance 1 ships 3) *//* the old first-search warning; 함께 on turn fixtures keeps the old 2/3-turn searches */a.Loot.Sites[0].Turns=3;a.Loot.Sites[1].Turns=4;a.Loot.Sites[2].Turns=4;
 await Coop(a,0);await Tick(s);Check(e.Warned&&e.Banner.activeSelf&&!e.IsOpen&&e.Rolls==0,"First turn must warn, not encounter");int rolls=e.Rolls;Check(FieldPawnTest.Detail(a,0)&&s.ReadOnly,"07 read only");await Tap(s.Back);a.Objects[0].onClick.Invoke();await Task.Delay(100);Check(e.Rolls==rolls&&!s.IsOpen,"UI rolled encounter");await Tick(s);Check(e.IsOpen&&!s.IsOpen&&!a.Loot.IsOpen&&!a.Main.blocksRaycasts&&a.Loot.State(0).Complete,"Encounter did not suspend completed search");Check(e.Fight.interactable&&e.Battle,"Battle route missing");Bounds(e.View);int turn=a.Rooms.Turns;int count=a.Loot.State(0).Loot.Values.Sum();e.Escape();Check(e.IsOpen,"Escape skipped encounter");a.Rooms.AskMove();Check(!a.Popup.activeSelf,"Room bypass");await Tap(e.Wait);Bounds(e.Review);await Tap(e.Cancel);Check(a.Rooms.Turns==turn&&e.IsOpen,"Cancel charged/resolved");
 e.WaitChance=0;int seed=0;for(;seed<100;seed++){UnityEngine.Random.InitState(seed);if(UnityEngine.Random.Range(0,100)>=20)break;}UnityEngine.Random.InitState(seed);await Tap(e.Wait);await Tap(e.Confirm);e.Confirm.onClick.Invoke();Check(e.IsOpen&&a.Rooms.Turns==turn+1&&!e.Review.activeSelf,"Failed wait state/double charge");e.WaitChance=100; // prior failure lowers chance to 85; choose a passing seed.
 for(seed=0;seed<100;seed++){UnityEngine.Random.InitState(seed);if(UnityEngine.Random.Range(0,100)<85)break;}UnityEngine.Random.InitState(seed);await Tap(e.Wait);await Tap(e.Confirm);Check(!e.IsOpen&&a.Loot.IsOpen&&e.Cooldown==2&&a.Rooms.Turns==turn+2,"Successful wait did not resume loot");Check(a.Loot.State(0).Loot.Values.Sum()==count,"Encounter rerolled rewards");await Tap(a.Loot.Back);if(a.Loot.LeaveReview.activeSelf)await Tap(a.Loot.LeaveConfirm);
 await Coop(a,1);await Tick(s);await Tick(s);Check(!e.IsOpen&&e.Cooldown==0,"Grace period failed");await Tick(s);Check(!e.IsOpen&&e.Warned,"Grace must return to warning first");await Tap(a.Loot.Back);if(a.Loot.LeaveReview.activeSelf)await Tap(a.Loot.LeaveConfirm);
 if(c.InventoryPanel.CountFor(a.Participants[0],"prybar")==0)Check(c.InventoryPanel.TransferField(a.Participants[0],"prybar",1,true),"Prybar fixture");await Ready(a);Check(FieldPawnTest.Coop(a,2,0,0),"Two pawns on the machine");await Tick(s);Check(e.IsOpen&&!a.Loot.State(2).Complete,"Incomplete search encounter missing");int progress=a.Loot.State(2).Progress;turn=a.Rooms.Turns;await Tap(e.Retreat);await Tap(e.Confirm);e.Confirm.onClick.Invoke();Check(a.InTransit&&a.Rooms.Turns==turn+1,"Retreat not one movement turn");await Task.Delay(2400);Check(a.Rooms.CurrentRoom==1&&!e.IsOpen&&a.Loot.State(2).Progress==progress,"Retreat state lost");await Ready(a);Check(await FieldPawnTest.Move(a,0),"Back to the arcade by gathering");await Ready(a);Check(FieldPawnTest.Detail(a,2)&&s.IsOpen&&a.Loot.State(2).Progress==progress&&FieldPawnTest.Option(a,0,FieldPawnTest.SearchKey(2),FieldSpotKind.Lead)?.Enabled==true,"Resume interrupted search");await Tap(s.Back);
 return "PASS: warning first, one roll per search, no UI reroll, input/Esc gate, cancel free, wait fail/success one turn, reward preservation, cooldown, retreat one turn, interrupted search preserved, text bounds.";
 }finally{e.BaseChance=baseChance;e.MaximumChance=maxChance;e.WaitChance=wait;e.NoiseThreshold=threshold;e.WarnSearches=warnAt;e.GraceSearches=grace;for(int i=0;i<turnsBefore.Length;i++)a.Loot.Sites[i].Turns=turnsBefore[i];}}
 public static async Task<string> Preview(){FieldIdleConfirm.AutoAccept=true;/* idle members hush without the question (VerifyIdleConfirm tests it) */var c=await Depart();var a=c.ArrivalPanel;var e=a.Encounter;int b=e.BaseChance,m=e.MaximumChance,t=e.NoiseThreshold,warnAt=e.WarnSearches,crateTurns=a.Loot.Sites[0].Turns;try{e.BaseChance=e.MaximumChance=100;e.NoiseThreshold=0;e.WarnSearches=1;a.Loot.Sites[0].Turns=3;await Coop(a,0);await Tick(a.Search);await Tick(a.Search);Bounds(e.View);EventSystem.current.SetSelectedGameObject(null);return "Encounter review fixture open. Rates restored to defaults.";}finally{e.BaseChance=b;e.MaximumChance=m;e.NoiseThreshold=t;e.WarnSearches=warnAt;a.Loot.Sites[0].Turns=crateTurns;}}
}
